feat(react): refactor composed modal to functional component
carbon-design-system/carbon pull request #10060
Opened 2021-11-05 19:18 UTC by abbeyhrt

Closes #10012 

Refactors `ComposedModal` to functional component and updates tests. 

#### Testing / Reviewing

Pull down PR and confirm that ComposedModal works as expected

2021-11-08 15:27 UTC, sstrubberg requested changes
This is great! Couple style nits and I noticed that when I use the keyboard and tab my way over to the close button and hit "enter", it doesn't close the modal. It will, however, close it in the current version of ComposedModal.

2021-11-08 15:27 UTC, sstrubberg commented on packages/react/src/components/ComposedModal/next/ComposedModal.js
> +    ...other
```suggestion
    ...rest
```

style nit

2021-11-08 15:27 UTC, sstrubberg commented on packages/react/src/components/ComposedModal/next/ComposedModal.js
> +      {...other}
```suggestion
      {...rest}
```

style nit

2021-11-09 00:08 UTC, dakahn approved these changes
nice! great job on the testing as well. approved, pending scotts changes 👍🏾

2021-11-09 22:13 UTC, abbeyhrt commented
@sstrubberg which story are you looking at? I am able to tab to the Close icon and use it but I might be looking at the wrong story! Separately, that might be because of changes coming from the `ModalHeader` refactor instead of this one, since the close icon button and functionality is coming from that component.

2021-11-09 22:25 UTC, sstrubberg commented
> @sstrubberg which story are you looking at? I am able to tab to the Close icon and use it but I might be looking at the wrong story! Separately, that might be because of changes coming from the `ModalHeader` refactor instead of this one, since the close icon button and functionality is coming from that component.

Super weird. I can't recreate it. Ah well. Nicely done!

2021-11-09 22:26 UTC, sstrubberg approved these changes

2021-11-09 22:26 UTC, merged