feat(dropdown): add renderSelectedItem prop
carbon-design-system/carbon pull request #10188
Opened 2021-11-29 16:07 UTC by kevinsperrine

Closes #10038

Adds a renderSelectedItem prop as a callback when it would be helpful to render the currently selected item as an element instead of just text

#### Changelog

**New**

- renderSelectedItem prop that is called to render the current `selectedItem` as an element
- added unit tests
- added RenderSelectedItem demo story

**Changed**

- if given, renderSelectedItem will be called and passed the currently selected item allowing the consumer to render the item as desired

#### Testing / Reviewing

- Added a RenderSelectedItem story to demonstrate the functionality
- added new tests to confirm

2021-12-03 21:39 UTC, dakahn requested changes
Hey there! Code lgtm, but do you think we could demonstrate this props intended usage in the story you've built out. Might help with reviews as well 👍🏾

2021-12-03 22:52 UTC, kevinsperrine commented
> Hey there! Code lgtm, but do you think we could demonstrate this props intended usage in the story you've built out. Might help with reviews as well 👍🏾

Yep! @dakahn, I just pushed up a version that uses icons in both the `itemToElement` callback for when the dropdown is open and the `renderSelectedItem` for when an item has been chosen.

2021-12-07 00:14 UTC, dakahn approved these changes
This looks good to me! The story is a big help thanks. Tested and speaks as expected with both NVDA and JAWS 2021 on Windows 11 🏄🏾

2021-12-07 17:26 UTC, joshblack approved these changes

2021-12-07 17:54 UTC, merged