fix(modal): fix modal footer height
carbon-design-system/carbon pull request #1038
Opened 2018-08-21 18:55 UTC by aledavila

Closes #1000 

Fixes button repositioning in footer. 

#### Changelog

**Changed**

- removed `display: flex` and added `inline-block` to footer and `text-align: right` to parent for flex-box positioning as flex was breaking the position of buttons. 

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2018-08-22 09:43 UTC, asudoh commented
Hi @aledavila thank you for jumping in! What I have got in mind is custom modal footers - The change drifting away from `display:flex` would impact that. Given this, we may consider the change in a future major release, have applications impacted by the issue apply the proposed style by themselves?

2018-08-22 14:21 UTC, aledavila commented
Hey @asudoh thanks for jumping in. Yea I'm ok with proposing applications to implement the style by themselves.

2018-08-22 14:49 UTC, shinytoyrobots commented
Will this actually cause any break? @asudoh - do you have an example of what might be impacted? We don't have custom modal footers, and I'm not sure we should support edge cases where someone else is building custom functionality outside of Carbon.

2018-08-23 00:26 UTC, asudoh commented
Hi @shinytoyrobots thank you for asking! e.g. IBM Cloud product tour dialog has a small content switcher at the dialog footer to switch the carousel in the dialog. Given the bottom left area of dialog is a blank space, applications tend to put their stuff in. I understand support of that use case is not declared anywhere, but given how common such use case is, I'd be reluctant to make the change all the sudden.

2018-08-23 14:12 UTC, alisonjoseph commented
Should we just somehow track this for `v10` and make the change then?

2018-08-23 20:51 UTC, asudoh commented
@alisonjoseph Agreed!

2018-08-24 01:01 UTC, alisonjoseph commented
Closing for now then and adding a v10 label to the original issue.

2018-11-19 16:57 UTC, aledavila commented
Re-opening for v10 release.

2018-11-21 17:30 UTC, lovemecomputer requested changes
`text-align: right` is applied to `bx--modal-container`, so it makes all of the modal content align right:

<img width="956" alt="screen shot 2018-11-21 at 11 19 10 am" src="https://user-images.githubusercontent.com/3846271/48858023-f31a0b80-ed7f-11e8-9912-2c79335ed985.png">

2018-11-21 17:30 UTC, lovemecomputer commented on src/components/modal/_modal.scss
> +    text-align: right;
would it work to move this rule onto a different div?

2018-11-30 15:49 UTC, emyarod commented
superseded by #1499

2018-11-30 15:49 UTC, closed without merging