feat: adding experimental button css
carbon-design-system/carbon pull request #1043
Opened 2018-08-23 18:33 UTC by chrsfshr

Closes #

{{short description}}

#### Changelog

**New**

Added Experimental Button mixin scss -- under feature flag 'components'

**Changed**

wrapped carbon Button scss in 'stable' when feature flag not in use

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2018-08-23 19:21 UTC, joshblack commented on src/globals/scss/_feature-flags.scss
> +  components: true,
Make sure to toggle this off 👍

2018-08-23 20:56 UTC, asudoh reviewed
@chrsfshr Great to see the 1st experimental variant! In addition to the default feature flag @joshblack pointed out, there seem various broken variable references causing Travis build failure - Great to see them fixed. Thanks!

2018-08-24 00:59 UTC, alisonjoseph commented
This is a good start! 

Looks like this is missing all the experimental mixins, variables. Its been a while since I've looked at the duo-components but I think you will need to bring over colors and the theme files also. Look through the files here and compare to what we have in carbon-components https://github.ibm.com/carbon/duo-components/tree/master/src/globals/scss

Should probably copy over the migrate-to-10x docs also.

2018-08-24 18:55 UTC, chrsfshr commented
I swapped out security's color vars with carbon's...Not sure if thats the correct solution if not, will try to bring over their theme files as you mentioned @alisonjoseph

2018-08-24 19:00 UTC, alisonjoseph commented
When I set the feature flag to true I'm not seeing the new button styles? 
<img width="881" alt="screen shot 2018-08-24 at 2 00 17 pm" src="https://user-images.githubusercontent.com/2753488/44602738-172c7780-a7a6-11e8-82dc-8755ce5bf733.png">

2018-08-24 20:13 UTC, alisonjoseph commented
Looks like you are missing the button styles from the `duo-components` repo. Along with the experimental mixins etc.

2018-08-24 23:11 UTC, asudoh commented on src/components/button/_button.scss
> +    $button: #{$prefix}--btn;
Everybody - Do y'all want to see this pattern in all our styles in our experimental blocks? I’m good with this, but I don’t want this pattern mixed with hand-writing (within our experimental blocks). Thanks!

2018-09-04 19:17 UTC, chrsfshr commented
Just pushing what I had locally not the full updated component yet, need to add in what @alisonjoseph  merged in from her checkbox exp-component

2018-09-06 19:25 UTC, diego-codes commented on src/globals/scss/_feature-flags.scss
> +  components: false,
Should this flag be named `components-x` to match what is in the button styles?

2018-09-07 03:33 UTC, chrsfshr commented
@alisonjoseph or @joshblack when you get a chance take a look I think I've got the exp-button component together. Thanks!

2018-09-07 04:24 UTC, asudoh reviewed
LGTM basically, just one comment - Great to see this work is getting there!

2018-09-07 04:24 UTC, asudoh commented on src/components/button/_button.scss
> +    @include button;
Is this line intentional? (Just double-checking if we want `button` mix-in in addition to `button--x`)

2018-09-07 14:28 UTC, alisonjoseph requested changes
Overall looks good. Will want design to review for sure though.

The colors should all be pulling from the theme tokens, not the color tokens. Also styles should be separated from the original styles, not overwriting them. So remove the line Akira mentioned and have the styles pulled over.

2018-09-07 16:58 UTC, chrsfshr commented
Hi @alisonjoseph what do you mean by theme tokens vs color tokens?

2018-09-07 17:19 UTC, alisonjoseph commented
I mean the tokens like
`$ui-01` `$brand-02` etc from the `theme.scss` file and specifically the theme--experimental mixin. 

There are also some button variables already defined in there that should have just gotten moved over when copying from the duo repo

> $button-font-weight: 400 !default !global;
>   $button-font-size: 0.875rem !default !global;
>   $button-border-radius: 0 !default !global;
>   $button-height: 48px !default !global;
>   $button-padding: 0.25rem 0.75rem 0 0.75rem !default !global;
>   $button-padding-sm: 0 $spacing-xs !default !global;
>   $button-padding-lg: $spacing-sm !default !global;
>   $button-border-width: 4px !default !global;
>   $button-outline-offset: -5px !default !global;
>   $button-outline: 1px solid $ibm-colors__white !default !global;

2018-09-07 18:34 UTC, joshblack requested changes
Could we un-nest selectors and make sure to use the main selector versus the `$button` variables? Only reason is that it can make it harder to search for a selector since we can only use the modifier or descendants in our search.

2018-09-07 18:35 UTC, joshblack commented
I don't know if the experimental colors in components can be applied as systematically as our current colors, unfortunately. Might be worth bringing in design here to make sure we have the right color tokens and values, maybe?

2018-09-07 18:58 UTC, alisonjoseph commented
Thats true @joshblack I would at least use them where we used them in the `duo-components` repo however.

2018-09-07 19:02 UTC, joshblack commented
@alisonjoseph good call, that makes sense.

2018-09-11 22:20 UTC, alisonjoseph commented
Can you post staging link for design to review?

2018-09-21 20:53 UTC, jeanservaas commented
@chrsfshr Here's button.

Note: Carbon has both a Primary Danger button and a danger button... we have only one danger button... I was going to ask Anna about this, if we need to add a second danger button we can, but in the meantime I wanted to get this to you.

[Button.zip](https://github.com/IBM/carbon-components/files/2407008/Button.zip)

2018-09-24 16:27 UTC, alisonjoseph commented
going to close this, I believe @tw15egan is going to start a clean PR since we have updated designs

2018-09-24 16:27 UTC, closed without merging