docs(aspect-ratio): update aspect ratio docs for v11
carbon-design-system/carbon pull request #10636
Opened 2022-02-03 18:22 UTC by joshblack

This PR introduces two updates to our storybook for v11:

- Grid storybook styles are now scoped to a storybook-specific class name
- The Aspect Ratio story has been updated and includes controls

#### Changelog

**New**

- The AspectRatio story has been updated and now uses controls

**Changed**

- The Grid storybook styles are now scoped

**Removed**

#### Testing / Reviewing

- Verify no regression exists between the current grid storybook styles and the ones in this PR
- Verify the AspectRatio story renders as intended (correct aspect ratio and background color per item)
  - Also, verify the controls work when switching the "ratio" prop

2022-02-04 01:16 UTC, jnm2377 reviewed
Looks great! Only change I think it needs is the aspect ratio story css only works for v10, we could just add an additional selector with `cds` or use `prefix`:
https://github.com/carbon-design-system/carbon/blob/3068b4224d82d65e19753b9b597771a0b27974d6/packages/react/src/components/AspectRatio/AspectRatio-story.scss#L8

2022-02-04 21:37 UTC, tay1orjones requested changes
Yeah, we're missing the purple boxes

![image](https://user-images.githubusercontent.com/3360588/152606454-ff6103a8-6713-40d8-a3eb-2fb63a3dd4b5.png)

2022-02-09 20:55 UTC, joshblack commented
Thanks for the catch @jnm2377 @tay1orjones! Updated

2022-02-09 21:36 UTC, jnm2377 approved these changes

2022-02-14 15:53 UTC, tay1orjones approved these changes

2022-02-14 16:47 UTC, merged