fix(Select): make changes based on design audit
carbon-design-system/carbon pull request #10903
Opened 2022-03-03 18:20 UTC by tw15egan

Refs https://github.com/carbon-design-system/carbon/issues/10430

Makes style changes based on design audit

#### Changelog

**Changed**

- Changes color tokens based on design feedback
- Changed `carbon-mini-units` (was not calculating) to `spacing` token 

#### Testing / Reviewing

Ensure `Select` `InlineSelect` and `Pagination` are rendering with the correct tokens, especially in FIrefox.

2022-03-03 18:30 UTC, joshblack approved these changes

2022-03-08 22:18 UTC, aledavila approved these changes

2022-03-09 16:19 UTC, laurenmrice requested changes
Looks great, just two things:

>   optgroup.#{$prefix}--select-optgroup,
>   .#{$prefix}--select-option {
>     // For the options to show in IE11
>     background-color: $**background-hover**;
>     color: $text-primary;

The background-color should be `$layer-hover` for the options in the menu.

2022-03-09 16:19 UTC, laurenmrice commented on packages/styles/scss/components/select/_select.scss
>        background-color: $background-hover;
```suggestion
      background-color: $field-hover;
```

2022-03-09 20:15 UTC, laurenmrice approved these changes
Looks good to me 👍

2022-03-10 15:06 UTC, merged