feat(radio-button): adds animation
carbon-design-system/carbon pull request #10943
Opened 2022-03-09 16:10 UTC by AlexanderMelox

Closes #10609 

This pull request adds micro-interactions to the RadioButton component.

#### Changelog

**New**

- Adds new hovers and active states to the radio button

**Changed**

-  packages/components/src/components/radio-button/_radio-button.scss
-  packages/styles/scss/components/radio-button/_radio-button.scss

#### Testing / Reviewing

- Used storybook to make sure changes do not change visuals and all props and controls are still functional.
- Made sure animations are still keyboard accessible.

2022-03-10 15:38 UTC, mjabbink commented
@AlexanderMelox I like it. Should tabbing through the radio buttons work on this preview?

2022-03-10 15:40 UTC, AlexanderMelox commented
Yes it should work! I double checked

2022-03-10 15:52 UTC, joshblack reviewed
Thanks for taking the time to do this plus port it over to the styles package! Really appreciate it 🙏  

I think the only thing I noticed is that the animation seems to still apply for the disabled state and I wanted to check if this was intended.

https://user-images.githubusercontent.com/3901764/157699961-cc731894-5ee7-4839-8520-2b92066c6452.mov

2022-03-10 16:04 UTC, tw15egan requested changes
The animation looks crisp! Just had a few comments

2022-03-10 16:04 UTC, tw15egan commented on packages/components/src/components/radio-button/_radio-button.scss
>      outline-offset: 1.5px;
Not included in your changes, but while reviewing I noticed that Firefox is calculating this incorrectly and causing a weird focus. 

![image](https://user-images.githubusercontent.com/11928039/157701499-db053538-da55-4846-b7d4-e842d8d9d3e9.png)

Can we just change this to 1px?

2022-03-10 16:04 UTC, tw15egan commented on packages/styles/scss/components/radio-button/_radio-button.scss
>      outline-offset: 1.5px;
Same as above

2022-03-10 16:04 UTC, tw15egan commented on packages/styles/scss/components/radio-button/_radio-button.scss
> +        transform $duration-moderate-01 motion(exit, productive);
We recently added an a11y helper to disable animations when `prefers-reduced-motion` is enabled. Can we add this media query to this style block?

```css
      @media (prefers-reduced-motion: reduce) {
        transition: none;
      }
```

2022-03-10 16:04 UTC, tw15egan commented on packages/styles/scss/components/radio-button/_radio-button.scss
> +        transform $duration-moderate-01 motion(entrance, productive);
Same comment as above regarding reduced motion.

2022-03-10 17:15 UTC, AlexanderMelox commented
> Thanks for taking the time to do this plus port it over to the styles package! Really appreciate it 🙏
> 
> I think the only thing I noticed is that the animation seems to still apply for the disabled state and I wanted to check if this was intended.
> 
>  Screen.Recording.2022-03-10.at.09.51.36.mov

@joshblack Interesting in the development storybook it wasn't applying to the disabled state 🤔 I'll take a look at it, thanks!

2022-03-11 15:22 UTC, kingtraceyj commented
From design: The hover states on the text work differently than Carbon's current paradigm. I suggest simplifying the animation to just the animation and not including the color changes on hover.

2022-03-14 19:13 UTC, AlexanderMelox commented
I will be out of office for a week, but will get back to these feedback next week.

2022-04-14 15:43 UTC, watsondesign commented
@kingtraceyj there appears to be components in Carbon where the type changes on hover (for example the tabs). My intention with the color change is to give the user feedback into which option is on hover. Without it, I don't believe it too be as effective

2022-04-19 14:25 UTC, AlexanderMelox commented
@kingtraceyj @watsondesign I went ahead and removed the hover animation on the text. Can we get this reviewed so we can merge this PR?

2022-04-26 12:52 UTC, AlexanderMelox commented
@kingtraceyj @laurenmrice Can we get this PR reviewed?

2022-05-02 20:12 UTC, kingtraceyj commented
@AlexanderMelox and @watsondesign would you mind sharing this at our design office hours perhaps in an open slot? We've had some back and forth discussion about implementation. We love the idea of adding in these microinteractions but we want to do it systematically. I will get you added to the invite but in the meantime, here is the info to sign up and join:

> Carbon Design Office Hours
> The goal is to help teams adopt Carbon v11, adopt Carbon for IBM Dotcom, achieve cross team alignment, and design in compliance with IBM Design Language.
> 
> Sign-up sheet: https://ibm.box.com/s/hyan6wyze3wgm50rd9yj3rrdv80w4gkt
> 
> https://ibm.webex.com/meet/digdes

2022-05-17 14:02 UTC, closed without merging