[WIP - ⚠️ DO NOT MERGE] feat: wip index carbon components
carbon-design-system/carbon pull request #11242
Opened 2022-04-18 14:00 UTC by andreancardona

Closes https://github.com/carbon-design-system/carbon-platform/issues/515

This is a draft PR to index the carbon-components

2022-04-18 18:20 UTC, francinelucca requested changes

2022-04-18 18:20 UTC, francinelucca commented on packages/carbon-components/carbon.yml
> +  externalDocsUrl: https://the-carbon-components.netlify.app/
```suggestion
  externalDocsUrl: https://the-carbon-components.netlify.app
```

2022-04-18 18:20 UTC, francinelucca commented on packages/carbon-components/carbon.yml
> +          url: https://react.carbondesignsystem.com/?path=/docs/components-accordion
i
```suggestion
          url: https://the-carbon-components.netlify.app/?nav=accordion
```

2022-04-18 18:20 UTC, francinelucca commented on packages/carbon-components/carbon.yml
> +          url: https://react.carbondesignsystem.com/?path=/docs/components-copybutton
```suggestion
```

2022-04-18 18:20 UTC, francinelucca commented on packages/carbon-components/carbon.yml
> +          url: https://the-carbon-components.netlify.app/?nav=loading
```suggestion
```

2022-04-18 18:20 UTC, francinelucca commented on packages/carbon-components/carbon.yml
> +      framework: react
```suggestion
      framework: vanilla
```

2022-04-19 22:35 UTC, francinelucca reviewed
LGTM, can see 46 components as expected: 
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/40550942/164112353-c154cc3a-0178-42da-8dee-4e21eca1ed73.png">

And library info:
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/40550942/164112199-df8463b8-8dda-4462-842e-3cd11118878d.png">

This should be good to go once we resolve remaining TODOs (get final thumbnails and tag approval) @andreancardona  👍 

Let's also confirm treeview status @andreancardona since it's unstable on styles and it's not present in storybook

2022-04-20 19:57 UTC, aubrey-oneal commented on packages/carbon-components/carbon.yml
> +      # TODO: @aubrey check tag
Approved 👍

2022-04-20 20:04 UTC, aubrey-oneal commented on packages/carbon-components/carbon.yml
> +      # TODO: @aubrey check tag
Remove this component.

2022-04-20 20:05 UTC, aubrey-oneal commented on packages/carbon-components/carbon.yml
> +      # TODO: @aubrey check tag
Approved 👍

2022-04-20 20:05 UTC, aubrey-oneal requested changes
Just remove the menu component.

2022-04-21 15:40 UTC, francinelucca approved these changes
Lib and comps being pulled correctly:
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/40550942/164498498-56082984-0df6-440f-a8d8-cffbc686b7de.png">
LGTM

2022-04-21 20:13 UTC, closed without merging