Shell header
carbon-design-system/carbon pull request #1125
Opened 2018-09-19 18:48 UTC by aledavila

Closes #1095 

Staging link: http://shell-nav-header-boring-otter.mybluemix.net/component/ui-shell--default

2018-09-19 18:51 UTC, joshblack requested changes
Could we use one arrow icon SVG and then have it rotate on hover?

Also noticed that when tabbing through, the menu will  disappear even though I should be on a nested link potentially?

Final note was that the font weights seem to be different for menus, is that intended?

2018-09-20 21:28 UTC, joshblack commented on src/components/ui-shell/ui-shell.config.js
> +const headernav = {
Would it help to add this onto `header` as another type? Maybe:

```js
const header = {
  company: 'IBM',
  platform: '[Platform]',
  links: [
    {
      href: '/component/ui-shell--default',
      title: 'L1 link 1',
    },
    {
      href: '/component/ui-shell--default',
      title: 'L1 link 1',
    },
    {
      type: 'menu',
      links: [
        // ...
      ],
    }
  ]
};
```

Then the template could support either type, similar to what we'll need to do in the React component.

2018-09-25 15:13 UTC, joshblack commented on src/components/ui-shell/ui-shell.config.js
> +  navlinks: [
Could this be camel-case, e.g. `navLinks`?

2018-09-25 20:19 UTC, joshblack approved these changes

2018-09-26 02:45 UTC, asudoh commented on src/components/ui-shell/ui-shell.config.js
> +    headernav,
Cannot see `headernav` definition, which seems to have caused the Travis error:

```
[19:21:15] TypeError: Cannot read property 'forEach' of undefined
    at cache.get.then (/home/travis/build/IBM/carbon-components/tools/templates.js:100:21)
    at <anonymous>:null:null
```

The underlying `fractal.load()` fails to populate `componentSource` property in such case, and thus causes JavaScript error at https://github.com/IBM/carbon-components/blob/v9.22.0/tools/templates.js#L100.

2018-09-26 03:50 UTC, aledavila commented
@asudoh good catch. Thanks try now

2018-09-26 03:59 UTC, asudoh reviewed
LGTM 👍 once our designer signs this off - Thanks @aledavila!

2018-09-27 16:14 UTC, designertyler commented
The focus state allows the menus to overlap
<img width="505" alt="screen shot 2018-09-27 at 11 12 26 am" src="https://user-images.githubusercontent.com/19270502/46159584-43746180-c246-11e8-8091-ec9ef33da86d.png">

2018-09-27 16:15 UTC, designertyler approved these changes

2018-09-27 16:27 UTC, merged

2018-09-27 16:29 UTC, chrisconnors-ibm commented
does "remove focus on dropdown to prevent from staying open" affect keyboard navigation of menus