fix(IconButton): adds `hasIconOnly` classname to fix right padding
carbon-design-system/carbon pull request #11352
Opened 2022-05-05 21:32 UTC by jnm2377

Closes #11295 

#### Changelog

- `IconButton` now uses `cds--btn--icon-only` and passes in a `className` prop
- adds margin to the `IconButton` story so the tooltip wouldn't be overflowing

#### Testing / Reviewing

1. View `IconOnly` story 
2. test the playground knobs for `size` & `kind` 
3. spacing should work correctly now (square btn not rectangle)

2022-05-06 15:43 UTC, abbeyhrt requested changes

2022-05-06 15:43 UTC, abbeyhrt commented on packages/react/src/components/IconButton/next/IconButton.stories.js
> +        label={label}>
I think this needs to have the `size` prop added to it? Not sure,  the size controls weren't working for me and I think that might be why

2022-05-09 16:20 UTC, jnm2377 commented on packages/react/src/components/IconButton/next/IconButton.stories.js
> +        label={label}>
@abbeyhrt oh, possibly. idk. I didn't change the story, just the spacing bc the tooltip was getting cut off. I just manually tested the sizes. But I'll look into the controls.

2022-05-09 18:09 UTC, abbeyhrt commented on packages/react/src/components/IconButton/next/IconButton.stories.js
> +        label={label}>
Ah sorry, I was thinking of this bit: `test the playground knobs for size & kind` and thought that meant the controls. You can totally ignore this then!

2022-05-09 18:09 UTC, abbeyhrt approved these changes

2022-05-10 20:31 UTC, tay1orjones approved these changes

2022-05-10 20:34 UTC, dakahn approved these changes

2022-05-10 20:48 UTC, merged