fix(link): fix on hover diabled text styles
carbon-design-system/carbon pull request #11461
Opened 2022-05-23 17:26 UTC by aledavila

Closes #11392

{{short description}}

#### Changelog

**Changed**

- added hover diabled styles to sm and lg links
- 
#### Testing / Reviewing

Make sure links is working as expected

2022-05-24 16:35 UTC, joshblack requested changes
Looks good! Only thing would be to remove the commented code if it's no longer needed 👀 (wasn't sure if it was still being used or not for testing)

2022-05-24 16:35 UTC, joshblack commented on packages/styles/scss/components/link/_link.scss
> +  // }
```suggestion
```

2022-05-24 18:12 UTC, aledavila commented on packages/styles/scss/components/link/_link.scss
> +  // }
Good catch! Forgot to remove that. Was testing

2022-05-24 18:57 UTC, jnm2377 approved these changes
LGTM pending Josh's comment :)

2022-05-26 19:45 UTC, aledavila commented
@joshblack can recheck

2022-05-26 19:46 UTC, joshblack approved these changes

2022-05-26 20:07 UTC, merged