chore(Copy, CopyButton): update tests to RTL
carbon-design-system/carbon pull request #11514
Opened 2022-05-31 23:03 UTC by jnm2377

Closes #11509 
Closes #11510 

#### Changelog

- updates `Copy` & `CopyButton` tests to RTL

#### Testing / Reviewing

- make sure tests pass

2022-06-01 15:07 UTC, abbeyhrt approved these changes

2022-06-01 19:07 UTC, joshblack requested changes

2022-06-01 19:07 UTC, joshblack commented on packages/react/src/components/CopyButton/CopyButton-test.js
> +    }, 5000); // custom feedback timeout
For timers, could you update this to use [timer mocks](https://jestjs.io/docs/timer-mocks) (just so we don't have to wait 5s for the test to complete)

2022-06-01 19:49 UTC, jnm2377 commented on packages/react/src/components/CopyButton/CopyButton-test.js
> +    }, 5000); // custom feedback timeout
ooh, I hadn't heard of this. Looking at the example, I'm wondering how that might apply here (sorry, if it's obvious). Would it literally just be adding 
```js
jest.useFakeTimers(); 
jest.spyOn(global, 'setTimeout');
```
 before the timeout or before all the tests? Just trying to figure out what it looks like in this situation bc it's different than their example. I'm not just trying to test that the timeout was called, more so trying to check that the animation changes correctly & for the amount of time designated (feedback animation during and after the timeout).

2022-06-02 15:36 UTC, joshblack commented on packages/react/src/components/CopyButton/CopyButton-test.js
> +    }, 5000); // custom feedback timeout
@jnm2377 I think in this case you could:

- At the top-level write `jest.useFakeTimers()`
- In the test, you can do:

```jsx
expect(button).toHaveClass('cds--copy-btn--animating');
jest.runAllTimers();
expect(button).not.toHaveClass('cds--copy-btn--animating');
```

2022-07-08 21:07 UTC, joshblack approved these changes

2022-07-12 14:23 UTC, merged