docs(breadcrumb): add controls to story
carbon-design-system/carbon pull request #11535
Opened 2022-06-02 16:12 UTC by aledavila

Closes #11468 

Add controls to breadcrumb playground

#### Changelog

**Changed**

- created new .stories.js file
- added controls to playground story

#### Testing / Reviewing

Make sure breadcrumb is working as intended and playground controls work

2022-06-02 22:31 UTC, jnm2377 approved these changes

2022-06-03 20:31 UTC, tay1orjones requested changes
Here's what I'm seeing:

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/3360588/171948019-d4fe05e9-82e7-4e68-a232-74af2ac687a0.png">


- `children` is still in the table, I think the intent was to remove it?
- `className` should be a string, or no? I'm not up to speed on if that was a decision y'all made for the playground stories or not. My assumption is it should be a text box for a string.

2022-06-13 19:16 UTC, aledavila commented
@tay1orjones oops sorry for this late reply. Its ready for review

2022-06-13 20:42 UTC, tay1orjones approved these changes

2022-06-13 21:18 UTC, merged