docs: improve the tab panel text with interactive content
carbon-design-system/carbon pull request #11551
Opened 2022-06-03 21:01 UTC by spraguejdev

Closes #https://github.com/carbon-design-system/carbon/issues/11291

This pr accomplished two items. 

1. Consistency for interactive content on tab 2
2. Keeps the tab label text and panel text, DRY. 🙂 

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

1. Navigate to any of the react tab stories http://localhost:3000/?path=/story/components-tabs--contained
2. Verify the text for the tab label  for each story 
4. Verify the text for the tab panel for each story 
5. Enjoy 🍿

2022-06-03 21:04 UTC, spraguejdev commented
I have read the DCO document and I hereby sign the DCO.

2022-06-03 21:19 UTC, tay1orjones requested changes
Super cool of you to just pick this up out of the blue, thanks! Just a couple comments.

2022-06-03 21:19 UTC, tay1orjones commented on packages/react/src/components/Tabs/next/Tabs.stories.js
> +      <Tab>{tabPanelEnums.tab1.linkText}</Tab>
The first tab has no text in the deploy preview

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/3360588/171953618-4f543dc0-f398-4673-83eb-44b6bd1de92e.png">

Maybe it's just this?
```suggestion
      <Tab>{tabPanelEnums.tab1.labelText}</Tab>
```

2022-06-03 21:19 UTC, tay1orjones commented on packages/react/src/components/Tabs/next/Tabs.stories.js
> +const tabPanelEnums = {
Small nit, but I wouldn't be opposed to a shorter/simpler name here

```suggestion
const tabs = {
```

Or if you'd like, could even break these out into their own variables to cut down on the chaining by one level
```
const tab1 = { labelText: '', panelText: '' };
const tab2 = { ... };
...etc
```

2022-06-06 21:49 UTC, abbeyhrt commented
Hey @spraguejdev! Super cool for you to jump and do this! I love the consistency in the second tab panel. One of the goals of our stories is to have them be as copy/paste-able as possible and using an enum for the text like this makes it harder for each story to be easily copied and pasted.  It definitely looks very repetitive in that file, but in this, that is on purpose.  With the way that storybook breaks down each story, the "story" panel on storybook is the copy/paste-able snippet that we are looking for.

2022-06-08 15:21 UTC, spraguejdev commented
> Hey @spraguejdev! Super cool for you to jump and do this! I love the consistency in the second tab panel. One of the goals of our stories is to have them be as copy/paste-able as possible and using an enum for the text like this makes it harder for each story to be easily copied and pasted. It definitely looks very repetitive in that file, but in this case, that is on purpose. With the way that storybook breaks down each story, the "story" panel on storybook is the copy/paste-able snippet that we are looking for.

Hey @abbeyhrt! Thanks for the review and for allowing me to be a noob 🙂 to how yall do stuff. I'm here to learn and I totally understand what you are recommending. I'll be making this change asap. 

Thanks and nice to virtually work with you 🥇

2022-07-26 14:36 UTC, aledavila commented
@[spraguejdev](https://github.com/spraguejdev) just wondering if you had a chance to look at the comments or if you still wanted to work on it. Thanks

2022-08-09 16:54 UTC, aledavila commented
Closing. Fixes have already been made

2022-08-09 16:54 UTC, closed without merging