docs(Theme): update @carbon/Theme README
carbon-design-system/carbon pull request #11635
Opened 2022-06-16 23:11 UTC by dakahn

Partially closes #11293 

Updates the /Themes README with v11 usage and guidance

2022-06-17 14:59 UTC, aledavila approved these changes

2022-06-17 18:49 UTC, joshblack requested changes

2022-06-17 18:49 UTC, joshblack commented on packages/themes/README.md
> +@use '@carbon/themes/scss/themes';
```suggestion
@use '@carbon/themes/scss/themes';
@use '@carbon/themes/scss/theme';
```

2022-06-17 18:49 UTC, joshblack commented on packages/themes/README.md
> +  @include theme($theme--g90) {
```suggestion
  @include theme.theme(themes.$g90) {
```

2022-06-17 18:49 UTC, joshblack commented on packages/themes/README.md
> +  @include theme($theme--g100) {
```suggestion
  @include theme.theme(themes.$g100) {
```

2022-07-05 14:52 UTC, joshblack approved these changes

2022-07-05 19:20 UTC, merged