Run `npx sass-migrator division **/*.scss`
carbon-design-system/carbon pull request #11753
Opened 2022-07-06 02:25 UTC by jzinn

Closes #11752

Remove deprecated uses of / as division in Sass code using the automated migration tool.

#### Changelog

**Changed**

- Remove deprecated uses of / as division in Sass code.

2022-07-06 02:27 UTC, jzinn commented
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> _**I have read the DCO document and I hereby sign the DCO.**_
> 
> **jzinn** seems not to be a GitHub user. You need a GitHub account to be able to sign the DCO. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the DCO document and I hereby sign the DCO.

2022-07-06 02:37 UTC, jzinn commented
recheck

2022-07-12 00:56 UTC, jnm2377 commented
recheck

2022-07-12 20:07 UTC, tay1orjones requested changes
The changes to use `list.slash` are okay, though it's worth noting the styles are currently working without it.

We can't blindly apply the output of the migration tool unfortunately. The problem is we're already conditionally using slash division or `math.div` based on if the function exists. 

```scss
// Example:
    @if meta.function-exists('div', 'math') {
      max-width: math.percentage(math.div($span, $columns));
      flex: 0 0 math.percentage(math.div($span, $columns));
    } @else {
      max-width: math.percentage(($span / $columns));
      flex: 0 0 math.percentage(($span / $columns));
    }
```

Replacing these slash division is not what we'd want, we need to instead remove the conditional altogether:

```diff
-    @if meta.function-exists('div', 'math') {
+      max-width: math.percentage(math.div($span, $columns));
+      flex: 0 0 math.percentage(math.div($span, $columns));
-    } @else {
-      max-width: math.percentage(($span / $columns));
-      flex: 0 0 math.percentage(($span / $columns));
-    }
```

Additionally, I think `_convert.import.scss` can actually be deleted. It's a leftover from supporting node-sass and dart-sass simultaneously where node-sass would always use files without the `.import.scss` suffix and dart-sass would use the `.import.scss` files. There's a [note](https://github.com/carbon-design-system/carbon/blob/779f223df3709de55e6542070d308c203ef1e367/packages/layout/scss/_convert.import.scss#L7-L20) about it in the file for further info

2022-07-12 23:18 UTC, jzinn commented
> @jzinn I think you need to comment the DCO statement without quote replying to it. That might do it. 👍🏽

I edited the original DCO comment.  If that doesn't work, I'll make a new comment.

2022-07-12 23:18 UTC, jzinn commented
recheck

2022-07-12 23:54 UTC, jzinn commented
> The changes to use `list.slash` are okay, though it's worth noting the styles are currently working without it.

I am still on Carbon 10, and the warnings I see there are for `math.div` and not `list.slash`.  Given that Carbon 11 works with `dart-sass` and nobody has yet run into a warning about `list.slash`, perhaps there is no warning and the change to use `list.slash` is not needed.

> We can't blindly apply the output of the migration tool unfortunately. The problem is we're already conditionally using slash division or `math.div` based on if the function exists.
> 
> ```css-scss
> // Example:
>     @if meta.function-exists('div', 'math') {
>       max-width: math.percentage(math.div($span, $columns));
>       flex: 0 0 math.percentage(math.div($span, $columns));
>     } @else {
>       max-width: math.percentage(($span / $columns));
>       flex: 0 0 math.percentage(($span / $columns));
>     }
> ```
> 
> Replacing these slash division is not what we'd want, we need to instead remove the conditional altogether:
>
> ```diff
> -    @if meta.function-exists('div', 'math') {
> +      max-width: math.percentage(math.div($span, $columns));
> +      flex: 0 0 math.percentage(math.div($span, $columns));
> -    } @else {
> -      max-width: math.percentage(($span / $columns));
> -      flex: 0 0 math.percentage(($span / $columns));
> -    }
> ```
> 

I missed that, thanks.  I force-pushed a change that removes the `math.div` changes.

The `list.slash` changes are the only changes remaining.  If they are not needed, then this PR should be closed.

> Additionally, I think `_convert.import.scss` can actually be deleted. It's a leftover from supporting node-sass and dart-sass simultaneously where node-sass would always use files without the `.import.scss` suffix and dart-sass would use the `.import.scss` files. There's a [note](https://github.com/carbon-design-system/carbon/blob/779f223df3709de55e6542070d308c203ef1e367/packages/layout/scss/_convert.import.scss#L7-L20) about it in the file for further info

Does Carbon 11 drop support for `node-sass`?  If so, and if you want, I can update the PR again to remove the conditionals so that only the contents of the `math.div` branches remain, and also remove `_convert.import.scss` (by moving the content to `_convert.scss`).  I would be making the changes blindly, but it could be useful to keep this PR moving, if that is desired.

2022-07-13 00:12 UTC, jzinn commented
I made another force push to rebase and replace the conditionals with their `math.div` branches, and to remove `_convert.import.scss`.

2022-07-13 20:11 UTC, tay1orjones requested changes
Awesome improvements! Thanks for making those changes. Yes v11 does not support node-sass and further it requires sass@>=1.33.0 which is crucial because before v1.33.0 the math.div function didn't exist.

One small thing left, but this is looking good!

2022-07-13 20:11 UTC, tay1orjones commented on packages/layout/examples/preview/styles.scss
> +  height: em(48px);
This example project is still using `@carbon/layout@v10.x`, so these prefixes will need to stay in. The `preview` project could be updated to use the v11 version of the package, but doing that may also require some changes to `@use` the appropriate modules instead of `@import`.

2022-07-13 20:42 UTC, jzinn commented on packages/layout/examples/preview/styles.scss
> +  height: em(48px);
Fixed.  Good eye, thanks.

2022-07-13 20:43 UTC, jzinn commented
Updated and rebased.  Thanks @tay1orjones for the excellent reviews.

2022-07-13 21:29 UTC, jzinn commented
I looked into updating the preview example project to use `@carbon/layout` v11, but couldn't figure out how to get past this error: ```% npx yarn run build
🚨 Build failed.

@parcel/transformer-sass: expected "{".
   ╷
11 │ 'iconSize01', 'iconSize02'];
   │                            ^
   ╵
  node_modules/@carbon/layout/es/index.js 11:28  @use
  styles.scss 1:1                                root stylesheet

  Error: expected "{".
     ╷
  11 │ 'iconSize01', 'iconSize02'];
     │                            ^
     ╵
    node_modules/@carbon/layout/es/index.js 11:28  @use
    styles.scss 1:1                                root stylesheet
```

2022-07-14 12:41 UTC, tay1orjones approved these changes
LGTM, thanks! 🎉

2022-07-14 15:23 UTC, tw15egan approved these changes
LGTM, thanks for contributing!

2022-07-14 16:46 UTC, merged