fix(FormLabel): update label with tooltip examples and styles
carbon-design-system/carbon pull request #11779
Opened 2022-07-12 05:49 UTC by jnm2377

Closes #11346 

#### Changelog

- updates form label with tooltip stories
- no longer includes tooltip as child of label for a11y reasons
- adds styles for label with tooltip

#### Testing / Reviewing

- ensure all tests pass
- view form label with tooltip story and ensure everything looks as expected (compare to v10 story)

2022-07-13 22:21 UTC, abbeyhrt commented on packages/styles/scss/components/form/_form.scss
> +  }
Are these styles the same as lines 55-58 above (without the position: relative)?

2022-07-13 22:24 UTC, abbeyhrt approved these changes
Looks good to me!

2022-07-21 14:16 UTC, tay1orjones approved these changes

2022-08-03 18:55 UTC, tay1orjones requested changes
@jnm2377 VRT is failing with this

```
Module not found: Error: Can't resolve '../Notification/next/Notification' in '/home/runner/work/carbon/carbon/packages/react/src/components/FormLabel'
```

I think the path just needs to be corrected within FormLabel story file?

2022-08-05 13:00 UTC, tay1orjones approved these changes

2022-08-05 13:21 UTC, merged