docs(Multiselect): update Storybook and add Playground story
carbon-design-system/carbon pull request #11801
Opened 2022-07-13 23:43 UTC by dakahn

Closes #11718 

Update MultiSelect and add Playground story

2022-07-14 16:40 UTC, tay1orjones requested changes
I think for all the ones with `control: false` we want them to be totally hidden from the controls pane. I think you can do this for all the stories by moving them up into the default export

```diff
 export default {
   ...
   argTypes: {
     ...
+    downshiftProps: {
+      table: { disable: true }
+    },
   },
 };
```

2022-07-14 16:40 UTC, tay1orjones commented on packages/react/src/components/MultiSelect/MultiSelect.stories.js
> +  },
This one and the others below with the same config can be moved up into the component level argTypes and totally removed from the table.

2022-07-15 17:35 UTC, abbeyhrt commented on packages/react/src/components/MultiSelect/MultiSelect.stories.js
> +    },
```suggestion
    },
    light: {
      table: { disable: true },
    },
```
Could we add the light prop to this? I think the styles have been removed for it so the prop doesn't change anything

2022-07-15 17:36 UTC, abbeyhrt approved these changes

2022-07-22 13:01 UTC, tay1orjones approved these changes

2022-07-22 14:42 UTC, merged