chore(checkbox): update label headings
carbon-design-system/carbon pull request #11860
Opened 2022-07-26 14:31 UTC by aledavila

Closes #11788

Updates labels for checkbox and radio button 

#### Changelog

#### Testing / Reviewing

Make sure checkbox and radio buttons work as intended

2022-08-01 19:55 UTC, tw15egan requested changes
Noticed an issue with the Radio Button Playground story

<img width="315" alt="Screen Shot 2022-08-01 at 3 54 09 PM" src="https://user-images.githubusercontent.com/11928039/182233837-6f4fdddd-e967-45cd-ad96-d9a65d944cfc.png">


Also, should we update the radio button labels to say "Radio button label"?

2022-08-03 20:20 UTC, aledavila commented
@tw15egan could you review again please.

2022-08-03 21:04 UTC, dakahn approved these changes

2022-08-04 15:42 UTC, tw15egan approved these changes
LGTM 👍 ✅

2022-08-09 20:43 UTC, jnm2377 approved these changes

2022-08-09 22:30 UTC, merged