fix(react): IconButton prop types for danger kind
carbon-design-system/carbon pull request #11893
Opened 2022-08-01 14:03 UTC by stanley-regnard

Closes https://github.com/carbon-design-system/carbon/issues/11892

Use `ButtonKinds` as possible values for `kind` property of IconButton component (just like how Button does), instead of the hardcoded string values that do not include any of the `danger` kind.

#### Changelog

**Removed**

- False alarm when using IconButton as a `danger` button

#### Testing / Reviewing

Using an IconButton with `kind` set to any of those values `['danger',  'danger--primary',  'danger--ghost',  'danger--tertiary']` should no longer trigger a warning in the console

2022-08-01 14:04 UTC, stanley-regnard commented
I have read the DCO document and I hereby sign the DCO.

2022-08-01 14:04 UTC, stanley-regnard commented
recheck

2022-08-01 14:22 UTC, tay1orjones requested changes
Thanks for submitting this! Unfortunately danger-ghost is not a valid option per design's guidance https://github.com/carbon-design-system/carbon/pull/10095#pullrequestreview-807656822

> **For `kind`** The following buttons do not come as icon only buttons and should be removed from the dropdown:
> 
> * [x]  danger
> * [x]  danger--primary
> * [x]  danger--ghost
> * [x]  danger--tertiary

2022-08-01 16:13 UTC, stanley-regnard commented
Thanks for the quick answer. So, by design, icon only buttons should not be usable as danger buttons? That's a curious choice. 
What would be the suggested alternative then?

2022-08-02 20:06 UTC, abbeyhrt commented
@stanley-regnard I think the idea is that a "danger"-ous action should be called out more prominently than through an icon. So in your case of the trash can icon, ideally that would become a "Delete" button so that we can feel more confident that the user knows they are about to perform a dangerous action

2022-08-03 07:48 UTC, stanley-regnard commented
Thank you for the clarification!

Closing this and the related issue since it's working as intended then.

2022-08-03 07:48 UTC, closed without merging

2022-08-11 04:16 UTC, sbuys commented
I know this is closed but this seems like an arbitrary design decision.

Signaling danger via symbol, color, etc. is pretty ubiquitous in the physical world (see traffic signs, hazardous chemicals warning, etc.). Text does not always make signal processing clearer....

2024-06-05 16:16 UTC, craigyu commented
Petition to reopen this PR