fix(type): update v10 token styles
carbon-design-system/carbon pull request #11977
Opened 2022-08-18 23:08 UTC by jnm2377

Closes #11864

#### Changelog
- updates type tokens for 
    - $expressive-heading-04
    - $expressive-heading-05
    - $productive-heading-05
    - $display-03
    - $display-04

#### Testing / Reviewing
- compare changes to v10 specs listed in original issue https://github.com/carbon-design-system/carbon/issues/11813

2022-08-19 19:16 UTC, aagonzales requested changes
Just one mix up.

✅ $expressive-heading-04
✅ $expressive-heading-05
❌ $productive-heading-05
✅ $display-03
✅ $display-04

2022-08-19 19:16 UTC, aagonzales commented on packages/type/src/styles.js
>  export const productiveHeading04 = {
This change should have been for "productive-heading-**05**" not "04"

2022-08-19 19:24 UTC, aagonzales approved these changes

2022-08-19 19:49 UTC, tay1orjones approved these changes
LGTM once tests pass with updated snaps

2022-08-22 19:39 UTC, tay1orjones commented on packages/type/scss/_scale.scss
> +
```suggestion
```

2022-08-22 21:01 UTC, merged