feat(FluidTextInput): add password input functionality
carbon-design-system/carbon pull request #12103
Opened 2022-09-15 18:42 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/12081

Adds in password functionality to `FluidTextInput` via the `isPassword` prop (open to other ideas).

#### Changelog

**New**

- `isPassword` prop added to `FluidTextInput`
- Additional styles to `fluid-text-input.scss` 
- Additional tests for `isPassword` variant
- Additional stories / controls for password input

**Changed**

- Updated `PasswordInput.js` to accommodate fluid styles

#### Testing / Reviewing

Go to `unstable_FluidTextInput` and check out the `Password Input` story.
Go to `Playground` story and enable the `isPassword` control, and verify the component works with `invalid` and `warn` styles.

2022-09-16 14:52 UTC, aagonzales requested changes
Just one bug: in the disabled state the view icon needs to be disabled as well. Its still getting a cursor and hover change. Use color token `$icon-disabled`
<img width="338" alt="image" src="https://user-images.githubusercontent.com/11670886/190667678-4e5a8b73-32ca-4253-887c-65a8a7c7bdb3.png">

2022-09-16 15:55 UTC, tw15egan commented
@aagonzales good catch, updated to fix that 👍🏻

2022-09-16 16:25 UTC, aagonzales approved these changes
🎉 ship it!

2022-09-16 21:05 UTC, abbeyhrt approved these changes

2022-09-21 22:39 UTC, aledavila approved these changes

2022-09-22 16:04 UTC, merged