feat(Listbox): add in `FluidComboBox`, `FluidMultiSelect`
carbon-design-system/carbon pull request #12163
Opened 2022-09-26 18:26 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/12120
Refs https://github.com/carbon-design-system/carbon/pull/12128

Initial PR adding in `FluidComboBox`. Branched off `FluidDropdown` PR

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2022-10-07 16:30 UTC, aagonzales requested changes
**All 3 dropdowns**
- [ ] Missing the border-bottom `$border-strong` on the `warn` states
<img width="379" alt="image" src="https://user-images.githubusercontent.com/11670886/194602596-6ec344f2-6f07-40a4-a04e-6794d39e315f.png">


**ComboBox**
- [x] Can we add the "Filter..." prompt text to the Combobox input
<img width="729" alt="image" src="https://user-images.githubusercontent.com/11670886/194599218-dd000618-dc8e-4e32-8682-51b41622b545.png">

- [ ] I wonder if we can shift the listbox down so the bottom border of the focus is still shown. Not a hill I'll die on just wondering if its possible. 

   <img width="690" alt="image" src="https://user-images.githubusercontent.com/11670886/194600446-ce6d1062-a446-47dc-865e-4181455b7a54.png">

2022-10-11 15:26 UTC, aagonzales approved these changes
Looks good! ✅ 👍

2022-10-14 20:42 UTC, abbeyhrt approved these changes

2022-10-21 13:08 UTC, tw15egan commented
cc @aledavila

2022-10-21 17:56 UTC, aledavila approved these changes

2022-10-21 19:43 UTC, merged