chore(error-boundry): rename stories file
carbon-design-system/carbon pull request #12232
Opened 2022-10-04 20:50 UTC by aledavila

Closes #12161

Rename Error Boundry story file to new file. No controls necessary.

#### Testing / Reviewing

Make sure stories are visible. No controls added

2022-10-04 20:59 UTC, abbeyhrt requested changes
Small typo in the new file name, should be `ErrorBoundary-stories.js` 🙂

2022-10-05 16:24 UTC, aledavila commented
@abbeyhrt done !

2022-10-05 16:50 UTC, tw15egan approved these changes

2022-10-10 19:34 UTC, sstrubberg approved these changes

2022-10-13 15:37 UTC, abbeyhrt approved these changes

2022-10-13 15:58 UTC, merged