fix(Type): update type tokens
carbon-design-system/carbon pull request #12284
Opened 2022-10-11 16:52 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/12174

Updates type tokens based on design issue

#### Changelog

**Changed**

- Modified the following type tokens:
  - `fluid-heading-05`
  - `productive-heading-05`
  - `fluid-heading-04`
  - `fluid-heading-03`

#### Testing / Reviewing

Check out the `@carbon/elements` preview and ensure type tokens match the spec

2022-10-12 20:19 UTC, tay1orjones approved these changes
> Closes https://github.com/carbon-design-system/carbon/issues/12174

Are the changes here for v11 enough, or does there need to be another separate PR for v10?

2022-10-18 04:03 UTC, aledavila approved these changes

2022-10-21 17:07 UTC, aagonzales requested changes
I always have a hard time checking these, so can we double check `$expressive/fluid-heading-05`? It should only be weight `400` at SM and should be `300` at all other breakpoints (according to spec in parent issue).

The rest looks good!

2022-10-21 19:03 UTC, tw15egan commented
@aagonzales fixed that 👍🏻  It is now `light` over the `sm` breakpoint

2022-10-21 19:06 UTC, aagonzales approved these changes

2022-10-21 20:54 UTC, merged