fix(react/pagination): render page number twice when `pagesUnknown` #12252
carbon-design-system/carbon pull request #12302
Opened 2022-10-14 14:03 UTC by 61130061

Closes #12252 

According to #12252, when pagesUnknown is `true`, pagination render page number as same as selector which does not make sense to render this information twice as shown in figure before. So, I change page number (pageText) to page label in front of the selector which makes more sense and make pagination looks cleaner. Also, change `pageText` prop from `function` to `string` so user can change the page label.

BREAKING CHANGE: From switching to render label instead of rendering page number twice, typeof pageText has to change from function to string because string is enough for pageText props as a page label. **This may effect users**

before:
![before_figure](https://user-images.githubusercontent.com/38994122/194210685-292b4b76-9b1f-40ec-85c1-b8528450b132.png)

after:
![after_figure](https://user-images.githubusercontent.com/54393468/195862663-e2ff75ba-4930-4062-a258-b84f364a4c3c.png)

#### Changelog

**New**

- {{new thing}}

**Changed**

- hide/show page label and total page number depend on pagesUnknown
- `pageText` default change to `page`
- typeof pageText change from `function` to `string`
- test case of pagination pagesUnknown = `true` change to expect just `page` since switch from page number to page label as shown in figures
- change border-left style form `selector` to `pagination__right`

**Removed**

- {{removed thing}}

#### Testing / Reviewing

- All test passed!

2022-10-14 14:07 UTC, 61130061 commented
I have read the DCO document and I hereby sign the DCO.

2022-10-14 14:24 UTC, tw15egan commented
@61130061 We'll need to keep this a function so that teams can pass down a function for translation keys. I think this can be fixed just by passing down ` pageText={() => ''}` to the `Pagination` component as-is. It seems like there is a slight styling issue in this scenario, but can be fixed by just adding the following CSS to `_pagination.scss`

```scss
.#{$prefix}--pagination__right .#{$prefix}--pagination__text:empty {
    margin: 0;
}

2022-10-18 17:03 UTC, tay1orjones approved these changes
One small suggested change, but overall this looks good to me. Thanks for contributing this fix!

@61130061 There are conflicts that need resolved before this can be merged

2022-10-18 17:03 UTC, tay1orjones commented on packages/react/src/components/Pagination/next/Pagination.js
> +    },
Let's match the style of the rest of the translatable function strings in this component and use an implicit return

```suggestion
    pageText = (page, pagesUnknown) => `page ${pagesUnknown ? '' : page}`,
```

2022-10-19 14:31 UTC, 61130061 commented
@tay1orjones Thank you for your approval and suggestion! I commit another `Pagination.js` with the same problem.  I think all conflicts are resolved now.

2022-10-27 01:16 UTC, tay1orjones commented
@61130061 There's still some merge conflicts here

2022-11-01 13:58 UTC, tay1orjones commented
I just fixed the merge conflicts.

@tw15egan the merge was a bit hairy, but I think I got it all. Could you review again once the deploy preview is updated?

2022-11-01 14:11 UTC, tw15egan requested changes
I think most of the merge was correct, I think these two just got added back in inadvertently

2022-11-01 14:11 UTC, tw15egan commented on packages/react/src/components/Pagination/next/Pagination.js
> +/**
I believe this file was removed in https://github.com/carbon-design-system/carbon/pull/12115

2022-11-01 14:11 UTC, tw15egan commented on packages/react/src/components/Pagination/next/__tests__/Pagination-test.js
> +/**
I believe this file was removed in https://github.com/carbon-design-system/carbon/pull/12115

2022-11-14 21:47 UTC, tay1orjones commented
@tw15egan Thanks for the catch - I just pushed a commit to remove those files

2022-11-15 14:19 UTC, tw15egan approved these changes

2022-11-15 14:52 UTC, merged