feat: readonly radio button group
carbon-design-system/carbon pull request #12412
Opened 2022-10-27 15:30 UTC by lee-chase

Contributes to #2177

Closes #12419 

Adds the read-only feature to the RadioButtonGroup component.

Note: This does not create a read-only RadioButton as having individual buttons read-only and selected makes the others readonly.

#### Changelog

**Added**

- Adds readOnly property to RadioButtonGroup and functionality
- Adds test for read-only RadioButtonGroup
- Adds styling for read-only RadioButtonGroup.
- Adds readOnly property to story

#### Testing / Reviewing

Reviewed the result in Storybook and a added read-only test.

2022-11-02 19:44 UTC, aagonzales requested changes
The visual styles look correct but the cursor interactions need to be updated:
- **As-is**: On hover the cursor is changing to a hand
- **To-be**: On hover over the icon cursor should remain an arrow and over the label text should become a type cursor. Similar to what is seen here in [Checkbox](https://github.com/carbon-design-system/carbon/pull/12398#issuecomment-1298926515).

2022-11-11 19:59 UTC, aagonzales approved these changes
Visually looks good, matches spec 👍

2022-11-14 18:23 UTC, alisonjoseph approved these changes

2022-11-14 19:47 UTC, tw15egan approved these changes

2022-11-14 20:13 UTC, merged