Readonly MultiSelect
carbon-design-system/carbon pull request #12435
Opened 2022-10-31 17:20 UTC by lee-chase

Contributes to #2177

Adds the read-only feature to the MultiSelect component.

#### Changelog

**Added**

- Adds readOnly property to MultiSelect and functionality
- Adds test for read-only MultiSelect
- Adds styling for read-only MultiSelect.

#### Testing / Reviewing

Reviewed the result in Storybook and a added read-only test.

2022-11-01 15:30 UTC, tw15egan approved these changes
LGTM 👍 ✅

2022-11-08 20:14 UTC, tay1orjones commented on packages/styles/scss/components/multiselect/_multiselect.scss
> +  $icon-disabled: $icon-disabled;
```suggestion
```

2022-11-08 20:17 UTC, tay1orjones requested changes
Minor nit on the story composition, but otherwise looks good to go!

2022-11-08 20:17 UTC, tay1orjones commented on packages/react/src/components/MultiSelect/MultiSelect.stories.js
> +    },
Instead of adding this here to all stories, interactive controls should only be added to the playground story args lower down in this file.

2022-11-08 20:19 UTC, tay1orjones approved these changes

2022-11-08 21:02 UTC, merged