fix(text-area): cols attribute
carbon-design-system/carbon pull request #12502
Opened 2022-11-04 22:44 UTC by ariellalgilmore

Closes #

#12465 

- cols was not working as expected. The `width: 100%` style was not letting user's set the amount of `cols`

#### Changelog

**Changed**

- Change the `width: 100%` to be an inline style, so now it's a conditional on if the `cols` value is set or not

**Removed**

- removed the default value of `cols: 50` because if there is no number assigned to `cols` then it should just be 100% width

#### Testing / Reviewing

- Check that all the TextArea stories show initially 100% width with no `cols` value.
- then go to the playground story and try updating the number set to `cols`
![Nov-04-2022 15-41-40](https://user-images.githubusercontent.com/20210594/200085240-4efd697e-49d6-4975-8587-54980e8addff.gif)

2022-11-07 21:09 UTC, alisonjoseph requested changes
This looks great! 

Looks like Percy is complaining because we have  `cols: 50` set in the `Form.stories` file. I think if we remove that it should show up back at the default of 100% which is what we want.

2022-11-07 22:55 UTC, ariellalgilmore commented
> This looks great!
> 
> Looks like Percy is complaining because we have `cols: 50` set in the `Form.stories` file. I think if we remove that it should show up back at the default of 100% which is what we want.

fixed!

2022-11-08 13:09 UTC, alisonjoseph approved these changes
🥳

2022-11-08 15:20 UTC, tw15egan approved these changes
LGTM 👍 ✅

2022-11-08 16:39 UTC, merged