feat(icons): renaming diamond status icon glyph
carbon-design-system/carbon pull request #12575
Opened 2022-11-08 17:32 UTC by conradennis

Old version of the icon was named "undefined" which was conflicting with another icon in the repo.

Renaming to "diamond-fill" to match the convention of other status glyph names and resolve the naming conflict.

Updated categories.yml file with new icon name.
Approved by Carbon and Brand team

#### Changelog

**Changed**

- svg/diamond-fill.svg

**Removed**

- svg/undefined.svg

2022-11-08 21:35 UTC, laurenmrice approved these changes

2022-11-09 14:59 UTC, alisonjoseph requested changes
Hey Conrad, I think you'll also need to add the Diamond fill icon to the `icons.yml `file, and remove the `- glyph` for the undefined icon in the same file since that no longer exists.

2022-11-09 15:20 UTC, conradennis commented
@alisonjoseph thanks, just made the update. Let me know if anything else needs to be done.

2022-11-11 14:15 UTC, alisonjoseph approved these changes

2022-11-15 14:38 UTC, tw15egan approved these changes

2022-11-15 15:18 UTC, merged