feat(FluidNumberInput): add `FluidNumberInput` variant
carbon-design-system/carbon pull request #12737
Opened 2022-11-28 19:39 UTC by tw15egan

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2022-12-08 16:32 UTC, tay1orjones requested changes
This looks super good! A couple minor things below.

Also, I think `packages/styles/scss/components/__tests__/number-input-test.js` (and others - `fluid-combo-box`, `fluid-multiselect`, etc.) need updated to ensure the new mixins exist. Sorry I didn't catch this before - might be something to do for all fluid inputs in a separate PR?

2022-12-08 16:32 UTC, tay1orjones commented on packages/react/src/components/FluidNumberInput/FluidNumberInput.stories.js
> +};
Could `FluidNumberInputSkeleton` be added as a subcomponent so it shows up in the prop api table on the mdx docs?

2022-12-08 16:32 UTC, tay1orjones commented on packages/react/src/components/FluidNumberInput/FluidNumberInput.stories.js
> +  // },
```suggestion
```

2022-12-08 17:11 UTC, tw15egan commented on packages/react/src/components/FluidNumberInput/FluidNumberInput.stories.js
> +};
Oh good catch, will add that

2022-12-08 17:27 UTC, tw15egan commented
I'll tackle that in a separate PR (created issue https://github.com/carbon-design-system/carbon/issues/12817) if that's alright. Pushed up changes adding all skeleton components as subcomponents to the story files

2022-12-09 16:38 UTC, tay1orjones approved these changes

2022-12-09 16:57 UTC, aagonzales reviewed
It looks good except for the label overflow (which I keep forgetting about). It needs to overflow like how we set it up in [fluid text input](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-fluidtextinput--playground). But that's the only thing I see wrong.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/11670886/206752716-0ad89dee-6ee3-4ad0-8311-a04d8896f11f.png">

2022-12-09 17:39 UTC, tw15egan commented
@aagonzales I'll update this one here, and I've created a new issue (https://github.com/carbon-design-system/carbon/issues/12825) to track the rest of the components and will add the same styles to all of them in a separate PR

2022-12-09 19:01 UTC, aagonzales reviewed
That looks good! One more change after talking to Jeannie, we want to just use the regular `$body-compact-01` here instead of the mono `$code-01`. She wants to change it in the fixed version as well.

2022-12-12 14:33 UTC, alisonjoseph approved these changes
LGTM!

2022-12-12 17:07 UTC, tw15egan commented
@aagonzales updated 👍🏻

2022-12-12 19:22 UTC, aagonzales commented
@tw15egan it does look like the number are appearing in Plex.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/11670886/207135338-09429b53-aac8-4057-a297-0fb39c20798f.png">


What the plex number should look like
<img width="233" alt="image" src="https://user-images.githubusercontent.com/11670886/207135379-42609b40-81c9-4a55-b96c-dc89fbec6370.png">

2022-12-12 19:59 UTC, tw15egan commented
@aagonzales good catch, forgot number inputs reset their own styles, and it was using the browser default. Updated it, so it should not load in IBM Plex Sans

2022-12-12 22:32 UTC, aagonzales approved these changes
Perfect! Ship it!

2022-12-13 14:41 UTC, merged