feat(FluidSearch): scaffold out files, initial styles
carbon-design-system/carbon pull request #12866
Opened 2022-12-15 16:18 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/12456

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2022-12-15 20:22 UTC, aagonzales requested changes
In the disabled state, the label needs to also change to `$text-disabled` and the border-bottom should still be shown but as `$border-subtle`

<img width="473" alt="image" src="https://user-images.githubusercontent.com/11670886/207959031-ecb99b1d-abed-49e1-bacb-5e5e23c7d5ce.png">


I also don't think search needs the tooltip, I don't think its a feature normally associated with a search field.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/11670886/207959320-d702cfec-a41d-4892-a80a-8c6dc4e85354.png">

2022-12-16 14:23 UTC, tw15egan commented
@aagonzales updated 👍

2022-12-16 14:36 UTC, tay1orjones approved these changes
I made a couple minor comments below. Overall looks great! 🎉

2022-12-16 14:36 UTC, tay1orjones commented on packages/react/src/components/FluidSearch/FluidSearch.js
> +  autoComplete: PropTypes.string,
Should we still provide the default within this component? I think without them we won't see the defaults in the storybook documentation and prop tables, etc.

2022-12-16 14:36 UTC, tay1orjones commented on packages/react/src/components/FluidSearch/FluidSearch.js
> +  role: PropTypes.string,
Same thing here with the defaults.

2022-12-16 16:16 UTC, aagonzales approved these changes
Nice, looks good to me now!

2022-12-19 17:58 UTC, alisonjoseph approved these changes

2022-12-19 18:46 UTC, tw15egan commented
@tay1orjones added, thanks for the suggestion 👍🏻

2022-12-19 21:42 UTC, merged