Experimental select
carbon-design-system/carbon pull request #1286
Opened 2018-10-18 19:51 UTC by chrsfshr

Closes #1211 

Adds in Experimental Select Component

Preview link: ....

2018-10-18 20:15 UTC, alisonjoseph commented on src/components/select/_select.scss
> +    }
```suggestion
    &:focus {
      outline: 2px solid $focus;
      box-shadow: none;
    }
```

Using a border is causing a shift in width, would be good to swap to outline.

2018-10-18 20:16 UTC, alisonjoseph commented on src/components/select/_select.scss
> +      color: $brand-01;
```suggestion
      color: $focus;
```

2018-10-18 20:17 UTC, alisonjoseph commented
Couple comments around focus state but otherwise LGTM!

2018-10-18 21:27 UTC, alisonjoseph commented on src/components/select/_select.scss
> +    grid-template-columns: auto auto;
Does this work cross-browser? Probably better to use flexbox here

2018-10-18 21:28 UTC, joshblack requested changes
Looks great so far! Would echo @alisonjoseph's comments, and then also suggest we try and avoid the nested selectors under the `--select-input` selector.

2018-10-19 22:37 UTC, dakahn commented
Hi. Testing on Chrome 69 on a Macbook using the aXe extension I found a few accessibility bugs:

- [ ] Looks like the color contrast on the Inline Select's label is too light. At 3.36:1 contrast for normal sized text it falls below WCAG AA spec. We're going to want closer to 4.50:1

- [ ] The color contrast for the category headings in the drop down itself is also far too light. Though I can't actually test the ratio on those menu items.

- [ ] Similar to the first point, Inline Select (Invalid) has the aforementioned color contrast label issues

- [ ] When the list box is in focus enter on the keyboard should expand the box.

For keyboard navigation reference [here's the relevant W3 page](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html)

2018-10-19 22:45 UTC, dakahn requested changes
Testing on Chrome 69 on a Macbook using the aXe extension I found a few accessibility bugs:

- [ ] Looks like the color contrast on the Inline Select's label is too light. At 3.36:1 contrast for normal sized text it falls below WCAG AA spec. We're going to want closer to 4.50:1

- [ ] The color contrast for the category headings in the drop down itself is also far too light. Though I can't actually test the ratio on those menu items.

- [ ] Similar to the first point, Inline Select (Invalid) has the aforementioned color contrast label issues

- [ ] When the list box is in focus enter on the keyboard should expand the box.

For keyboard navigation reference [here's the relevant W3 page](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html)

@aagonzales FYI the label text is too light for inline select.

2018-10-19 22:52 UTC, alisonjoseph commented
@dakahn Can you check against a white background and see if the label contrast issue is still there. Unfortunately our dev env. isn't updated yet and still renders all of these on the gray.

2018-10-19 22:53 UTC, alisonjoseph commented
@chrsfshr can you add a preview link and let Anna know when its up

2018-10-19 22:54 UTC, alisonjoseph commented
nvm @dakahn it is on a white background. sorry

2018-10-19 22:56 UTC, dakahn commented
@alisonjoseph No sweat! For the record I double checked any contrast errors using the [WebAIM Contrast Checker.](https://webaim.org/resources/contrastchecker/) which gave me specific ratios against AA/AAA spec.

2018-10-19 22:59 UTC, alisonjoseph commented
@dakahn Yep! thats what I use too, I tagged Anna above to take a look at updating it.

2018-10-19 22:59 UTC, alisonjoseph commented
@aagonzales 
<img width="747" alt="screen shot 2018-10-19 at 5 59 35 pm" src="https://user-images.githubusercontent.com/2753488/47247361-c95c7600-d3c8-11e8-8e8b-6a3f80a086ac.png">

2018-10-20 03:21 UTC, alisonjoseph commented
Yea, the standard browser styles show up like this. Not sure how to handle the color contrast issue here. 
<img width="719" alt="screen shot 2018-10-19 at 10 20 17 pm" src="https://user-images.githubusercontent.com/2753488/47250772-3eda3d80-d3ed-11e8-984f-8d85f07944eb.png">

2018-10-29 15:32 UTC, closed without merging