refactor(react): convert `Search` to TypeScript
carbon-design-system/carbon pull request #12998
Opened 2023-01-20 19:59 UTC by metonym

Closes #12553

#### Changelog

**Changed**

- refactor(react): convert `Search` to TypeScript

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-01-23 20:30 UTC, francinelucca commented
Hey @metonym 👋🏼, thanks for contributing this! One minor ask - instead of renaming the .js file to .tsx, could you actually rename it using git?

`git mv packages/react/src/components/Search/Search.js packages/react/src/components/Search/Search.tsx`

This way the diff will clearly show the file extension change but also the proper unified diff showing your changes within file.

Right now it's hard to tell what you've added to the file vs was was in it to begin with.

2023-01-23 20:39 UTC, tay1orjones requested changes
@metonym thanks! Could you rename the file via `git mv` so the diff is more readable? Right now a totally red `.js` and a completely green `.tsx` makes it hard to know what changed vs what was there before.

2023-01-23 22:03 UTC, metonym commented
@francinelucca Thanks for the feedback. When I ran the `git mv` command, it successfully displayed it as [one change](https://github.com/carbon-design-system/carbon/pull/12998/commits/de826447e1e62b97e7754f63835a5628863a3d34). However, after applying the actual changes to `Search.tsx`, it appears as two separate files again.

2023-01-24 15:46 UTC, francinelucca requested changes
Minor suggestion, other than that LGTM

2023-01-24 15:46 UTC, francinelucca commented on packages/react/src/components/Search/Search.tsx
> +  closeButtonLabelText?: string;
```suggestion
  /**
   * Specify a label to be read by screen readers on the "close" button
   * @default "Clear search input"
   */
  closeButtonLabelText?: string;
```

2023-03-23 00:23 UTC, aledavila commented
Bump. Looks like there are some merge conflicts @metonym to fix ! TIA

2023-03-24 19:07 UTC, tay1orjones approved these changes

2023-03-25 00:12 UTC, metonym commented
Thanks for the nudge – resolved conflicts in this commit: adf2045cb4c3ad6ed35d6b72b9ac437ebd4c9bd4

2023-03-27 16:20 UTC, francinelucca commented
Looks like a couple tests are failing for search now @metonym

2023-03-31 14:36 UTC, aledavila commented
Hey @metonym. Thanks so much for working on this contribution! We’d really like to get this merged but with the current test failures it’s not able to merge. If we can resolve those in the next few days we can merge, otherwise we’ll close this for inactivity.

2023-04-26 16:59 UTC, metonym commented
Closed by #13533

2023-04-26 16:59 UTC, closed without merging