feat: add create-react-app template to build apps with IBM Carbon
carbon-design-system/carbon pull request #13002
Opened 2023-01-23 08:10 UTC by Shankar-CodeJunkie

Closes #12598

Provided a Create React App template, so that it's easy for someone to spin up an app with everything you need to start building with Carbon.

**Changed**

- Used the content and the  design of the carbon tutorial
- Included theme switching example as part of it
- UIShell with a basic CSS Grid layout
- Use a Stack within Grid
- Provided basic unit tests for all the components. 

#### Testing / Reviewing

I tested the cra template locally using the file location of the template, and could see the app spinning up with Carbon design. 

`npx create-react-app my-app --template file:../carbon-bootstrapv1/ `

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/56068832/213991860-4f29ca97-b833-4457-a707-b0035b83b772.png">

2023-01-24 16:16 UTC, francinelucca requested changes
Confirmed can spin up and run an application using test script 🎉.

Just some suggestions.

@Shankar-CodeJunkie This PR seems to tackle bullet 1 of 3 in #12598  (correct me if I'm wrong), can we please switch out the `Closes` in the PR description for a reference? thanks!

2023-01-24 16:16 UTC, francinelucca commented on packages/cra-template/template/src/components/Header/Header.test.js
> +afterEach(cleanup);
```suggestion
import AppHeader from "./Header";
afterEach(cleanup);
```

2023-01-24 16:16 UTC, francinelucca commented on packages/cra-template/template/src/content/HomePage/Homepage.test.js
> +    //swith another tab;
```suggestion
    //switch to another tab;
```

2023-01-24 16:16 UTC, francinelucca commented on packages/cra-template/template/src/content/HomePage/Homepage.test.js
> +    //swith another tab;
```suggestion
    //switch to another tab;
```

2023-01-24 16:16 UTC, francinelucca commented on packages/cra-template/template/src/index.js
> +);*/
```suggestion
```

2023-01-24 16:16 UTC, francinelucca commented on packages/cra-template/README.md
> +# Getting Started with Create React App
is this the correct Heading title?

2023-01-24 16:16 UTC, francinelucca commented on packages/cra-template/README.md
> +
Should this README also include info on how to spin up an application using this template?

2023-01-24 16:23 UTC, tay1orjones commented
I just pushed an update to improve the readme docs and a few fields in the package.json

2023-01-24 16:23 UTC, tay1orjones commented on packages/cra-template/README.md
> +# Getting Started with Create React App
Fixed

2023-01-24 16:24 UTC, tay1orjones commented on packages/cra-template/README.md
> +
Fixed

2023-01-24 16:30 UTC, tay1orjones commented
I just pushed two more updates that correctly format the files, include the workspace dependency in the `yarn.lock`, and excludes the package from the global eslint requirements.

2023-02-02 17:04 UTC, francinelucca requested changes
Minor cleanup that I missed the first time, otherwise this looks good!
Still think we should modify the description so that the #12598 doesn't autoclose @Shankar-CodeJunkie

2023-02-02 17:04 UTC, francinelucca commented on packages/cra-template/template/src/content/RepoPage/RepoPage.js
> +    //console.log('hey man')
```suggestion
```

2023-02-02 17:04 UTC, francinelucca commented on packages/cra-template/template/src/content/RepoPage/RepoPage.js
> +    //console.log('hey man1', data);
```suggestion
```

2023-02-03 17:57 UTC, francinelucca approved these changes
🚀🔥

2023-02-06 16:10 UTC, tay1orjones approved these changes
@carbon-design-system/developers Since this is a new package, I'm not sure how lerna will treat this at the next release - it may pull through without issue, but it's possible it may not publish properly. We'll need to keep an eye on it during the next release.

2023-02-07 17:02 UTC, merged

2023-02-08 22:06 UTC, sstrubberg commented
@Shankar-CodeJunkie Are you an IBMer? I would love to send you some recognition! What's your Slack handle?

2023-02-10 13:58 UTC, Shankar-CodeJunkie commented
@sstrubberg :  Yes .. You can reach me at ```@Shankar Venkatachalam ``` in slack.