fix: combobox focus input
carbon-design-system/carbon pull request #13070
Opened 2023-02-01 18:05 UTC by andreancardona

Closes #9776 

Adds input focus when opening and collapsing menu

- [ ] Make sure when toggling the up/down arrow the input receives focus

2023-02-02 15:06 UTC, tw15egan approved these changes

2023-02-02 16:25 UTC, francinelucca requested changes
Looks good! one minor code suggestion

2023-02-02 16:25 UTC, francinelucca commented on packages/react/src/components/ComboBox/ComboBox.js
> +          setIsFocused(evt.type === 'focus' ? true : false);
is the ternary necessary here? 🤔
```suggestion
          setIsFocused(evt.type === 'focus');
```

2023-02-07 22:48 UTC, francinelucca approved these changes
🚀

2023-02-08 22:17 UTC, merged