feat(theme): add $icon-interactive token
carbon-design-system/carbon pull request #13219
Opened 2023-02-23 17:18 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/13217

Adds a new `$icon-interactive` token

White and Gray 10 theme: Blue 60 `#0f62fe`

Gray 90 and Gray 100 theme: White `#ffffff`

#### Changelog

**New**

- `$icon-interactive` added to all themes

**Changed**

- Updated snapshots

#### Testing / Reviewing

Ensure token values are correct for each theme

2023-02-23 18:51 UTC, alisonjoseph requested changes

2023-02-23 18:51 UTC, alisonjoseph commented on packages/themes/src/tokens/v11TokenGroup.js
> +    'icon-inverse',
should this be icon-interactive?
```suggestion
    'icon-interactive',
```

2023-02-23 18:51 UTC, alisonjoseph commented on packages/themes/src/tokens/__tests__/metadata-test.js
> +          "name": "icon-inverse",
```suggestion
          "name": "icon-interactive",
```

same with this?

2023-02-23 18:52 UTC, tw15egan commented on packages/themes/src/tokens/v11TokenGroup.js
> +    'icon-inverse',
yeah whoops! 🙃  Thanks for catching

2023-02-23 18:54 UTC, tw15egan commented on packages/themes/src/tokens/__tests__/__snapshots__/v11-test.js.snap
> +  "icon-inverse",
```suggestion
  "icon-interactive",
```

2023-02-23 18:54 UTC, tw15egan commented on packages/themes/src/tokens/__tests__/__snapshots__/v11-test.js.snap
> +  "icon-inverse",
```suggestion
  "icon-interactive",
```

2023-02-23 19:31 UTC, tw15egan commented
@alisonjoseph should be fixed now, thanks for catching that 😅

2023-02-23 19:39 UTC, alisonjoseph approved these changes
🚀

2023-02-23 20:39 UTC, francinelucca approved these changes

2023-02-23 20:49 UTC, tay1orjones approved these changes

2023-02-23 20:49 UTC, tay1orjones commented
@tw15egan Any idea why the elements preview didn't deploy for this PR? I was going to check it but it's not listed 🤔

2023-02-23 20:51 UTC, tw15egan commented
@tay1orjones I just checked a few other PR's and I'm not seeing it on any of them ... 😬

2023-03-01 14:04 UTC, tw15egan commented
@thyhmdo this should be ready for review now 👍🏻

2023-03-02 16:19 UTC, thyhmdo approved these changes
looks good. Thanks!

2023-03-02 17:32 UTC, merged