chore: add postinstall deprecation warning to old packages
carbon-design-system/carbon pull request #13304
Opened 2023-03-07 20:20 UTC by francinelucca

Closes #12495 

Adds deprecation warnings to `carbon-components` and `carbon-components-react`

#### Changelog

**New**

- packages/carbon-components-react/scripts/postinstall.js: script to log deprecation warning message
- packages/carbon-components/scripts/postinstall.js: script to log deprecation warning message

**Changed**

- packages/carbon-components-react/package.json: call `postinstall` script, add `chalk` dependency
- packages/carbon-components/package.json:  call `postinstall` script, add `chalk` dependency

#### Testing / Reviewing

You can test manually by running `yarn run postinstall`  inside the packages dirs: `packages/carbon-components-react` and `packages/carbon-components`
<img width="952" alt="image" src="https://user-images.githubusercontent.com/40550942/223543056-e6e19677-39de-4b77-bd65-cf24052d2077.png">

2023-03-16 04:54 UTC, aledavila approved these changes
lgtm. can see it when running. just some merge conflicts

_thats the longest branch name i've ever seen 😆 _

2023-03-16 18:24 UTC, tay1orjones requested changes
We'll still be updating these packages while we're on v11.x, so just a couple suggestions on the phrasing of the message to reflect that.

2023-03-16 18:24 UTC, tay1orjones commented on packages/carbon-components-react/scripts/postinstall.js
> +    " is soon to be deprecated and is no longer receiving updates, we recommend to move to it's replacement, " +
```suggestion
    " will soon be deprecated and no longer receive updates. We recommend to move to it's replacement, " +
```

2023-03-16 18:24 UTC, tay1orjones commented on packages/carbon-components/scripts/postinstall.js
> +    " is soon to be deprecated and is no longer receiving updates, we recommend to move to it's replacement, " +
```suggestion
    " will soon be deprecated and no longer receive updates. We recommend to move to it's replacement, " +
```

2023-03-17 16:22 UTC, tay1orjones approved these changes

2023-03-17 16:39 UTC, merged