refactor: add types to props in PasswordInput
carbon-design-system/carbon pull request #13311
Opened 2023-03-08 16:50 UTC by shryoo-ibm

Closes #12550 #12513 

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-03-08 19:20 UTC, shryoo-ibm commented
I have read the DCO document and I hereby sign the DCO.

2023-03-16 19:57 UTC, tay1orjones requested changes
Just one suggestion, otherwise I think this looks good!

2023-03-16 19:57 UTC, tay1orjones commented on packages/react/src/components/TextInput/PasswordInput.tsx
> +    : PropTypes.oneOf(['sm', 'md', 'lg', 'xl']),
This feature flag will always `true` now that we've released v11. This toggle could be removed entirely. The type definition should be updated as well. `xl` is no longer a valid value.

2023-03-16 20:52 UTC, shryoo-ibm commented on packages/react/src/components/TextInput/PasswordInput.tsx
> +    : PropTypes.oneOf(['sm', 'md', 'lg', 'xl']),
Got it, I was a bit confused about that so the clarification is a big help!

2023-03-17 14:49 UTC, tay1orjones approved these changes
Looks great, thanks! 🎉

2023-03-17 14:49 UTC, tay1orjones commented
@shryoo-ibm looks like there's a minor conflict to resolve - just regen the allcontributors probably

2023-03-17 15:04 UTC, alisonjoseph approved these changes

2023-03-23 00:22 UTC, aledavila commented
bump @shryoo-ibm looks like you have some minor conflicts to fix :) then we can review thanks!

2023-03-24 18:50 UTC, tay1orjones approved these changes
Looks good to me 👍 thanks!

2023-03-30 18:09 UTC, merged