refactor(typescript): Convert TableHead, TableHeader to tsx
carbon-design-system/carbon pull request #13367
Opened 2023-03-17 08:51 UTC by pratikkarad

Closes #12527, #12528

Converts TableHead and TableHeader to tsx in preparation for the main Table conversion

#### Changelog

**Changed**

- Converted TableHead.js -> TableHead.tsx
- Converted TableHeader.js -> TableHeader.tsx

#### Testing / Reviewing

To verify these changes are working, we can check to see if the existing storybook behavior is still working correctly. Should be able to properly import converted components in a TS environment

2023-03-17 15:35 UTC, francinelucca requested changes
Thanks for putting this together @pratikkarad! Just one change request regarding the `thead` interface. also looks like some of the CI checks are failing

2023-03-17 15:35 UTC, francinelucca commented on packages/react/src/components/DataTable/TableHead.tsx
> +export type TableHeadProps = ThHTMLAttributes<HTMLTableCellElement>;
should this be an `HTMLTableSectionElement` instead? https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement. Doesn't look like `thead` is considered an HTMLTableCellElement https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement
```suggestion
export type TableHeadProps = ThHTMLAttributes<HTMLTableSectionElement>;
```

2023-03-17 18:47 UTC, pratikkarad commented on packages/react/src/components/DataTable/TableHead.tsx
> +export type TableHeadProps = ThHTMLAttributes<HTMLTableCellElement>;
Thanks for pointing it out. I have updated the code.

2023-03-17 18:55 UTC, pratikkarad commented on packages/react/src/components/DataTable/TableHeader.tsx
> +  const ariaSort = !isSortHeader ? 'none' : sortDirection ? sortDirections[sortDirection] : sortDirections[sortStates.NONE];
It is still failing here. I tried debugging but got no luck. Any help or suggestion is appreciated. 😃

2023-03-20 16:28 UTC, francinelucca commented on packages/react/src/components/DataTable/TableHeader.tsx
> +  const ariaSort = !isSortHeader ? 'none' : sortDirection ? sortDirections[sortDirection] : sortDirections[sortStates.NONE];
let's change this line to ` const ariaSort = (!isSortHeader || !sortDirection) ? 'none' : sortDirections[sortDirection];`

and change the type of `sortDirections` in the top to 
```
const sortDirections: {[key: string]: 'none' | 'ascending' | 'descending'} = {
  [sortStates.NONE]: 'none',
  [sortStates.ASC]: 'ascending',
  [sortStates.DESC]: 'descending',
};
```


That should fix this issue

2023-03-22 06:57 UTC, pratikkarad reviewed
.

2023-03-22 16:18 UTC, francinelucca commented
> Hi @francinelucca, I'm facing a problem with declaring the static properties on the functional component in typescript. For eg. `TableHeader.translationKeys = Object.values(translationKeys);` In TableHeader, `translationKeys` is giving the compilation error. I tried creating a separate type as suggested on StackOverflow/blogs, but still got no luck.

can you try doing `(TableHeader as any).translationKeys = Object.values(translationKeys);`

2023-03-22 17:30 UTC, francinelucca approved these changes

2023-03-23 00:27 UTC, aledavila approved these changes

2023-03-23 00:58 UTC, merged