fix(MultiSelect): remove enter key select
carbon-design-system/carbon pull request #13362
Opened 2023-03-16 13:13 UTC by pratikkarad

Closes #13119 

**Removed**

- Removed additional `Enter` key from MultiSelect keyboard selection

2023-03-16 13:17 UTC, prakarsh70 commented
I have read the DCO document and I hereby sign the DCO.

2023-03-16 13:20 UTC, prakarsh70 approved these changes
LGTM.

2023-03-16 14:06 UTC, tw15egan requested changes
It looks like there is a linting error (`MenuKeyDownEnter` can be removed if it is not used), and the tests need to be updated to account for the new behavior (can change the failing tests truthiness)

2023-03-16 14:31 UTC, pratikkarad commented
Hey @tw15egan, I have corrected the lint error and test cases.
I had a question regarding running scoped test cases because it takes too much time to run the whole test suite.
Any suggestion on how do I run test suite only for a specific package?

2023-03-16 15:15 UTC, tw15egan commented
@pratikkarad yeah, running the whole test suite is time-consuming. You can run specific tests by running this command from the root of the monorepo: 

`yarn test packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js --watch`

If you use VS Code, you can also install the `Jest` extension, which lets you run specific tests inside the editor.

2023-03-16 15:31 UTC, pratikkarad commented
Thanks for the suggestion. I have updated the PR. PTAL, Thanks!

2023-03-16 17:29 UTC, tw15egan commented on packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js
> +    );
```suggestion
```

We can probably just remove this. I didn't see that the block below it is the same. We should also rename this test to say `should not toggle selection with enter`

2023-03-21 14:38 UTC, tw15egan approved these changes

2023-03-21 18:40 UTC, tay1orjones approved these changes

2023-03-21 19:39 UTC, merged