fix(UIShell): add bg color to selected states
carbon-design-system/carbon pull request #13385
Opened 2023-03-21 18:05 UTC by jsehull

Closes #10132 

Add desired background colors for **selected** menu-items

@aagonzales helped confirm the story above just needs proper background color to bring it up to spec. Let me know if there are any other design requirements!

#### Changelog

**New**

- add background colors for both selected states ("selected" and "selected + hover")

**Changed**

- n/a

**Removed**

- n/a

#### Testing / Reviewing
1. open `UIShell.stories.js` and find `HeaderBaseWNavigation`
2. add `isCurrentPage` to a `HeaderMenuItem` under both `HeaderNavigation`(desktop) and `SideNav`(mobile) 
![image](https://user-images.githubusercontent.com/9935383/226699660-4f40e9e4-28a5-4b56-b805-66a6cd4eaa78.png)
3. visit Storybook > UI Shell > Header Base w/Navigation to confirm updates for desktop and mobile now display as designed

Please reference the issue for design details.

2023-03-21 20:52 UTC, aagonzales commented
@jsehull My dev skills aren't good enough to test the change locally. Could you post some screenshots of the selected state? The token look right in code, I just want to double-check the visuals

2023-03-21 21:09 UTC, aagonzales commented
@jsehull  Thank you! Just one thing, it doesn't look like the blue vertical bar is extending the full height of the container... I think this was probably an existing bug, but can you fix it?

<img width="82" alt="image" src="https://user-images.githubusercontent.com/11670886/226741502-efb74084-732b-4e53-94b3-b61b5ff2b64d.png">

2023-03-22 14:28 UTC, jsehull commented
👍 I can have a fix on the SUBMENU items by removing the border for submenu items ONLY (which is `2px` all around).

But now I'm seeing the same is true for the MENU items (both horizontal and vertical layouts). 
![image](https://user-images.githubusercontent.com/9935383/226933326-58875516-2ae6-4e31-bfd7-aeaa86aea10a.png)
![image](https://user-images.githubusercontent.com/9935383/226934216-eef21812-946e-4bbe-a628-ac0a70d1df37.png)

@aagonzales Is this an issue as well? If so, do we need borders on these? I'm not familiar with all of the downstream impact on states or other IBM implementation this would have. Maybe some developer input is good too.

Options
- static changes to absolute positioning/width if needed
- dynamic - remove border so blue line is always 100% length

If this is simple, I guess we can add it on. If it requires a longer discussion, I'd be glad to help put in a PR on a new issue. Let me know what you'd like!

2023-03-22 18:40 UTC, tw15egan commented
You can also fake it with the pseudo element, I just bumped up the width to `calc(100% + 4px)` to account for the `2px` focus border on each side, and set `left` to `-2px` to set it equal to the transparent border. 

<img width="834" alt="Screenshot 2023-03-22 at 2 36 26 PM" src="https://user-images.githubusercontent.com/11928039/227004397-8550b75b-38e7-48cb-90f2-1ff122f78fa2.png">


The same can probably be done with the vertical `current` indicator, just adjusting the `height` and the `top` values

2023-03-23 15:05 UTC, jsehull commented
They should be full length "border highlights" now @aagonzales 

![image](https://user-images.githubusercontent.com/9935383/227245588-2d1776c6-a865-4002-8ac7-522669b2101d.png)

![image](https://user-images.githubusercontent.com/9935383/227245949-3ec8a0c0-0aba-4447-9c26-1ea60ade0840.png)

2023-03-23 16:17 UTC, aagonzales approved these changes
Looks good to me! Thanks for working on this!

2023-03-23 16:24 UTC, aagonzales requested changes
Oh wait, I just saw the other comments and doubled check some things. It looks like the selected state is not remaining when the shell responds down the to left nav. 
![Mar-23-2023 11-22-04](https://user-images.githubusercontent.com/11670886/227269464-f0d07d52-c2c5-4c54-bea3-26d124645cbb.gif)

2023-03-23 20:12 UTC, jsehull commented
Thanks for clarifying, I'll get that sorted out

2023-03-24 14:25 UTC, closed without merging

2023-03-24 15:44 UTC, jsehull commented
Sorry for the confusion team, this PR continues over at #13402