feat(checkbox): add checkbox group and validation states
carbon-design-system/carbon pull request #13394
Opened 2023-03-23 06:33 UTC by aledavila

Closes #12645 

Implementation for CheckboxGroup and validation states 

#### Changelog

**New**

- added new `CheckboxGroup` component
- added `helperText` `invalid` `readOnly` and `warn` to `CheckboxGroup`

**Changed**

- Updated stories to apply new `CheckboxGroup`

#### Testing / Reviewing

Make sure props work as intended.

2023-03-24 17:55 UTC, aagonzales requested changes
Looks good, except the state icons are off my 1px. Should be 2px left and right (its 3px left, 1px right atm)

<img width="180" alt="image" src="https://user-images.githubusercontent.com/11670886/227603252-640a9cd4-5596-4962-961c-7e26e3221177.png">

2023-03-27 16:50 UTC, francinelucca approved these changes
LGTM, do we need to add a test file for `CheckboxGroup` ? or would that be tracked elsewhere?

2023-03-29 22:22 UTC, aledavila commented
Yup pushed now @francinelucca thanks for the reminder

2023-03-30 17:02 UTC, francinelucca approved these changes
Minor wording suggestions

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/Checkbox/__tests__/Checkbox-test.js
> +  it('should be set data-invalid when invalid prop is true', () => {
```suggestion
  it('should set data-invalid when invalid prop is true', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/Checkbox/__tests__/Checkbox-test.js
> +  it('should be respect readOnly prop', () => {
```suggestion
  it('should respect readOnly prop', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/Checkbox/__tests__/Checkbox-test.js
> +  it('should be respect warn prop', () => {
```suggestion
  it('should respect warn prop', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/Checkbox/__tests__/Checkbox-test.js
> +  it('should display warnText if message is true', () => {
```suggestion
  it('should display warnText if warn prop is true', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/CheckboxGroup/CheckboxGroup-test.js
> +  it('should be set data-invalid when invalid prop is true', () => {
```suggestion
  it('should set data-invalid when invalid prop is true', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/Checkbox/__tests__/Checkbox-test.js
> +  it('should display invalidText if message is true', () => {
```suggestion
  it('should display invalidText if invalid prop is true', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/CheckboxGroup/CheckboxGroup-test.js
> +  it('should display invalidText if message is true', () => {
```suggestion
  it('should display invalidText if invalid prop is true', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/CheckboxGroup/CheckboxGroup-test.js
> +  it('should be respect readOnly prop', () => {
```suggestion
  it('should respect readOnly prop', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/CheckboxGroup/CheckboxGroup-test.js
> +  it('should be respect warn prop', () => {
```suggestion
  it('should respect warn prop', () => {
```

2023-03-30 17:02 UTC, francinelucca commented on packages/react/src/components/CheckboxGroup/CheckboxGroup-test.js
> +  it('should display warnText if message is true', () => {
```suggestion
  it('should display warnText if warn prop is true', () => {
```

2023-03-30 17:07 UTC, aledavila commented
@tay1orjones @tw15egan ready for review. 

@aagonzales I think we said that the 3px was fine

2023-03-30 18:33 UTC, aagonzales approved these changes
Yup we measured it and 3px is actually correct due to the checkbox construction.

2023-03-31 12:45 UTC, tw15egan approved these changes
Looks awesome! 👍🏻 ✅

2023-03-31 15:50 UTC, merged