fix(Modal): add proper right padding to header
carbon-design-system/carbon pull request #13409
Opened 2023-03-27 19:29 UTC by jsehull

Closes #13228 

Ensure Heading has proper padding alignment to match design specs shown here
![image](https://user-images.githubusercontent.com/9935383/228045457-276cf778-7092-455c-a97e-3402540231bf.png)

Currently, only the paragraph text has the 20% right padding layout

#### Changelog

**New**

- add 20% `padding-right` for the Header text to match the `p` text

**Changed**

- n/a

**Removed**

- n/a

#### Testing / Reviewing

1. Open Storybook > Modal > Default (or any version)
2. Inspect the `h3` Header and confirm there is now right padding
![image](https://user-images.githubusercontent.com/9935383/228045947-064387d9-eb0e-416a-8b09-46ebe3a1f559.png)
3. Also note that the padding values match the `p` tag below since they maintain an equal cutoff point (only IF there is a description area on that modal variation)

2023-03-28 13:48 UTC, francinelucca requested changes
Looks like the header is more padded than the content here
<img width="654" alt="image" src="https://user-images.githubusercontent.com/40550942/228257371-c98d9b8c-c896-42ca-ad2e-8cb1f810d7d6.png">

Should the padding-right be reduced by `3rem` since the modal header is padded-right by 3rem?
<img width="243" alt="image" src="https://user-images.githubusercontent.com/40550942/228258228-c20373bd-2e72-4af3-9253-76c70bb16056.png">

I also think the content is over-padded by `1rem`. Since it is right-padded `1rem` but then the `p` tag is reducing `2rem` from the 20%
<img width="244" alt="image" src="https://user-images.githubusercontent.com/40550942/228258542-2bb03513-95c9-4e0d-9b08-a1f18bdbf893.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/40550942/228258613-b3552abf-5011-4fbc-9b98-9ceeadcacc1d.png">

2023-03-28 20:39 UTC, jsehull commented
@francinelucca Good eye, it does need to account for that right side padding. 

Your question had me dig for how the `padding-right` percentages work currently. Here's what I found when testing a consistent length:

___
Calculation info
type: (total `padding-right`)/full div length = right padding % | calculation used
**i.e. `padding-right` sum of both the item (h3) and outer div
__

`h3`
current: (99.2 + 3rem)/720 = 20.44% | `20% - 2rem` (current as of this PR)
perfect: (96 + 3rem)/720 = 20% | `20% - 2.2rem`

`p`
current: (105.7 + 1rem)/720 = 16.88% | `20% - 2rem`
perfect: (128 + 1rem)/720 = 20% | `20% - 0.6rem`


The header was close, but the `p` text area was further off, which is probably why you caught it so fast.
___
Shall I update them both to use the "perfect 20%" or use a simpler rem calculation? (i.e. p: `20% - 1rem` = 19.1%, h3: `20% - 2rem` = 20.44%) I didn't know if that makes it easier to understand/maintain.

2023-03-29 15:15 UTC, francinelucca requested changes
Thanks for that detailed explanation @jsehull. let's just deduct an extra rem in the header and that should be good enough.

2023-03-29 15:15 UTC, francinelucca commented on packages/styles/scss/components/modal/_modal.scss
> +    padding-right: calc(20% - $spacing-07);
```suggestion
    // padding should take into account the left and right padding of modal container
    padding-right: calc(20% - $spacing-09);
```

2023-03-29 16:14 UTC, jsehull commented on packages/styles/scss/components/modal/_modal.scss
> +    padding-right: calc(20% - $spacing-07);
Simple - sounds good

2023-03-29 20:32 UTC, francinelucca approved these changes

2023-03-31 14:25 UTC, aledavila approved these changes

2023-03-31 15:20 UTC, merged