feat(Tabs): add renderIcon prop
carbon-design-system/carbon pull request #13427
Opened 2023-03-29 20:26 UTC by francinelucca

Closes #12844 

Specs:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/40550942/228659150-26559d2d-638b-4e11-bff5-f49cbd5a4c26.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/40550942/228659177-496874dc-c597-4f59-b6c2-fa7728cdb2fc.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/40550942/228659270-6808ce3e-ca1e-49e9-9527-097d5e76a895.png">

#### Changelog

**New**

- Adds `renderIcon` prop to `Tab`
- Adds e2e and RTL testing for new Icon use cases
- Adds 3 new Tab stories to demonstrate new renderIcon use cases

**Changed**

- Refactors `hasSecondaryLabel` prop to be consumed through the `TabContext` instead (This is a prop that's meant for internal use only and makes more sense to have it within the context)
- Renamed `IconTab`'s Icon class from `${prefix}--tabs__nav-item--icon` to `${prefix}--tabs__nav-item--icon-only`

#### Testing / Reviewing

See deployed stories, compare to spec:
- With Icons
- Contained With Icons
- Contained With Secondary Labels and Icons

2023-03-30 19:30 UTC, aledavila approved these changes

2023-04-06 20:13 UTC, laurenmrice requested changes
@francinelucca this looks good! Just three things:

- The tab labels should be sentence-case. So instead of "Tab Label 1", lets say "Tab label 1".
- The only small thing I see is a shift in the icon position when going between the "Contained with icons" story and the "Contained with Secondary Labels" story. It might be a 1px difference.
![Apr-06-2023 16-00-25](https://user-images.githubusercontent.com/43969356/230483970-48774347-67d7-4c26-8ecf-835ac91e20b6.gif)
- I also noticed the Default tabs do not have a hover state change (this may be unrelated to this PR and I can make a separate bug issue).

2023-04-07 13:43 UTC, laurenmrice approved these changes

2023-04-07 16:46 UTC, francinelucca commented
> @francinelucca this looks good! Just three things:
> 
> * The tab labels should be sentence-case. So instead of "Tab Label 1", lets say "Tab label 1".
> * The only small thing I see is a shift in the icon position when going between the "Contained with icons" story and the "Contained with Secondary Labels" story. It might be a 1px difference.
>   ![Apr-06-2023 16-00-25](https://user-images.githubusercontent.com/43969356/230483970-48774347-67d7-4c26-8ecf-835ac91e20b6.gif)
> * I also noticed the Default tabs do not have a hover state change (this may be unrelated to this PR and I can make a separate bug issue).

Good catch! fixed the icon issue and modified the labels, should be ready for re-review @laurenmrice .
Also created an issue for the hover state https://github.com/carbon-design-system/carbon/issues/13490

2023-04-10 23:51 UTC, tay1orjones approved these changes
Sorry for the delay on this review! I missed the request right before my vacation last week 🤦

2023-04-11 19:12 UTC, merged