V10 structured list
carbon-design-system/carbon pull request #1344
Opened 2018-10-25 21:48 UTC by aledavila

Closes #1275 

#### Changelog

**New**

**Changed**

- background color
- font size and color
- position of the selectable structure list checkbox

#### Testing / Reviewing

check dev environment is not broken

Staging Link: 
http://structured-list-x-appreciative-gelada.mybluemix.net/?nav=structured-list

2018-10-26 00:03 UTC, asudoh reviewed
LGTM basically, my only question is if we have a plan to create color tokens for new colors introduced here. Thanks @aledavila!

2018-10-26 13:21 UTC, alisonjoseph requested changes
LGTM other than adding the focus mixin and color tokens. 👍 

Although can you explain why an html change is needed? We've been able to avoid them on other components up until this point (other than tags, but that's just class names). On the surface looking at the two designs its hard to tell since they seem to be very similar. 

Oh and don't forget to name the PR so that it will trigger semantic release

2018-10-26 13:21 UTC, alisonjoseph commented on src/components/structured-list/_structured-list.scss
> +      outline: 2px solid $ibm-colors__blue--60;
Should be able to use the focus mixin here, looks like the spec has it on the inside anyway. 
```suggestion
      @include focus-outline('outline');
```

2018-10-26 13:21 UTC, alisonjoseph commented on src/components/structured-list/_structured-list.scss
> +      background-color: $ibm-colors__gray--10;
```suggestion
      background-color: $ui-01;
```

2018-10-26 13:21 UTC, alisonjoseph commented on src/components/structured-list/_structured-list.scss
> +      background-color: $ibm-colors__gray--20;
```suggestion
      background-color: $ui-03;
```

2018-10-26 13:21 UTC, alisonjoseph commented on src/components/structured-list/_structured-list.scss
> +      border-bottom: 1px solid $ibm-colors__gray--20;
```suggestion
      border-bottom: 1px solid $ui-03;
```

2018-10-26 13:21 UTC, alisonjoseph commented on src/components/structured-list/_structured-list.scss
> +    color: $ibm-colors__gray--100;
```suggestion
    color: $text-01;
```

2018-10-26 13:21 UTC, alisonjoseph commented on src/components/structured-list/_structured-list.scss
> +    color: $ibm-colors__gray--70;
```suggestion
    color: $text-02;
```

2018-10-26 13:21 UTC, alisonjoseph commented on src/components/structured-list/_structured-list.scss
> +      fill: $ibm-colors__gray--100;
```suggestion
      fill: $text-01;
```

2018-10-26 13:55 UTC, aledavila commented
@alisonjoseph it was because the check selected check is now at the end instead of the of the first row.

2018-10-26 14:05 UTC, alisonjoseph commented
Ah ok 👍 that makes sense then. 

Can you make an issue for React for this component and tags? We will need to support the updated html since we can't just swap the feature flag in sass anymore.

2018-10-26 14:06 UTC, aledavila commented
Yup can do

2018-10-29 15:14 UTC, laurenmrice commented
One thing I noticed
Selection and Hover: Text in selected and hover rows needs to be Gray 100 instead of Gray 70 :) otherwise looks good to me!

2018-10-30 16:39 UTC, aledavila commented
@alisonjoseph & @laurenmrice it is ready for review with all the updates. thanks!

2018-10-30 18:09 UTC, laurenmrice commented
Couple things:

-When a row is on hover, the line rules on the bottom and the top of the hover states should not appear.
![screen shot 2018-10-30 at 1 03 34 pm](https://user-images.githubusercontent.com/43969356/47739866-5ebafe00-dc44-11e8-91c6-15f25ffc9131.png)

-If a row has already been selected, there should not be a hover state on top of the selected state.

- On Focus state, the text can remain Gray 70 instead of switching to Gray 100.
![screen shot 2018-10-30 at 1 09 17 pm](https://user-images.githubusercontent.com/43969356/47740129-0e906b80-dc45-11e8-878c-0445a9b82cef.png)

2018-10-31 16:19 UTC, tw15egan commented on src/components/structured-list/_structured-list.scss
> +    // }
☠️ Delete me ☠️

2018-11-01 14:32 UTC, alisonjoseph commented
Not sure if this was ready to re-review or not @aledavila but seeing a border/outline flash on hover

2018-11-01 16:21 UTC, aledavila commented
@alisonjoseph  @laurenmrice yes its ready now.

2018-11-01 16:51 UTC, laurenmrice commented
Looks good. 👌

2018-11-01 16:57 UTC, tw15egan approved these changes
Looks great to me! 👍 🎉

2018-11-01 18:39 UTC, alisonjoseph approved these changes
looks great!

2018-11-01 18:39 UTC, merged