feat(DatePickerSkeleton): add types (#12541)
carbon-design-system/carbon pull request #13532
Opened 2023-04-17 08:40 UTC by kubijo

Closes #12541

#### Changelog

**New**

- Added types to `DatePickerSkeleton`

2023-04-17 08:46 UTC, kubijo commented
I have read the DCO document and I hereby sign the DCO.

2023-04-18 05:26 UTC, falsepopsky requested changes

2023-04-18 05:26 UTC, falsepopsky commented on packages/react/src/components/DatePicker/DatePicker.Skeleton.tsx
>  const DatePickerSkeleton = ({ range, id, className, ...rest }) => {
```suggestion
const DatePickerSkeleton = ({ range, id, className, ...rest }: DatePickerSkeletonProps) => {
```

Use the types

2023-04-25 18:51 UTC, tay1orjones approved these changes

2023-04-26 18:43 UTC, alisonjoseph approved these changes

2023-04-26 19:20 UTC, merged