feat(Slider): update invalid state add warning state
carbon-design-system/carbon pull request #13674
Opened 2023-04-26 18:39 UTC by alisonjoseph

Closes #13476

#### Changelog

**New**

- add warn, warnText and invalidText props

**Changed**

- update invalid styling to add icon

#### Testing / Reviewing
Check slider `invalid` and `warn` states match spec

<details><summary>Design spec</summary>

![image](https://user-images.githubusercontent.com/2753488/234671238-4fa8826b-294e-44bd-9ddf-c63f3bd35dff.png)
![image](https://user-images.githubusercontent.com/2753488/234671267-579fe8e6-f145-456d-bb63-02b7f0a72966.png)

</details>

2023-04-27 16:44 UTC, francinelucca requested changes
Mostly LGTM, one minor change suggestion.
Also is it ok that when readOnly and invalid are both true for it to show up like this? I also see it in prod but just wanted to double check 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/40550942/234932260-bc730d70-b72c-4a8e-85b5-5b54d8004689.png">

2023-04-27 16:44 UTC, francinelucca commented on packages/react/src/components/Slider/Slider.tsx
> +  invalidText: React.ReactNode;
should this one be optional as well? 
```suggestion
  invalidText?: React.ReactNode;
```

2023-04-27 17:36 UTC, alisonjoseph commented
@francinelucca ah good catch, based on the other components I believe it is a bug. fixed

2023-04-27 19:08 UTC, francinelucca approved these changes
🚀

2023-05-08 19:32 UTC, laurenmrice requested changes
- There should be `16px` padding before and after the error/warning icon. Right now the left padding seems to be 24px.
<img width="732" alt="Screen Shot 2023-05-08 at 3 30 53 PM" src="https://user-images.githubusercontent.com/43969356/236915594-f0cc65a3-ffe9-4f56-9b56-966766a9b5ee.png">

2023-05-08 19:34 UTC, andreancardona approved these changes
Other than Lauren's comment looks good on the dev side - will approve

2023-05-08 19:36 UTC, alisonjoseph commented on packages/styles/scss/components/slider/_slider.scss
> +    width: 6rem;
```suggestion
    width: rem(88px);
```

2023-05-08 19:43 UTC, alisonjoseph commented
@laurenmrice I updated it, it look correct with a two digit number, but may be issues with others?

Just as a FYI on how this is built, the number input for the slider is currently set to 4rem (64px), and with an error/warning state it is now set to 5.5rem (88px). The padding won't be correct for a 1 digit number, as it doesn't resize. It also just barely cuts off a 3 digit number at 88px wide, even though the padding for the icon is correct.  Just wanted to check that was ok, I'm not sure there is an easy way around that. 

![Screenshot 2023-05-08 at 2 40 44 PM](https://user-images.githubusercontent.com/2753488/236917933-d14b0112-315a-43ee-88b0-d75c57041cbb.png)
![Screenshot 2023-05-08 at 2 40 53 PM](https://user-images.githubusercontent.com/2753488/236917935-fff427cf-be81-4b43-80b4-91cc021c5146.png)
![Screenshot 2023-05-08 at 2 41 08 PM](https://user-images.githubusercontent.com/2753488/236917936-e90980d4-4b8e-40bc-be72-2d5d42b9b2d2.png)
![Screenshot 2023-05-08 at 2 41 16 PM](https://user-images.githubusercontent.com/2753488/236917937-7bee49d0-d4b7-4dbc-88f7-036b7d315d4e.png)

2023-05-09 15:59 UTC, tay1orjones approved these changes

2023-05-10 16:15 UTC, alisonjoseph commented
@laurenmrice updated after our discussion. Input is now always left aligned, and width is 6rem when invalid/warn is true.

2023-05-10 18:16 UTC, laurenmrice approved these changes

2023-05-10 19:19 UTC, merged