fix(search): scope contained list search styles
carbon-design-system/carbon pull request #13737
Opened 2023-05-04 18:09 UTC by alisonjoseph

Closes #13725 

Fix search background color, currently broken live
![Screenshot 2023-05-04 at 1 10 11 PM](https://user-images.githubusercontent.com/2753488/236291837-0dba90d0-22cc-40ea-a14e-9724f66c34f7.png)

#### Changelog

**Changed**

- Make sure all search styles in contained-list are scoped only to that component

#### Testing / Reviewing
Ensure `ContainedList` with search looks correct, ensure correct background color is fixed for `Search`

https://deploy-preview-13737--carbon-components-react.netlify.app/?path=/story/components-containedlist--with-persistent-search

https://deploy-preview-13737--carbon-components-react.netlify.app/?path=/story/components-search--default

2023-05-04 18:15 UTC, tay1orjones approved these changes

2023-05-08 17:48 UTC, andreancardona requested changes, later dismissed
For the persistent search in Contained List do we want to keep the focus styles on the `x` button - can't seem to remember the design specs for this

https://user-images.githubusercontent.com/32720851/236894283-061f84d5-f5bc-4190-8427-9df2ff42b364.mov

https://deploy-preview-13737--carbon-components-react.netlify.app/?path=/story/components-containedlist--with-persistent-search

2023-05-08 18:20 UTC, tw15egan commented
@andreancardona I know we've moved away from focusing on the `x` button in other components because it is a sighted-only affordance. A keyboard user would be used to pressing the `esc` key to clear the input, rather than focusing on a clear button. [Filterable Multiselect](https://react.carbondesignsystem.com/?path=/story/components-multiselect--filterable) / [ComboBox](https://react.carbondesignsystem.com/?path=/story/components-combobox--default)

 We should make the experience consistent between these search examples though, but it may be a separate issue.

2023-05-08 19:03 UTC, alisonjoseph commented
Looks like there is a focus state on the live storybook, and not in this PR, I'll take a look

2023-05-08 21:29 UTC, aagonzales approved these changes

2023-05-09 14:56 UTC, tw15egan approved these changes

2023-05-10 15:11 UTC, merged