feat: added types for the AspectRatio component
carbon-design-system/carbon pull request #13753
Opened 2023-05-07 12:05 UTC by SunnyJohal

Closes #13545 

Added types for the AspectRatio component

#### Changelog

**New**

- Added type definitions to AspectRatio component.

**Changed**

- Changed component to arrow function.

**Removed**

- n/a

#### Testing / Reviewing

Ran unit tests and checked storybook to make sure it's all working as before.

2023-05-09 14:54 UTC, tay1orjones requested changes
This looks good, just needs one small change

2023-05-09 14:54 UTC, tay1orjones commented on packages/react/src/components/AspectRatio/AspectRatio.tsx
> +   * @description Provide a custom component or string to be rendered as
The `@description` JSDoc annotation is [not supported](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#unsupported-tags)

```suggestion
   * Provide a custom component or string to be rendered as
```

Additional usages of `@description` in this PR will need updated as well

2023-05-09 19:26 UTC, SunnyJohal commented
Changes have been made 👍

2023-05-11 19:06 UTC, alisonjoseph approved these changes

2023-05-16 19:06 UTC, tw15egan approved these changes

2023-06-07 14:10 UTC, tay1orjones approved these changes

2023-06-07 14:38 UTC, merged