feat: added types to Link component
carbon-design-system/carbon pull request #13754
Opened 2023-05-07 17:46 UTC by SunnyJohal

Closes #13561

Added typescript types to Link component.

#### Changelog

**New**

- Added typescript types to Link component.

**Changed**

-  File extensions from .js to .tsx

**Removed**

- n/a

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-05-09 14:50 UTC, tay1orjones requested changes
Thanks! Just one small change needed

2023-05-09 14:50 UTC, tay1orjones commented on packages/react/src/components/Link/Link.tsx
> +      target,
This needs to be added to propTypes

2023-05-09 14:56 UTC, tay1orjones requested changes

2023-05-09 14:56 UTC, tay1orjones commented on packages/react/src/components/Link/Link.tsx
> +   * @description Indicates the element that represents the
The `@description` JSDoc annotation is [not supported](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#unsupported-tags)

```suggestion
   * Indicates the element that represents the
```

Additional usages of `@description` in this PR will need updated as well

2023-05-23 19:43 UTC, SunnyJohal commented on packages/react/src/components/Link/Link.tsx
> +   * @description Indicates the element that represents the
Will remove these now

2023-05-23 19:44 UTC, SunnyJohal commented on packages/react/src/components/Link/Link.tsx
> +      target,
Will add this now

2023-05-25 01:05 UTC, andreancardona approved these changes
Thank you so much for this - looks good!

2023-06-07 14:12 UTC, tay1orjones approved these changes

2023-06-07 15:08 UTC, merged