feat: added typescript types to ClassPrefix component
carbon-design-system/carbon pull request #13755
Opened 2023-05-07 18:12 UTC by SunnyJohal

Closes #13547 

added typescript types to ClassPrefix component

#### Changelog

**New**

- added typescript types to ClassPrefix component

**Changed**

- file extension from .js to .tsx

**Removed**

- n/a

#### Testing / Reviewing

- Run storybook and check that the components are rendering.
- Run unit tests.

2023-05-09 14:47 UTC, tay1orjones approved these changes

2023-05-09 14:55 UTC, tay1orjones requested changes
Sorry I just noticed this

2023-05-09 14:55 UTC, tay1orjones commented on packages/react/src/components/ClassPrefix/index.tsx
> +   * @description The value used to prefix the CSS selectors
The `@description` JSDoc annotation is [not supported](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#unsupported-tags)

```suggestion
   * The value used to prefix the CSS selectors
```

Additional usages of `@description` in this PR will need updated as well

2023-05-16 19:07 UTC, tw15egan commented
@SunnyJohal the `@description` comments are still present

2023-05-17 19:42 UTC, tw15egan approved these changes

2023-05-18 18:45 UTC, alisonjoseph approved these changes

2023-05-18 18:46 UTC, alisonjoseph commented
recheck

2023-05-23 19:29 UTC, SunnyJohal commented
Hi I'm going to close this branch and create a new one as I have accidentally rebased prev changes (the issue was my earlier commit was from an e-mail address from a company I was working with, I don't have access to that e-mail anymore)

2023-05-23 19:29 UTC, closed without merging