fix(Popover): nested popover - css fix
carbon-design-system/carbon pull request #13750
Opened 2023-05-05 20:05 UTC by guidari

Closes #13684 

When an IconButton is placed within a Popover, the iconDescription is always visible. Popover's *--open classes are not properly scoped to only impact children Popovers one "level" deep.

Repro
https://stackblitz.com/edit/github-b5r8er?file=src/App.jsx

In order to apply the style to only the first child of the CSS class `.#{$prefix}--popover`, we are specifically checking for its direct child

#### Testing / Reviewing

You can find a new component called 'Test Issue' inside `Popover` in Storybook. Checking out this component will allow you to test its functionality. Additionally, going to the `Button` storybook and checking if everything is okay with the 'Icon Button' would also be a good idea.

Once its approved I'll remove the storybook, or the second approver can remove

2023-05-08 15:39 UTC, andreancardona requested changes
It looks like the change in styles produces a bug for this story below [Tab Tip - deploy preview](https://deploy-preview-13750--carbon-components-react.netlify.app/?path=/story/components-popover--tab-tip)

<img width="1084" alt="Screenshot 2023-05-08 at 09 37 41" src="https://user-images.githubusercontent.com/32720851/236867210-9b254234-7a3a-4383-8dad-691e4386ae16.png">

Current design / how it should look: 

- https://react.carbondesignsystem.com/?path=/story/components-popover--tab-tip

2023-05-11 12:27 UTC, guidari commented
@andreancardona I added a new CSS style to make sure that when `isTabTip` is set the display is iguals none

2023-05-11 15:37 UTC, andreancardona approved these changes

2023-05-22 18:43 UTC, tay1orjones approved these changes

2023-05-22 18:43 UTC, tay1orjones commented on packages/react/src/components/Popover/Popover.stories.js
> +import { ThumbsUp } from '@carbon/icons-react';
```suggestion
```

2023-05-22 18:43 UTC, tay1orjones commented on packages/react/src/components/Popover/Popover.stories.js
> +};
```suggestion
```

2023-05-22 19:11 UTC, merged