feature/OrderedList, UnorderedList, and ListItem types
carbon-design-system/carbon pull request #13775
Opened 2023-05-09 15:48 UTC by mrkjdy

Closes #13565 

Converted OrderedList, UnorderedList, and ListItem to tsx and added appropriate prop types.

#### Changelog

**New**

- Created types for OrderedList, UnorderedList, and ListItem props

**Changed**

- Updated tests after removing defaultProps

**Removed**

- Removed duplicate exports of OrderedList, UnorderedList, and ListItem

#### Testing / Reviewing

You can check this by confirming that there are no errors when:

- building
- viewing the stories that have a OrderedList, UnorderedList, or ListItem
- creating a component that uses the OrderedList, UnorderedList, or ListItem and testing which props are valid/invalid

2023-05-09 16:00 UTC, tay1orjones requested changes

2023-05-09 16:00 UTC, tay1orjones commented on packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
> -  },
This shouldn't be changing. Might need to revert the change to how the component is exported.

2023-05-11 14:51 UTC, mrkjdy commented on packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
> -  },
Should be fixed!

2023-05-12 19:52 UTC, tay1orjones approved these changes
Sweet, thanks!

2023-05-15 14:01 UTC, alisonjoseph approved these changes

2023-05-15 14:42 UTC, merged