Component Accessibility Status: EAC Default state baseline audit/coverage
carbon-design-system/carbon pull request #13892
Opened 2023-05-30 16:36 UTC by guidari

Closes #13746

We checked for the `avt` and `vrt` tests within the "e2e/components" folder and included all tests that were missing.

#### Testing / Reviewing

Run the command `yarn playwright test` in the root and hopefully all the tests will pass.

2023-06-05 16:17 UTC, alisonjoseph approved these changes
🥳

2023-06-06 19:17 UTC, francinelucca requested changes
Mostly LGTM, just one question on the changes in OverflowMenuV2. Also looks like there's some conflicts after Jan's bring menu to stable PR merged in @guidari @andreancardona.

FYI I see 3 avt failures locally but they're not reflected upstream 🤔
<img width="823" alt="image" src="https://github.com/carbon-design-system/carbon/assets/40550942/dd40c39b-2881-46f3-a0a9-8a1b3c45da0e">

2023-06-06 19:17 UTC, francinelucca commented on packages/react/src/components/OverflowMenuV2/index.js
> +  'aria-labelledby': PropTypes.string,
is this necessary here? I don't see it being used in the component 😅

2023-06-12 18:29 UTC, francinelucca approved these changes
Confirmed locally with @guidari it runs successfully on his machine. Mine runs considerably slower and I think some tests are timing out due to that. This should be good to merge as I see no errors upstream

2023-06-12 19:01 UTC, merged