feat: storybook 7 migration
carbon-design-system/carbon pull request #13917
Opened 2023-06-02 17:20 UTC by francinelucca

Closes #12912 

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-06-13 15:21 UTC, alisonjoseph requested changes
This looks great!! 🥳  Only noticed a couple super minor things posted below. 😄 

Button overview
<img width="520" alt="Screenshot 2023-06-13 at 9 45 54 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/97d69c1e-8a5c-4883-910b-a7935f0c6d6b">

Composed modal overview, 7 on the left, live site on the right. This might be ok? 
<img width="1216" alt="Screenshot 2023-06-13 at 9 52 28 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/6a4bb28a-c908-4306-a3a7-5e39ec291fb2">


Slide overview, example is disabled, differs from what is on live.
<img width="529" alt="Screenshot 2023-06-13 at 10 14 36 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/6b6fbe43-7a07-4930-8f91-12a963628321">

Is there a way to have overview first here? 
<img width="259" alt="Screenshot 2023-06-13 at 10 19 18 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/9f771956-77b4-447d-8d69-9f98fdff0901">

2023-06-13 15:23 UTC, alisonjoseph commented
This is unrelated to this PR, but can we add padding here? I can also create a separate issue/PR for this. 
<img width="597" alt="Screenshot 2023-06-13 at 10 09 57 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/a04e32a5-6c4f-43cd-8756-d65e48a80e3b">

2023-06-13 18:34 UTC, francinelucca commented
@alisonjoseph nice catches!

- Button Overview docs should be fixed
- Added padding to OrderedList docs
- Overview should be showing up first in all stories now

- The composedModal notification changes I did on purpose, I was modeling after the notifications in https://react.carbondesignsystem.com/?path=/docs/components-modal--default. I thought the ack of a CodeSnippet in ComposedModal might have been an oversight 🤔. I can revert back to just quotes but I think they should be the same in both places
- For the Slider, is it possible that you went into the Playground, turned on the disabled control and then went into the overview and that's when you saw it disabled? I don't see it disabled on first render on my end.

Let me know if you find anything else 🙏🏻, TIA!

2023-06-20 03:38 UTC, andreancardona approved these changes
Wow 🔥 I feel like I did a pretty thorough review and caught some bugs on our end. This is more a question - I assume it's a v7 feature - but just saw a small discrepancy with the `deprecated` props in the docs. 
<img width="1243" alt="Screenshot 2023-06-19 at 21 31 46" src="https://github.com/carbon-design-system/carbon/assets/32720851/cc79b438-23d7-4764-8808-326ab38f6334">
<img width="1343" alt="Screenshot 2023-06-19 at 21 32 04" src="https://github.com/carbon-design-system/carbon/assets/32720851/6e7e2cac-0580-41bb-b971-c8cbc7085d5c">

2023-06-20 12:48 UTC, alisonjoseph approved these changes
This all LGTM me now! I think it would be nice to add some styling to the new deprecated messages that show up in the props table. We can just make a new issue for design for that and add it in a future PR, don't think it needs to block this. 🥳

2023-06-20 14:01 UTC, tay1orjones approved these changes
This update looks super good! I pushed a commit to update the links to the feature flag overview page. That page URL changed slightly with the update.

> it is expected for some of the CIs to fail since the command used to build storybook changed in V7 and main branch still doesn't know about it. you'll need to build this manually and test it for this PR :)

Once this merges I'll go in and update the Netlify config settings so the deploy previews will work moving forward 👍

2023-06-20 15:35 UTC, francinelucca commented
> but just saw a small discrepancy with the `deprecated` props in the docs.

Yeah I believe that's a consequence of switching from `<Props />` to `<ArgsTable />`. I created an issue to have design take a look as per @alisonjoseph comment https://github.com/carbon-design-system/carbon/issues/14040

2023-06-28 16:50 UTC, tay1orjones approved these changes
Yesss, looks great! Lets go! 🎉

2023-06-28 16:50 UTC, tay1orjones commented on packages/react/.storybook/main.js
> +const storyGlobs =
Could you add a brief comment here explaining why we conditionally exclude some globs when this flag is false?

2023-06-28 19:19 UTC, merged