WIP: feat(Tabs): Contained tabs on the grid
carbon-design-system/carbon pull request #13927
Opened 2023-06-05 19:32 UTC by francinelucca

Closes #13353 

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-06-07 20:44 UTC, francinelucca commented
We're still ironing some dev things out but this should be good for design review @kingtraceyj . You can check it out at this url: https://deploy-preview-13927--carbon-components-react.netlify.app/iframe.html?args=&id=components-tabs--contained-grid-test&viewMode=story

2023-06-08 16:40 UTC, kingtraceyj approved these changes
this is working as intended! 💥

2023-06-15 15:29 UTC, alisonjoseph commented
Question: are we not aligning individual tabs on the grid anymore? That was the original intent of the design spec, but maybe it changed? 

<img width="1537" alt="Screenshot 2023-06-15 at 10 26 54 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/d35cc525-88e3-4884-bc7a-b6ba64dbcdc0">

2023-06-16 13:07 UTC, alisonjoseph requested changes
This is looking great! I think we can make the docs a little clearer by adding / showing an example on how to actually get the tabs on the grid by matching the column numbers. We might want to show that in the code sample on the docs also.

2023-06-16 13:07 UTC, alisonjoseph commented on packages/react/src/components/Tabs/Tabs.mdx
> +`fullWidth` paired up with a wrapping `Grid` component will allow for "grid-aware" tabs:
I think we could add some more docs here no how to get the tabs to align on the grid exactly using this. 

> In order to have the tabs align on grid columns you will want to be sure to make the number of columns match the number of tabs. For example if you have 5 tabs you would want to use. `<Column lg={5} md={5}>`

2023-06-16 19:12 UTC, francinelucca commented
@alisonjoseph yeah we confirmed with Tracey & Lauren only the Container needs to be aligned to the Grid and if the number of columns coincide with the number of Tabs then the individual tab items will also be aligned to the Grid. We just added some extra guidance around that in the Docs, let us know what you think :)

2023-06-19 17:11 UTC, alisonjoseph approved these changes
Awesome! LGTM, and a lot easier to understand now with added docs 🥳

2023-06-21 15:48 UTC, tay1orjones approved these changes

2023-06-22 20:13 UTC, merged