Types/content switcher
carbon-design-system/carbon pull request #13993
Opened 2023-06-13 15:22 UTC by anton-tsymuk-viacomcbs

Closes #13550 

Added typescript types to ContentSwitcher, Switch and Layout components.

#### Changelog

**New**

- Added typescript types to ContentSwitcher, Switch and Layout components.

**Changed**

- Updated list of contributors

#### Testing / Reviewing

- Start storybook, check that ContentSwitcher component works as expected.
- Check unit tests

2023-06-13 15:32 UTC, anton-tsymuk-viacomcbs commented
I have read the DCO document and I hereby sign the DCO.

2023-06-13 22:40 UTC, francinelucca requested changes
This is looking great @anton-tsymuk-viacomcbs , thanks for getting this PR up!
Just have some cleanup suggestions, let me know your thoughts

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +  density: PropTypes.oneOf(densities),
```suggestion
  density: PropTypes.oneOf<Density>(densities),
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +  size: PropTypes.oneOf(sizes),
```suggestion
  size: PropTypes.oneOf<Size>(sizes),
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +} as WeakValidationMap<LayoutProps & React.RefAttributes<React.ReactNode>>;
This conversion shouldn't necessary with the suggested changes
```suggestion
}
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +const sizes = ['xs', 'sm', 'md', 'lg', 'xl', '2xl'];
```suggestion
const sizes: Size[]  = ['xs', 'sm', 'md', 'lg', 'xl', '2xl'];
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +const densities = ['condensed', 'normal'];
```suggestion
const densities: Density[] = ['condensed', 'normal'];
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +  };
```suggestion
  density?: {
    min?: Density | null;
    default?: Density | null;
    max?: Density | null;
  } | null;
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +  };
```suggestion
  size?: {
    min?: Size | null;
    default?: Size | null;
    max?: Size | null;
  } | null;
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +  }),
```suggestion
  density: PropTypes.shape({
    min: PropTypes.oneOf<Density>(['condensed', 'normal']),
    default: PropTypes.oneOf<Density>(['condensed', 'normal']),
    max: PropTypes.oneOf<Density>(['condensed', 'normal']),
  }),
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +  }),
```suggestion
  size: PropTypes.shape({
    min: PropTypes.oneOf<Size>(['xs', 'sm', 'md', 'lg', 'xl', '2xl']),
    default: PropTypes.oneOf<Size>(['xs', 'sm', 'md', 'lg', 'xl', '2xl']),
    max: PropTypes.oneOf<Size>(['xs', 'sm', 'md', 'lg', 'xl', '2xl']),
  }),
```

2023-06-13 22:40 UTC, francinelucca commented on packages/react/src/components/Layout/index.tsx
> +>;
This conversion shouldn't be necessary with the suggested changes
```suggestion
}
```

2023-06-14 10:41 UTC, anton-tsymuk-viacomcbs commented
> This is looking great @anton-tsymuk-viacomcbs , thanks for getting this PR up! Just have some cleanup suggestions, let me know your thoughts

i applied suggested changes. please take a look

2023-06-14 14:47 UTC, francinelucca approved these changes
👏🏽

2023-06-16 13:02 UTC, alisonjoseph approved these changes

2023-06-16 15:18 UTC, merged