fix(Datepicker): fix calendar cannot close issue
carbon-design-system/carbon pull request #14028
Opened 2023-06-18 04:29 UTC by tongyy

Closes #[14025](https://github.com/carbon-design-system/carbon/issues/14025)

This is caused by misusing js built-in new Date api to parse date string. Almost all main stream browsers consider Y-m-d format as ISO 8601 format which has zero hour offset. 

ex: you can test this in console
new Date("2022-05-05");
Wed May 04 2022 20:00:00 GMT-0400 (Eastern Daylight Time)
new Date("2022/05/05")
Thu May 05 2022 00:00:00 GMT-0400 (Eastern Daylight Time)

#### Changelog

**Changed**

- use parseDate from flatpicker instead of using builtin new Date with date string as initial arg.

#### Testing / Reviewing

Follow reproduction steps in [14025](https://github.com/carbon-design-system/carbon/issues/14025)

2023-06-19 16:22 UTC, francinelucca requested changes
Thanks for putting this PR together @tongyy! 
Mostly LGTM just a function rename suggestion.
Also if this is your first contribution feel free to add yourself to the contributors table: https://github.com/carbon-design-system/carbon/blob/main/.github/CONTRIBUTING.md#5-add-yourself-to-the-contributor-list

Note: noticed calendar does not close on tab out when using keyboard navigation and opened up https://github.com/carbon-design-system/carbon/issues/14033

2023-06-19 16:22 UTC, francinelucca commented on packages/react/src/components/DatePicker/plugins/fixEventsPlugin.js
> +  const parse = (dateStr) => fp.parseDate(dateStr, fp.config.dateFormat);
let's give this function a more intentful name
```suggestion
  const parseDateWithFormat = (dateStr) => fp.parseDate(dateStr, fp.config.dateFormat);
```

2023-06-19 17:02 UTC, tongyy commented on packages/react/src/components/DatePicker/plugins/fixEventsPlugin.js
> +  const parse = (dateStr) => fp.parseDate(dateStr, fp.config.dateFormat);
updated

2023-06-19 19:29 UTC, andreancardona approved these changes
Tested and looks good thanks @tongyy! 🎉

2023-06-19 21:07 UTC, francinelucca approved these changes

2023-06-20 12:41 UTC, tay1orjones approved these changes
Thank you!

2023-06-20 13:11 UTC, merged