fix(search): AVT1 bugs
carbon-design-system/carbon pull request #1416
Opened 2018-11-09 06:17 UTC by dakahn

Closes #1363

Implements various changes to address AVT1 bugs found in the search component during testing.

2018-11-09 06:55 UTC, asudoh approved these changes
LGTM :+1: - Thanks @dakahn!

2018-11-09 16:10 UTC, joshblack requested changes

2018-11-09 16:10 UTC, joshblack commented on src/components/search/search.hbs
> +    <input class="bx--search-input" type="text" id="search__input-1" placeholder="Search" aria-labelledby="search-input-label-1">
This is more-so an issue with the originally markup, but why do we have `label` with `for` and `aria-labelledby` set?

2018-11-12 23:24 UTC, dakahn commented on src/components/search/search.hbs
> +    <input class="bx--search-input" type="text" id="search__input-1" placeholder="Search" aria-labelledby="search-input-label-1">
Totally. Took it out. 👍

2018-11-13 19:38 UTC, alisonjoseph approved these changes
LGTM

2018-11-13 19:43 UTC, merged