chore: updated next and react version in example
carbon-design-system/carbon pull request #14219
Opened 2023-07-13 21:06 UTC by guidari

After working on this [PR](https://github.com/carbon-design-system/carbon/pull/14198) it was found a few errors when running an example using NextJS.

To fix that it was updated the next and react versions in the `package.json`

**Changed**

- next and reacr version in `package.json` examples

#### Testing / Reviewing

Pull the branch locally and run the examples

2023-07-17 16:56 UTC, tay1orjones requested changes
Elements previews look good and the light-dark-mode example looks good.

The incremental-migration one is not working for me though
![image](https://github.com/carbon-design-system/carbon/assets/3360588/42c1de26-a943-44dd-a022-0a307ab80ddd)

2023-07-27 12:44 UTC, guidari commented
> The incremental-migration one is not working for me though

Hey @tay1orjones I didn't find a way to fix that on NextJS. The example works outside of the monorepo, but not inside it, for some reason.

But I could fixed it by migrating the example to use Vite instead of NextJS. Check this [Draft PR](https://github.com/carbon-design-system/carbon/pull/14317)

My suggestion is to use that migration as an example to this [issue](https://github.com/carbon-design-system/carbon/issues/13637), about how we can approach this transition.

2023-07-27 19:57 UTC, tay1orjones approved these changes
Sounds good, thanks @guidari!

2023-07-28 16:01 UTC, alisonjoseph approved these changes

2023-08-01 21:48 UTC, merged