UI shell header submenu
carbon-design-system/carbon pull request #1429
Opened 2018-11-13 00:49 UTC by emyarod

Closes #1355 

This PR will implement header submenu logic for the UI Shell

#### Changelog

**New**

- header submenu opening/closing logic
- keyboard navigation for header submenus

2018-11-13 06:41 UTC, asudoh approved these changes
LGTM :+1::tada: - Thanks @emyarod for completing this!!

2018-11-13 15:42 UTC, joshblack requested changes
Looks amazing so far! 🎉 Thanks for adding this in 🙏 Couple of things I noticed when going through it:

- The menus should display on hover versus click (I think in React we used mouseover/mouseleave)
- Only one menu item in the bar should have `tabindex="0"`, the rest should be `-1`. By default the first item has this set. After interacting with the widget, the most recently focused nav item should have it set.
- When pressing arrow down on a menu, it should move focus to the first item in the list
- When inside a menu, using arrow left or right should close the menu and shift focus to the previous/next nav item
- Home/End should be added for navigating to the first/last item
- As a form of enhancement, when focusing on a menu item typing a letter should jump to the next nav item that first matches that letter

2018-11-13 15:47 UTC, joshblack commented
I think in our README we have some of the examples that can help depict what I think the behavior is that we want to go for keyboard-wise: https://github.com/IBM/carbon-components/tree/8bd1cee785021cdb1e3fc8010f897e2082bd3cb2/src/components/ui-shell#header

2018-11-16 15:53 UTC, joshblack commented
@emyarod could you add a staging link and add @aagonzales as a reviewer btw?

2018-11-16 22:37 UTC, emyarod commented
staging link: http://ui-shell-header-submenu-delightful-parrot.mybluemix.net/component/ui-shell--default.html

2018-11-19 22:57 UTC, aagonzales reviewed
Looks good!! Just want to confirm something. For the `bx--header_action` in the top right when you click on them it goes blue. The blue fill should be the selected state and the on click color should be #3D3D3D/Gray 80. 

And one small design change, any time there's a hover can we have the hovered text change to White?

2018-11-20 04:02 UTC, emyarod commented
thanks for the feedback @aagonzales! sorry there was a bit of guesswork with the styles since I had to make some assumptions based on the Sketch file I have. Just want to double check something:

> For the `bx--header_action` in the top right when you click on them it goes blue. The blue fill should be the selected state and the on click color should be #3D3D3D/Gray 80.

Right now the `bx--header__action` is also `#3d3d3d` on hover. Do we want the on click color to be identical to the hover color?

2018-11-20 16:06 UTC, aagonzales commented
For `bx--header__action` hover should be `#333333` and active should be `#3d3d3d`

2018-11-26 15:13 UTC, alisonjoseph commented on src/components/ui-shell/_header.scss
> +    background-color: #333;
this should probably be a token?

2018-11-26 18:06 UTC, aagonzales approved these changes

2018-11-26 19:47 UTC, marijohannessen approved these changes
It looks good to me! 👍 ✅

2018-11-27 18:19 UTC, alisonjoseph approved these changes

2018-11-27 18:20 UTC, merged