14304 tabs avt
carbon-design-system/carbon pull request #14318
Opened 2023-07-26 19:21 UTC by andreancardona

Part of https://github.com/carbon-design-system/carbon/issues/13747

Closes #14304 

Changelog
New

Broke @avt tests out into their own Tabs-test.avt.e2e.js file
@vrt tests remain in the Tabs-test.e2e.js file

Add keyboard navigation tests covering default Tabs state

Update playwright config glob to match and include the new test file naming structure (avt.e2e.js)

Testing / Reviewing
CI should pass
Ensure the tests pass a sniff test and don't look problematic

2023-07-27 11:52 UTC, alisonjoseph approved these changes

2023-07-28 14:06 UTC, tw15egan requested changes
Looks good, but we can probably remove some of the a11y tests and expand on the keyboard testing.

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +    await expect(page.getByRole('textbox')).toBeVisible();
I don't think we need to test for focus moving through the tab panel items. Could we add a test instead to make sure that when you arrow to the last tab item, it goes back to the start?

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +  test.slow('default state - keyboard nav', async ({ page }) => {
We should have another test ensuring dismissable tabs have arrow key navigation and can be dismissed with `Delete`. We should also have another test suite that captures the differences between `automatic` and `manual` (arrow only moves focus, space bar / enter changes tabs) selection modes

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +  test('accessibility-checker tabs contained full width', async ({ page }) => {
I don't think we need to run a11y checker on this, it seems the same as the basic contained story.

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +  test('accessibility-checker tabs contained with secondary labels and icons', async ({
We can probably just keep this test and remove the previous two variants that just have secondary labels or just have icons.

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +  test('accessibility-checker tabs dismissable with icons', async ({
Same as above, we can probably just test this more complex version as it will catch any a11y violations the non-icon variant would have

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +  test('accessibility-checker tabs icon 20 only', async ({ page }) => {
Only need to test one icon size variant

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +  test('accessibility-checker tabs manual', async ({ page }) => {
I don't think we need this a11y test, but we should test the difference between `manual` and `automatic` in the keyboard testing section.

2023-07-28 14:06 UTC, tw15egan commented on e2e/components/Tabs/Tabs-test.avt.e2e.js
> +  test('accessibility-checker tabs components tabs with icons', async ({
I think this is captured by other tests as well

2023-07-31 15:51 UTC, closed without merging