chore: update stylelint-prettier to version 3
carbon-design-system/carbon pull request #14468
Opened 2023-08-19 12:08 UTC by dbrugger

Closes #

Version upkeep for `stylelint-prettier`. Reason: I would like to use `stylelint-config-carbon` in apps. Some of these are already on Prettier 3, and getting stylelint-prettier to v4 is required for that. So this PR is a stepping stone.

#### Changelog

**Changed**

- stylelint-prettier to version 3

**Removed**

- Removed deprecated rules per https://github.com/prettier/stylelint-prettier/blob/main/CHANGELOG.md#300-2023-02-22 and https://stylelint.io/user-guide/rules#deprecated which are covered by Prettier anyway

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-08-21 13:47 UTC, tay1orjones requested changes
Thanks for this! I found one small thing to change.

> Removed deprecated rules per https://github.com/prettier/stylelint-prettier/blob/main/CHANGELOG.md#300-2023-02-22 and https://stylelint.io/user-guide/rules#deprecated which are covered by Prettier anyway

Covered by Prettier v2.x or v3.x? We won't want to have any lapse in rule coverage until we adopt Prettier v3. With that in mind, do we need to upgrade Prettier alongside these changes?

Also unless I'm mistaken, we will need to release this as a new major version for `stylelint-config-carbon`, correct?

2023-08-21 13:47 UTC, tay1orjones commented on config/stylelint-config-carbon/package.json
> +    "stylelint-prettier": "3",
^3.0.0

2023-08-22 01:13 UTC, dbrugger commented
Both prettier v2 and v3 cover the formatting of scss. That's why stylelint v15 deprecated these rules. There was a config `stylelint-config-prettier` which disabled these, which was useful before v15. Now this config is no longer required, as the rules are no longer used by default. That's why `stylelint-prettier` removed this config from its default.
I don't think a major version bump is required with this PR, as for the consumer nothing changes.
The only "interface" of this package is the peerDependency of stylelint v15. Once stylelint-prettier is updated to v4, which requires prettier v3 a major version bump is required imo, and then that should also include the prettier update.

2023-08-22 08:12 UTC, dbrugger commented
@tay1orjones please have a look again. I now also added the other related packages, and took a systematic approach to see effective rule differences. In https://github.com/carbon-design-system/carbon/actions/runs/5936086642/job/16095800231?pr=14468 you see 27 new findings. We have to decide whether to ignore these new rules for now or to fix the offending scss.

Also a question. When I run `yarn lint:styles` locally it just hangs. The only way I can get it to run is if I add `--ignore-path .gitignore`, but then get a much higher number of findings than the pipeline. Can you run it locally? Is the pipeline doing anything special?

2023-09-04 18:26 UTC, guidari submitted a review, later dismissed

2023-10-09 18:53 UTC, tay1orjones commented
Thanks again for taking a jab at this! A few things have happened that I think might make this PR obsolete. 

1. Dependabot/renovate issued individual updates for multiple stylelint packages over the past few weeks. These PRs got these deps to their most current version, many of which are listed in the PR.
2. We've approached the prettier update from a new angle in https://github.com/carbon-design-system/carbon/pull/14744 and I think we'll land the update (and the related stylelint updates) there

For those reasons, I'm going to close this out. We can reopen if you think we've missed anything, or we could work together to get changes present here also present over in #14744. I think we've got them all, but let us know. Thank you again!

2023-10-09 18:53 UTC, closed without merging