feat(Modal|ComposedModal): add inline loading option
carbon-design-system/carbon pull request #14490
Opened 2023-08-22 15:31 UTC by Tomahaawk

Contributes to #10495

This PR introduces the [inline loading variant](https://carbondesignsystem.com/components/modal/usage/#loading) to Modals.  
The figma designs can be found [here](https://www.figma.com/file/uSSXI5VprCEcnuLgkfThtz/Loader-in-modal_-Spec?type=design&node-id=162-217164&mode=design).

#### Changelog

**New**

- The following properties are now available to Modal and ModalFooter: 
`loadingStatus`: loading status (active, inactive, error, finished)
`loadingDescription`: the description for the loading text 
`loadingIconDescription`: the description for the loading text 
`onLoadingSuccess`:  an optional handler to be invoked when loading is successful

- Added a new scss selector (`{prefix}--btn--loading`) that changes the button to be transparent.

#### Testing / Reviewing

- [ ] Inline loading should be active when passing `active` to `loadingStatus`
- [ ] Primary and secondary buttons should be disabled.
- [ ] Primary button background color should change to transparent when loading is active.
- [ ] After status is changed to `finished`, success state should be displayed.

2023-08-22 17:02 UTC, Tomahaawk commented
I have read the DCO document and I hereby sign the DCO.

2023-10-16 13:37 UTC, Tomahaawk commented
@tay1orjones @guidari Hey, just wanted to know if you guys had time to look at the changes. 
Can the PR be set as ready for review?

2023-10-17 13:53 UTC, guidari reviewed
> @tay1orjones @guidari Hey, just wanted to know if you guys had time to look at the changes. Can the PR be set as ready for review?

I few like the PR is ready for review, the functionality and code looks good to me!

2023-10-17 13:53 UTC, guidari commented on packages/react/src/components/ComposedModal/ModalFooter.tsx
> +  loadingStatus: PropTypes.oneOf(['inactive', 'active', 'finished', 'error']),
You just have to sort alphabetically here

2023-10-18 18:45 UTC, guidari approved these changes

2023-10-20 16:07 UTC, kingtraceyj requested changes
it looks like the loading state text is slightly off. i'm having a hard time inspecting the elements, but it looks like the text during loading is maybe 2px higher than it should be. here are the 2 states overlayed and the text  should be baseline aligned to avoid jumping:
![image](https://github.com/carbon-design-system/carbon/assets/20582179/bf7a58f5-b6ed-4477-9a98-786685adc3e4)

2023-10-23 19:07 UTC, kingtraceyj commented
@Tomahaawk thanks for the update! i'm still seeing that it's a little off. maybe it's the type size. are you using `$body-short-01` when it's loading?

i'm not using any tools. i guess we just do a lot of these reviews 😅

2023-10-23 20:08 UTC, Tomahaawk commented
@kingtraceyj True, I had not used it. After adding `body-short-01` it seems the text has same height now (I hope this extension I used works properly haha)

Before adding $body-short-01
![image](https://github.com/carbon-design-system/carbon/assets/12561157/2d204e30-14cd-4311-a7c9-361f803035f0)

After adding $body-short-01
![image](https://github.com/carbon-design-system/carbon/assets/12561157/9a1481c8-3b25-4226-81cb-6f6101d39657)
![image](https://github.com/carbon-design-system/carbon/assets/12561157/06d1616d-d051-46ee-b841-1d2b0cd3b403)

2023-10-24 15:02 UTC, kingtraceyj approved these changes
with the updated type token, it looks good to go! thanks for contributing 💥

2023-11-07 11:34 UTC, Tomahaawk commented
@alisonjoseph hi, merge conflicts are solved

2023-11-15 23:55 UTC, andreancardona approved these changes

2023-11-16 18:36 UTC, guidari approved these changes
LGTM! 🚀

2023-11-16 18:39 UTC, kingtraceyj approved these changes

2023-11-17 14:11 UTC, merged