[AVT] - Added keyboard nav test `Breadcrumb`
carbon-design-system/carbon pull request #14639
Opened 2023-09-12 14:42 UTC by guidari

Closes #14638 

Added keyboard navigation to `Breadcrumb` component.

#### Changelog

**New**

- Added new file `e2e/components/breadcrumb/breadcrumb-test.avt.e2e.js`

#### Testing / Reviewing

- Ensure the test pass.
- Ensure that all the necessary navigation is covered.

2023-09-13 18:10 UTC, tay1orjones requested changes
Small naming updates to help with https://github.com/carbon-design-system/carbon/issues/14595

2023-09-13 18:10 UTC, tay1orjones commented on e2e/components/breadcrumb/breadcrumb-test.avt.e2e.js
> +  test('accessibility-checker', async ({ page }) => {
```suggestion
  test('@avt-default-state', async ({ page }) => {
```

2023-09-13 18:10 UTC, tay1orjones commented on e2e/components/breadcrumb/breadcrumb-test.avt.e2e.js
> +  test('accessibility-checker with overflow menu', async ({ page }) => {
```suggestion
  test('@avt-advanced-states with overflow menu ', async ({ page }) => {
```

2023-09-13 18:10 UTC, tay1orjones commented on e2e/components/breadcrumb/breadcrumb-test.avt.e2e.js
> +  test('accessibility-checker skeleton', async ({ page }) => {
```suggestion
  test('@avt-advanced-states skeleton ', async ({ page }) => {
```

2023-09-13 18:10 UTC, tay1orjones commented on e2e/components/breadcrumb/breadcrumb-test.avt.e2e.js
> +  test('accessibility-checker keyboard navigation', async ({ page }) => {
```suggestion
  test('@avt-keyboard-nav', async ({ page }) => {
```

2023-09-13 18:10 UTC, tay1orjones commented on e2e/components/breadcrumb/breadcrumb-test.avt.e2e.js
> +  test('accessibility-checker keyboard navigation - item without href prop', async ({
```suggestion
  test('@avt-keyboard-nav - item without href prop', async ({
```

2023-09-13 18:10 UTC, tay1orjones commented on e2e/components/breadcrumb/breadcrumb-test.avt.e2e.js
> +  test('accessibility-checker with overflow menu keyboard navigation', async ({
```suggestion
  test('@avt-keyboard-nav with overflow menu keyboard navigation', async ({
```

2023-09-13 18:12 UTC, tay1orjones approved these changes
LGTM 👍

2023-09-13 18:24 UTC, tw15egan approved these changes

2023-09-15 17:06 UTC, merged

2023-09-15 18:15 UTC, guidari commented
@tay1orjones FYI, 

I had to changed the way I was expecting this test to work to pass.  For some reason after clicking in a link, the playwright was failing in the CI and even with me increasing the timeout from default 3000ms to 120000ms, 500000ms… kept failing. 

While I was trying to figure out this issue, I found that the tests written with `test.slow()` are not being run in the CI neither locally. I found that once I download the report from playwiright and took a deeper look, the tests are not being addressed there. Maybe we might have to re-write those tests in another way?

![Screenshot 2023-09-14 at 16 51 20](https://github.com/carbon-design-system/carbon/assets/52183462/f4526ee2-8059-40f3-a37b-b1a847f76ce9)

If we search the title of the test with `test.slow()` it doesn't appear in the `report.json` from playwright.
Also it is the screenshot with a long timeout there.