feat: ErrorBoundary avt test
carbon-design-system/carbon pull request #14754
Opened 2023-10-02 23:16 UTC by andreancardona

Closes #14753

Added keyboard navigation to`ErrorBoundary` component.

Added new file e2e/components/DefinitionTooltip /ErrorBoundary-test.avt.e2e.js

Testing / Reviewing: `yarn playwright test components/ErrorBoundary/ErrorBoundary-test.avt.e2e.js`

Ensure the test pass.
Ensure that the expected navigation is covered.

2023-10-04 16:08 UTC, tw15egan approved these changes

2023-10-06 14:56 UTC, guidari requested changes
Hey @andreancardona the tests LGTM! 🚀

Just a couple notes about the declaration, before merge.

2023-10-06 14:56 UTC, guidari commented on e2e/components/ErrorBoundary/ErrorBoundary-test.avt.e2e.js
> +test.describe('ErrorBoundary', () => {
```suggestion
test.describe('ErrorBoundary @avt', () => {
```

2023-10-06 14:56 UTC, guidari commented on e2e/components/ErrorBoundary/ErrorBoundary-test.avt.e2e.js
> +  test('accessibility-checker ErrorBoundary with Custom context @avt', async ({
```suggestion
  test('@avt-advanced-states ErrorBoundary with Custom context', async ({
```

2023-10-06 19:28 UTC, guidari approved these changes

2023-10-10 21:02 UTC, merged