Add Keyboard Nav AVT test for `IconButton`
carbon-design-system/carbon pull request #14829
Opened 2023-10-09 17:39 UTC by guidari

Closes #14798 

Added keyboard navigation to `IconButton` component.

#### Changelog

**New**

- Added new file `e2e/components/IconButton/IconButton-test.avt.e2e.js`

#### Testing / Reviewing

- Ensure the test pass.
- Ensure that the expected navigation is covered.

2023-10-09 17:49 UTC, tay1orjones requested changes
Just one small thing to change, otherwise looks good

2023-10-09 17:49 UTC, tay1orjones commented on e2e/components/IconButton/IconButton-test.avt.e2e.js
> +  test('@avt-keyboard-state IconButton', async ({ page }) => {
```suggestion
  test('@avt-keyboard-nav IconButton', async ({ page }) => {
```

2023-10-09 19:17 UTC, tay1orjones approved these changes

2023-10-10 01:12 UTC, alisonjoseph approved these changes

2023-10-10 12:17 UTC, merged