Add LTS notification - v10 storybook
carbon-design-system/carbon pull request #14860
Opened 2023-10-10 20:06 UTC by guidari

Closes #14765

I've tested each default story, and they all appear to be working well. However, when it comes to the UIShell, there's an issue with the sticky/fixed header. I'm considering the best course of action, which might involve excluding the UIShell to prevent any additional problems when working with that particular story.

#### Changelog

**New**

- Added LTS notification

#### Testing / Reviewing

- Check if the design looks good
- Check if the components looks good

**_OBS: The messege it is just an example, we are still selecting the best one._**

2023-10-10 21:32 UTC, tay1orjones approved these changes
Overall I think it's fine if this doesn't show up on the uishell stories for now, this will hit the vast majority of users being on every other component.

2023-10-10 21:32 UTC, tay1orjones commented on packages/react/.storybook/Container.js
> +            Carbon v10 is currently in maintenance mode, support is scheduled to
Would it make more sense in the storybook to be more explicit on what package and version this applies to? I think the meaning of "v10" could easily be lost on folks.
```suggestion
            carbon-components-react@7.x is in maintenance mode, support is scheduled to
```

2023-10-11 12:16 UTC, guidari commented on packages/react/.storybook/Container.js
> +            Carbon v10 is currently in maintenance mode, support is scheduled to
@tay1orjones Yeah that make sense! 
I also added a link to the release schedule, let me know if looks good.

![Screenshot 2023-10-11 at 09 15 57](https://github.com/carbon-design-system/carbon/assets/52183462/7b7d85aa-4232-4376-8635-d06ce82b245d)

2023-10-11 13:43 UTC, sstrubberg approved these changes

2023-10-11 21:07 UTC, alisonjoseph requested changes, later dismissed
Overall looks good, the link color is wrong for a black background, so may want to get a designer to take a look. Could be easiest to match what we have on the [website banner](https://github.com/carbon-design-system/carbon-website/pull/3769) style-wise?

2023-10-13 13:13 UTC, guidari commented
> Overall looks good, the link color is wrong for a black background, so may want to get a designer to take a look. Could be easiest to match what we have on the [website banner](https://github.com/carbon-design-system/carbon-website/pull/3769) style-wise?

Could be something like this: 

![Screenshot 2023-10-13 at 10 13 14](https://github.com/carbon-design-system/carbon/assets/52183462/0a9ead87-1381-4b32-bbf1-9ba70f63918e)

2023-10-18 19:34 UTC, tw15egan approved these changes

2023-10-19 16:30 UTC, merged