refactor: Add header panel types
carbon-design-system/carbon pull request #15096
Opened 2023-11-02 20:06 UTC by danoro96

Closes #13594

Typed out HeaderPanel.

#### Changelog

**New**

- Added myself to contributors

**Changed**

- Changed HeaderPanel.js to HeaderPanel.tsx and added types as well as fixing an error

#### Testing / Reviewing

Run in storybook and check that there are no issues.

2023-11-02 20:14 UTC, danoro96 commented
I have read the DCO document and I hereby sign the DCO.

2023-11-06 20:27 UTC, tay1orjones requested changes
Thank you! This looks good, just one minor piece on required vs. optional on a few props

2023-11-06 20:27 UTC, tay1orjones commented on packages/react/src/components/UIShell/HeaderPanel.tsx
> +  href: string;
I don't think any of these are required

2023-11-09 20:58 UTC, tay1orjones approved these changes

2023-11-30 00:36 UTC, andreancardona approved these changes

2023-12-04 21:01 UTC, tay1orjones commented on packages/react/src/components/UIShell/HeaderPanel.tsx
> +      [customClassName]: !!customClassName,
It looks like CI is failing on this line

2023-12-04 21:23 UTC, tay1orjones approved these changes
Fixed, looks good 👍

2023-12-04 21:42 UTC, merged