Support docs revised
carbon-design-system/carbon pull request #15180
Opened 2023-11-13 20:17 UTC by sstrubberg

Based on a conversation earlier today with @laurenmrice and @tay1orjones, we have updated our support docs to better clarify what "being on support" looks like.

### What's changed

### Reviewing

Please give feedback where your experience differs on how you deliver support, bringing together all the best practices.

2023-11-14 17:21 UTC, laurenmrice requested changes
Looks good! Just found a couple typos

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +syndrome. Whether you are triaging new issues in Github or responding to Slack
```suggestion
syndrome. Whether you are triaging new issues in GitHub or responding to Slack
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +- “Could you share more about you’ve already tried?”
```suggestion
- “Could you share more about what you’ve already tried?”
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +- “Can you share more about your use-case?”
```suggestion
- “Can you share more about your usecase?”
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +  the person in the community that answered it by adding an emojii or response
```suggestion
  the person in the community that answered it by adding an emoji or response
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +  "How far off am I"? What am I missing? Remember, you're acting as an advocate
```suggestion
  "How far off am I"? "What am I missing"? Remember, you're acting as an advocate
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +- “After searching through FILL IN RESOURCE HERE, I was able to find this and
Just a suggestion: When saying ...FILL IN RESOURCE HERE, you could also put it in brackets like this [FILL IN RESOURCE HERE]

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +  for the person who originally asked the question. Respresent their needs to
```suggestion
  for the person who originally asked the question. Represent their needs to
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +  - [carbon-angulur](https://ibm.enterprise.slack.com/archives/CBZC0LM2N)
```suggestion
  - [carbon-ng](https://ibm.enterprise.slack.com/archives/CBZC0LM2N)
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +### Configuring the Github Slack integration
```suggestion
### Configuring the GitHub Slack integration
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +the template type. There are three types of issues the maintainer team are
```suggestion
the template type. There are three types of issues the maintainer team is
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +the issue. Either `role: dev 🤖` or `role: design :pencil2:`, depending on which
I would double check the pencil emoji here to make sure its showing up.

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +After assigning the role and serverity, be sure to apply the correct categories
```suggestion
After assigning the role and severity, be sure to apply the correct categories
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +in the Github Project:
```suggestion
in the GitHub Project:
```

2023-11-14 17:21 UTC, laurenmrice commented on docs/guides/support.md
> +  - Needs a11y review - Issues that need to be brough the Carbon Accessibility
```suggestion
  - Needs a11y review - Issues that need to be brought to the Carbon Accessibility
```

2023-11-14 23:47 UTC, andreancardona approved these changes
looks good! would recommend @aubrey-oneal to review

2023-11-16 12:11 UTC, guidari approved these changes
Awesome! The docs looks good to me 🚀

One thing that also might be good is implementing bookmarks in the 'carbon-support' channel. For example the Stackblitz draft for reproduction examples and etc...

![Screenshot 2023-11-16 at 09 08 30](https://github.com/carbon-design-system/carbon/assets/52183462/e439133e-fa66-46da-8a54-075843330649)

I can add a few that I find interesting to be there.

2023-11-17 17:20 UTC, laurenmrice approved these changes
Looks good Scott!

2023-11-17 17:23 UTC, sstrubberg commented
> Awesome! The docs looks good to me 🚀
> 
> One thing that also might be good is implementing bookmarks in the 'carbon-support' channel. For example the Stackblitz draft for reproduction examples and etc...
> 
> ![Screenshot 2023-11-16 at 09 08 30](https://user-images.githubusercontent.com/52183462/283443592-e439133e-fa66-46da-8a54-075843330649.jpg)
> 
> I can add a few that I find interesting to be there.

that's a fantastic idea. Please add them!

2023-11-17 17:30 UTC, aubrey-oneal approved these changes
Looks great! 🚀

2023-11-20 20:12 UTC, merged