refactor: Add header types
carbon-design-system/carbon pull request #15242
Opened 2023-11-22 18:06 UTC by danoro96

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2023-11-27 21:18 UTC, tay1orjones requested changes
Thanks for taking this on! I think it looks great. The only thing I see is that each interface needs the prop comments copied from the proptypes for future documentation efforts.

2023-12-01 12:48 UTC, guidari approved these changes
LGTM! 🚀 @danoro96 
Just one minor change

2023-12-01 12:48 UTC, guidari commented on packages/react/src/components/UIShell/HeaderGlobalAction.tsx
> +  children?: ReactNode;
This one should be required
```suggestion
  children: ReactNode;
```

2023-12-04 21:31 UTC, danoro96 commented
Hey all,

It says that there is a merge conflict with `HeaderMenu.js`.
I pulled main and tried to rebase but git says I'm up to date.
Not sure how to fix a merge conflict with a file that is no longer there. 

Any ideas?

2023-12-05 16:54 UTC, danoro96 commented
> Hey all,
> 
> It says that there is a merge conflict with `HeaderMenu.js`. I pulled main and tried to rebase but git says I'm up to date. Not sure how to fix a merge conflict with a file that is no longer there.
> 
> Any ideas?

I was able to remove and re-add the file. That fixed the issue.

2023-12-13 20:47 UTC, tay1orjones requested changes

2023-12-13 20:47 UTC, tay1orjones commented on packages/react/src/components/UIShell/HeaderMenu.tsx
> +    });
This is a functional change, right? This no longer recursively looks through descendant children. I think we'll want to retain that.

2024-01-18 19:50 UTC, closed without merging