fix(react): export types for Stack component
carbon-design-system/carbon pull request #15456
Opened 2024-01-01 19:00 UTC by onurozkardes

Closes #

Add some missing typescript exports for Stack component.

#### Changelog

**New**

- {{new thing}}

**Changed**

- Add missing Stack component export as default.
- Add missing StackProps interface export.
- Isolate & import type declarations of Stack component.
- Isolate & import definitions (SPACING_STEPS) of Stack component.

**Removed**

- Component type declarations (StackProps) moved to new "types.ts" file from "Stack.tsx" file. In this way, complicated code block has been prevented. 

#### Testing / Reviewing

- Compiled component files have been tested on storybook playground. 
- Compiled component files have been tested on a project which works with **Carbon Design System**.

2024-01-01 19:18 UTC, onurozkardes commented
I have read the DCO document and I hereby sign the DCO.

2024-01-01 19:23 UTC, onurozkardes commented
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> I have read the DCO document and I hereby sign the DCO.
> 
> **Onur Özkardeş** seems not to be a GitHub user. You need a GitHub account to be able to sign the DCO. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the DCO document and I hereby sign the DCO.

2024-01-01 19:52 UTC, onurozkardes commented
I have read the DCO document and I hereby sign the DCO.

2024-01-08 14:43 UTC, andreancardona approved these changes

2024-01-08 16:10 UTC, tay1orjones requested changes
Hey there, thanks for this. Could you outline further what the problem is that this is solving?

There's a few conventions we've been following that I outlined below.

2024-01-08 16:10 UTC, tay1orjones commented on packages/react/src/components/Stack/types.ts
So far the convention we've been following is to have the interface directly in the component source file.

2024-01-08 16:10 UTC, tay1orjones commented on packages/react/src/components/Stack/definitions.ts
> +);
To my knowledge this does not (and likely will never) be used outside of the context of `Stack`. Is there a reason requiring this to be in a separate file?

2024-01-08 16:10 UTC, tay1orjones commented on packages/react/src/components/Stack/Stack.tsx
> +export default Stack;
Could you elaborate on why the named export a problem?

2024-01-08 17:58 UTC, onurozkardes commented
> Hey there, thanks for this. Could you outline further what the problem is that this is solving?
> 
> There's a few conventions we've been following that I outlined below.

Hey there,

I'm glad to your review. 
Firstly, I had faced a issue when I used the component on my React & Typescript project due to lack of type declarations on Stack component.
I had purposed to fix that issue and improve code readability by dividing some files (like types, definitions) at my first commit.
Then, as you say, there were some changes that out of your standard. 

I refactored some parts of the code below that you've outlined.

- Type declarations has been moved into main component file again.
- "SPACING_STEPS" variable has been moved into main component file again. 
- "HStack" and "VStack" functions have been moved to its own files. 
- "index.ts" has been changed name instead of "index.tsx". 
- Component exportations has been revised according to what you outlined.

As far as I see, other component index.ts files look quite simple, that's why I divided "HStack" and "VStack" components into new files from "index.tsx".
In this way, "index.ts" file looks very simple anymore and I've just exported related files & types.  

Best regards.

2024-01-16 20:56 UTC, tay1orjones requested changes
Getting close on this one, thanks for your continued effort here

2024-01-16 20:56 UTC, tay1orjones commented on packages/react/src/components/Stack/Stack.tsx
> +});
This should be reverted. Why would the `TextLineSpacing` icon from `@carbon/icons-react` be used to generate the valid spacing steps?

<img width="240" alt="image" src="https://github.com/carbon-design-system/carbon/assets/3360588/873fe3eb-70a3-49f1-a8e6-8e97d6d3e5aa">

2024-01-16 21:11 UTC, onurozkardes commented
> Getting close on this one, thanks for your continued effort here

Hi there,

Thanks for your feedback.
I've just fixed that.

2024-02-15 18:02 UTC, tay1orjones approved these changes

2024-02-15 18:02 UTC, tay1orjones commented
@onurozkardes sorry for the delay here - this has a few conflicts that need resolved

2024-03-13 20:05 UTC, andreancardona approved these changes
tested and looks good!

2024-03-19 14:24 UTC, merged