docs(Slug): add dev docs to Slug overview
carbon-design-system/carbon pull request #15812
Opened 2024-02-21 18:18 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/15784

Adds in documentation regarding the usage of the `Slug` component and its props

#### Changelog

**New**

- Documentation about how to use the `Slug` component and a few of its props

**Changed**

- Added some doc-specific overrides for styles that were being affected. 

#### Testing / Reviewing

Ensure the spelling/grammar is correct and the content makes sense. Is there anything else we are missing?

2024-02-21 20:29 UTC, mattrosno commented
@tw15egan this is excellent. What about the other components? Are there docs explaining how to pass in a Slug component into the slug prop?

2024-02-21 20:33 UTC, tw15egan commented
@mattrosno I can add that. Would it make sense to keep it all in this overview, or should I add it to the examples folder? I’ll add some DataTable docs as well

2024-02-21 20:35 UTC, mattrosno commented
@tw15egan at minimum, maybe something in all 4 Overviews, even if 3 of them just point you to the first that includes all documentation.

<img width="244" alt="image" src="https://github.com/carbon-design-system/carbon/assets/1691245/151c60d4-a773-4bce-bc10-cf83778680e1">

No strong preference here besides having something mentioned in all Overviews.

2024-02-23 14:05 UTC, tw15egan commented
@mattrosno updated

2024-02-26 12:04 UTC, guidari approved these changes
LGTM! 🚀

2024-02-26 16:10 UTC, mattrosno requested changes

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/Slug-datatable.mdx
> +[GitHub](https://github.com/carbon-design-system/carbon/edit/main/packages/react/src/components/RadioButton/RadioButton.mdx).
This link to `RadioButton` needs updated?

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/Slug-datatable.mdx
> +[Slug Release Status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```suggestion
[Slug release status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/Slug.mdx
> +[Slug Release Status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```suggestion
[Slug release status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/SlugExamples.mdx
> +[Slug Release Status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```suggestion
[Slug release status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/SlugForm.mdx
> +[Slug Release Status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```suggestion
[Slug release status](https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo)
```

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/SlugForm.mdx
> +[GitHub](https://github.com/carbon-design-system/carbon/edit/main/packages/react/src/components/RadioButton/RadioButton.mdx).
Here too.

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/SlugExamples.mdx
> +[GitHub](https://github.com/carbon-design-system/carbon/edit/main/packages/react/src/components/RadioButton/RadioButton.mdx).
Here too.

2024-02-26 16:10 UTC, mattrosno commented on packages/react/src/components/Slug/Slug.mdx
> +[GitHub](https://github.com/carbon-design-system/carbon/edit/main/packages/react/src/components/RadioButton/RadioButton.mdx).
Here too.

2024-02-26 16:13 UTC, mattrosno commented on packages/react/src/components/Slug/SlugExamples.mdx
> +  - [Checkbox](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--checkbox)
Not a big deal, but I noticed these open in new browser tabs. When we cross-link stories, do we typically use relative paths or absolute like this?

2024-02-28 15:33 UTC, tw15egan commented
@mattrosno fixed 👍🏻

2024-02-28 16:05 UTC, mattrosno approved these changes

2024-02-28 17:09 UTC, tay1orjones approved these changes

2024-02-28 17:27 UTC, merged