feat(structuredList): update to use radio button icon, radios are left aligned under featureflag
carbon-design-system/carbon pull request #15910
Opened 2024-03-07 10:55 UTC by 2nikhiltom

Closes #15479

**New**

- StructuredList (Selection and with background layer) are updated to use radio buttons icons instead of checkmarks
- Should keep radio unchecked if no defaultSelected is provided
- Adds new feature flag "enable-v12-tile-radio-icons"

**Changed**

- Icons are changed : checkmarks -> radio icons
- Adds "enable-v12-tile-radio-icons" to toggle the position of radio icons (left or right) 
-If featureflag is turned on the radio icons will be at the left 

#### Testing / Reviewing
Verify that radio icons are rendered
Verify the radio are rendered at the end (right) of the list if featureflag is OFF
Verify the radio are rendered at the start (left) of the list if featureflag is ON

2024-03-07 12:46 UTC, 2nikhiltom commented
Hey @Kritvi-bhatia17 : Can I get your design review on this .

2024-03-07 12:52 UTC, Kritvi-bhatia17 commented
Yes! sure @2nikhiltom will do that

2024-03-08 17:51 UTC, tay1orjones requested changes
Feature flags should be used to modify component source code. The feature flag stories for that component would then show the result of the flag being turned on and the modified behavior of the component source code.

Is the current checkmark functionality built into any of the components' source, or does it require the consumer to compose the checkmark into the proper location within StructredListCell?

If it's already on the consumer to compose this properly, we wouldn't need a feature flag. We could just update the existing stories to show the new icon being used on the right.

2024-03-11 09:44 UTC, Kritvi-bhatia17 approved these changes
Looks good to me from design perspective!!
Nice work @2nikhiltom 🔥

2024-03-11 16:55 UTC, Kritvi-bhatia17 requested changes
Hii @2nikhiltom! after speaking with @laurenmrice , I realized that we need to add a prop for both with and without background options under the 'Structured Lists' section for both 'Default' and 'Selection'.

2024-03-12 17:22 UTC, tay1orjones commented
I just pushed an update here that adds the feature flag to modify the styling, and also added a new `selection` prop to `StructuredListRow` that will handle adding the radio button icon on the left.

2024-03-12 17:28 UTC, tay1orjones commented
@2nikhiltom I think I got the focus ring working actually, take a look and let me know what you think

2024-03-20 10:10 UTC, 2nikhiltom commented
I've implemented focus ring operations for keyboard and mouse navigation, following has changed.
- The first item in the list will now receives focus when navigating via the Tab key.
- Items receives focus rings upon being clicked and
- Focus rings are removed when the user clicks away/outside from the focused item

2024-03-20 16:28 UTC, tay1orjones commented
The PublicAPI snapshot is failing, just needs a `yarn test -u` and push up the changes

2024-03-20 18:04 UTC, tay1orjones requested changes
This is looking great, just a couple things to change and I think this will be good to go.

2024-03-20 18:04 UTC, tay1orjones commented on packages/react/src/components/StructuredList/StructuredList.tsx
> +  const useClickOutside = (handler) => {
There's a `useOutsideClick` helper in the codebase that does essentially this same thing that can be used instead.

2024-03-20 18:04 UTC, tay1orjones commented on packages/react/src/components/StructuredList/StructuredList.tsx
> +        hasFocusWithin && (selectedRow === id || selectedRow === null),
Looking at the diff, it seems like the condition here may need to be something closer to

`(hasFocusWithin && !selection) || (hasFocusWithin && selection && selectedRow === id`)

So that the existing behavior is preserved when `!selection`, and that we only check the `selectedRow` if we know `selection` is turned on.

2024-03-20 18:04 UTC, tay1orjones commented on packages/styles/scss/components/structured-list/_structured-list.scss
> +      $enable-v12-structured-list-visible-icons
Both of these need to be false I think
```suggestion
  @if not(
    enabled('enable-v12-structured-list-visible-icons') and
      $enable-v12-structured-list-visible-icons
```

2024-03-20 18:04 UTC, tay1orjones commented on packages/styles/scss/components/structured-list/_structured-list.scss
> +}
```suggestion
```

2024-03-21 04:45 UTC, 2nikhiltom commented on packages/react/src/components/StructuredList/StructuredList.tsx
> +        hasFocusWithin && (selectedRow === id || selectedRow === null),
Hey Taylor,
```
[`${prefix}--structured-list-row--focused-within`]:
        (hasFocusWithin && !selection) ||
        (hasFocusWithin && selection && (selectedRow === id || selectedRow === null)),
```
   Added `(selectedRow === id || selectedRow === null)  `condition as well to ensure focus on the first item/row when list is navigating through Tab keys and no-row is selected (selectedRow === null)

2024-03-21 04:46 UTC, 2nikhiltom commented on packages/react/src/components/StructuredList/StructuredList.tsx
> +  const useClickOutside = (handler) => {
Great catch, thank you. 
Updated the code to use existing `useOutsideClick` helper

2024-03-21 04:52 UTC, 2nikhiltom commented
Hey @tay1orjones , thanks for the review.
I have made suggested changes and few other changes to ensure rows receive focus only when `selection` is enabled, eliminating focus rings on `default` stories.

2024-03-25 08:11 UTC, 2nikhiltom commented
> The PublicAPI snapshot is failing, just needs a `yarn test -u` and push up the changes

Hey @tay1orjones , @andreancardona : it seems like the problem is still there even after running "yarn test -u" and pushing changes. Any ideas on what might be missing?

2024-03-26 16:53 UTC, tay1orjones commented
@2nikhiltom based on [the logs](https://github.com/carbon-design-system/carbon/actions/runs/8369783506/job/22916086871#step:8:82), it was failing on a snapshot change unrelated to the changes you made here. Generally that signals that the PR needs to be updated with the latest from `main` and then the snapshots updated again.

I pressed the "update with latest" button on the PR interface here, pulled down the PR locally, ran `yarn`, `yarn build`, and `yarn test -u` which resulted in two snapshot changes. I pushed them up - I think this should resolve the CI failures.

2024-03-26 16:55 UTC, tay1orjones approved these changes

2024-03-26 16:55 UTC, tay1orjones commented
@Kritvi-bhatia17 @andreancardona this is ready for your review

2024-03-26 21:19 UTC, andreancardona approved these changes
looks good to me - nice job @2nikhiltom !

2024-03-27 12:05 UTC, Kritvi-bhatia17 approved these changes
Great work Nikhil!! 🔥

2024-03-27 13:55 UTC, merged