feat: added dividers accross multiple states for AI select
carbon-design-system/carbon pull request #15952
Opened 2024-03-13 13:09 UTC by riddhybansal

Closes #15860 

Added dividers accross multiple states for AI select

#### Changelog

**New**

- Added dividers accross multiple states for AI select

#### Testing / Reviewing

- Go to the storybook and test the divider by adding warn/invalid to AI select

2024-03-13 14:01 UTC, guidari requested changes
Hey @riddhybansal LGTM 🚀

Just on thing in the Select component
![Screenshot 2024-03-13 at 11 00 01](https://github.com/carbon-design-system/carbon/assets/52183462/f0f5a328-633c-4f7d-80af-9176f6274999)

2024-03-13 14:01 UTC, guidari commented on packages/styles/scss/components/select/_select.scss
> +    inset-inline-end: convert.to-rem(82px);
Maybe you just to have to add the slug `.#{$prefix}--select--slug` class here to make sure it won't change the select.

Something like that:
```suggestion
.#{$prefix}--select--slug
  .#{$prefix}--select-input__wrapper[data-invalid]
    .#{$prefix}--select-input
    ~ .#{$prefix}--select__invalid-icon,
    .#{$prefix}--select--slug
  .#{$prefix}--select-input__wrapper
    .#{$prefix}--select-input
    ~ .#{$prefix}--select__invalid-icon {
    inset-inline-end: convert.to-rem(82px);
```

2024-03-13 15:01 UTC, guidari approved these changes

2024-03-13 15:48 UTC, tay1orjones requested changes
The `padding-inline-end` on the select needs to be modified so text doesn't run behind the icon.

![image](https://github.com/carbon-design-system/carbon/assets/3360588/5575c5b7-a533-4325-99ac-e0804dc69141)

2024-03-13 15:53 UTC, tay1orjones commented
A few other questions I just thought of:

* For the `px` values, could we derive those from the spacing tokens in certain situations? 
* Does this need to be supported for the other `size` options? If so, could we add a control to be able to see how it works with the other sizes?

2024-03-18 15:30 UTC, tay1orjones commented
> * Does this need to be supported for the other `size` options? 

@alina-jacob could you help answer this? The spec only refers to horizontal spacing, so I think the existing solution would work for all sizes _if_ the values should be the same on every size.

2024-03-19 18:48 UTC, alina-jacob commented
> > * Does this need to be supported for the other `size` options?
> 
> @alina-jacob could you help answer this? The spec only refers to horizontal spacing, so I think the existing solution would work for all sizes _if_ the values should be the same on every size.

Hi @tay1orjones you're right, the spacing stays the same across large, medium and small sizes.

2024-03-20 16:23 UTC, alisonjoseph commented on packages/styles/scss/components/select/_select.scss
> +    inset-inline-start: convert.to-rem(-9px);
```suggestion
    inset-inline-start: calc(-#{$spacing-03} - convert.to-rem(1px));
```

In the spirit of @tay1orjones [PR around magic numbers](https://github.com/carbon-design-system/carbon/pull/15995), would we want to update these values to be the padding value plus the divider size?

2024-04-03 12:52 UTC, tay1orjones approved these changes

2024-04-03 12:54 UTC, alina-jacob approved these changes
looks good Riddhi! 🚀 
thanks!

2024-04-03 12:58 UTC, alisonjoseph approved these changes

2024-04-03 19:17 UTC, merged