fix: flush state for accordian component
carbon-design-system/carbon pull request #15993
Opened 2024-03-18 14:49 UTC by riddhybansal

Closes #15849 

Accordion with flush alignment does not meet design spec

**Changed**

- Some styles

#### Testing / Reviewing

Go to Playground for accordion component, enable flush property, title and arrow should be aligned to the borders of accordion

2024-03-18 23:32 UTC, andreancardona approved these changes
tested and looks good to me!

2024-03-21 13:53 UTC, alina-jacob commented
Hi @riddhybansal great work! 💯 
Just one tiny observation 👀 

This is the intended specs for the Hover state of [Flush Accordion](https://carbondesignsystem.com/components/accordion/style#interactive-states)
<img width="1168" alt="image" src="https://github.com/carbon-design-system/carbon/assets/159760598/56b8245e-3331-4134-8efd-af917be4e38d">

The deploy preview link has the horizontal divider stand out in **hover state**, is there a way to blend it the way it works for the regular accordion? 
Also in the preview it looks like the chevron goes missing on **hover state**, not sure why, but could you take a look! 
The chevron up to chevron down interaction is also missing, maybe that's solved if the hover state issue is fixed.
![image](https://github.com/carbon-design-system/carbon/assets/159760598/28e7ca43-4eef-4800-8ae2-2bc2433a7f2f)

2024-03-21 14:01 UTC, tw15egan commented
@alina-jacob it seems like the divider is still there on hover when not `isFlush`, but it is less noticeable since the divider and hover area have the same surface area.

 <img width="905" alt="Screenshot 2024-03-21 at 9 58 27 AM" src="https://github.com/carbon-design-system/carbon/assets/11928039/aae28978-3e4a-455d-8f34-9a63ac2eab8e"> Should this be removed in the normal, non `isFlush` variant as well? 

@riddhybansal it seems like we need to add a `transition` property to the pseudo element, as it is currently instantly appearing / disappearing and causing a flicker on hover

![2024-03-21 09 56 53](https://github.com/carbon-design-system/carbon/assets/11928039/87b42d07-c6c3-48ce-8aa9-77cee7483ab8)

2024-03-25 14:52 UTC, alina-jacob commented
> @alina-jacob it seems like the divider is still there on hover when not `isFlush`, but it is less noticeable since the divider and hover area have the same surface area.
> 
> <img alt="Screenshot 2024-03-21 at 9 58 27 AM" width="905" src="https://private-user-images.githubusercontent.com/11928039/315318536-aae28978-3e4a-455d-8f34-9a63ac2eab8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzgyOTYsIm5iZiI6MTcxMTM3Nzk5NiwicGF0aCI6Ii8xMTkyODAzOS8zMTUzMTg1MzYtYWFlMjg5NzgtM2U0YS00NTVkLThmMzQtOWE2M2FjMmVhYjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OGUyNzZkYjk1ZWE1MGExZTlkNTAxNjI3ZmM2NTBmNTE3ODQ4MTIyMTQ5NzVmMDIxMzM5MGUyNzg2ZDZlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNPcYWl1_VEDrsFLInMM-Rkx5sgjOhfJV04FewsBin4"> Should this be removed in the normal, non `isFlush` variant as well?
> 
> @riddhybansal it seems like we need to add a `transition` property to the pseudo element, as it is currently instantly appearing / disappearing and causing a flicker on hover
> 
> ![2024-03-21 09 56 53](https://private-user-images.githubusercontent.com/11928039/315319449-87b42d07-c6c3-48ce-8aa9-77cee7483ab8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzgyOTYsIm5iZiI6MTcxMTM3Nzk5NiwicGF0aCI6Ii8xMTkyODAzOS8zMTUzMTk0NDktODdiNDJkMDctYzZjMy00OGNlLThhYTktNzdjZWU3NDgzYWI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYzAzNWUwYThhNTIzZjI0ODkzODVmOWFlODBhMTgwNzY2NjA5N2U1ZDcwZTkxMzAxMWM1ZjhhN2MyYmMzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CXH7aYG-nkOsL3Oc8PIvt9MrfcN9UmqNAVlDukCE44Y) [ ![2024-03-21 09 56 53](https://private-user-images.githubusercontent.com/11928039/315319449-87b42d07-c6c3-48ce-8aa9-77cee7483ab8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzgyOTYsIm5iZiI6MTcxMTM3Nzk5NiwicGF0aCI6Ii8xMTkyODAzOS8zMTUzMTk0NDktODdiNDJkMDctYzZjMy00OGNlLThhYTktNzdjZWU3NDgzYWI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYzAzNWUwYThhNTIzZjI0ODkzODVmOWFlODBhMTgwNzY2NjA5N2U1ZDcwZTkxMzAxMWM1ZjhhN2MyYmMzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CXH7aYG-nkOsL3Oc8PIvt9MrfcN9UmqNAVlDukCE44Y) ](https://private-user-images.githubusercontent.com/11928039/315319449-87b42d07-c6c3-48ce-8aa9-77cee7483ab8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzgyOTYsIm5iZiI6MTcxMTM3Nzk5NiwicGF0aCI6Ii8xMTkyODAzOS8zMTUzMTk0NDktODdiNDJkMDctYzZjMy00OGNlLThhYTktNzdjZWU3NDgzYWI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYzAzNWUwYThhNTIzZjI0ODkzODVmOWFlODBhMTgwNzY2NjA5N2U1ZDcwZTkxMzAxMWM1ZjhhN2MyYmMzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CXH7aYG-nkOsL3Oc8PIvt9MrfcN9UmqNAVlDukCE44Y) [ ](https://private-user-images.githubusercontent.com/11928039/315319449-87b42d07-c6c3-48ce-8aa9-77cee7483ab8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzgyOTYsIm5iZiI6MTcxMTM3Nzk5NiwicGF0aCI6Ii8xMTkyODAzOS8zMTUzMTk0NDktODdiNDJkMDctYzZjMy00OGNlLThhYTktNzdjZWU3NDgzYWI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYzAzNWUwYThhNTIzZjI0ODkzODVmOWFlODBhMTgwNzY2NjA5N2U1ZDcwZTkxMzAxMWM1ZjhhN2MyYmMzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CXH7aYG-nkOsL3Oc8PIvt9MrfcN9UmqNAVlDukCE44Y)

yes ✅  @tw15egan, @riddhybansal 
the horizontal divider should be removed/hidden during hover states in flush and default modes for the Accordion. 

here's a [Figma ref file](https://www.figma.com/file/SH2gjkLOP9WvwGFn319iBT/Flush-accordion-specs?type=design&node-id=0%3A1&mode=design&t=1uf2A4zvQOMK7kxq-1) that  @laurenmrice has created and here's [Accordion's style documentation](https://carbondesignsystem.com/components/accordion/style) from the Carbon website indicating the same.

<img width="1180" alt="image" src="https://github.com/carbon-design-system/carbon/assets/159760598/344ab687-a0c9-4b44-a56f-17ef3138bee5">

2024-03-26 11:46 UTC, riddhybansal commented
@alina-jacob the issue regarding the hover states are fixed and the issue of divider for both the flush and non flush states are addressed in the same PR

2024-03-26 13:26 UTC, alisonjoseph requested changes
Removing the border on hover is causing a layout shift. You may have to update the color of the border to match the background?


https://github.com/carbon-design-system/carbon/assets/2753488/84ae924d-fa03-4865-95a6-7b77ad8bb7f9

2024-03-26 17:35 UTC, alisonjoseph commented
Taking a closer look I'm still seeing a weird flash/flickr on hover, however I want to confirm with design that the way its hanging outside of the content area is correct. Or should the text align between the two variants with the divider lines moved in, vs. the hover/focus area pushed out. 

@alina-jacob or @carbon-design-system/design can you weigh in here. This is a screen shot with the padding we add for all our storybook stories removed. You can see that the isFlush variant hangs outside the normal content area. 
<img width="825" alt="Screenshot 2024-03-26 at 12 29 09 PM" src="https://github.com/carbon-design-system/carbon/assets/2753488/378cea04-1cdd-4ca2-972c-4c060af8716d">




Compared with how we handle something similar with ContainedList
<img width="934" alt="Screenshot 2024-03-26 at 12 34 00 PM" src="https://github.com/carbon-design-system/carbon/assets/2753488/f0283cb8-185c-4f8f-b71a-c55fed57975a">

2024-04-01 13:38 UTC, alina-jacob commented
Hi @alisonjoseph, 
Based on the deploy preview, the flush execution seems okay.
Is it an issue if the hover/active/focus state hangs out of the content area from a dev perspective?

- Riddhi has pushed the text and icons to the left and right to meet the width of the divider.
- The contained list screenshot that you have shared, that has the line pushed in to meet the text and the icons.
(is one better than the other from a dev perspective, because design wise, the current way also works)

2024-04-01 14:00 UTC, alisonjoseph commented
My opinion is that we wouldn't want it to hang outside of the content area, and instead push in. @tw15egan @laurenmrice thoughts?

2024-04-01 14:31 UTC, laurenmrice commented
For context, this is the type of area in a UI where our users are using the flush accordion to achieve better vertical text alignment. The focus and hover states would hit the edges of the left panel container, and those states would extend outside of the divider borders between the rows. People should not mix the flush alignment with the default alignment within one accordion group. 

And yes, to Alison's point above, we do not want to remove the hang for the hover and focus states for this because it would create visual tension between the edges of the state containers and the text.

<img width="708" alt="Screenshot 2024-04-01 at 10 24 56 AM" src="https://github.com/carbon-design-system/carbon/assets/43969356/e60a5338-f907-4c95-beea-67335688d331">

2024-04-01 16:34 UTC, alisonjoseph commented
@laurenmrice thank you so much for the example! That clears things up for me. 

@riddhybansal If you see the in-context example above from Lauren you'll see how it should display in a container. So you'll want to adjust the styles so that the appearance of the border shifts inward by 1rem on either side instead of the entire accordion shifting outward by 1rem. 

Currently the border is set on `.cds--accordion__item`, for this you'll have to remove that border and use psuedo-elements instead. You'll need to do something similar for the hover on `.cds--accordion__heading`. Something similar to below. Let me know if you get stuck/need to pair up. 
<img width="302" alt="Screenshot 2024-04-01 at 11 30 41 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/567671ba-2112-47dd-95bf-01864fa7bf7c">

2024-04-15 13:33 UTC, alisonjoseph commented
@riddhybansal whats the status on this one? Let me know if you need to pair up.

2024-04-22 16:10 UTC, tw15egan requested changes, later dismissed
Noticed some other hover issues:

`isFlush` enabled, hovering over an expanded `AccordionItem` seems to make a border disappear
![2024-04-22 12 05 35](https://github.com/carbon-design-system/carbon/assets/11928039/16698386-8f94-4c3e-bc42-409b9cc2f060)



<br />
<br />
<br />

Issues when hovering over expanded `AccordionItem` when `isFlush` is not being used

![2024-04-22 12 04 40](https://github.com/carbon-design-system/carbon/assets/11928039/dae7d33d-8da3-4a4d-a5d4-89149acca6d2)

Issues when hovering over the 2nd to last item when `isFlush` is not present

![2024-04-22 12 03 51](https://github.com/carbon-design-system/carbon/assets/11928039/2207da93-f47e-4a4f-bb60-c3110e49fe61)

2024-04-22 16:10 UTC, tw15egan commented on packages/styles/scss/components/accordion/_accordion.scss
> +
Can we add a transition to the `border-color` for the `accordion-item` so it matches the background change? 

L62:
```scss
transition: border-color motion(standard, productive) $duration-fast-02;
```

2024-04-22 16:10 UTC, tw15egan commented on packages/styles/scss/components/accordion/_accordion.scss
> +  margin-inline-start: $spacing-05;
Same as above, can we add a transition so the hover styles match the background color change?

```suggestion
  margin-inline-start: $spacing-05;
  transition: border-color motion(standard, productive) $duration-fast-02;
```

2024-04-22 16:10 UTC, tw15egan commented on packages/styles/scss/components/accordion/_accordion.scss
> +  block-size: 100%;
Does this need to be 100%, or can it just be 1px? Seems to just be acting as a pseudo border

2024-04-22 16:10 UTC, tw15egan commented on packages/styles/scss/components/accordion/_accordion.scss
> +
Is this still needed?

2024-04-22 16:10 UTC, tw15egan commented on packages/styles/scss/components/accordion/_accordion.scss
> +// }
Is this commented out code still relevant?

2024-04-22 16:19 UTC, riddhybansal commented
@tw15egan removing border for the hover state of flush or default states is one of the requirement mentioned above by @alina-jacob . Oh may be we can have dividers in the expanded state. Is that what you mean ?

2024-04-22 16:48 UTC, tw15egan commented
@riddhybansal yes, it seems like the divider is being removed when it is expanded and hovering over the content section

2024-04-24 11:02 UTC, riddhybansal commented
Hi @tw15egan I hope all the above issues have been resolved. I restricted blending of border when accordian is in expanded state. But I wonder if we could blend the top border even if its expanded and somehow restrict the blending when the content is hovered. If yes how can I restrict parent element to apply its hovering properties when child is being hovered, any idea ?

2024-04-26 13:31 UTC, alisonjoseph requested changes
I'm seeing some changes to the original accordion with the border disappearing on hover.
<img width="1258" alt="Screenshot 2024-04-26 at 8 23 40 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/ab882d6b-f784-43c4-970c-cd5bf3f84c76">

and this is in this PR

<img width="1264" alt="Screenshot 2024-04-26 at 8 25 00 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/a1ef15bc-260a-4f63-9e09-0a0f63b71c68">

Is this intentional?

I'm also seeing some alignment issues between flush and default when testing locally with them side by side. 
<img width="1283" alt="Screenshot 2024-04-26 at 8 26 05 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/7309280b-7215-4d0f-880b-82cb3cd71215">

2024-05-13 18:52 UTC, alisonjoseph commented
@riddhybansal I pushed some updates to this PR, we can talk through in a webex if needed. 

I added a test story so we can view the flush variant side by side, I also updated/fixed skeleton states. (will need to remove test story before merging)

2024-05-15 14:01 UTC, alisonjoseph approved these changes

2024-05-17 16:38 UTC, aagonzales approved these changes
Oh wow lots of comments in this PR but it looks like everything has been addressed. Final demo is working as expected.

2024-05-21 15:00 UTC, tay1orjones approved these changes

2024-05-21 16:57 UTC, merged