fix: radio button storybook bug
carbon-design-system/carbon pull request #16082
Opened 2024-03-27 18:55 UTC by andreancardona

Closes #15705 

added the  `defaultSelected` prop in the `RadioButton` playground

#### Changelog

**Removed**

Removed the following props from `RadioButton`

- checked 
- defaultChecked

#### Testing / Reviewing
- Checkout the `defaultSelected` prop in the `RadioButton` playground

2024-03-27 18:56 UTC, andreancardona commented on packages/react/src/components/RadioButton/RadioButton.stories.js
> +    options: ['radio-1', 'radio-2','radio-3'],
```suggestion
    options: ['radio-1', 'radio-2',' radio-3'],
```

2024-03-27 18:57 UTC, andreancardona commented on packages/react/src/components/RadioButton/RadioButton.stories.js
> +    options: ['radio-1', 'radio-2','radio-3'],
```suggestion
    options: ['radio-1', 'radio-2', 'radio-3'],
```

2024-03-27 19:10 UTC, alisonjoseph requested changes
Looking at the issue, looks like we also need to remove the `defaultSelected` prop from the default story.

2024-03-27 19:25 UTC, tay1orjones approved these changes
Yeah, I agree with Alison. Other than that I think this looks great

2024-03-27 22:10 UTC, andreancardona commented
it shouldn't be selected? Just want to clarify here:

![Uploading Screenshot 2024-03-27 at 15.09.19.png…]()

2024-03-29 13:25 UTC, alisonjoseph approved these changes

2024-03-29 13:27 UTC, alisonjoseph requested changes
oops hit approve accidentally. The issue says not selected.

<img width="825" alt="Screenshot 2024-03-29 at 8 26 11 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/332e4b0f-0a5c-4d46-bd42-9f4f519d7330">

2024-04-02 08:00 UTC, Kritvi-bhatia17 requested changes, later dismissed
Hi @andreancardona, I noticed the smart adjustment you made for the default dropdown options!
However, I'm encountering an issue where the default dropdown options 1, 2, and 3 aren't functioning as expected. When I select different options, the output consistently shows the 3rd option as selected. Could you please take a look?

https://github.com/carbon-design-system/carbon/assets/158570656/c0ea6aa6-5511-43e6-8b6a-55852115c662

2024-04-02 19:55 UTC, tay1orjones commented
@Kritvi-bhatia17 `defaultSelected` only impacts which one is selected in the initial render. To see your change you'll need to refresh the story


https://github.com/carbon-design-system/carbon/assets/3360588/b427e00b-2a69-4ae9-be64-e3fe135ac2ec

2024-04-03 09:25 UTC, Kritvi-bhatia17 commented
> @Kritvi-bhatia17 `defaultSelected` only impacts which one is selected in the initial render. To see your change you'll need to refresh the story
> 
>  defaults.update.after.refresh.mov

Ohh damn, I didn't know that earlier. Thanks Taylor!

2024-04-03 09:26 UTC, Kritvi-bhatia17 approved these changes
Nice work @andreancardona 🔥
Looks good to me from design perspective!

2024-04-03 13:41 UTC, tw15egan approved these changes
LGTM 👍 ✅

2024-04-03 13:47 UTC, alisonjoseph approved these changes

2024-04-03 16:36 UTC, merged