fix: collapse sidenav menus when side nav is closed
carbon-design-system/carbon pull request #16096
Opened 2024-03-29 12:57 UTC by riddhybansal

Closes #15900 

Submenus should close when side nav closes

#### Changelog

**Changed**

- Style changes

#### Testing / Reviewing

Go to storybook , Open Side Nav -> Open Submenu -> Close side nav ,  sub menu  should collapse autromatically.

2024-03-29 19:12 UTC, tay1orjones requested changes
Generally `display: none` can't be used because it [removes the element(s) from the accessibility tree](https://developer.mozilla.org/en-US/docs/Web/CSS/display#accessibility_concerns) and so it won't be read by screenreaders.  

Instead of a style-related fix, would it make sense to modify the internal state of SideNavMenu to account for the change in the parent SideNav?

This bug was introduced https://github.com/carbon-design-system/carbon/pull/15349, my guess is the fix for this would be something similar to what was removed, but without reintroducing the bug it was fixing.

2024-04-02 17:05 UTC, tay1orjones requested changes

2024-04-02 17:05 UTC, tay1orjones commented on packages/react/src/components/UIShell/SideNavMenu.tsx
> +    if (isSideNavExpanded === false && isExpanded === true && isRail === true) {
```suggestion
    if (!isSideNavExpanded && isExpanded && isRail) {
```

2024-04-02 17:05 UTC, tay1orjones commented on packages/react/src/components/UIShell/SideNavMenu.tsx
> +    ) {
```suggestion
    } else if (isSideNavExpanded && prevExpanded && isRail) {
```

2024-04-02 17:07 UTC, tay1orjones approved these changes

2024-04-03 10:31 UTC, guidari approved these changes
LGTM! 🚀

2024-04-03 16:36 UTC, merged