fix(15859,16095): Added divider to NumberInput,Unintended Divider/Outline removed, Avoids magic numbers
carbon-design-system/carbon pull request #16133
Opened 2024-04-04 10:54 UTC by 2nikhiltom

Closes #15859 & #16095

- Added dividers to `NumberInput` across all states (warn/invalid)
- Fixes :  Unintended Divider/Outline Appears When Input is Focused or is Invalid
- Removed Magic numbers

 
**New**

- Dividers in `NumberInput`
- Styles fixes
- Magic numbers removed

**Changed**

-  Styles changes  

**Removed**

- Magic Numbers removed

#### Testing / Reviewing

1. Open story book
2. Open unstable--slug component under experimental_folder
3. Expand examples sub-folder and open numberInput component
4. Test the dividers across all states (warn/invalid)

2024-04-08 14:13 UTC, guidari approved these changes
LGTM! 🚀

2024-04-08 17:04 UTC, alisonjoseph requested changes
Overall looks good, just a couple suggestions to make sure we're using the correct tokens vs. hard coded values anywhere.

2024-04-08 17:04 UTC, alisonjoseph commented on packages/styles/scss/components/number-input/_number-input.scss
> +      box-shadow: 0 -1px 0 var(--cds-border-strong) inset;
```suggestion
      box-shadow: 0 -1px 0 $border-strong inset;
```

2024-04-08 17:04 UTC, alisonjoseph commented on packages/styles/scss/components/number-input/_number-input.scss
> +    border-color: var(--cds-focus, #0f62fe);
```suggestion
    border-width: 2px 0;
    border-style: solid;
    border-color: $focus;
```

2024-04-08 17:04 UTC, alisonjoseph commented on packages/styles/scss/components/number-input/_number-input.scss
> +    box-shadow: -4px 0 0 -2px #0f62fe inset;
```suggestion
    box-shadow: -4px 0 0 -2px $focus inset;
```

2024-04-08 17:04 UTC, alisonjoseph commented on packages/styles/scss/components/number-input/_number-input.scss
> +    box-shadow: -4px 0 0 -2px #da1e28 inset;
```suggestion
    box-shadow: -4px 0 0 -2px $support-error inset;
```

2024-04-08 17:04 UTC, alisonjoseph commented on packages/styles/scss/components/number-input/_number-input.scss
> +    border-color: var(--cds-support-error, #da1e28);
```suggestion
    border-width: 2px 0;
    border-style: solid;
    border-color: $support-error;
```

2024-04-08 17:04 UTC, alisonjoseph commented on packages/styles/scss/components/number-input/_number-input.scss
> +  box-shadow: 0 -1px 0 var(--cds-ai-border-strong, #4589ff) inset;
```suggestion
  box-shadow: 0 -1px 0 $ai-border-strong inset;
```

2024-04-08 19:24 UTC, 2nikhiltom commented
Thanks @alisonjoseph for looking into this, styles are now updated with correct Saas tokens

2024-04-09 14:43 UTC, alisonjoseph approved these changes

2024-04-09 19:34 UTC, tay1orjones approved these changes

2024-04-09 20:01 UTC, tay1orjones commented
@Kritvi-bhatia17 this one just needs a visual review

2024-04-10 11:21 UTC, Kritvi-bhatia17 commented
> @Kritvi-bhatia17 this one just needs a visual review

Hi @tay1orjones! @alina-jacob has worked on the dropdown and would be better positioned to review it since she has more context.

2024-04-10 15:29 UTC, alina-jacob approved these changes
Looks good to me Nikhil! 🚀 
Thanks!

2024-04-10 17:25 UTC, merged