feat(structuredlist): aligned the radio icons to center
carbon-design-system/carbon pull request #16208
Opened 2024-04-16 12:21 UTC by Gururajj77

Closes #16081 

aligned the icons as expected

#### Changelog

**Changed**

- modified the margin to accommodate centre alignment.

#### Testing / Reviewing

no new observations recored.

2024-04-16 13:32 UTC, Kritvi-bhatia17 approved these changes
Looks good to me @Gururajj77 from design perspective!!

2024-04-16 14:42 UTC, alisonjoseph requested changes
Looks good, just want to make sure we use spacing tokens.

2024-04-16 14:42 UTC, alisonjoseph commented on packages/styles/scss/components/structured-list/_structured-list.scss
> +    margin-block-start: 2px;
```suggestion
    margin-block-start: $spacing-01;
```

2024-04-16 14:42 UTC, alisonjoseph commented on packages/styles/scss/components/structured-list/_structured-list.scss
> +    margin-block-start: 2px;
```suggestion
    margin-block-start: $spacing-01;
```

2024-04-17 07:54 UTC, Gururajj77 commented on packages/styles/scss/components/structured-list/_structured-list.scss
> +    margin-block-start: 2px;
Will use tokens from now.

2024-04-17 17:50 UTC, alisonjoseph requested changes
Sorry missed this on the first review, you will also want to update the classname to follow [BEM](https://github.com/carbon-design-system/carbon/blob/main/docs/developer-handbook.md#coding-style).

2024-04-17 17:50 UTC, alisonjoseph commented on packages/react/src/components/StructuredList/StructuredList.tsx
> +                className={`${prefix}--structured-list-icons`}
```suggestion
                className={`${prefix}--structured-list--icon`}
```

2024-04-17 17:50 UTC, alisonjoseph commented on packages/react/src/components/StructuredList/StructuredList.tsx
> +              <RadioButton className={`${prefix}--structured-list-icons`} />
```suggestion
              <RadioButton className={`${prefix}--structured-list--icon`} />
```

2024-04-17 17:50 UTC, alisonjoseph commented on packages/styles/scss/components/structured-list/_structured-list.scss
> +  .#{$prefix}--structured-list-icons {
```suggestion
  .#{$prefix}--structured-list--icon {
```

2024-04-25 14:52 UTC, alisonjoseph approved these changes

2024-04-30 17:45 UTC, tay1orjones approved these changes

2024-05-03 16:30 UTC, merged