feat: export props for accordion
carbon-design-system/carbon pull request #16284
Opened 2024-04-30 08:19 UTC by Gururajj77

Closes #16154

Created a Draft PR to get the export reviewed

#### Changelog

**Changed**

- Exporting AccordionProps

2024-05-01 20:10 UTC, tay1orjones requested changes
We probably should be as explicit as possible with both the imports and exports. 


--- 

Do you think we could batch all the other ones into one PR or would you prefer to do separate ones for each listed in https://github.com/carbon-design-system/carbon/issues/16154

Also see my note over there: https://github.com/carbon-design-system/carbon/issues/16154#issuecomment-2089046474 - I think the expectation here for now is that we'll only be able to make these available through fully qualified import paths, e.g. 

```
import { type AccordionProps } from "@carbon/react/es/components/Accordion";
```

Does that match what you've understood so far here working on this? Maybe I'm incorrect.

2024-05-01 20:10 UTC, tay1orjones commented on packages/react/src/components/Accordion/index.tsx
> +import Accordion, { AccordionProps } from './Accordion';
```suggestion
import Accordion, { type AccordionProps } from './Accordion';
```

2024-05-01 20:10 UTC, tay1orjones commented on packages/react/src/components/Accordion/index.tsx
> +export type { AccordionProps };
```suggestion
export { Accordion, type AccordionProps };
```

2024-05-13 10:27 UTC, Gururajj77 commented
This was a demo PR, actual PRs for the export are raised: #16447 and #16448

2024-05-13 10:27 UTC, closed without merging