chore: refactor to use useCombobox
carbon-design-system/carbon pull request #16283
Opened 2024-04-30 06:50 UTC by preetibansalui

Closes #14684 

Refactored the code to use usecombobox

#### Changelog

**Changed**

Code refactored

#### Testing / Reviewing

It should work in similar ways as existing combobox.

2024-05-01 13:07 UTC, tay1orjones commented on packages/react/src/components/ComboBox/ComboBox.tsx
> +  >,
I'm concerned this could be a breaking change

2024-05-02 05:23 UTC, preetibansalui commented on packages/react/src/components/ComboBox/ComboBox.tsx
> +  >,
Any suggestions please? 
Functionality wise it's working fine although with 'onStateChange' like what we were using this prop earlier.

2024-05-06 12:05 UTC, tay1orjones commented on packages/react/src/components/ComboBox/ComboBox.tsx
> +  >,
Yeah you're right this looks fine, my mistake

2024-05-06 12:08 UTC, tay1orjones commented
@tw15egan @guidari This one's ready for review

It looks like this solves https://github.com/carbon-design-system/carbon/issues/15927 too. 

I've closed the original PR, https://github.com/carbon-design-system/carbon/pull/15904

2024-05-08 16:37 UTC, guidari requested changes
Hey Preeti! Sorry for the late review on this.

A few things I noticed
1 - The ComboBox only opens when the icon is clicked. it should open if is clicked in the anywhere inside the input.
2 - When opening the Combobox with keyboard and searching for "3" (which is the disabled option) and after that pressing Enter, the Combobox is closed. It should stay open. 
Also looks like is not announcing the disabled option in the VO when searching.

I'm happy to pair up to check any of those cases, if you want.

2024-05-08 16:38 UTC, guidari commented on packages/react/src/components/ComboBox/ComboBox.tsx
> +            break;
We can remove that.
```suggestion
```

2024-05-08 17:19 UTC, tay1orjones commented
> A few things I noticed
> 1 - The ComboBox only opens when the icon is clicked. it should open if is clicked in the anywhere inside the input.
> 2 - When opening the Combobox with keyboard and searching for "3" (which is the disabled option) and after that pressing Enter, the Combobox is closed. It should stay open.

It would be awesome if as these are fixed, new test cases could be written to cover this functionality and ensure it continues to work as expected

2024-05-09 13:34 UTC, guidari approved these changes
LGTM! 🚀
Let's open an issue to track the VO not reading the disabled item

2024-05-09 13:51 UTC, tay1orjones approved these changes
LGTM once the conflicts are fixed 🎉

2024-05-10 09:27 UTC, merged