Added Popover example to DataTable filtering story
carbon-design-system/carbon pull request #16303
Opened 2024-05-02 14:58 UTC by guidari

Closes #15339

The idea wast to build a filter functionality off the Datatable so the users can grab the code as a template example to build their own filter.

#### Changelog

**New**

- New template code in Datatable Filtering stories

#### Testing / Reviewing

- Make sure the overview.mdx make it clear the step to implement the `TableToolbarFilter.tsx` 
- Test the Datatable Filtering stories

2024-05-06 12:39 UTC, tay1orjones approved these changes
This looks so good! 🔥 

Just a couple minor edits on the docs, otherwise this looks ready to merge to me.

2024-05-06 12:39 UTC, tay1orjones commented on packages/react/src/components/DataTable/DataTable.mdx
> +### Filtering with checkboxes
```suggestion
### Multiple filters with batch updates
```

Just to match the section on the [website](https://carbondesignsystem.com/patterns/filtering/#multiple-filters-with-batch-updates)

2024-05-06 12:39 UTC, tay1orjones commented on packages/react/src/components/DataTable/DataTable.mdx
> +you to implement a filter using checkboxes.
```suggestion
The filtering story shows an example of how to implement the [batch filtering](https://carbondesignsystem.com/patterns/filtering/#multiple-filters-with-batch-updates) pattern.
```

2024-05-06 12:39 UTC, tay1orjones commented on packages/react/src/components/DataTable/DataTable.mdx
> +`TableToolbarContent` like that:
```suggestion
To implement this in your own project you can copy the
[`TableToolbarFilter`](https://github.com/carbon-design-system/carbon/blob/15339-datatable/packages/react/src/components/DataTable/stories/examples/TableToolbarFilter.tsx)
example component into your code. You can then import and use it inside `TableToolbarContent`:
```

2024-05-06 12:39 UTC, tay1orjones commented on packages/react/src/components/DataTable/DataTable.mdx
> +the initial data you want to pass into the DataTable.
```suggestion
You can write the code to handle the filters in the same file where you have your DataTable with your data. Use the code below as a
template and then customize it as needed. Make sure to replace "YOUR_DATA" with
the initial data you want to pass into the DataTable.
```

2024-05-06 12:39 UTC, tay1orjones commented on packages/react/src/components/DataTable/DataTable.mdx
> +Finally pass in the Datatable props the value from the `useState`.
```suggestion
Finally, pass the array of rows from the `useState` into the DataTable.
```

2024-05-07 12:44 UTC, alisonjoseph approved these changes
Looks good!

2024-05-07 12:47 UTC, alisonjoseph requested changes
Sorry, just went to close my preview window and realized the popover colors are different for settings and filter. I think settings is correct, but we should check with design if not sure.
<img width="284" alt="Screenshot 2024-05-07 at 7 47 11 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/2f387011-87ad-429c-a5f6-8888bdda51ba">
<img width="409" alt="Screenshot 2024-05-07 at 7 47 33 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/28ef0be1-82f9-4066-be43-5a243a3f278b">

2024-05-07 13:33 UTC, guidari commented
> Sorry, just went to close my preview window and realized the popover colors are different for settings and filter. I think settings is correct, but we should check with design if not sure. Functionality and docs look great though 🔥

Ohh! Good catch. I'm gonna take a look and check with design if they want to change something!

2024-05-07 18:27 UTC, thyhmdo commented
Good catch @alisonjoseph yeah the color should be the same with the settings' popover, or one layer up from it. 
I also noticed another thing is that these two buttons can be opened at the same time? Is there a way to close one popover if the user chooses to open another one? 

https://github.com/carbon-design-system/carbon/assets/77697351/729d4e7f-d9da-43f2-b5dc-edc773336541

2024-05-08 12:57 UTC, guidari commented
> Good catch @alisonjoseph yeah the color should be the same with the settings' popover, or one layer up from it. I also noticed another thing is that these two buttons can be opened at the same time? Is there a way to close one popover if the user chooses to open another one?

Fixed @thyhmdo ! Looks like the Popover gets an error when clicks on an OverflowMenu, which results in the state being kept open instead of closing it.
I can open an issue to track that.

2024-05-08 13:00 UTC, alisonjoseph approved these changes
LGTM!
<img width="344" alt="Screenshot 2024-05-08 at 8 00 35 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/d5c0ed5b-7c20-4215-bcd8-58bea0219627">

2024-05-08 13:23 UTC, alisonjoseph requested changes
Percy caught an issues with different themes

2024-05-08 16:34 UTC, alisonjoseph approved these changes
🔥

2024-05-08 16:56 UTC, merged