fix(ComposedModal): removed extra tooltip for close icon
carbon-design-system/carbon pull request #16728
Opened 2024-06-10 09:19 UTC by nandininarayanofficial

Closes #16724

Removed additional close tooltip for ComposedModel

**Changed**

- ModalHeader.tsx
Removed title value from close icon
Updated ComposedModal-test.js

#### Testing / Reviewing

ComposedModal

2024-06-10 09:21 UTC, nandininarayanofficial commented
I have read the DCO document and I hereby sign the DCO.

2024-06-11 15:05 UTC, guidari approved these changes
LGTM! The VO still reading as expected

2024-06-11 19:43 UTC, tay1orjones approved these changes

2024-06-11 19:51 UTC, tay1orjones commented
@nandininarayanofficial this looks good to merge but needs the all contributors regenerated to resolve the merge conflict.

2024-06-12 06:50 UTC, nandininarayanofficial commented
@tay1orjones I resolved the conflicts, please review, Thanks!

2024-06-12 13:18 UTC, preetibansalui commented on README.md
> +    <td align="center"><img src="https://avatars.githubusercontent.com/u/37899503?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Kilian Collender</b></sub><br /><a href="https://github.com/carbon-de
Hey, looks like you removed the anchor tag from name and picture of this contributor.

2024-06-12 13:20 UTC, preetibansalui requested changes
A minor change is required.

2024-06-12 14:28 UTC, nandininarayanofficial commented
@preetibansalui thank you for noticing this, fixed it, please review!

2024-06-13 07:53 UTC, preetibansalui approved these changes

2024-06-14 17:45 UTC, merged