feat: initial commit
carbon-design-system/carbon pull request #16786
Opened 2024-06-14 14:37 UTC by preetibansalui

Closes #16541 

Add floating ui to new overflow menu(behind the enable-v12-overflowmenu flag)

2024-06-17 17:31 UTC, tay1orjones requested changes
The alignment options need to reflect [the spec](https://carbondesignsystem.com/components/menu-buttons/usage#alignment) and be restricted so that the floating element doea not appear to the left or right of the trigger element, only above and below. The `start` and `end` options for `top` and `bottom` are valid too I believe. 

These two are invalid though, for instance:

| | |
|--------|--------|
| <img width="200" src="https://github.com/carbon-design-system/carbon/assets/3360588/cbd616c3-a2b3-46a1-90e0-1c2839fc53b2"> | <img width="200" src="https://github.com/carbon-design-system/carbon/assets/3360588/a5165302-8fb4-49a7-91fe-a722214ee10b"> |

2024-06-17 17:31 UTC, tay1orjones commented on packages/react/src/components/OverflowMenu/OverflowMenu.featureflag.stories.js
> +        }}>
Could this use the setup used in the popover autoalign stories instead? Right now I can't test to see what happens when scrolling side to side.

The popover autoalign stories center the element in a large box and uses `scrollIntoView` to ensure it's visible when the story is rendered.

2024-06-18 08:22 UTC, preetibansalui commented
> The alignment options need to reflect [the spec](https://carbondesignsystem.com/components/menu-buttons/usage#alignment) and be restricted so that the floating element doea not appear to the left or right of the trigger element, only above and below. The `start` and `end` options for `top` and `bottom` are valid too I believe.
> 
> These two are invalid though, for instance:
> 
> <img alt="" width="200" src="https://private-user-images.githubusercontent.com/3360588/340396005-cbd616c3-a2b3-46a1-90e0-1c2839fc53b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTUzODAsIm5iZiI6MTcxODY5NTA4MCwicGF0aCI6Ii8zMzYwNTg4LzM0MDM5NjAwNS1jYmQ2MTZjMy1hMmIzLTQ2YTEtOTBlMC0xYzI4MzlmYzUzYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDcxODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc4MzY4ZjdjYTE4ZjA0ZTM0ZTA0MjU0NjYyYThkN2Y5MjMxNDcyOTI3YTk1OGFlOTY2MjQ0ZDkwN2RiNzgzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hWdecpXseFRwywDjnk0rcoNHoHiajjoRA4dCg4DAlZU">	<img alt="" width="200" src="https://private-user-images.githubusercontent.com/3360588/340396049-a5165302-8fb4-49a7-91fe-a722214ee10b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTUzODAsIm5iZiI6MTcxODY5NTA4MCwicGF0aCI6Ii8zMzYwNTg4LzM0MDM5NjA0OS1hNTE2NTMwMi04ZmI0LTQ5YTctOTFmZS1hNzIyMjE0ZWUxMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDcxODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWNiYWVjMTFiYTdlODg3YThiMjQ1NWFiYmYxMWNiYzM2Zjc1NGU1MzFjZDM2ZTZlODkyMjc3Yjk2MWQyZDk4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u1PuSTbqq8DH5wC6AbgtR4dbiG36fpH3yzcKzfGwyYk">

@tay1orjones : Thanks for the suggestions, I have added the fallbackPlacements, please review.

2024-06-20 18:33 UTC, tay1orjones approved these changes
🎉

2024-06-21 07:10 UTC, riddhybansal approved these changes
This looks so good !!

2024-06-21 07:25 UTC, merged