fix(search): a11y warning on search not expanded
carbon-design-system/carbon pull request #16873
Opened 2024-06-26 17:01 UTC by ariellalgilmore

Closes from ibm-products [#4766](https://github.com/carbon-design-system/ibm-products/issues/4766)

IBM Equal Access Accessibility Checker - warning on the search icon with `role="button"` since it's not tabbable

#### Changelog

**Changed**

- added a conditional on the `aria-label` and `role` for the search icon to only have values when `onExpand`

#### Testing / Reviewing

Ran the IBM Equal Access Accessibility checker on the component

Before:
<img width="1725" alt="Screenshot 2024-06-26 at 9 58 07 AM" src="https://github.com/carbon-design-system/carbon/assets/20210594/18d90cf3-8341-4137-b22e-7334c50780f5">

After:
<img width="1689" alt="Screenshot 2024-06-26 at 9 57 24 AM" src="https://github.com/carbon-design-system/carbon/assets/20210594/ed00cc2b-5870-47bb-aeb6-61356dfc6ff9">

2024-06-26 18:26 UTC, guidari requested changes
LGTM!
Just one note. Can we apply `undefined`, so we don't have an attribute without a value.

![Screenshot 2024-06-26 at 15 22 49](https://github.com/carbon-design-system/carbon/assets/52183462/4036b8e1-4e45-438b-a613-37ffbfe24998)

2024-06-26 18:26 UTC, guidari commented on packages/react/src/components/Search/Search.tsx
> +        aria-label={onExpand ? 'button' : ''}
```suggestion
        aria-label={onExpand ? 'button' : undefined}
```

2024-06-26 18:26 UTC, guidari commented on packages/react/src/components/Search/Search.tsx
> +        role={onExpand ? 'button' : ''}
```suggestion
        role={onExpand ? 'button' : undefined}
```

2024-06-26 18:30 UTC, ariellalgilmore commented on packages/react/src/components/Search/Search.tsx
> +        role={onExpand ? 'button' : ''}
yes good call!! thank you!

2024-06-28 08:55 UTC, riddhybansal approved these changes
LGTM 🚀

2024-06-28 19:18 UTC, tay1orjones approved these changes

2024-07-01 13:09 UTC, alisonjoseph approved these changes

2024-07-01 17:49 UTC, guidari approved these changes

2024-07-01 18:05 UTC, merged