feat(theming): Add component specific variables
carbon-design-system/carbon pull request #169
Opened 2017-06-07 20:41 UTC by tw15egan

# Theming - Components

Watson theme change requests can be found here: https://ibm.ent.box.com/file/179323525996

## Changed
**Accordion**
- Added variables so that the chevrons could align to the right, and other variables to ensure padding/margin stays consistent once swapped.

**Checkbox**
- Added variable to change `border-width`. Also, removed our `border-radius` as this was incorrect according to @aagonzales 

**Content Switcher**
- Added variable to allow a user to remove left/right border, as well as set the border-radius on the end buttons. 

**Data Table**
- Added variable that allows a user to set the `text-transform` property on a table header

**Modal**
- Added variable that allows a user to set the `border-top` property

**Radio Button**
- Added variable to change `border-width`.

### To Test:
Add these variables to `styles.scss` and see the differences. 

```scss
///// Watson
// Color Variables
$brand-01: #047cc0;
$brand-02: #175d8d;
$brand-03: #95c4f3;
$inverse-01: #ffffff;
$ui-01: #f6f6f6;
$ui-02: #ffffff;
$ui-03: #eaeaea;
$ui-04: #eaeaea;
$ui-05: #777677;
$text-01: #272727;
$text-02: #595859;
$text-03: #777677;
$field-01: #eaeaea;
$support-01: #e62325;
$support-02: #34bc6e;
$support-03: #fed500;
$support-04: #5c1f1b;
$nav-01: #1b2834;
$nav-02: #1c496d;

// Button
$button-font-weight: 400;
$button-font-size: 1rem;
$button-border-radius: 1rem;
$button-height: 32px;
$button-padding: 0 2rem;
$button-padding-sm: 0 1rem;
$button-border-width: 1px;

// Accordion (Reverse)
$accordion-flex-direction: row-reverse;
$accordion-justify-content: space-between;
$accordion-arrow-margin: 0 .25rem 0 0;
$accordion-title-margin: 0 0 0 0;
$accordion-content-padding: 0 1.75rem 0 0;

// Checkbox
$checkbox-border-width: 1px;

// Content Switcher
$content-switcher-border-radius: 1.5rem;
$content-switcher-option-border: none;

// Data Table
$data-table-heading-transform: none;

// Modal
$modal-border-top: none;

// Radio Button
$radio-border-width: 2px !default;
```

2017-06-13 16:13 UTC, hellobrian commented on src/components/checkbox/_checkbox.scss
> +    border: $checkbox-border-width solid $ui-05;
1px border-width:
![image](https://user-images.githubusercontent.com/4185382/27092441-f9b8c17a-5028-11e7-9c22-b8ea64f9d08b.png)

2px border-width:
![image](https://user-images.githubusercontent.com/4185382/27092488-2d3cc0e6-5029-11e7-8f18-d11062f9454e.png)

☝️ One small thing with checkbox is that the border-width helps to center the checkmark. 
To me, checkmark looks more centered using 2px border.

2017-06-13 16:23 UTC, tw15egan commented on src/components/checkbox/_checkbox.scss
> +    border: $checkbox-border-width solid $ui-05;
Is this something we can fix by adding another variable?

2017-06-13 16:33 UTC, hellobrian commented on src/components/checkbox/_checkbox.scss
> +    border: $checkbox-border-width solid $ui-05;
One solution would be to do this:

```scss
.bx--checkbox:checked + .bx--checkbox-appearance,
.bx--checkbox:checked + .bx--checkbox-label .bx--checkbox-appearance {
  padding: $checkbox-border-width;
}
```

2017-06-13 16:53 UTC, aagonzales commented on src/components/checkbox/_checkbox.scss
> +    border: $checkbox-border-width solid $ui-05;
We can also tweak the actual checkmark if that's a better solution.

2017-06-13 18:14 UTC, hellobrian commented on src/components/checkbox/_checkbox.scss
> +    border: $checkbox-border-width solid $ui-05;
I think it works fine to use the checkmark as-is since this is more of a positioning issue. No issue with the actual checkmark as far as I can tell.

2017-06-13 18:24 UTC, tw15egan commented on src/components/checkbox/_checkbox.scss
> +    border: $checkbox-border-width solid $ui-05;
That seems like a good solution @hellobrian. I'll make the update this afternoon

2017-06-13 22:17 UTC, hellobrian requested changes
Just need those changes for checkbox and then I can approve.

2017-06-14 16:08 UTC, tw15egan commented on src/components/checkbox/_checkbox.scss
> +    border: $checkbox-border-width solid $ui-05;
@aagonzales, @hellobrian and I just switched it so the checkmark takes up all available space, rather than a hardcoded value.

2017-06-15 02:27 UTC, hellobrian approved these changes
👍 ✅

2017-06-20 14:59 UTC, marijohannessen commented
👍 ✅

2017-06-20 15:05 UTC, merged