feat(icons): deprecate and remove AI lettering icon
carbon-design-system/carbon pull request #16927
Opened 2024-07-09 14:00 UTC by conradennis

Deprecating the AI lettering icon. The icon is causing confusion among product teams. The definitive AI icon should be the Carbon for AI slug.

Let me know if I should remove the icon from the icons.yml or categories.yml files as well.

Per the request of @mjabbink original issue for reference: https://github.ibm.com/brand/ui-icons/issues/335

#### Changelog

**Removed**

- 32/AI.svg

2024-07-09 14:43 UTC, alisonjoseph requested changes
Small suggestion for the deprecation reason. The slug is in the process of being renamed to AILabel. We can't actually remove the icon as it would be a breaking change, however we can hide the icon from the icon library on the Carbon website to help reduce confusion similar to what we did for IBM Z https://github.com/carbon-design-system/carbon-website/pull/2781

2024-07-09 14:43 UTC, alisonjoseph commented on packages/icons/deprecated.yml
> +      in favor of product teams using the Carbon for AI slug
```suggestion
      Icon should not be used. Teams should use the Carbon 
      AILabel component.
```

2024-07-09 14:47 UTC, conradennis commented on packages/icons/deprecated.yml
> +      in favor of product teams using the Carbon for AI slug
Works for me, I'll update the reason in the yml file.

2024-07-09 14:52 UTC, alisonjoseph approved these changes

2024-07-22 12:01 UTC, 2nikhiltom approved these changes

2024-07-22 12:01 UTC, riddhybansal approved these changes

2024-08-09 20:06 UTC, merged