fix: added readonly state variant to passwordInput
carbon-design-system/carbon pull request #17031
Opened 2024-07-24 09:16 UTC by riddhybansal

Closes #16922 

PasswordInput does not have readonly state

#### Changelog

**New**

- Added readonly state and test cases for the same

#### Testing / Reviewing

Check if readonly state of passwordInput is working as intented.

2024-07-24 11:29 UTC, 2nikhiltom approved these changes
LGTM

2024-07-24 12:39 UTC, alisonjoseph requested changes
Looks like the show/hide icon is missing styling for readOnly, I believe it should use the $icon-disabled token, and not have any hover states/cursor change.

2024-07-24 12:39 UTC, alisonjoseph commented on packages/react/src/components/TextInput/PasswordInput.tsx
> +  readOnly: PropTypes.bool,
missing comment here
```suggestion
   /**
   * Whether the PasswordInput should be read-only
   */
  readOnly: PropTypes.bool,
```

2024-07-24 12:46 UTC, riddhybansal commented
> Looks like the show/hide icon is missing styling for readOnly, I believe it should use the $icon-disabled token, and not have any hover states/cursor change.

I thought of a same but I could  see  hover things in disabled state as well , thought its what designed. So do we need to use the $icon-disabled token, and not have any hover states/cursor changes for both disable and readOnly state

2024-07-25 12:58 UTC, riddhybansal commented
> > Looks like the show/hide icon is missing styling for readOnly, I believe it should use the $icon-disabled token, and not have any hover states/cursor change.
> 
> I thought of a same but I could see hover things in disabled state as well , thought its what designed. So do we need to use the $icon-disabled token, and not have any hover states/cursor changes for both disable and readOnly state

Fixed for both disable and readonly state

2024-07-25 13:56 UTC, alisonjoseph reviewed
I had one question about the cursor, I'm wondering if the show/hide cursor shouldn't change on hover when in readonly. @laurenmrice?

2024-08-02 08:30 UTC, Kritvi-bhatia17 reviewed
> I had one question about the cursor, I'm wondering if the show/hide cursor shouldn't change on hover when in readonly. @laurenmrice?

Hi @alisonjoseph @riddhybansal,

I checked the readonly state for Combobox and NumberInput (which have interactive elements similar to PasswordInput) and noticed that the cursor does not change on hover. 
However, @laurenmrice can confirm this for further validation.

https://github.com/user-attachments/assets/c2ca410f-bd47-4c8c-acc8-a2871d453667

---

Also, a small doubt: are we planning to add the readonly state to the FluidPasswordInput as well?

2024-08-05 10:11 UTC, laurenmrice requested changes
@Kritvi-bhatia17 @preetibansalui 

When hovering over the eye icon button in the read-only state, the cursor should be an `arrow` and now a pointer.
<img width="546" alt="Frame 1" src="https://github.com/user-attachments/assets/754c4819-48e3-435d-aea1-87efe3fdf926">

2024-08-08 13:44 UTC, Kritvi-bhatia17 commented
> Also, a small doubt: are we planning to add the readonly state to the FluidPasswordInput as well?

Hi @riddhybansal, could you please confirm this?

2024-08-14 10:19 UTC, alisonjoseph approved these changes
This LGTM. Did you want to add to the fluid version also, or create a new issue?

@Kritvi-bhatia17 do we already have issues for design to add to Figma? Looks like read-only states are missing there also. 👀

2024-08-14 12:27 UTC, riddhybansal commented
> This LGTM. Did you want to add to the fluid version also, or create a new issue?
> 
> @Kritvi-bhatia17 do we already have issues for design to add to Figma? Looks like read-only states are missing there also. 👀

I guess there are missing read only states for many fluid components we can tackle them together as a list of task maybe

2024-08-14 12:34 UTC, laurenmrice approved these changes
Yeah, lets add the fluid in at a future date in a separate PR. Looks good to me @riddhybansal ! ⭐️

2024-08-14 14:36 UTC, merged