fix(16740, 17071): DatePicker calendar close issue on clickAway
carbon-design-system/carbon pull request #17072
Opened 2024-07-31 14:07 UTC by 2nikhiltom

Closes #16740, #17071

Currently the calendar closes on click away
WIP: Focus management, flickering issue 

 

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2024-08-01 16:53 UTC, tay1orjones requested changes
The storybook interaction looks good, but I'm concerned this change as is could have some unintended effects due to how the code is modifying how `savedOnClose` is used.

2024-08-01 16:53 UTC, tay1orjones commented on packages/react/src/components/DatePicker/DatePicker.tsx
> +  const onCalendarClose = useCallback(
`savedOnClose` is already wrapping `onCalendarClose` in a useCallback. Could the new useCallback be removed?

2024-08-01 16:53 UTC, tay1orjones commented on packages/react/src/components/DatePicker/DatePicker.tsx
> +
This is the only spot `savedOnClose` is used directly, but it's also used in the dependency array of the huge useEffect this is all wrapped in.

2024-08-02 13:05 UTC, guidari commented
Hey Nikhil, looks like the overview page is not loading
![Screenshot 2024-08-02 at 10 04 27](https://github.com/user-attachments/assets/9f1f3b3c-7b04-4e1a-be84-a050e5c360da)

2024-08-02 13:19 UTC, guidari approved these changes
I pulled down locally to test and looks good!
You can also close this issue https://github.com/carbon-design-system/carbon/issues/16991, It's working fine now!
🚀

2024-08-02 14:55 UTC, emyarod approved these changes
looks good to me! I think we can update the stories to remove the console.logs now

2024-08-05 16:41 UTC, riddhybansal approved these changes
Great Work !! 🚀

2024-08-06 13:02 UTC, tay1orjones approved these changes

2024-08-06 13:18 UTC, merged