feat(PaginationNav): add `size` prop with `sm` and `md` variants
carbon-design-system/carbon pull request #17175
Opened 2024-08-15 15:39 UTC by emyarod

Closes #16539

This PR adds the `size` prop and the `md` and `sm` variants to the PaginationNav. The default size will still be `lg`

#### Changelog

**New**

- `size` prop on PaginationNav
- `md` and `sm` variants

**Changed**

- mark potential style deprecations
- realign selected page underline

#### Testing / Reviewing

view the playground story for PaginationNav and verify the `size` variants look and function as expected

confirm that the deprecation TODOs are accurate

2024-08-16 19:03 UTC, tay1orjones approved these changes
Looks great to me! 🔥

2024-08-19 05:33 UTC, riddhybansal approved these changes

2024-08-19 13:14 UTC, laurenmrice approved these changes
Looks good. Thanks Andrew!

2024-08-23 18:35 UTC, alisonjoseph approved these changes

2024-08-23 18:38 UTC, alisonjoseph requested changes
nvm

2024-08-23 18:39 UTC, alisonjoseph approved these changes

2024-08-23 18:55 UTC, merged