feat(upgrade): adds featureflag-deprecate-flags-prop codemod and deprecates flags prop
carbon-design-system/carbon pull request #17266
Opened 2024-08-25 17:29 UTC by 2nikhiltom

Closes https://github.com/carbon-design-system/carbon/issues/17243

This introduces a new codemod to Convert FeatureFlags' `flags` object prop to individual `boolean` props
and  `deprecates` the existing `flags` prop
#### Changelog

**New**

- Added a new `featureflag-deprecate-flags-prop` codemod 
- Added `test fixtures` for all existing featureflags and tests to validate 
- `flags` prop for FeatureFlag is marked as deprecated 

**Changed**

- Updated `FeatureFlags/overview.stories.mdx` to document the codemod 
- Added instructions for running the `codemod` to the flags deprecation warning message

#### Testing / Reviewing

- Ensure that the test fixtures make sense - input is what someones code should look like before running the codemod, and the output is what we expect the codemod to generate/change it to.
- Make sure the docs read well and I didn't miss anything
- I used below command to run the codemode locally to verify it works 
- `jscodeshift -t featureflag-deprecate-flags-prop.js _your_file_path_`

curious to hear how you feel about this

2024-08-26 10:44 UTC, riddhybansal commented
Hey @tay1orjones one doubt , what do you think on test fixture ? can we just make it generic for all feature flags , May be just this 

The input.js 

`<FeatureFlags 
  flags={{ 
    'enable-v12-tile-default-icons': true, 
    'enable-v12-overflowmenu': true, 
  }}> 
  <Tile /> 
</FeatureFlags>;
`


The output.js 
`<FeatureFlags 
  enableV12TileDefaultIcons 
  enableV12Overflowmenu

> 
  <Tile /> 
</FeatureFlags>;`

2024-08-27 13:47 UTC, tay1orjones reviewed
This looks great! Just a few things from our pair reviewing session today:

* Add this codemod to the available migrations via @carbon/upgrade migrate, in packages/upgrade/src/upgrades.js
* Update the codemod to remove old flags that are no longer needed, like `enable-v11-release`. Mention this in the description of the migration in packages/upgrade/src/upgrades.js
* Add some new test fixtures mixing old flags and new to validate that the right one are being removed

2024-08-27 13:47 UTC, tay1orjones commented on packages/react/src/components/FeatureFlags/index.js
> +      'been deprecated. Please run the `featureflag-deprecate-flags-prop` codemod to migrate to individual boolean props.'
Once added to the packages/upgrade/src/upgrades.js, update this to have the full command they can copy and paste to run

```
npx @carbon/upgrade migrate featureflag-deprecate-flags-prop --write
```

2024-08-27 13:47 UTC, tay1orjones commented on packages/react/src/components/FeatureFlags/index.js
> +  enableUseControlledStateWithValue = false,
I don't think this flag is actually used anywhere and can be removed. https://github.com/carbon-design-system/carbon/pull/17239#discussion_r1729308202

2024-09-04 18:38 UTC, tay1orjones requested changes
This looks so good! 🔥 just three minor things I saw

2024-09-04 18:38 UTC, tay1orjones commented on packages/upgrade/src/upgrades.js
> +  },
This should be moved up into the `migrations` array after `update-carbon-icons-react-import-to-carbon-react`

2024-09-04 18:38 UTC, tay1orjones commented on packages/react/src/components/FeatureFlags/__tests__/FeatureFlags-test.js
> -      <FeatureFlags flags={{ a: true, b: false }}>
Even though this usage is deprecated, I think we should still have a test covering its usage. `console.warn` will need spied/mocked like this test from ComboButton

https://github.com/carbon-design-system/carbon/blob/afce28df13ae3475eb32c7b65e0599eb86775458/packages/react/src/components/ComboButton/ComboButton-test.js#L191-L202

I'd just copy the old test into a new block above the new `should provide access to the feature flags for a scope` and call it `should provide access to the feature flags for a scope through deprecated flags prop` or something

2024-09-04 18:38 UTC, tay1orjones commented on packages/react/src/components/FeatureFlags/index.js
> +  enableUseControlledStateWithValue = false,
This still applies and can be removed

2024-09-05 09:22 UTC, 2nikhiltom commented on packages/react/src/components/FeatureFlags/__tests__/FeatureFlags-test.js
> -      <FeatureFlags flags={{ a: true, b: false }}>
Great catch to cover all cases 🔥

2024-09-10 13:29 UTC, tay1orjones approved these changes
There's one more spot where `enable-use-controlled-state-with-value` is used that could probably be deleted, it's not used anywhere else in the styles

https://github.com/carbon-design-system/carbon/blob/b9abee7893060affe080b215d9feba8618f9cc10/packages/styles/scss/_feature-flags.scss#L11

2024-09-21 20:37 UTC, kennylam approved these changes

2024-09-21 20:57 UTC, merged