fix: ComboBox readonly state fixed
carbon-design-system/carbon pull request #17457
Opened 2024-09-17 13:34 UTC by Gururajj77

Closes #17382 

Fixed the Combobox's Read Only state, which previously would allow the user to interact with the list box.

This modification has been done after referring the read only states of Dropdown and Multiselect.
Dropdown's readonly story for reference:
https://react.carbondesignsystem.com/?path=/story/components-dropdown--playground&args=readOnly:!true

#### Changelog

**New**

- Added read only prop check to stop the list box opening.
- Added onFocus and onClick event handlers for readOnlyEventHandlers.
- Added `event.preventDefault();` for Tab interaction for readOnly prop

#### Testing / Reviewing

- Navigate to the playground story of Combobox component
- Turn on the readOnly prop
- check the interaction and make sure it doesn't open or allows text focus, only the box focus is present.

2024-09-18 09:33 UTC, alina-jacob approved these changes
Looks good Guru! 🚀

2024-09-19 05:18 UTC, preetibansalui requested changes
Hi Gururaj, The readonly prop is working fine now. Only one thing I noticed in deploy preview is when we press Tab Key, The focus move to other elements which is fine but combobox is still in highlight state, which I believe should not be. Please check attached screen recording.

After that I am not able to remove highlight from combobox even by clicking outside as well.

https://github.com/user-attachments/assets/e460caa3-2bb0-45c4-a3a2-d4cb9fcca800

2024-09-20 12:34 UTC, kennylam commented on packages/react/src/components/ComboBox/ComboBox.tsx
> +          // },
Looks good! Can remove this now

2024-10-01 11:48 UTC, preetibansalui approved these changes
Working fine now 👍

2024-10-02 12:15 UTC, kennylam approved these changes

2024-10-02 12:35 UTC, merged