Added tests for FluiTimePicker
carbon-design-system/carbon pull request #17541
Opened 2024-09-20 19:59 UTC by guidari

Closes #17516

Added tests for FluiTimePicker

#### Testing / Reviewing

- CI should pass

2024-09-23 20:08 UTC, tay1orjones requested changes
Looks awesome! Just one small thing

2024-09-23 20:08 UTC, tay1orjones commented on packages/react/src/components/FluidTimePicker/__tests__/FluidTimePicker-test.js
> +      fireEvent.click(screen.getByRole('textbox'));
Could this use `userEvent` instead? It more realistically simulates the interaction, [see here](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-user-event.md)

2024-10-02 11:47 UTC, kennylam approved these changes
LGTM, pending Taylor's comment.

2024-10-08 17:11 UTC, tay1orjones approved these changes

2024-10-08 20:25 UTC, merged