feat: codemod to deprecate light prop
carbon-design-system/carbon pull request #17641
Opened 2024-10-03 10:46 UTC by riddhybansal

Closes #17115 

This introduces a new codemod to remove the `light` prop from components and embed it within the `<Layer>` component. 

Changelog

**New**
* Added a new `deprecate-light-prop` codemod
* Added test fixtures for components using the `light` prop and tests to validate the transformation

Testing / Reviewing
* Ensure that the test fixtures accurately represent the before and after states of the codemod transformation
* Review the codemod logic to ensure it handles all edge cases and component variations
* Test the codemod on a variety of real-world code samples to confirm its effectiveness

To run the codemod locally and verify its functionality, use the following command:

```bash
npx @carbon/upgrade migrate deprecate-light-prop --write

2024-10-09 15:07 UTC, tay1orjones requested changes
This is awesome! 🔥 

I think we'll need to revert all the changes to the component source files, and I have a couple questions/comments.

2024-10-09 15:07 UTC, tay1orjones commented on packages/react/src/components/ComboBox/ComboBox.tsx
> -          light={light}
The codemod shouldn't be ran against our own code - we need to retain the light prop in the source of components so it will continue to work until we can remove it in v12.

2024-10-09 15:07 UTC, tay1orjones commented on packages/upgrade/src/upgrades.js
> +        name: 'deprecate-light-prop',
What if we renamed this to match the action being performed? The codemod doesn't deprecate the light prop in the users code, it more-so "removes" it or "refactor"s it. Maybe `refactor-light-to-layer`?

2024-10-09 15:07 UTC, tay1orjones commented on packages/upgrade/src/upgrades.js
> +         Deprecate the light prop and wrap components with Layer
```suggestion
         Refactor 'light' prop usage to instead wrap components with Layer
```

2024-10-09 15:07 UTC, tay1orjones commented on packages/upgrade/transforms/__testfixtures__/deprecate-light-prop.output.js
> +    </Layer>
The input for this piece in the other file is

```
    <Layer>
      <Button light>Nested light button</Button>
    </Layer>
```

If they're still using `light` inside a `Layer` would we want to nest it inside another layer instead?

```suggestion
    <Layer>
      <Layer>
        <Button>Nested light button</Button>
      </Layer>
    </Layer>
```

but I might be wrong here, not sure if you already tested this. Let me know what you find.

2024-11-13 22:12 UTC, riddhybansal commented
Hey I have another PR for the same , there were issues with the conflict . Check Here :#18070

2024-11-13 22:12 UTC, closed without merging