fix: use plex as per family
carbon-design-system/carbon pull request #17683
Opened 2024-10-08 18:54 UTC by riddhybansal

Closes #11661 

Updates `@carbon/styles`  to have flexibility of using both individual `@ibm/plex-${font-style}` packages and `@ibm/plex` by using a variable `use-per-family-plex` which is false by default.

#### Changelog

**New**

- 8 new packages for each of the `@ibm/plex` families 

<img width="455" alt="Screenshot 2024-07-25 at 9 17 15 AM" src="https://github.com/user-attachments/assets/9903e7e3-a911-4052-ae7f-dc994e8c1730">

- `font-feature-settings: 'liga' 1;` added to `_reset.scss` to ensure ligatures render even with `letter-spacing` set
- `$package-name` field added to font src resolver

**Changed**

- Updated the `url` field in font src resolver to use new package name format when `use-per-family-plex` is true

**Removed**

- Split fonts do not seem to ship `.woff`, so [they have been removed](https://github.com/carbon-design-system/carbon/pull/17025/files#diff-95fa1084e7c21be991e52f92b77cc405b040c0356534cd670dc5db7708739dafR16) from the individual font formats

#### Testing / Reviewing

Ensure the fonts are loaded correctly, either using the Akamai CDN or not. Ensure the `fi` ligature renders properly.

2024-10-08 20:18 UTC, tay1orjones requested changes
This looks really good!🥳 

It would be nice if the existing documentation could be updated to reflect this change and surface the new config option. I'm specifically thinking about the .md we have in the repo that covers how to self-host plex and write your own font resolver, etc. 

Probably need some new docs as well covering stuff like:


* What happens if both `$use-akamai-cdn` and `$use-per-family-plex` are set to true?
* How would someone migrate from `$use-akamai-cdn`?
* How would someone migrate from basic/existing `$font-path` usage?
* What will be the default in the next major

2024-10-08 20:18 UTC, tay1orjones commented on packages/styles/scss/_config.scss
> +/// codebase
```suggestion
/// Specify if the new per-family plex packages (e.g. @ibm/plex-sans) should be used
```

2024-10-08 20:19 UTC, tay1orjones commented
If you'd like to put the documentation work in a different issue/PR, I'd be fine approving and merging this 👍

2024-10-08 21:47 UTC, ariellalgilmore approved these changes

2024-11-05 21:03 UTC, tay1orjones requested changes
A couple things I saw - I'll work on a small refactor and push the changes to this PR

2024-11-05 21:03 UTC, tay1orjones commented on docs/guides/ibm-plex.md
> +  containing all fonts
```suggestion
- [`@ibm/plex`](https://www.npmjs.com/package/@ibm/plex): The legacy package
  containing all fonts. This package is no longer updated and uses an outdated version of plex.
```

2024-11-05 21:03 UTC, tay1orjones commented on docs/guides/ibm-plex.md
> +```
This isn't necessary because the per-family packages are listed as hard dependencies in `@carbon/styles`
```suggestion
```

2024-11-05 21:03 UTC, tay1orjones commented on docs/guides/ibm-plex.md
> +```
Same thing here, this isn't necessary. To move off akamai they just need to remove `$use-akamai-cdn` and add `$use-per-family-plex: true;`

2024-11-05 21:03 UTC, tay1orjones commented on docs/guides/ibm-plex.md
> +  - Migration will not be required but recommended
```suggestion
```

2024-11-14 21:23 UTC, tay1orjones commented
I pushed an update here, let me know what you think!

2024-11-15 06:30 UTC, riddhybansal commented
> I pushed an update here, let me know what you think!

Oh I see what you have done here !! These details will be helpful.

2024-11-15 14:14 UTC, tay1orjones approved these changes

2024-11-15 14:34 UTC, merged