fix(Dropdown): remove extra space at the end
carbon-design-system/carbon pull request #17751
Opened 2024-10-15 16:33 UTC by tekno0ryder

Closes #17750

#### Changelog

**Changed**

- Changed from `grid` to `flex` so that it only add `gap` if there is more than 1 child element to the wrapper.
  - are there any drawbacks to this change?

**Removed**

- Removed `.#{$prefix}--form-requirement` it seems not used since there is no reference from `Dropdown.tsx`

#### Testing / Reviewing

No other inline elements:
<img width="350" alt="Screenshot 2024-10-15 at 7 29 47 PM" src="https://github.com/user-attachments/assets/ff4b3518-3645-4587-909c-f8d26112119e">

When there are other inline elements:
<img width="303" alt="Screenshot 2024-10-15 at 7 07 10 PM" src="https://github.com/user-attachments/assets/cf127ca8-1f1a-4eb7-ab1b-265818913811">

2024-10-15 16:35 UTC, tekno0ryder commented
I have read the DCO document and I hereby sign the DCO.

2024-10-23 15:37 UTC, alisonjoseph requested changes
This breaks the error and warning states for the component. You can go to the playground story and set inline to true. Form requirement classes are used to display the error and warning messages, so those shouldn't be removed. 

![Screenshot 2024-10-23 at 10 36 23 AM](https://github.com/user-attachments/assets/b65955c1-7c6b-4285-8966-9653d59d2fd4)

2024-10-24 19:54 UTC, tekno0ryder commented
@alisonjoseph Thanks for the review, have another I look I found relying on grid system to add more rows when needed works in all cases.

<img width="351" alt="Screenshot 2024-10-24 at 10 42 12 PM" src="https://github.com/user-attachments/assets/8ac46e5f-b3c5-45d6-b1f2-041bd31f9cf9">

<img width="257" alt="Screenshot 2024-10-24 at 10 41 50 PM" src="https://github.com/user-attachments/assets/09935f9b-cc24-4110-a186-d77d1d563d25">

<img width="331" alt="Screenshot 2024-10-24 at 10 23 30 PM" src="https://github.com/user-attachments/assets/e4401821-3cf3-4e78-aaa5-e3d0abdcea99">

2024-10-24 20:29 UTC, alisonjoseph reviewed
LGTM! Thanks

2024-10-24 20:30 UTC, alisonjoseph approved these changes

2024-10-24 20:47 UTC, ariellalgilmore approved these changes

2024-10-24 21:07 UTC, merged