docs: updated multiselect docs with select all feature details and usage
carbon-design-system/carbon pull request #17758
Opened 2024-10-16 06:29 UTC by Gururajj77

Closes #17689 

Added documentation about select all overview and usage  in the  Multiselect's storybook over page

#### Changelog

**New**

- select all feature documentation

#### Testing / Reviewing

go to deploy preview, check the multiselect component overview page, scroll down and see the select all documentation in the page

2024-10-16 13:18 UTC, kennylam approved these changes

2024-10-16 13:18 UTC, kennylam commented on packages/react/src/components/MultiSelect/MultiSelect.mdx
> +- isSelectAll: Set to true
```suggestion
To implement the "Select All" feature in your MultiSelect component,
add a new option to your options array with these properties:

- `id`: A unique identifier (e.g., 'select-all')
- `text`: The label for the "Select All" option
- `isSelectAll`: Set to true
```

Looks good! Just a small suggestion to clean up the instructions.

2024-10-16 15:16 UTC, alisonjoseph requested changes
I would change the wording a little, also might be nice to add to the nav at the top of the storybook docs also, could easily be missed otherwise at the bottom of the page.

2024-10-16 15:16 UTC, alisonjoseph commented on packages/react/src/components/MultiSelect/MultiSelect.mdx
> +## New "Select All" Feature
```suggestion
### Select all
```

2024-10-16 15:16 UTC, alisonjoseph commented on packages/react/src/components/MultiSelect/MultiSelect.mdx
> +The MultiSelect component now includes a "Select All" feature, allowing users to
```suggestion
The MultiSelect component includes a "Select All" feature, allowing users to
```

2024-10-23 15:25 UTC, alisonjoseph approved these changes

2024-10-23 15:45 UTC, merged