test: file uploader drop container
carbon-design-system/carbon pull request #17792
Opened 2024-10-18 06:15 UTC by soumyaraju

Closes #

#17484

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2024-10-21 12:58 UTC, alisonjoseph requested changes
Do you mind filling out the body of the PR?

I'm only seeing around 60% coverage, we're looking for ideally 100%, but minimum 80%.

2024-10-24 10:24 UTC, soumyaraju commented
@alisonjoseph increased coverage upto 80%, can you re check now?

2024-10-24 12:09 UTC, alisonjoseph approved these changes

2024-10-25 06:41 UTC, soumyaraju commented
@ariellalgilmore could you help me approve this PR and merge the changes. TIA

2024-10-25 15:23 UTC, ariellalgilmore approved these changes

2024-10-25 15:44 UTC, merged