feat:  callout implementation
carbon-design-system/carbon pull request #17815
Opened 2024-10-21 09:38 UTC by Gururajj77

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2024-10-23 15:21 UTC, alisonjoseph commented
@Gururajj77 do you want to add a couple tests for this functionality?

2024-10-29 12:43 UTC, guidari approved these changes
LGTM! Thanks for testing that!

2024-11-05 17:46 UTC, guidari approved these changes
LGTM! 🚀

2024-11-05 18:14 UTC, alisonjoseph requested changes
Couple things to make this a little clearer.

- Can you clarify in the PR description what changed, I believe we talked about it no longer redirecting to the new prop, but just having the deprecation warning.
- Update the playground story so the `kind` prop displays `info` and `warning`.
- Update the Overview Component API documentation, so correctly reflects the `kind` prop options.

2024-11-05 18:30 UTC, alisonjoseph commented on packages/react/src/components/Notification/Notification.tsx
> +    ['success', 'info', 'warning', 'error'],
Should these just be info and warning?

2024-11-06 17:46 UTC, alisonjoseph commented
@Gururajj77 its still showing error as the default kind

2024-11-06 17:47 UTC, Gururajj77 commented
> @Gururajj77 its still showing error as the default kind

Ill fix it

2024-11-06 17:51 UTC, alisonjoseph commented
> to deprecate the values success and warning in prop types
I think the deprecated props should be `error` and `success` based on design spec/docs

2024-11-07 15:19 UTC, alisonjoseph commented
@Gururajj77 its still showing error state in storybook

<img width="1121" alt="Screenshot 2024-11-07 at 9 18 24 AM" src="https://github.com/user-attachments/assets/f1e2f675-6e5f-4538-917b-b6711ebd3141">


<img width="1121" alt="Screenshot 2024-11-07 at 9 18 36 AM" src="https://github.com/user-attachments/assets/a3c7b5e2-5058-4950-b426-625087aa53e2">

2024-11-07 18:26 UTC, alisonjoseph approved these changes

2024-11-07 21:19 UTC, merged