test(SideNav): #17491 increased unit test coverage
carbon-design-system/carbon pull request #17869
Opened 2024-10-24 12:12 UTC by ashna000

**Closes** https://github.com/carbon-design-system/carbon/issues/17491

This PR adds unit tests for the SideNav component to ensure its proper rendering and functionality. These tests ensure that this component renders with the appropriate class names, accommodates custom class names, and correctly applies additional props.

**Changelog**
**Changed**

- Added Unit test file for SideNav.

**Testing / Reviewing**

- Run the test suite to ensure that all new tests pass.
- Review the tests for clarity and coverage.

**Additional Notes**
Please let me know if any further modifications are needed or if you have any questions regarding the changes.

2024-10-25 03:50 UTC, ashna000 commented
@kennylam , @guidari Please review this PR

2024-10-25 13:50 UTC, guidari approved these changes
LGTM! 🚀
I see that there are couple line that weren't tested, but I guess those lines are not possible to be tested, right?
https://app.codecov.io/gh/carbon-design-system/carbon/pull/17869/blob/packages/react/src/components/UIShell/SideNav.tsx

2024-10-30 12:28 UTC, ashna000 commented
@kennylam Please review this PR

2024-11-01 11:43 UTC, ashna000 commented
@alisonjoseph Please review this PR

2024-11-05 18:04 UTC, guidari requested changes
Hey @ashna000 
Looks like the Files changetestd is missing the test file for some reason. Maybe got lost in a commit.

2024-11-08 13:55 UTC, ashna000 commented
> Hey @ashna000 Looks like the Files changetestd is missing the test file for some reason. Maybe got lost in a commit.

@guidari @kennylam  It seems while updating the branch the test changes got missed. I have updated the tests. Please review.

2024-11-08 19:22 UTC, guidari commented
Hey @ashna000 Do you think you could test the `onMouseLeave` as well?

Example in carbon: https://github.com/carbon-design-system/carbon/blob/1232b5ecad9ab650d773ff028c03ffbc9654ecd3/packages/react/src/components/Menu/Menu-test.js#L151-L156
Example in Stack Overflow: https://stackoverflow.com/questions/75952818/how-to-write-jest-test-case-for-moveover-and-mouseleave-for-functional-component#:~:text=simulate(%27-,mouseleave,-%27)%3B%0A%20%20%20%20expect

![Screenshot 2024-11-08 at 16 19 15](https://github.com/user-attachments/assets/e7cf91b2-aeca-4f50-a0e6-d95203b5ee28)

2024-12-04 21:43 UTC, ariellalgilmore reviewed
Adding additional test cases like @guidari suggested

2024-12-04 21:43 UTC, ariellalgilmore commented on packages/react/src/components/UIShell/__tests__/SideNav-test.js
> +    render(<SideNav aria-label="test" expanded onToggle={onToggle} />);
```suggestion
    render(
      <SideNav
        aria-label="test"
        expanded
        onToggle={onToggle}
        href="#main-content"
      />
    );
```

2024-12-04 21:43 UTC, ariellalgilmore commented on packages/react/src/components/UIShell/__tests__/SideNav-test.js
> +  it('should not call handleToggle if isRail is false', () => {
```suggestion
  it('should handleToggle if isRail is true', () => {
    const onToggleMock = jest.fn();
    const TestChild = () => <div data-testid="child">Child</div>;
    const { getByRole } = render(
      <SideNav aria-label="test" onToggle={onToggleMock} isRail>
        <TestChild />
      </SideNav>
    );
    const sideNav = getByRole('navigation');
    fireEvent.focus(sideNav);
    expect(onToggleMock).toHaveBeenCalled();
    fireEvent.mouseLeave(sideNav);
    expect(onToggleMock).toHaveBeenCalledWith(false, false);
    fireEvent.mouseEnter(sideNav);
    expect(onToggleMock).toHaveBeenCalledWith(true, true);
  });
  
  it('should not call handleToggle if isRail is false', () => {
```

2024-12-04 21:43 UTC, ariellalgilmore commented on packages/react/src/components/UIShell/__tests__/SideNav-test.js
> +  });
```suggestion
  });
  
  it('should focus SideNav after tabbing from headerMenuButton', () => {
    render(
      <>
        <button className="cds--header__menu-toggle"></button>
        <SideNav
          aria-label="test"
          expanded
          isFixedNav={false}
          defaultExpanded
        />
      </>
    );
    const mockHeaderMenuButton = screen.getByRole('button');
    const sideNav = screen.getByRole('navigation');

    mockHeaderMenuButton.focus();
    fireEvent.keyDown(window, { key: 'Tab' });
    expect(document.activeElement).toBe(sideNav);
  });
```

2024-12-05 12:24 UTC, guidari approved these changes

2024-12-05 12:25 UTC, guidari commented
Thanks for adding that @ariellalgilmore  🚀

2024-12-06 16:34 UTC, 2nikhiltom approved these changes

2024-12-06 17:08 UTC, merged