feat(DataTable): add double toolbar prop
carbon-design-system/carbon pull request #17868
Opened 2024-10-24 09:23 UTC by pilarfernandezz

Closes #17844

This PR allows both Batch Actions and Actions toolbars to be displayed simultaneously.
Right now the Batch Actions toolbar overrides the Actions toolbar when there is some row selected. With that, the search bar and actions buttons can not be changed/clicked.

<img width="1591" alt="image" src="https://github.com/user-attachments/assets/fa7c0869-1f51-4cdf-9c7e-530d0d4025bc">

#### Changelog

**New**

- Added ```useDoubleToolbar``` property to Table and TableToolbar.  

**Changed**

- The default value for the prop is ``` false```, maintaining the current behavior. 
- If the prop is ```true``` the Batch Actions toolbar will be displayed bellow the Actions toolbar.

#### Testing / Reviewing

Change the prop to true and select any row in the DataTable. The blue Batch Actions toolbar should be displayed bellow the Actions toolbar. Should be possible to click in the Actions buttons and edit the search bar input.
<img width="1917" alt="image" src="https://github.com/user-attachments/assets/8a701a5d-dfcc-4669-b09e-cb7a33b2d737">

2024-10-24 11:12 UTC, pilarfernandezz commented
I have read the DCO document and I hereby sign the DCO.

2024-10-24 11:12 UTC, pilarfernandezz commented
recheck

2024-10-28 14:31 UTC, tay1orjones commented
Before we can review this we need a finalized spec from design, https://github.com/carbon-design-system/carbon/issues/17844#issuecomment-2441750479

2024-10-28 14:32 UTC, tay1orjones requested changes
Before we can review this we need a finalized spec from design, https://github.com/carbon-design-system/carbon/issues/17844#issuecomment-2441750479

2025-02-11 15:28 UTC, closed without merging