fix(dropdown): integrate component audit feedback
carbon-design-system/carbon pull request #1793
Opened 2019-02-12 21:15 UTC by emyarod

References #1749

Closes #1792

This PR aims to align the experimental dropdown component with the latest component audit feedback.

#### Changelog

**Changed**

- spacing and color based on component audit feedback
- inline dropdown is now actually inline
- decouple invalid icon styles from data attribute

2019-02-12 23:38 UTC, asudoh reviewed
LGTM basically, just one thing - I believe we are using `rem()` function with pixel values, though there are some exceptions. I see many of dropdown code is not in such exception. Thanks!

2019-02-12 23:38 UTC, asudoh commented on src/components/dropdown/_dropdown.scss
> +    padding-left: 1rem;
```suggestion
    padding-left: rem(16px);
```

2019-02-12 23:38 UTC, asudoh commented on src/components/dropdown/_dropdown.scss
> +    margin: 0 1rem;
```suggestion
    margin: 0 rem(16px);
```

2019-02-12 23:38 UTC, asudoh commented on src/components/dropdown/_dropdown.scss
> +      padding: rem(11px) 1rem;
```suggestion
      padding: rem(11px) rem(16px);
```

2019-02-12 23:38 UTC, asudoh commented on src/components/dropdown/_dropdown.scss
> +    margin-right: 1.25rem;
```suggestion
    margin-right: rem(20px);
```

2019-02-14 17:54 UTC, tw15egan commented
Not sure what's causing it, but I'm getting this error when checking out this PR and trying to switch to experimental styles:

![screen shot 2019-02-14 at 11 52 16 am](https://user-images.githubusercontent.com/11928039/52806663-31595b00-304f-11e9-9f90-050905699a31.png)

2019-02-14 18:04 UTC, emyarod commented
thanks @tw15egan should be fixed now

2019-02-14 19:35 UTC, tw15egan approved these changes
Looks good now!

2019-02-14 19:45 UTC, jnm2377 requested changes
I'm seeing this weird bug on hover. Both locally and in netlify. 
The lines disappear if you're hovering anywhere on the dropdown.

![dropdown](https://user-images.githubusercontent.com/32556167/52813084-97011380-305e-11e9-9bbe-0028bcbde9bc.gif)

2019-02-14 21:21 UTC, emyarod commented
that was my interpretation of the component audit feedback

> * Rulers need to not show on hover

cc @IBM/carbon-designers for clarification

2019-02-14 21:27 UTC, tw15egan commented
I take it as the currently selected item loses the divider on hover, like how it currently is:

https://next.carbondesignsystem.com/components/dropdown/code

2019-02-14 21:40 UTC, emyarod commented
isn't that due to the similarities between the border and hover colors? unless I am misunderstanding

2019-02-14 22:16 UTC, tw15egan commented
I feel like hiding all of the dividers when hovering over the entire dropdown is a pretty jarring effect.

I think they are referring to the 1 px divider that is still being shown like here: 
<img width="643" alt="screen shot 2019-02-14 at 4 15 14 pm" src="https://user-images.githubusercontent.com/11928039/52821222-ce2def80-3073-11e9-99c3-3a2bdd23cb8a.png">

2019-02-14 22:23 UTC, emyarod commented
I guess that's why I put a question mark [here](https://github.com/IBM/carbon-components/pull/1793/commits/9c8fa0708cbc192f067f509229b2ebc7565faf1b) 😆 

changed it to hide only the hovered element's border

2019-02-14 22:25 UTC, tw15egan commented
Looks great, thanks!

2019-02-14 23:03 UTC, asudoh commented
@jnm2377 Does @emyarod's latest code look good to you...? Thanks!

2019-02-15 16:35 UTC, jnm2377 approved these changes
Looks great! 🎉

2019-02-15 17:05 UTC, merged