fix: definition tooltip breaks with large text
carbon-design-system/carbon pull request #17964
Opened 2024-11-05 05:37 UTC by preetibansalui

Closes #17848 

Definition Tooltip breaks with large text

#### Changelog

1. Update default `align` value to `bottom` instead of `bottom-start`
2. Added autoAlign prop

#### Testing / Reviewing

1. Go to Storybook > Definition Tooltip > Default
2. Hover on text, it should open the tooltip.

2024-11-05 06:40 UTC, 2nikhiltom approved these changes
LGTM

2024-11-05 09:24 UTC, Gururajj77 approved these changes
Looks good!

2024-11-07 13:40 UTC, laurenmrice requested changes
@preetibansalui There are just a couple of alignments that are a bit visually off (top-left, top-right, bottom-left, and bottom-right). I have created specs for them below. 

<img width="608" alt="Frame 1" src="https://github.com/user-attachments/assets/ef0eadeb-cc13-4791-88d4-d8018b35fae6">

2024-11-13 16:23 UTC, preetibansalui commented
> @preetibansalui When the `autoAlign` prop is set to True, the "bottom" alignment looks fine, but the "bottom-left" and "bottom-right" caret is visually off. I also think that if the user is choosing a "bottom-left" or "bottom-right" alignment, the tooltip container needs to be vertically flush with the definition text depending on which alignment is being used.
> 
> <img alt="Definition tooltip (auto align_ true)" width="928" src="https://private-user-images.githubusercontent.com/43969356/383995969-e2864b3f-1a42-4b4a-9636-230175087114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MTQ4OTYsIm5iZiI6MTczMTUxNDU5NiwicGF0aCI6Ii80Mzk2OTM1Ni8zODM5OTU5NjktZTI4NjRiM2YtMWE0Mi00YjRhLTk2MzYtMjMwMTc1MDg3MTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDE2MTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NDYzM2QyNGFlYjU1MGZiNzYxY2U2NDM2ZTIzZDhmM2JkOTliZTQ5ZDVhYzRhZDA3NTI3YjBjZWE1ZGFmOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FIpfbVoEuAxbJBf1jjsPgHD0HzNzU5lnUbbtTlhl39Y">
> * Also unrelated, but there seems to be some more spacing alignment bugs with some of the alignment options that is unrelated to this PR, and I can make a separate issue for that in our repo.

Hey @laurenmrice , Sorry little confusion here. 
Do you want me to add a padding from left/right in case of `bottom-left` or `bottom-right` as you shown me in the image attached?

In that case will it be similar for `top-left` or `top-right` as well?

Also, do we have to tackle it in `tooltip component` as well to make consistency?

2024-11-18 17:21 UTC, laurenmrice commented
@preetibansalui

> Do you want me to add a padding from left/right in case of bottom-left or bottom-right as you shown me in the image attached?

When the tooltip container appears, it needs to align vertically flush with the beginning (bottom-left) or end (bottom-right) of the definition tooltip text on the page. If adding padding from left/right helps resolve that then yes.

> In that case will it be similar for top-left or top-right as well?

Yes, if that is possible to do for the `top-left` and `top-right` alignments then those could be adjusted as well with the same logic but on the top instead of the bottom.

> Also, do we have to tackle it in tooltip component as well to make consistency?

Would that be a separate PR from this? I see some spacing issues in the Tooltip component, but it's mostly around where the caret is being placed on the tooltip container.

2025-01-16 14:29 UTC, guidari reviewed
Hey Preeti! 

I guess the caret is in the wrong position, right?

The design specs:
![image](https://github.com/user-attachments/assets/900d35c0-8fdc-4fc8-8c54-43ed3e1bc9c0)

Here it is the deploy preview with `bottom-right`

![Screenshot 2025-01-16 at 11 28 39](https://github.com/user-attachments/assets/8554b15c-46e7-4ca1-bdb6-ec836d5b8e5e)

2025-01-16 14:48 UTC, preetibansalui commented
> ens with the other postions

Hmm.. I think it's taking the tooltip to the position we are assigning, not sure about what logic it's applying to calculate the arrow position. Let me check how we are showing for other tooltip/popover with large target text.

2025-01-17 20:23 UTC, tay1orjones requested changes
A few small things I saw in the comments below. Does this fix the root issue of DefinitionTooltip's misplaced caret with long text _without_ having to turn on `autoAlign`?

2025-01-17 20:23 UTC, tay1orjones commented on packages/react/src/components/Popover/index.tsx
> +  arrowPadding?: number;
```suggestion
  caretPadding?: number;
```

This is minor, but the website docs exclusively refer to it as a caret and not an arrow.

2025-01-17 20:23 UTC, tay1orjones commented on packages/react/src/components/Popover/index.tsx
> +   * Will add padding value to arrow in case of bottom-left, bottom-right or top-left, top-right
I think we should avoid specifying the deprecated alignment options. Keeping it experimental for now seems prudent, too. Maybe revising to something like this:

```suggestion
   * **Experimental**: Specify padding between the caret and the popover edge. 
   * This helps avoid the caret visually separating from Popovers with rounded 
   * corners when aligned bottom-start, bottom-end, top-start, or top-end.
```

2025-01-17 20:23 UTC, tay1orjones commented on packages/react/src/components/Tooltip/DefinitionTooltip.stories.js
> +        autoAlign
Using experimental props on default stories could be troublesome because devs use these as a snippet to copy/paste. A new `with autoAlign` story could be added instead that has the ability to scroll and validate the autoAlign functionality is working correctly.

2025-01-17 20:23 UTC, tay1orjones commented on packages/react/src/components/Toggletip/index.tsx
> +  arrowPadding: PropTypes.number,
Mirror the `caretPadding` name change and updated prop/type comment from Popover to here

2025-02-10 08:57 UTC, preetibansalui commented on packages/react/src/components/Popover/index.tsx
> +  arrowPadding?: number;
Sounds good to me, changes applied as suggested.

2025-02-10 08:58 UTC, preetibansalui commented on packages/react/src/components/Tooltip/DefinitionTooltip.stories.js
> +        autoAlign
Made a separate story 'With Large Text'.

2025-02-10 08:59 UTC, preetibansalui commented on packages/react/src/components/Tooltip/DefinitionTooltip.stories.js
> +        autoAlign
Enabled the controls of this new story for testing purpose, will remove those controls before merge.

2025-02-14 20:59 UTC, tay1orjones commented
@preetibansalui just wanted to confirm this can be fixed without having to turn on `autoAlign`?

2025-02-17 14:04 UTC, preetibansalui commented
> @preetibansalui just wanted to confirm this can be fixed without having to turn on `autoAlign`?

let me take a look without autoAlign

2025-02-18 07:36 UTC, preetibansalui commented
> > @preetibansalui just wanted to confirm this can be fixed without having to turn on `autoAlign`?
> 
> let me take a look without autoAlign

Hey @tay1orjones, Looks like we can do it without autoAlign as well. I have pushed the changes. Thanks for the suggestion. Now it will work fine with/without autoAlign. In the storybook, I have not set autoAlign to true.

Will remove the controls of 'With Large Text' story before merge.

2025-02-21 17:57 UTC, tay1orjones commented on packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
> -      },
Is this a breaking change?

2025-02-21 17:57 UTC, tay1orjones commented on packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
> +      },
Is this still needed now that we have the css-based fix?

2025-02-27 14:16 UTC, tay1orjones approved these changes
LGTM! 🎉  Just need to remove the test story before merge

2025-03-03 21:10 UTC, laurenmrice approved these changes

2025-03-04 14:44 UTC, merged