feat(radio-button): add new decorator prop
carbon-design-system/carbon pull request #18029
Opened 2024-11-08 17:32 UTC by ariellalgilmore

Closes #17977 

Updates radio-button to include new decorator prop

#### Changelog

**New**

- new decorator prop, classes, and styles

**Changed**

- deprecated slug prop
- update rendering slug to render the decorator component but still set the size if it's an AILabel
- updated tests

#### Testing / Reviewing

Check radiobutton with AILabel storybook

TODO:

- [ ] remove RadioButton with tooltip before merging!

2024-11-11 10:18 UTC, riddhybansal requested changes
Hey this looks good to me but , when I go to playground and try to add decorator its default value is giving me this error. I think default value should be something that gives an idea to user how decorator works or what kind of value should be passed.

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/bcd8814e-e5a5-47b6-af4f-bf2e5c5e1f7c">

2024-11-12 10:31 UTC, riddhybansal approved these changes

2024-11-13 13:25 UTC, guidari commented
Hey @ariellalgilmore 
I noticed that when we click in the `Tooltip` the radio is being selected. Is that an expected behaivour or we should use event.stopPropagation to avoid that?

2024-11-13 15:34 UTC, ariellalgilmore commented
@guidari i was wondering the same thing haha, but this approach makes sense to me: https://github.com/carbon-design-system/carbon/pull/18040#issuecomment-2468969372

2024-11-13 18:33 UTC, guidari approved these changes

2024-11-15 18:41 UTC, alisonjoseph approved these changes

2024-11-18 17:10 UTC, merged