fix: checkbox invalid message to match figma kit
carbon-design-system/carbon pull request #18057
Opened 2024-11-13 11:53 UTC by riddhybansal

Closes #18033 

CheckboxGroup component renders the invalidText at the different position from the figma library.
With orientation="horizontal", invalidText shows at the right of the Checkboxs, and I expected it to be shown at the bottom.

#### Changelog

**Changed**

- Seperated the container of error message from the flex container of radio buttons and hence modified the classes

#### Testing / Reviewing

Go to checkbox and check if invalid message is rendered correctly at bottom

2024-11-14 13:32 UTC, guidari requested changes
Hey Riddhi, It is looking good! Just one thing.
I think we should keep the `invalid` and `readonly` message inside the `fieldset`. If you test with VO in the [current Storybook](https://react.carbondesignsystem.com/?path=/story/components-checkbox--playground&args=invalid:!true), you’ll notice that they are grouped together, which helps the screen reader user understand that the message is part of the same group label. 
We can also confirm that with Raghu if needed.

2024-11-14 13:45 UTC, riddhybansal commented
> Hey Riddhi, It is looking good! Just one thing. I think we should keep the `invalid` and `readonly` message inside the `fieldset`. If you test with VO in the [current Storybook](https://react.carbondesignsystem.com/?path=/story/components-checkbox--playground&args=invalid:!true), you’ll notice that they are grouped together, which helps the screen reader user understand that the message is part of the same group label. We can also confirm that with Raghu if needed.

Oh I see what you are saying !!

2024-11-17 11:31 UTC, riddhybansal commented
Hey @guidari Look at this found an alternative way to fix that bug . Lemme know what do you think about it ?

2024-11-18 13:39 UTC, guidari approved these changes
LGTM! 🚀

2024-11-18 13:39 UTC, guidari commented on packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx
> +      : '';
```suggestion
      : undefined;
```
LGTM! Let's just change to `undefined` to hide the empty class.

![Screenshot 2024-11-18 at 10 38 00](https://github.com/user-attachments/assets/89c28c08-5452-47fe-85a3-2784dc4629df)

2024-11-18 16:58 UTC, thyhmdo approved these changes

2024-11-18 17:21 UTC, alisonjoseph requested changes
This does technically fix the bug, however I think it would be preferable if we just update the styles vs. changing the underlying html structure. I believe you should be able to add a  inline-size (width) of 100% to the invalid or warn text when its horizontal and it will display correctly below the checkboxes.

2024-11-20 12:21 UTC, alisonjoseph approved these changes

2024-11-20 12:42 UTC, merged