feat(tag): add new decorator prop
carbon-design-system/carbon pull request #18109
Opened 2024-11-19 00:12 UTC by ariellalgilmore

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2024-11-19 21:06 UTC, alisonjoseph reviewed
Looks great! Just a couple tiny things

2024-11-19 21:06 UTC, alisonjoseph commented on packages/react/src/components/Tile/Tile.tsx
> +   * **Experimental**: Provide a `decorator` component or set the boolean to True for an AILabel icon to be rendered inside the `TextInput` component
```suggestion
   * **Experimental**: Provide a `decorator` component or set the boolean to True for an AILabel icon to be rendered inside the `ClickableTile` component
```

2024-11-19 21:06 UTC, alisonjoseph commented on packages/react/src/components/Tile/Tile.tsx
> +   * **Experimental**: Provide a `decorator` component or set the boolean to True for an AILabel icon to be rendered inside the `TextInput` component
```suggestion
   * **Experimental**: Provide a `decorator` component or set the boolean to True for an AILabel icon to be rendered inside the `ClickableTile` component
```

2024-11-19 21:06 UTC, alisonjoseph commented on packages/styles/scss/components/tile/_tile.scss
>    // To Do: Replace svg overrides with actual AI icon
```suggestion
```
I think we can remove this todo

2024-11-19 21:09 UTC, ariellalgilmore commented on packages/styles/scss/components/tile/_tile.scss
>    // To Do: Replace svg overrides with actual AI icon
lol idk how i left that

2024-11-19 21:09 UTC, alisonjoseph requested changes
I think we can update the `Tile.featureflag.stories.js` to use the decorator also.

2024-11-19 21:56 UTC, alisonjoseph approved these changes
🥳

2024-11-20 15:27 UTC, tay1orjones approved these changes

2024-11-20 18:10 UTC, merged