fix(composed-modal): don't close on mouse drag and release outside modal
carbon-design-system/carbon pull request #18188
Opened 2024-12-03 16:43 UTC by vsvsv

Closes #18187

Fixed incorrect behavior of ComposedModal closing when user clicks inside modal window, drags cursor outside and releases the mouse button in Chrome.

#### Changelog

**Changed**

- instead of checking only `event.target` node of 'onClick' event also check `event.target` of 'onMouseDown' event, and close the modal only if both are not inside the modal window node.

2024-12-03 16:44 UTC, vsvsv commented
I have read the DCO document and I hereby sign the DCO.

2024-12-09 17:56 UTC, tay1orjones requested changes
Thanks for taking a look at this. Could you add some tests to cover this functionality?

2024-12-09 17:56 UTC, tay1orjones commented on packages/react/src/components/ComposedModal/ComposedModal.tsx
> +      console.log({ target, mouseDownTarget });
```suggestion
```

2024-12-22 15:50 UTC, vsvsv commented
@tay1orjones Sure, added unit tests to cover this fix.

2025-01-02 19:46 UTC, ariellalgilmore approved these changes
LGTM!

2025-01-03 21:01 UTC, tay1orjones approved these changes

2025-01-06 17:40 UTC, merged