feat(icon-indicator): new component
carbon-design-system/carbon pull request #18191
Opened 2024-12-03 20:32 UTC by ariellalgilmore

Closes #17539

worked on with @preetibansalui and @2nikhiltom! 🎉 

New Icon indicator component

#### Changelog

**New**

- new Icon indicator component, stories, tests, readme for react and web components
- new icon indicator styles 
- new status tokens in themes packags

**Changes**
- update data-table dynamic story to include the icon-indicator component in the status column

#### Testing / Reviewing

confirm icon indicators look good in react and web component storybooks
confirm tests and coverage are passing

2024-12-16 20:01 UTC, tay1orjones requested changes
This looks awesome! Two main points to call out, plus a few addl things in comments

* The react component needs to be exported from the entrypoint `packages/react/src/index.js` and `packages/react/src/index.ts`
  * The exports should be marked unstable/experimental for now so we have space to get feedback and alter the API if necessary
  * `export { IconIndicator as unstable__IconIndicator } from './components/IconIndicator';`
* Could the story be updated to align the icons into two uniform columns?

2024-12-16 20:01 UTC, tay1orjones commented on packages/react/src/components/IconIndicator/IconIndicator.stories.js
> +  title: 'Components/StatusIndicators/IconIndicator',
This should be down in the experimental section for now
```suggestion
  title: 'Experimental/StatusIndicators/unstable__IconIndicator',
```

2024-12-16 20:01 UTC, tay1orjones commented on packages/react/src/components/IconIndicator/__tests__/IconIndicator-test.js
> +  });
This can also make sure this follows the convention to place the class on the outermost element

```suggestion
  it('should support a custom class name on the outermost element', () => {
    const { container } = render(
      <IconIndicator kind="error" label="label" className="custom-class" />
    );
    expect(container.firstChild).toHaveClass('custom-class');
  });
```

2024-12-16 20:01 UTC, tay1orjones commented on packages/react/src/components/IconIndicator/index.tsx
> +const IconIndicator = ({
It would be good for this to use forwardRef out of the gate, technically adding forwardRef after the fact could be considered a breaking change. It probably makes the most sense to put the `ref` on the `IconForKind`, what do you think?

2024-12-16 20:01 UTC, tay1orjones commented on packages/react/src/components/IconIndicator/__tests__/IconIndicator-test.js
> +});
Can add a test here for the forwardRef like what's in popover

https://github.com/carbon-design-system/carbon/blob/afce28df13ae3475eb32c7b65e0599eb86775458/packages/react/src/components/Popover/__tests__/Popover-test.js#L16-L24

2024-12-16 20:01 UTC, tay1orjones commented on packages/react/src/components/IconIndicator/index.tsx
> +  size?: number;
This can be more strict to ensure invalid sizes aren't given

```suggestion
  /**
   * Specify the size of the Icon Indicator. Defaults to 16.
   */
  size?: 16 | 20;
```

2024-12-16 20:01 UTC, tay1orjones commented on packages/react/src/components/IconIndicator/index.tsx
> +   * Specify the size of the Icon Indicator. Currently supports either 16 (default) or 20  sizes
```suggestion
   * Specify the size of the Icon Indicator. Defaults to 16.
```

2024-12-16 20:01 UTC, tay1orjones commented on e2e/components/IconIndicator/IconIndicator-test.avt.e2e.js
> +      id: 'components-statusindicators-iconindicator--default',
This will need updated when it's moved to the experimental section and includes `__unstable`

2024-12-16 20:01 UTC, tay1orjones commented on e2e/components/IconIndicator/IconIndicator-test.e2e.js
> +          id: 'components-statusindicators-iconindicator--default',
Same thing here wrt the section/name change

2024-12-16 20:01 UTC, tay1orjones commented on packages/styles/scss/components/icon-indicator/_tokens.scss
Could put an example of these in the custom-theme example if you'd like, alongside the button override.

https://github.com/carbon-design-system/carbon/blob/acead26eeb6f15ec6d39970e4af08aa23ee48cdc/examples/custom-theme/src/index.scss#L16-L19

2024-12-16 20:01 UTC, tay1orjones commented on packages/web-components/src/components/icon-indicator/icon-indicator.stories.ts
Could we mirror the `unstable__` name and stories in the experimental section here into the wc storybook?

2024-12-16 20:10 UTC, tay1orjones commented
Overall I think this is in good shape for a visual review @thyhmdo 👍

2024-12-17 17:37 UTC, ariellalgilmore commented on packages/styles/scss/components/icon-indicator/_tokens.scss
I added this to the PR, but thinking I should instead add it in a separate PR after this gets merged/released because currently the way the example works it can't find the new icon-indicator component/styles till it's in the next release

2024-12-18 18:22 UTC, ariellalgilmore commented on packages/styles/scss/components/icon-indicator/_tokens.scss
i added it to this PR, but since the styles/component hasn't been released yet it's causing the build to fail. I will remove for now and make a PR once this is in the next release.

2025-01-02 16:12 UTC, thyhmdo commented
@ariellalgilmore This looks great! There's only one thing and this is on my that I didn't check on the name update. But these two status icons' names need tobe updated:

Error --> Failed 
Information --> Informative

2025-01-02 17:44 UTC, thyhmdo approved these changes
Looks great!

2025-01-02 18:01 UTC, tay1orjones approved these changes
LGTM!

2025-01-06 15:53 UTC, annawen1 approved these changes

2025-01-06 17:39 UTC, merged