chore(search): change hover and active state colors
carbon-design-system/carbon pull request #2005
Opened 2019-03-07 15:46 UTC by aledavila

Closes #1975 

#### Changelog

**Changed**

- hover colors on active state

**Removed**

- full search hover change

2019-03-07 16:35 UTC, laurenmrice requested changes
**Changes:**

~In Chrome: When the whole search field is in focus, and you click the close icon to show the active state, the background color is correct but there shouldn't be a focus blue border around the icon as well.~ Following DAs recommendations for accessibility.

In all browsers:
- [x] There are some weird glitchy black lines popping up when the field is in focus and you hover on the close icon, if we could remove that.

2019-03-07 16:46 UTC, aledavila commented
@dakahn pinging for accessibility audit on the close button

2019-03-07 17:57 UTC, dakahn commented
On mouse down the X button should become focused. The slight color change on the background of the X button isn't strong enough contrast to convey this information alone. So the blue border is actually preferable -- though it is missing in the latest build of Firefox.

Thinking of a scenario where a user has entered a search -- then moved onto something else on the page -- then returned to the search and clicks the bar to give it focus and accidentally clicks the X button erasing their previous search. On mouse down if the button was more obvious (a blue border or heightened contrast) then they could correct their click by dragging their pointer off the button before mousing up.

2019-03-07 18:11 UTC, laurenmrice commented
okay cool, I'm fine with that for close button, thanks DA! Ale let me know when you resolve the black line glitches and we will be good to go!

2019-03-08 18:54 UTC, joshblack requested changes

2019-03-08 18:54 UTC, joshblack commented on src/components/search/_search.scss
> +    border-left: 0px;
```suggestion
    border-left: 0;
```

2019-03-08 18:54 UTC, joshblack commented on src/components/search/_search.scss
> +    border-left: 0px;
```suggestion
    border-left: 0;
```

2019-03-08 19:06 UTC, laurenmrice requested changes
The only thing I am seeing now is for the active state of the close icon, the focus is showing up which is good, but the background color beneath it should not be the hover-ui color token it should be the  'selected-ui' color token.

2019-03-08 20:06 UTC, aledavila commented on src/components/search/_search.scss
> +    border-left: 0px;
Done !

2019-03-08 20:19 UTC, dakahn approved these changes
Great work! 🐬🐬🐬

2019-03-08 23:01 UTC, dakahn approved these changes
👍🏽

2019-03-11 15:54 UTC, laurenmrice requested changes
Okay one more change, the close icon for the 48px search needs to be 20px instead of 16px.

2019-03-11 16:22 UTC, lovemecomputer approved these changes
cool good work!! i know the cross-browser stuff on this one was weirdly tricky.

2019-03-11 16:23 UTC, laurenmrice approved these changes
Everything looks good to me ! 👍

2019-03-11 16:35 UTC, joshblack approved these changes

2019-03-11 16:42 UTC, joshblack requested changes

2019-03-11 16:42 UTC, joshblack commented on src/components/search/_search.scss
> +  // .#{$prefix}--search--xl .#{$prefix}--search-close {
Could we remove the commented changes?

2019-03-11 16:48 UTC, aledavila commented
@joshblack done

2019-03-11 16:55 UTC, joshblack approved these changes

2019-03-11 17:09 UTC, merged