docs(sass): add public and private sass API annotations
carbon-design-system/carbon pull request #2044
Opened 2019-03-11 15:49 UTC by jnm2377

Closes #1856 

**Reviewing**
Let me know if there's any description or example that is incorrect.

2019-03-11 22:21 UTC, asudoh reviewed
Great work - Thanks a lot @jnm2377 for doing this! In addition to my comments on code - I see changes in `_css--body.scss` that are not related to your work. Would you be able to back them out?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_feature-flags.scss
> +/// @type Map | Bool
Any scenario where `$feature-flags` becomes a bool...?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_layer.scss
> +/// @type Map | Value
Any scenario where `$layer-shadows` becomes a non-map value...?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_layer.scss
> +/// @param {Map} $layer - a value from the $layer-shadows map
I think `$layer` is a key of `$layer-shadows`, thus a string?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_layout.scss
> +/// @param {Map} $value - mobile or xs
I think `$value` is a key of `$padding`, thus a string?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_layout.scss
> +/// @param {Map} $size - from $breakpoints map (see line 16)
I think `$size` is a key of `$breakpoints`, thus a string?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_layout.scss
> +/// @param {Map} $size - from $breakpoints map (see line 16)
I think `$size` is a key of `$breakpoints`, thus a string?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_typography.scss
> +/// @param {Map} $size - value of type size
I think `$size` is a key of `$typescale-map`, thus a string?

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_typography.scss
> +///@access public
Formatting nit:

```suggestion
/// @access public
```

2019-03-11 22:21 UTC, asudoh commented on src/globals/scss/_typography.scss
> +/// @param {Map} $size value from $font-size-map
I think `$size` is a key of `$font-size-map`, thus a string?

2019-03-13 16:36 UTC, joshblack commented on src/globals/scss/_css--body.scss
> -@mixin css-body--x {
Any reason for dropping the `x` variant here?

2019-03-20 08:12 UTC, asudoh commented
@jnm2377 Added several commits for bringing up `@mixin css--body` and fixing several SassDoc annotations. Hoping it doesn't break any of your intents, but please don't hesitate to speak up otherwise. Thanks!

2019-03-20 08:13 UTC, asudoh approved these changes
And thank you for your great work here @jnm2377!

2019-03-20 15:16 UTC, joshblack requested changes
Ignore me! Went ahead and pushed up some slight tweaks to help get this in!

2019-03-20 20:33 UTC, joshblack approved these changes

2019-03-20 23:03 UTC, asudoh commented
Need to decide if `@mixin css--body` should be public or private, and the name of the mix-in if we are making it public, but I don't want to block this PR on that. Thanks again @jnm2377 for all your work!

2019-03-20 23:03 UTC, merged