chore(content-switcher): update styles from audit
carbon-design-system/carbon pull request #2085
Opened 2019-03-13 15:30 UTC by aledavila

Closes #1956 

#### Changelog

**Changed**

- border radius
- padding
- align text left
- focus to align with border radius

2019-03-13 15:57 UTC, jnm2377 approved these changes
Looks good besides the comments I left.

2019-03-13 15:57 UTC, jnm2377 commented on src/components/content-switcher/_content-switcher.scss
> +    height: 40px;
Can you use `rem()` here?

2019-03-13 15:57 UTC, jnm2377 commented on src/components/content-switcher/_content-switcher.scss
> +    border-bottom-left-radius: 4px;
same for these

2019-03-13 15:57 UTC, jnm2377 commented on src/components/content-switcher/_content-switcher.scss
> +    border-bottom-right-radius: 4px;
and these

2019-03-13 16:13 UTC, lovemecomputer commented
@aledavila good work!! 

❓ @laurenmrice  : just want to check if we want to put any minimum or maximum widths, on either the entire ContentSwitcher wrapper, and/or on individual buttons? (possibly ellipsis overflow as if we're putting a max width)

i think it looks great as-is, but just wanted to point out some oddness that can come with edge cases:

![Screen Shot 2019-03-13 at 11 03 22 AM](https://user-images.githubusercontent.com/3846271/54295421-fc262700-4580-11e9-8de0-02ea052bde9f.png)
![Screen Shot 2019-03-13 at 11 06 06 AM](https://user-images.githubusercontent.com/3846271/54295428-ff211780-4580-11e9-8507-1406a2d68e94.png)

2019-03-13 16:15 UTC, aledavila commented
true @laurenmrice do we want to add a min or max widths on this?

2019-03-13 16:27 UTC, aledavila commented
@lovemecomputer I wonder if not putting constraints on the content switcher will give flexibility to users. Since its on them to not make it overwhelmingly long and doubt they have a sentence in the switcher.  If we don't give them widths then it allows them to set their own depending on how they want their layout to look ?

2019-03-13 17:07 UTC, lovemecomputer requested changes
@aledavila we DMed about notes after discussion with @laurenmrice, posting here for tracking:

- [x]  all ContentSwitcher buttons should be same with. 
    - for the time being, we will resolve this by setting the ContentSwitcher to be full width, and each button should be an equal proportion of the width
- [x]  ContentSwitcher button text should do the ellipsis overflow thing instead of wrapping to a next line
- [ ]  currently there is a disparity btw chrome & other browers: chrome always displays the focus outline after clicking, but other browsers on mac only display the outline when using keyboard navigation. we want to make this consistent across all browsers
    - for the time being, we will make sure the border display on safari & firefox after clicking. it's probably the easiest thing to implement, and is more consistent with other components.

other than that i think all looks good!!

2019-03-13 17:51 UTC, laurenmrice commented
Thanks Audrey for documenting ! @aledavila let me know when you are ready for another review :)

2019-03-13 21:15 UTC, aledavila commented
Note: focus isn't triggered in FF and safari but is consistent with all components. For consistency will leave as is. We can address post-v10 how we want to and if we want to address library wide.

2019-03-13 21:52 UTC, laurenmrice requested changes
**Changes:**

- [x] The small rule is showing between hover states. it needs to be hidden or overlapped by the hover.
<img width="196" alt="Screen Shot 2019-03-13 at 4 30 48 PM" src="https://user-images.githubusercontent.com/43969356/54317088-470b6300-45b0-11e9-967e-4b8e41aef47f.png">

- [x] When focusing on a section that is not currently selected. The text color should not change to text-01 it should remain text-02.
<img width="483" alt="Screen Shot 2019-03-13 at 4 33 03 PM" src="https://user-images.githubusercontent.com/43969356/54317064-3bb83780-45b0-11e9-8fa5-da9396c4e164.png">

- [x] Could we make the default widths for the sections to be 192px? instead of 265px?

- [x] If the ellipses occurs, we should include the interaction of having the tooltip to show the full text. This will be the same tooltip used for progress indicator.

2019-03-13 22:10 UTC, asudoh commented
Thanks @laurenmrice for another round of review? May I ask what absolute `v10` no-go items are in the latest list?

2019-03-14 01:50 UTC, asudoh commented
Per out discussion, tracking the remainder at #2092.

2019-03-14 01:52 UTC, asudoh approved these changes
LGTM except the one we tack in #2092 - Thanks @aledavila!

2019-03-14 02:05 UTC, merged