chore(components): update spacing tokens
carbon-design-system/carbon pull request #2093
Opened 2019-03-14 07:34 UTC by asudoh

This PR attempts to migrate away from `v9` spacing tokens by replacing the references with `v10` spacing tokens. And upgrade `carbon-elements`.

Refs #1501.

#### Changelog

**Changed**

- Updated `carbon-elements` dependency.
- Replaced `v9` spacing tokens with `v10` spacing tokens.
- Replaced IBM color variable references to catch up with latest `carbon-elements`.

#### Testing / Reviewing

Testing should make sure no component is broken.

2019-03-14 13:43 UTC, emyarod commented on src/components/dropdown/_dropdown.scss
> +    padding: rem(7px) rem(32px) rem(7px) $carbon--spacing-04; // TODO: spacing token
I think we can remove the comment here right?

2019-03-14 14:02 UTC, emyarod commented on src/globals/scss/vendor/@carbon/elements/scss/grid/12.scss
> +    lg:
I'm a bit out of the loop on the grid changes, have the `sm` and `md` breakpoints moved?

2019-03-14 14:15 UTC, emyarod approved these changes
all components look good on my end, thanks @asudoh !

2019-03-14 18:17 UTC, alisonjoseph commented on src/components/code-snippet/_code-snippet.scss
> +    height: carbon--mini-units(3.5);
Do we have a rule when to use mini-units vs when to just use height?

2019-03-14 18:19 UTC, alisonjoseph commented on src/components/search/_search.scss
> +    padding: 0 carbon--mini-units(3.5);
Should this be a spacing token because its padding?

2019-03-14 18:20 UTC, alisonjoseph commented on src/components/text-area/_text-area.scss
> +    padding-right: carbon--mini-units(3.5);
same here, should it be spacing token?

2019-03-14 18:21 UTC, alisonjoseph requested changes
Overall looks good, just had a few small questions 😄

2019-03-14 18:27 UTC, joshblack commented
We could use the aliases if we wanted to! e.g `spacing-01` instead of `carbon--spacing-01` 👍

2019-03-14 20:43 UTC, asudoh commented
@joshblack The mini-unit usage @alisonjoseph pointed out is due to there is no spacing token associated with `$spacing-2xl` (`carbon--mini-units(3.5)`). Would you think of any better migration path...? Thanks!

2019-03-14 20:51 UTC, alisonjoseph commented
Oh, didn't realize there wasn't a spacing token  🤔

2019-03-14 21:40 UTC, shixiedesign commented
This looks great! Thanks!

2019-03-14 21:41 UTC, shixiedesign approved these changes
This looks great! Thanks!

2019-03-14 21:51 UTC, asudoh commented
Thanks @joshblack for your input offline! Updated upon [the new migration map](https://github.com/IBM/carbon-elements/blob/v0.0.1-beta.1/docs/migration/10.x-layout.md#migrating).

2019-03-15 03:43 UTC, asudoh commented
Merging as @alisonjoseph's comment has been addressed. But please don't hesitate to speak up you see any concerns!

2019-03-15 03:43 UTC, merged