add inverse support tokens
carbon-design-system/carbon pull request #2784
Opened 2019-05-20 18:55 UTC by shixiedesign

Closes https://github.com/carbon-design-system/carbon/issues/2684

**New**
Adds 4 tokens: `$inverse-support-01` `$inverse-support-02` `$inverse-support-03` `$inverse-support-04`

2019-05-20 19:16 UTC, shixiedesign commented
I'm also not sure what's causing the circleCi to fail. Please help! 🤕

2019-05-20 19:55 UTC, joshblack commented on packages/themes/src/g10.js
> +  blue50
```suggestion
  blue50,
```

2019-05-20 19:56 UTC, joshblack commented on packages/themes/src/white.js
> +  green40;
```suggestion
  green40,
```

2019-05-20 19:57 UTC, joshblack requested changes
Left a couple suggestions that should help fix some of the CI troubles 😄

2019-05-20 20:23 UTC, mattrosno requested changes
Need to add tokens to `themes/metadata.yml`.

Need to run themes build to generate new Sass output.

2019-05-20 20:59 UTC, shixiedesign commented
Thanks @joshblack and @mattrosno ! Fixed both of your comments.

2019-05-20 23:44 UTC, asudoh approved these changes
LGTM 👍 - Thanks @shixiedesign!

2019-05-21 20:08 UTC, joshblack approved these changes

2019-05-22 07:50 UTC, asudoh commented
@shixiedesign Ran `yarn build` on `packages/themes` which seems to yield [some build artifacts](https://github.com/carbon-design-system/carbon/pull/2784/commits/95ee5ce02f2b3b2dec2dba67f58efc2f7db9a11b) and I guess it's what @mattrosno meant.

2019-05-22 13:51 UTC, mattrosno approved these changes

2019-05-22 13:55 UTC, mattrosno commented
@asudoh thanks for running the themes build! Everything looks consistent with our other support tokens in the themes package. LGTM.

2019-05-22 18:50 UTC, merged

2019-05-22 18:50 UTC, shixiedesign commented
Thanks Akira!

2019-05-22 22:00 UTC, joshblack commented
Just a reminder @shixiedesign that the commit needs to be formatted before we merge in, definitely no sweat but without it we lose info that gets generated in changelogs 😞 

If you want, we can definitely write this out when merging in for the appropriate change. Also totally fair if you want to do it too! 👍

2019-05-23 02:40 UTC, shixiedesign commented
@joshblack Sorry I forgot about it! I'll pay attention to commit messages of my own PRs. Thanks for making the new PR. It looks good to me and I will leave a msg there too.