feat(data-table): merge sticky header style
carbon-design-system/carbon pull request #2965
Opened 2019-06-07 09:43 UTC by asudoh

Merges @jnm2377's sticky header code.

#### Changelog

**New**

- Sticky header style (originally from @jnm2377).

**Changed**

- Fix missing overflow menu column CSS class in template.

#### Testing / Reviewing

Testing should make sure data table is not broken.

2019-06-07 09:56 UTC, asudoh commented
Sticky header UI can be seen at https://deploy-preview-2965--the-carbon-components.netlify.com/component/data-table--default.html and https://deploy-preview-2965--the-carbon-components.netlify.com/component/data-table--with-pager.html.

2019-06-07 12:32 UTC, emyarod submitted a review, later dismissed
looks good to me, we can probably remove the commented code

2019-06-07 12:32 UTC, emyarod commented on packages/components/src/components/data-table/_data-table-core.scss
> +    // max-height: rem(300px);
```suggestion

```

2019-06-07 13:05 UTC, emyarod reviewed
![Kapture 2019-06-07 at 7 58 55](https://user-images.githubusercontent.com/8265238/59105712-25452200-88fa-11e9-905e-154eb4ac3921.gif)

it looks like data table row height increases on hover now

2019-06-07 15:17 UTC, dakahn requested changes
Seeing the same bug as @emyarod 🐛

2019-06-11 08:22 UTC, asudoh commented
@emyarod @dakahn Thank you for spotting the row height! Fixed.

2019-06-11 12:53 UTC, emyarod approved these changes
looks good to me!

2019-06-11 22:07 UTC, aagonzales commented
In this deploy preview the pagination isn't aligning with the data table: 
https://deploy-preview-2965--the-carbon-components.netlify.com/component/data-table--with-pager.html

![image](https://user-images.githubusercontent.com/11670886/59310238-611a1780-8c6b-11e9-9c4f-c6350d59af2a.png)

2019-06-12 10:00 UTC, asudoh commented
Thanks you for spotting that @aagonzales! Fixed.

2019-06-12 15:57 UTC, aagonzales commented
For the batch action version, can we keep the border-bottom on the column header? So that the selected backgrounds don't blend in with the column header background?

Before scrolling:
![image](https://user-images.githubusercontent.com/11670886/59366986-d257da00-8d00-11e9-8531-d570f408eb92.png)

While scrolling (as-is):
![image](https://user-images.githubusercontent.com/11670886/59366958-c53aeb00-8d00-11e9-94e2-7d637c5652d5.png)

2019-06-13 09:20 UTC, asudoh commented
Good finding @aagonzales - Fixed.

2019-06-13 22:39 UTC, dakahn approved these changes

2019-06-17 15:19 UTC, joshblack commented
cc @aagonzales if you have a chance to re-review 👍

2019-06-17 15:56 UTC, shixiedesign reviewed
Hi @asudoh, sorry I clearly remember reviewing this with gifs but somehow I'm not seeing my comment so here's my notes: 
- animation of the action bar appears broken: 
_Current (at 10% speed)_
![Jun-17-2019 10-49-21](https://user-images.githubusercontent.com/15144993/59618333-9dc39400-90ed-11e9-9016-0b6e8ef87632.gif)
_Should be_
![56475145-f823d980-6449-11e9-8a1c-2226af00c362](https://user-images.githubusercontent.com/15144993/59618810-9c469b80-90ee-11e9-80aa-b3ff316c3f2a.gif)

2019-06-17 16:41 UTC, joshblack requested changes
Mirroring @shixiedesign's comments so the review state is displayed correctly

2019-06-18 06:16 UTC, asudoh commented
@shixiedesign Thank you for catching this - Seems that it happens in `master` (at https://the-carbon-components.netlify.com/component/data-table--select.html), so addressing it in a separate PR seems to make more sense.

2019-06-18 14:17 UTC, shixiedesign approved these changes

2019-06-18 22:05 UTC, merged