fix(file-uploader): incorporate audit feedback
carbon-design-system/carbon pull request #3016
Opened 2019-06-11 14:21 UTC by emyarod

awaiting confirmation on invalid file uploader item text color token change

---

Closes #2088

#### Changelog

**Changed**

- invalid form message is now calling `caption-01`
- success icon (`CheckmarkFilled16` to `Checkmark16`)
- success icon color (`support-02` to `interactive-01`)
- increased file uploader item right padding

2019-06-11 16:50 UTC, joshblack approved these changes

2019-06-11 18:00 UTC, lovemecomputer approved these changes

2019-06-12 13:20 UTC, asudoh commented on packages/components/tests/spec/file-uploader_spec.js
> +        selectorInput: `input[type="file"].${prefix}--file-input`,
We don't do variable prefix in test at this moment, rather tests see if default prefix is applied.

2019-06-12 13:27 UTC, emyarod commented
looking into increasing coverage for file uploader tests to bring us over the threshold again

2019-06-12 14:52 UTC, laurenmrice requested changes
Vanilla:
- [x] Change checkmark to be 16/checkmark--filled. Fill:`interactive-01` and Check: `icon-03`
![Screen Shot 2019-06-12 at 2 48 10 PM](https://user-images.githubusercontent.com/43969356/59381514-1f4ba880-8d21-11e9-8362-50f36faaebdf.png)

- [x] Change loader to have a container of 16px but the actual icon will be 14px within the container. Doing this to have the same size icon for all states.

- [x] Make the checkmark state file not closeable. 
- [x] Error state needs to have these specs to match the drag and drop file uploader (ref: #2962 )

Spec:
![Screen Shot 2019-06-12 at 2 51 10 PM](https://user-images.githubusercontent.com/43969356/59381639-8c5f3e00-8d21-11e9-9eda-12e0aa651a45.png)

- [x] When adding a file from the add button, the file shows up without a close icon. The close icon needs to appear and should be `icon-02`. 
![Screen Shot 2019-06-12 at 2 09 17 PM](https://user-images.githubusercontent.com/43969356/59379423-27551980-8d1c-11e9-90b4-7365a7ad5a36.png)

- [x] Upon adding a file we want to show the transition of the loader, to the checkmark, to the close icon like the current implementation for the drag and drop file uploader so we can be consistent.

2019-06-13 14:10 UTC, emyarod commented
will consolidate these changes with @asudoh's #2848

2019-06-19 17:04 UTC, emyarod commented
closing in favor of upcoming drag and drop file uploader PR

2019-06-19 17:04 UTC, closed without merging

2019-06-20 16:47 UTC, emyarod commented
got it, I removed `parentNode` usage in the new feature branch https://github.com/emyarod/carbon/tree/drag-and-drop-file-uploader