fix(TextArea): add ref forwarding to TextArea
carbon-design-system/carbon pull request #3295
Opened 2019-07-05 14:37 UTC by webadam1

I've added ref forwarding to the TextArea component the same way it's done in the TextInput component.

#### Changelog

**Changed**

- TextArea

#### Testing / Reviewing

In theory this change should not affect existing functionality of the TextArea component-

2019-07-05 19:12 UTC, joshblack requested changes
Would you mind adding `TextArea.displayName = 'TextArea'` right about `TextArea.propTypes`? We tend to include this change when using `forwardRef` since some teams may rely on the string identifier for the component. It's been helpful in the meantime to set `displayName` to help out during this transition period 😄

2019-07-08 13:23 UTC, emyarod commented on packages/react/src/components/TextArea/TextArea.js
> +const TextArea = React.forwardRef(function  TextArea(
not sure why prettier/the linter didn't catch this

```suggestion
const TextArea = React.forwardRef(function TextArea(
```

2019-07-09 08:21 UTC, webadam1 commented
Added displayName and removed unnecessary space :)

2019-07-09 15:38 UTC, joshblack approved these changes

2019-07-09 16:09 UTC, aledavila approved these changes

2019-07-09 16:39 UTC, dakahn approved these changes

2019-07-09 18:48 UTC, merged