fix(InlineLoading): announce loaded state on success
carbon-design-system/carbon pull request #3312
Opened 2019-07-09 14:27 UTC by emyarod

Closes #2896

This PR refactors our `<InlineLoading>` component to pass the `active` prop into the underlying `<Loading>` component in order to modify the `aria-live` attribute. This PR also refactors the storybook UX example to change the description when the mock loading state is successful

#### Testing / Reviewing

Ensure the component behaves as expected, especially on state changes

2019-07-09 15:44 UTC, emyarod commented
I think we can remove 10.4 milestone unless we can get Voiceover testing in time

2019-07-09 15:53 UTC, joshblack reviewed
Could you share what you're hoping happens between renders with `getLoading` and `active`? Having a hard time understanding how things are flowing and would really appreciate it 🙏 

Also, should we add a test for this use-case to verify that `active` is being set correctly?

2019-07-09 16:01 UTC, emyarod commented
sure, `getLoading` is a method which renders the `<Loading>` component or a check mark depending on the loading state

`active` is a prop that the `<Loading>` component takes which controls `aria-live`

both of these are carried over from the existing implementation, the difference is that we are now passing `active` into the underlying `<Loading>` component instead of spreading it into a wrapper div

2019-07-09 17:04 UTC, dakahn requested changes
_Testing on latest macOS using VoiceOver in Chrome latest_

Screen reader output for React component
![Jul-09-2019 12-00-24](https://user-images.githubusercontent.com/40970507/60908400-6609c100-a241-11e9-8951-e009f7b7b175.gif)

2019-07-09 17:08 UTC, emyarod commented
@dakahn do you mind expanding on the issue? does the suggestion by @snidersd in the original ticket need revising or is this a separate problem?

2019-07-09 17:22 UTC, dakahn commented
No, I don't think the original ticket needs revising. The suggested fix is pretty textbook i'll dig around and see if I can provide some resources for a React specific fix 👍🏽

As for the issue -- when the UX example successfully loads -- that change of state is not announced to the screen reader.

For reference here's our vanilla loader's behavior, same browser, same screen reader
![Jul-09-2019 11-59-01](https://user-images.githubusercontent.com/40970507/60909297-876bac80-a243-11e9-820b-c469c0a83f86.gif)

2019-07-09 21:14 UTC, dakahn commented
Right now when the user clicks the button they hear

"Click, submit...............submitted!"

So we're close. The success state is communicated but not the loading state.

2019-07-09 21:15 UTC, dakahn requested changes
Right now when the user clicks the button they hear

"Click, submit...............submitted!"

So we're close. The success state is communicated but not the loading state.

2019-07-11 17:20 UTC, emyarod commented
@dakahn are you expecting all three states to be read ("Submitting", "Active loading indicator", "Submitted")? I think the change between "Submitting" to "Active loading indicator" may be too quick for the reader to announce, but the dialog text will briefly show all three states

2019-07-12 19:19 UTC, dakahn approved these changes
🎉 Great work! Announces states "Submitting" and "Submitted" using VO 👍🏽

2019-07-12 19:20 UTC, dakahn commented
@emyarod I think we've got what's crucial. When they click they button they're told it's submitting and finally that it's submitted 👍🏽

2019-07-15 19:50 UTC, laurenmrice commented
The loading and success are working properly in both vanilla and react.

There is currently an issue open to fix the loading icon and checkmark icon for `inline loading` . ref: #3040. Not sure if you wanted to cover those changes in here or in a different issue?

Either way, in the dark themes, the check icon needs to be `interactive-04` to match the active part of the loading icon which is a lighter blue in the dark themes for that token.

2019-07-16 13:56 UTC, emyarod commented
@laurenmrice updated the color tokens for the loader and check mark. I can tackle #3040 separately

2019-07-16 15:23 UTC, laurenmrice reviewed
In react, is it possible to have the text change to read as 'Data loaded'. when the knob is turned on for success state? Just trying to keeps things consistent per state between vanilla and react.

2019-07-16 18:18 UTC, emyarod commented
@laurenmrice yes but if we hard code the 'Data loaded' text you wouldn't be able to control the description knob

2019-07-16 18:26 UTC, laurenmrice approved these changes
Okay cool, in that case I think this looks good with the function and color change for dark themes and we can track #3040 in another pr.

2019-07-16 19:23 UTC, joshblack approved these changes

2019-07-16 23:50 UTC, merged