fix(notification): fix explanation mark color
carbon-design-system/carbon pull request #3377
Opened 2019-07-12 06:33 UTC by asudoh

Fixes #3216.

#### Changelog

**Changed**

- Fixed explanation mark icon color in notification.

#### Testing / Reviewing

Testing should make sure our notification is not broken.

@carbon-design-system/design: I chose gray 100 to match text color in dark theme, but please let me know if we should choose literally black or pick another color. Thanks!

2019-07-12 14:06 UTC, emyarod approved these changes
looks good to me, pending design approval

2019-07-12 15:15 UTC, laurenmrice approved these changes
looks good to me !

2019-07-12 15:16 UTC, laurenmrice requested changes
Wait actually, the value needs to be Black. not Gray 100

2019-07-16 19:32 UTC, joshblack commented
@laurenmrice is there a token for this or nah?

2019-07-16 19:40 UTC, laurenmrice commented
@joshblack I don't believe there is a token for a black value. We are using pure black fills for these instead of Gray 100 to make this as accessible as possible (according to Sadek).

2019-07-16 20:56 UTC, joshblack commented
Oh sorry @laurenmrice! Didn't see the black note. Makes sense! I believe we have `black-100` or `carbon--black-100` for this 👍

2019-07-16 20:59 UTC, laurenmrice commented
ok great! thanks @joshblack

2019-07-17 06:38 UTC, asudoh commented
Thanks @laurenmrice for reviewing! Fixed.

2019-07-17 16:35 UTC, laurenmrice reviewed
Warning notification icon fill looks good now for both toast and inline notifications 👍. However I am noticing we need to have a black fill for the check and error icon as well for these light themes. Would you want to tackle that in this pr or make a separate one?

![Screen Shot 2019-07-17 at 11 33 50 AM](https://user-images.githubusercontent.com/43969356/61393672-18b3d200-a887-11e9-8e6f-b2a33ed18371.png)

2019-07-17 16:46 UTC, joshblack approved these changes

2019-07-17 16:47 UTC, joshblack submitted a review, later dismissed
`ibm-color` variables are deprecated

2019-07-17 16:47 UTC, joshblack commented on packages/components/src/components/notification/_inline-notification.scss
> +    fill: $ibm-color__black-100;
```suggestion
    fill: $carbon__black-100;
```

2019-07-17 16:47 UTC, joshblack commented on packages/components/src/components/notification/_toast-notification.scss
> +    fill: $ibm-color__black-100;
```suggestion
    fill: $carbon__black-100;
```

2019-07-17 18:26 UTC, jeanservaas commented
@asudoh @laurenmrice just talked to @joshblack and he says it makes sense to keep the requested  changes to the checkmark and the error icons in this PR too since they all pertain to notifications.

So can we make these updates before we merge this PR too:

- [ ] need black fill for error icon for accessibility

- [ ] need black fill for check mark icon for accessibility

<img width="650" alt="image" src="https://user-images.githubusercontent.com/43144260/61400503-02614280-a896-11e9-9fd1-545935e177bc.png">

2019-07-17 18:28 UTC, joshblack commented
Yeah, seems like we could tackle those along with these changes if that's okay @asudoh?

2019-07-18 02:19 UTC, asudoh commented
Let's track extra change in a separate issue. Adding requirement in PR review process will make PR review process unhealthy.

2019-07-18 17:18 UTC, jeanservaas approved these changes
LGTM will move these other icon changes to a seperate issue

2019-07-18 17:22 UTC, laurenmrice approved these changes

2019-07-18 17:23 UTC, jeanservaas commented
new issue is tracked here, we can merge this PR

https://github.com/carbon-design-system/carbon/issues/3452

2019-07-18 23:33 UTC, merged