new and updated icons july
carbon-design-system/carbon pull request #3378
Opened 2019-07-12 14:08 UTC by conradennis

16 net new icons and 1 update
metadata.yml updated to include additions

#### Changelog

**New**

- augmented-reality.svg
- calculator--check.svg
- migrate--alt.svg
- misusue--alt.svg
- network--1.svg
- network--2.svg
- network--3.svg
- network--4.svg
- undefined--filled.svg
- undefined.svg
- unkown--filled.svg
- unkown.svg
- warning--alt-inverted--filled.svg
- warning--alt-inverted.svg
- warning-square--filled.svg
- warning-square.svg

**Changed**

- types.svg

2019-07-13 15:30 UTC, joshblack approved these changes

2019-07-16 17:51 UTC, joshblack approved these changes

2019-07-17 15:26 UTC, joshblack requested changes

2019-07-17 15:26 UTC, joshblack commented on packages/icons/metadata.yml
> +          - unkown--filled
```suggestion
          - unknown--filled
```

2019-07-22 21:44 UTC, joshblack approved these changes

2019-07-22 22:49 UTC, lovemecomputer approved these changes
awesome, thanks!! 💫

2019-07-22 23:14 UTC, merged