Dropdown motion update dynamic duration
carbon-design-system/carbon pull request #366
Opened 2017-10-13 18:12 UTC by wonilsuh

## Overview

Applies System 360 motion specs to the Dropdown component. This includes both the new curves and the duration scale.

Also adds three more variables to the globals.

### Added

```
// src/globals/scss/_vars
$transition--expansion: 150ms;
$transition--fade: 100ms;
$transition--delay-unit:200ms;
```

### Changed

Both the JS and SCSS were changed.

```
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.scss
```

## Testing / Reviewing

`$ npm run test`

2017-10-13 19:12 UTC, tw15egan commented
This PR is out of date with changes from master. Can you rebase off of master and push up the changes?

2017-10-14 00:26 UTC, asudoh approved these changes
@wonilsuh Great that you came up with a much simpler version! Let’s see if this is something the team can agree on - I think this simpler version has higher bet.

In addition to my comment to the code, the separated open/closes states (CSS classes) for `.bx—dropdown-list` has to be reflected to the test cases, given that most of them tests that all necessary CSS classes are updated upon user action, etc. Thanks!

2017-10-14 00:26 UTC, asudoh commented on package.json
> +    "@ibm/motion": "^0.2.1",
Should be in `dependencies`

2017-10-14 00:26 UTC, asudoh commented on src/components/dropdown/dropdown.js
> +        // listEl.style.transitionDuration = '';
Please remove this commented-out line.

2017-10-14 00:26 UTC, asudoh commented on src/components/dropdown/dropdown.js
> +          element.focus();
Keyboard focus should be done after transition ends.

2017-10-14 00:26 UTC, asudoh commented on src/components/dropdown/dropdown.js
> +    this._toggle({ type: 'blur' });
Kind of nit-picky, but `handleBlur()` takes actual event in the first arg, and I’d rather use it for the sake of consistency. The event has `focusin` or `focus` type.

2017-10-14 00:28 UTC, asudoh requested changes
Oops I made a wrong selection - Changes are needed to get it through, sorry!

2017-10-15 21:54 UTC, asudoh requested changes
Thanks @wonilsuh for making the updates! Seems that some of changes in https://github.com/carbon-design-system/carbon-components/pull/357/files and https://github.com/carbon-design-system/carbon-components/pull/362/files are still lost, great to have you take a look at them - Thanks!

2017-10-16 12:58 UTC, wonilsuh commented
@asudoh Thanks for checking the files - can you pull again please? I do see the files on both local and on Git.

2017-10-17 01:50 UTC, wonilsuh commented
@asudoh now i understand the problems, fixing them. Thank you again!

2017-10-17 14:15 UTC, closed without merging