feat(inline-loading): introduce error state
carbon-design-system/carbon pull request #3772
Opened 2019-08-21 07:04 UTC by asudoh

This change introduces a new state (error) to the inline loading component, in addition to active loading state and finished (complete) state we have had.

Given the inline loading state is no longer binary, `success` prop in React one has been deprecated and replaced with new `status` prop, which takes `inactive`, `active`, `finished` and `error`.

Fixes #3760.

#### Changelog

**New**

- Error state in inline loading
- `state` prop to the React variant, replacing `success` prop

#### Testing / Reviewing

Testing should make sure our inline loading component is not broken.

2019-08-21 15:46 UTC, laurenmrice requested changes
The success icon need to be changed to the spec below.
![Inline loader - White theme Copy 2](https://user-images.githubusercontent.com/43969356/63447047-eb67c000-c400-11e9-8b81-dc18ee853dd6.png)

2019-08-22 06:46 UTC, asudoh commented
@laurenmrice Thank you for reviewing! Fixed the icon.

2019-08-22 13:58 UTC, emyarod approved these changes
looks good to me!

2019-08-22 13:58 UTC, emyarod commented on packages/react/src/components/InlineLoading/InlineLoading.js
> +  const loadingAnimation = !loading ? (
would this be identical?

```suggestion
  const loadingAnimation = loading && <div className={`${prefix}--inline-loading__animation`}>{loading}</div>
```

2019-08-22 16:10 UTC, laurenmrice requested changes
Can you make sure the loading icon is 16px  in both Vanilla and React? Looks larger in React, or maybe not the correct loader? 

The checkmark background color needs to be `interactive-04`. 
![Screen Shot 2019-08-22 at 11 07 35 AM](https://user-images.githubusercontent.com/43969356/63531121-72826a00-c4cd-11e9-8591-c7e1666c9f4b.png)

2019-08-23 03:42 UTC, asudoh commented
Thanks @laurenmrice for another review! The icon size may have been caused by broken Netlify build upon my earlier commit. Fixed and my apologies for this.

Wrt checkmark background, currently the background color (the checkmark) that icon cannot be changed. We are trying the issue at #3443.

2019-08-23 14:37 UTC, laurenmrice commented
@asudoh Oh sorry, the background color that I am referring to is the color that is currently blue 60 (not the checkmark).

2019-08-24 17:42 UTC, joshblack approved these changes

2019-08-26 05:25 UTC, asudoh commented
@laurenmrice I see, thank you for clarifying! Updated.

2019-08-26 17:11 UTC, laurenmrice requested changes
In Vanilla: We need the error message to say failed, not filed.

In React:
The success icon is hanging down a bit and need to be center with the type. Make sure its calling the right icon and is the same size and the error and loading one
![Screen Shot 2019-08-26 at 12 09 36 PM](https://user-images.githubusercontent.com/43969356/63708594-79c1b480-c7fa-11e9-90c1-d205a3320053.png)

2019-08-27 03:32 UTC, asudoh commented
@laurenmrice Thank you for spotting those - Fixed both.

2019-08-27 16:25 UTC, laurenmrice approved these changes
looks good 👍

2019-08-27 20:38 UTC, merged

2019-08-28 13:11 UTC, gotreasa commented
@asudoh Has the change been deployed to http://react.carbondesignsystem.com/?path=/story/inlineloading--inline-loading or is that yet to happen?

2019-08-28 14:35 UTC, laurenmrice commented
It looks like it has not updated react yet @gotreasa

2019-08-28 22:02 UTC, asudoh commented
Yeah... You can see it at https://deploy-preview-3772--carbon-components-react.netlify.com/?path=/story/inlineloading--inline-loading for the time being.