feat(TooltipDefinition): port vanilla WCAG 2.1 fixes
carbon-design-system/carbon pull request #3840
Opened 2019-08-27 14:39 UTC by emyarod

Closes #3813
Closes #3420

This PR ports the changes from #3151 to the React package and restores support for child nodes (#3420)

#### Testing / Reviewing

Ensure the definition tooltip appears and functions properly

2019-08-27 15:42 UTC, joshblack requested changes
Looks great, just one questions 👍

2019-08-27 15:42 UTC, joshblack commented on packages/react/src/components/TooltipDefinition/TooltipDefinition.js
> +  tooltipText: PropTypes.node.isRequired,
Should this be `PropTypes.node`? Would have assumed tooltips can only be a string, especially if this is wrapped in `bx--assistive-text`

2019-08-27 15:46 UTC, emyarod commented on packages/react/src/components/TooltipDefinition/TooltipDefinition.js
> +  tooltipText: PropTypes.node.isRequired,
this is reverting a breaking change that came within v10 (#3420)

2019-08-27 15:51 UTC, joshblack approved these changes

2019-08-27 16:13 UTC, elizabethsjudd commented on packages/react/src/components/TooltipDefinition/TooltipDefinition.js
> +  tooltipText: PropTypes.node.isRequired,
@emyarod is there a way to add a deprecation warning here since users should be switching from to the interactive tooltip if they want node children?

2019-08-27 21:23 UTC, dakahn approved these changes

2019-08-28 12:58 UTC, emyarod commented on packages/react/src/components/TooltipDefinition/TooltipDefinition.js
> +  tooltipText: PropTypes.node.isRequired,
@elizabethsjudd yeah I suppose we could add a prop types validator, will have to look more into that

2019-08-28 14:26 UTC, elizabethsjudd approved these changes

2019-08-30 15:38 UTC, shixiedesign approved these changes
From what I understand, this PR should not affect visuals & behaviors of this component. I verified those are consistent as before. Thank you!

2019-08-31 01:56 UTC, merged