chore(release): update package versions
carbon-design-system/carbon pull request #3863
Opened 2019-08-29 16:40 UTC by jnm2377

release `v10.6.0`

2019-08-29 17:39 UTC, joshblack requested changes

2019-08-29 17:39 UTC, joshblack commented on packages/react/package.json
>    },
Should we update `peerDependencies` here to `carbon-components; "^10.6.0"`?

2019-08-29 18:10 UTC, jnm2377 commented on packages/react/package.json
>    },
ah, yes, makes sense! Do I run a script for that or do I just do it manually? @joshblack

2019-08-29 18:12 UTC, joshblack commented on packages/react/package.json
>    },
Just manually IIRC 😞

2019-08-29 19:44 UTC, joshblack approved these changes

2019-09-04 16:27 UTC, designertyler approved these changes

2019-09-04 16:29 UTC, merged