fix(OverflowMenu): support automatic primary focus
carbon-design-system/carbon pull request #3935
Opened 2019-09-09 08:20 UTC by asudoh

This change ports the logic introduced in #3476 that auto-detects an overflow menu item to put focus on, without needing to specify `data-floating-menu-primary-focus` in the menu item.

This change introduces `selectorFocusable` setting, for finding focusable DOM elements. The formerly-used `selectorTabbable` is for finding sequential-focus targets, which was not necessary the the right list for finding the menu item to focus on.

This change also fixes an issue in `OverflowMenu-story.js` where the menu could not be opened by mouse, etc.

Refs #3372.

#### Changelog

**New**

- `selectorFocusable` to `settings.js`, for finding focusable DOM elements (rather than click-focusable elements or sequential-focusable elements).
- Code to support focusing on first focusable element when React overflow menu gets open (that logic has already been supported in vanilla by #3476).

**Changed**

- Vanilla overflow menu code to use `selectorFocusable` rather than `selectorTabbable`.
- Storybook fix to get overflow menu demo back working.

**Removed**

- Unused code in React overflow menu.

#### Testing / Reviewing

Testing should make sure overflow menu, especially React one, is not broken.

2019-09-09 13:41 UTC, emyarod reviewed
looks good to me, and functionality is restored in the React overflow menu

are we going to deprecate `primaryFocus` prop and `[data-floating-menu-primary-focus]` usage in the next version?

2019-09-09 13:41 UTC, emyarod commented on packages/components/src/globals/js/settings.js
> + *   By default selectorFocusable refereneces links, areas, inputs, buttons, selects, textareas,
```suggestion
 *   By default selectorFocusable references links, areas, inputs, buttons, selects, textareas,
```

2019-09-09 15:02 UTC, abbeyhrt approved these changes
This looks good to me! Should we remove the guidance in the OverflowMenu README that specifies to add primaryFocus to the first OverflowMenuItem since it's not needed anymore?

2019-09-09 15:58 UTC, joshblack requested changes
We could borrow some helpers from WAI ARiA examples if we want, specifically the JS in https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html ([Link](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/js/dialog.js))

They have an interesting alternative to `querySelector` that might be worthwhile:

```js
function attemptFocus(element) {
  if (!isFocusable(element)) {
    return false;
  }

  try {
    element.focus();
  } catch (e) {}
  return document.activeElement === element;
}

function isFocusable(element) {
  if (
    element.tabIndex > 0 ||
    (element.tabIndex === 0 && element.getAttribute('tabIndex') !== null)
  ) {
    return true;
  }

  if (element.disabled) {
    return false;
  }

  switch (element.nodeName) {
    case 'A':
      return !!element.href && element.rel !== 'ignore';
    case 'INPUT':
      return element.type !== 'hidden' && element.type !== 'file';
    case 'BUTTON':
    case 'SELECT':
    case 'TEXTAREA':
      return true;
    default:
      return false;
  }
}

function focusFirstDescendant(element) {
  for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    if (attemptFocus(child) || focusFirstDescendant(child)) {
      return true;
    }
  }
  return false;
}
```

Another option the React side is to expose a prop that takes in a `ref`, this seems to be the strategy that Reach UI is taking: https://ui.reach.tech/dialog#dialogoverlay-initialfocusref

2019-09-10 06:12 UTC, asudoh commented
Thanks everyone for the input. Withdrawing this PR given there seems a valid concern on edge cases. Anybody feel free to continue the work - A few notes for further implementation; There are a few spec proposals and libraries I see in this space:

https://github.com/WICG/spatial-navigation (`focusableArea()` seen in https://drafts.csswg.org/css-nav-1/explainer, etc., polyfill available)
https://github.com/awesomeeng/FocusTraversalAPI (Polyfill available)
https://allyjs.io

Some take “testing candidates” approach and the rest take “flattening tree” approach, to avoid custom recursive traversal. Another thing that we need to be careful, given I brought up those libraries, is not bringing in those in entirety, given those polyfills/libraries contain other features we don’t use.

Another good discussion happening this problem space (not directly related to this PR, though) can be found at issue# 4607 in https://github.com/whatwg/html.

Note on `data-floating-menu-primary-focus` attribute (the one that is similar to `initialFocusRef` in Reach UI); This PR does _not_ intend to kill that attribute. There are cases, especially in modal, where an application wants to focus on a specific element when modal (or floating menu) gets open, not necessarily the first focusable element.

2019-09-10 06:12 UTC, closed without merging