Fix(Modal): adds tabIndex so user can scroll with arrow key
carbon-design-system/carbon pull request #3942
Opened 2019-09-09 20:26 UTC by abbeyhrt

Closes #3261 

This PR adds `tabIndex="0"` to the modal content so that the text area can receive focus and be scrollable with arrow keys when necessary.  This seems to be an issue with webkit browsers that was supposedly fixed [here](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/Fku6784p0wI/3MyOMTk7BwAJ) but we aren't seeing that. Let me know if the aria-labelledby needs to be changed, the label already supplied to the modal seemed sufficient but I'm not sure! 

used this: https://developer.paciellogroup.com/blog/2016/02/short-note-on-improving-usability-of-scrollable-regions/ as guidance 
#### Changelog

**Changed**

- tabIndex added to modal body content

#### Testing / Reviewing

Go to the ModalWrapper -> transactional/passive modal open the modal and tab to the content, make sure it receives focus and that you can use the arrow keys to scroll

2019-09-09 21:46 UTC, asudoh reviewed
Thank you for tacking another issue in this problem space @abbeyhrt! One question - How does the focus-wrap behavior works with this change?

2019-09-09 21:49 UTC, dakahn commented
@asudoh looks like it just adds another tab stop to the focus wrap.

2019-09-09 21:49 UTC, dakahn approved these changes

2019-09-09 21:52 UTC, joshblack requested changes

2019-09-09 21:52 UTC, joshblack commented on packages/react/src/components/Modal/Modal.js
> +        <div
Should we be adding this dynamically when we know the content has overflowed?

2019-09-09 21:53 UTC, asudoh commented
@dakahn Yeah that's what I imagined. In case I wasn't clear enough; My question is more about if it'd be desirable for users.

2019-09-09 22:01 UTC, dakahn commented
@asudoh Without this functionality we're in violation of [principle 2.1.1](https://www.ibm.com/able/guidelines/ci162/keyboard.html) -- since the _as is_ is a scrollbar operable only via mouse. The scrollable content order makes sense. 

Unless you're talking about what @joshblack brought up -- where this keyboard focusability _always on_ and should probably only be there if we have scrollable content.

2019-09-09 22:03 UTC, asudoh commented
I can see your point @dakahn. Another question; Does this problem reproduce with a focusable element in the modal content?

2019-09-10 12:46 UTC, emyarod commented
I had open work for this to address #3816 but it looks like the ticket was closed as a dupe yesterday. there might be some overlap with what I have already but I opened up https://github.com/carbon-design-system/carbon/pull/3943 to check in what I currently have

2019-09-10 14:36 UTC, elizabethsjudd commented
I brought up the point of dynamically checking for the content scrolling as well when I did the vanilla version and was told not to add that.  If that decision is changed can you make an issue to update vanilla as well and assign it to me (we have code in WH that we can port over).

2019-09-10 14:54 UTC, abbeyhrt commented
@emyarod PR has a larger scope and addresses this problem in multiple places so I'm happy to go with his PR instead of this one, we can decide here or there if we want the tabIndex to be applied dynamically.

2019-09-10 17:29 UTC, dakahn commented
@elizabethsjudd Can you talk about what reason you were given to _not_ check for scrollable content?

2019-09-10 19:58 UTC, elizabethsjudd commented
@dakahn https://github.com/carbon-design-system/carbon/issues/3196#issuecomment-517453125

2019-09-10 21:49 UTC, joshblack commented
> we can decide here or there if we want the tabIndex to be applied dynamically.

It seems like we'd want to offer this in terms of the experience, otherwise we'd rely on teams having to implement this logic each time they'd want to support this use-case. Seems like something we could offer by default (although haven't explored what the full implementation should look like)

2019-09-10 23:23 UTC, joshblack commented
Side-note, did we even want to implement this? It seemed like a webkit specific bug, wasn't it @dakahn? At least going through the reported webkit bugs and the implementors seemed to agree FF was implementing to spec.

2019-09-11 15:18 UTC, abbeyhrt commented
Closing since it's covered in #3943

2019-09-11 15:18 UTC, closed without merging