adds pictos and updates categories
carbon-design-system/carbon pull request #4041
Opened 2019-09-19 17:03 UTC by chrisconnors-ibm

#### Changelog

**New**

- mexico--city--angel--of--independence.svg
- mexico--city--museo--soumaya.svg
- milan--duomo--di--milano.svg
- milan--skyscrapers.svg

**Changed**

- categories.yml
- pictogram-master.ai

2019-09-19 17:07 UTC, jnm2377 commented on packages/pictograms/categories.yml
> +    - milan--skyscrapers.svg
Is there a reason this one includes `.svg` and the other don't?

2019-09-19 17:07 UTC, jnm2377 commented
Also can we update the commit title to use proper commit syntax? Thanks!

2019-09-19 17:08 UTC, joshblack requested changes

2019-09-19 17:08 UTC, joshblack commented on packages/pictograms/categories.yml
> +    - milan--skyscrapers.svg
```suggestion
    - milan--skyscrapers
```

per @jnm2377 comments 👍

2019-09-20 16:06 UTC, jnm2377 approved these changes

2019-09-20 16:07 UTC, jnm2377 commented
hmm... I think the pictograms need to be added to testing maybe? It seems like ci is failing bc it says they're missing.

2019-09-20 16:27 UTC, joshblack approved these changes

2019-09-20 16:28 UTC, joshblack requested changes
Looks like CI is noting that they need to be defined in metadata.yml

2019-09-23 15:38 UTC, joshblack commented
Bump @chrisconnors-ibm do you have a sec to add in the metadata into `metadata.yml`?

2019-09-25 14:22 UTC, joshblack approved these changes

2019-09-25 17:41 UTC, merged