fix(TooltipDefinition): change children proptype check to allow a node
carbon-design-system/carbon pull request #4218
Opened 2019-10-04 13:49 UTC by fabienchn

I just changed the proptypes rule in the TooltipDefinition react component to allow its child to be a node and not only a string.
This is needed to prevent getting the console error:
`Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `TooltipDefinition`, expected `string`. in TooltipDefinition` 

And then obviously, a little test to make sure the changes work. I'm not sure that test is really needed, but I thought better testing too much than not enough. 
Feel free to tell me if you think I should get rid of it.

2019-10-04 14:28 UTC, joshblack commented
Hey @fabienchn! 👋 What use-case do you have for the `children` to be of type `node`?

2019-10-04 14:39 UTC, fabienchn commented
Hi @joshblack !
So my 2 common usecases are having an image or a checkbox (I'm going to add screenshots of it in the description).
The child of the TooltipDefinition is the node that you have to hover to see the tooltip message, so in the end, it could be anything.

2019-10-04 15:12 UTC, joshblack commented
Thanks @fabienchn! I think this restriction may be intentional, as the Definition Tooltip is meant for a specific moment, namely:

![image](https://user-images.githubusercontent.com/3901764/66218751-6d4d3900-e68f-11e9-9bef-112300848eb1.png)

Maybe we need a more generic tooltip component/style to help handle the use-cases you're sharing? 👀

2019-10-04 18:55 UTC, fabienchn commented
@joshblack I see your point, but wouldn't it be too much to create a new component for that knowing that the only different is this proptype ?
It would literally be a copy & paste from this component... Not ideal right ?

2019-10-04 19:02 UTC, joshblack commented
@fabienchn I only bring it up because this use-case is popping up around the place and definitely would be worth us considering 😄 

Given that this component has a narrow use-case, it would actually impact us long-term to have it take on more use-cases than what is documented on our site. Mostly because it would impact what kinds of changes we could make to the component, particularly if `children` is no longer a `string`.

2019-10-04 20:27 UTC, fabienchn commented
@joshblack 
Okay, I see your point ! Cool that I'm not the first one mentioning this haha.
So I could create a new Component for this, with the same features as the TooltipDefinition for now and it might grow in a seperate direction later on.
What do you think ?

2019-10-04 23:52 UTC, asudoh commented
CC @carbon-design-system/design to see if we should have a UX patten to cover the use case the issue author describes. I see it's a common requirement back and forth between people wanting to adhere to our style guide (no rich content) vs. people wants to put richer content in (e.g. bold text).

2019-10-07 13:24 UTC, emyarod commented
yeah I think this use case is valid and warrants a reexamination of our tooltip offerings. until then in the meantime maybe the `<TooltipIcon>` would work better here as a temporary solution since it accepts nodes instead of only strings as `children`

2019-10-07 19:47 UTC, chrisconnors-ibm commented
what specific use case does this cover that is not handled by one of the three tool tip variants here:
https://www.carbondesignsystem.com/components/tooltip/code/

2019-10-07 19:59 UTC, chrisconnors-ibm requested changes
awaiting more detail of the use cases this covers.

2019-10-07 20:28 UTC, aagonzales commented
_Adding because I had a response half typed up when Chris replied_

Yes, as @joshblack pointed out, `definition tooltip` has a [specific purpose](https://www.carbondesignsystem.com/components/tooltip/usage#definition-tooltip).

This first example looks like it should be an `icon tooltip` and maybe allowing images for icon tooltip is valid (if it's a png instead of an svg for some reason).

The second example looks like a design band-aid. I think that information should appear somewhere other than in a tooltip. I don't think we want to encourage checkboxes to have tooltips attached to them. A user should already have a clear understanding of what will happen when they click a checkbox, they shouldn't need extra help in that scenario.

2019-10-09 11:33 UTC, fabienchn commented
Hi @aagonzales ! I didn't know about the TooltipIcon component ! It's must be quite recent.
But that component actually solves the issue !
So I'm closing this PR
Thank you to everyone for you time

2019-10-09 11:33 UTC, closed without merging