fix(notification): change box-shadow to border
carbon-design-system/carbon pull request #4299
Opened 2019-10-11 08:20 UTC by asudoh

This change also makes inline notification's text color non-themeable for now (good to have your thoughts here @aagonzales given it's different from your latest spec), given the background color is non-themeable and making it themeable requires themeable component-specific token (or new global theme tokens).

This stop-gap approach may be enough for short team because IIRC low-contrast notifications is there for a backword-compatibility reason.

Refs #4282.

#### Changelog

**Changed**

- Replaced box shadow for inline notification with border.
- Made the text color of inline notification fixed.

#### Testing / Reviewing

Testing should make sure our inline notification is not broken.

2019-10-11 13:25 UTC, emyarod approved these changes
just a few notes on the pseudo elements but looks good to me, dark theme low contrast notifications are readable again with stop gap solution, and drop shadows have been replaced by borders

![image](https://user-images.githubusercontent.com/8265238/66654624-47301780-ec00-11e9-89ce-1d3771094693.png)

2019-10-11 13:25 UTC, emyarod commented on packages/components/src/components/notification/_inline-notification.scss
> +    &:before {
can use CSS3 double colon syntax for pseudo elements?

```suggestion
    &::before {
```

2019-10-11 15:38 UTC, dakahn approved these changes

2019-10-11 18:42 UTC, abbeyhrt commented
@asudoh should this address the Toast variation as well? Noticed this: 
![Screen Shot 2019-10-11 at 1 41 26 PM](https://user-images.githubusercontent.com/17281178/66676336-d8b57e80-ec2c-11e9-9cf1-674fb4f00d05.png)
Sorry if I'm totally off here or if this is being addressed elsewhere!

2019-10-11 22:45 UTC, asudoh commented
Great catch @abbeyhrt! Fixed.

2019-10-14 14:45 UTC, abbeyhrt commented
![Screen Shot 2019-10-14 at 9 43 46 AM](https://user-images.githubusercontent.com/17281178/66760168-2ddcd480-ee67-11e9-814e-124866c4225c.png)
Descriptions still aren't showing up for me but the titles are!

2019-10-15 03:50 UTC, asudoh commented
Oops another good catch @abbeyhrt! Fixed.

2019-10-15 18:31 UTC, aagonzales requested changes
Yeah our notifications kind of break our theming modal (without component level tokens). I think its ok for now if we make these non-themeable. I think its more important that they look right for use at IBM than allowing people to theme them. I know there were issues brought up around this last time we tried to update notifications and I'm not sure where the discussion ended with that. 

The Gray 10 and White low contrast notifications look good!

However, the low contrast notifications in the **gray 90 and gray 100 themes still aren't correct** according to the new spec (let me know if its not possible to achieve this in code then we'll need to evaluate what the options are). 

**As-is:**
![image](https://user-images.githubusercontent.com/11670886/66858827-f5102e80-ef3e-11e9-9e2b-a773511bcdb4.png)

**To-be:**
![image](https://user-images.githubusercontent.com/11670886/66858935-28eb5400-ef3f-11e9-97c0-75a7e6b3b2b3.png)

2019-10-15 21:17 UTC, asudoh commented
@aagonzales Thank you for the review! The problem is that we don't have a theme token that achieves the color switch as you specified. Does this make sense...?

2019-10-16 15:04 UTC, aagonzales commented
Ok so is achieving this style of dark notification not possible? Can it only be the same color as the Gray 10 and white ones?

2019-10-17 02:56 UTC, asudoh commented
@aagonzales 

> Can it only be the same color as the Gray 10 and white ones?

Yes with the status quo of underlying codebase.

> How can we resolve this?

Here are some options I can think of:

1. Implement the notion of component-level theme tokens (The direct limiting factor for implementing your specification, but expecting push-back from some devs as I'm not sure if the team is ready for that notion - CC @emyarod)
2. Create new global theme tokens
3. Implement code to detect current effective theme and switch style upon that (Expecting push-back from some devs due to its hacky/band-aid nature)

2019-10-17 17:15 UTC, aagonzales commented
Ok so I think maybe we can go ahead with adding the border style into the components because at least those will be correct in the White and Gray 10 themes. Then in a separate issue/PR we can figure out how to correctly implement the low contrast notifications in the dark themes.


----------
**Changes needed before merging:** 

- The toast notifications should not have the border but a drop shadow instead. Only the inline notifications have the border. 

![image](https://user-images.githubusercontent.com/11670886/67026003-98427e80-f0cc-11e9-8501-66afee26373a.png)


- In the Gray 100 and Gray 90 themes the "action" (inline) and "x" (inline and toast) are the wrong colors. Action should be using `$link-01` and the `x` should be the same color as the text.

![image](https://user-images.githubusercontent.com/11670886/67026137-d8096600-f0cc-11e9-96ef-3c92371835da.png)

2019-10-18 00:24 UTC, asudoh commented
Thanks for the updated spec @aagonzales! Fixed.

2019-10-18 15:58 UTC, aagonzales reviewed
✅ Inline notification is good

❌ For Toast in the gray 90 and Gray 100 themes the close icon `x` is still not visible. It should be the same color as the text (#161616).

![image](https://user-images.githubusercontent.com/11670886/67109473-38b0a580-f196-11e9-9e46-c83352b1a91e.png)

2019-10-21 03:11 UTC, asudoh commented
Oops thank you for catching that @aagonzales! Fixed.

2019-10-21 15:15 UTC, abbeyhrt approved these changes
Looks good to me!

2019-10-21 16:14 UTC, aagonzales approved these changes
Yup, looks good for now. Thanks for fixing! 
(Note: we will address the low contrast dark theme issues separately)

2019-10-22 01:01 UTC, merged