Spinner radius inline loading
carbon-design-system/carbon pull request #4382
Opened 2019-10-18 08:04 UTC by asudoh

Fixes #3040.

#### Changelog

**Changed**

- The stroke radius of the spinner of inline loading.

#### Testing / Reviewing

Testing should make sure our inline loading component is not broken.

2019-10-18 15:13 UTC, emyarod commented on packages/components/src/components/inline-loading/_inline-loading.scss
> +      r: 26.8125;
it looks like Firefox still does not properly support modifying `r` with CSS?

Firefox 69 and 71

![image](https://user-images.githubusercontent.com/8265238/67106148-ac9b7f80-f18f-11e9-8464-b06a9e4145a9.png)

Chrome

![image](https://user-images.githubusercontent.com/8265238/67106264-dd7bb480-f18f-11e9-877e-e1f880b73a40.png)

2019-10-18 17:10 UTC, laurenmrice requested changes
The 16px loader should be used in three different places:

Vanilla
- small loader under Loading. (its currently using the 20px)
- inline loading (currently seems to be getting extra padding than the success icon)
- file uploader (looks correct)

React
- small loader under Loading. (its currently using the 20px)
- inline loading (its currently using the 20px)
- file uploader (looks correct size, but it is jumping to the left. It should stay in place like the complete and edit states )
![Oct-18-2019 12-09-51](https://user-images.githubusercontent.com/43969356/67113884-36534900-f1a0-11e9-87f8-0c0b0cea5790.gif)

2019-10-21 08:48 UTC, asudoh commented
Thank you for reviewing @laurenmrice - Updated the right padding for file uploader as well as the size for small loading and inline loading. I tried to make the spinner the size the same as complete/invalid icon (to get the same padding as them), but please let me know if a larger size is desired.

2019-10-21 13:45 UTC, emyarod approved these changes
Firefox issue is resolved, looks good to me pending design approval

2019-10-21 15:46 UTC, laurenmrice requested changes
The only place where it still needs to be update is in Vanilla under File uploader in the upload states example. It still too big here. 
![Screen Shot 2019-10-21 at 10 43 07 AM](https://user-images.githubusercontent.com/43969356/67220890-30ec3d80-f3f0-11e9-9030-6d5ea3fda1bf.png)

2019-10-22 23:03 UTC, asudoh commented
Thank you for catching that @laurenmrice - Fixed.

2019-10-23 14:13 UTC, laurenmrice approved these changes
looks good, thank you !👍

2019-10-23 20:10 UTC, abbeyhrt approved these changes
Looks good to me!

2019-10-23 22:59 UTC, merged