fix(select): resolve inline select alignment issues
carbon-design-system/carbon pull request #4465
Opened 2019-10-25 16:19 UTC by emyarod

Closes #4423

This PR resolves some alignment and spacing issues in our `<select>` component. Some additional clarification is needed to reproduce some of the remaining reported issues

#### Testing / Reviewing

Ensure the Carbon Select component appears correct

2019-11-11 20:38 UTC, laurenmrice requested changes
Vanilla and React:

Inline Select (Invalid and Invalid with helper text)
On disabled invalid states the hover color and cursor change comes on. There should be no hover and it should be the error cursor change.
![Nov-11-2019 14-33-55](https://user-images.githubusercontent.com/43969356/68619290-d09d6880-0490-11ea-90ab-6310a27421ca.gif)


Vanilla and React:
All select invalid states
The icons are too close together. There should be 16px padding between the chevron and the alert icon in all selects except for the inline select. The inline select should have 8px paddings.
![Screen Shot 2019-11-11 at 2 34 32 PM](https://user-images.githubusercontent.com/43969356/68619297-d3985900-0490-11ea-9291-69d515427ce3.png)

2019-11-11 22:12 UTC, emyarod commented
I updated the spacing tokens (they were annotated and most likely the spec was changed/we were affected by the move away from glyph icons) but I'm not able to reproduce the first issue with the disabled invalid hover state

2019-11-12 16:37 UTC, abbeyhrt commented
@emyarod I'm not sure if this is something that should be addressed in this PR but I'm getting an extra focus outline on the select in Firefox for the react version 
<img width="320" alt="Screen Shot 2019-11-12 at 10 34 01 AM" src="https://user-images.githubusercontent.com/17281178/68690827-4b6d8e80-0538-11ea-938c-ba94a3c93e84.png">

2019-11-12 19:30 UTC, emyarod commented
@abbeyhrt this doesn't appear to be a regression and we can tackle it separately if we're fine with introducing FF specific rules (or updating our CSS reset)

2019-11-12 19:35 UTC, laurenmrice approved these changes
looks good 👍

2019-11-12 21:33 UTC, asudoh approved these changes
LGTM 👍 - Thanks @emyarod!

2019-11-12 21:33 UTC, merged