fix(skeleton-components): convert Breadcrumb, Fileuploader, ProgressIndicator, RadioButton, Tabs, and Tag skeletons to function declarations
carbon-design-system/carbon pull request #4484
Opened 2019-10-29 19:16 UTC by jendowns

Partially addresses #4398

I was looking at some of the skeleton components noted to have missing props in #4398, including:

- [x] `BreadcrumbSkeleton`
- [x] `FileuploaderSkeleton`
- [x] `ProgressIndicatorSkeleton`
- [x] `RadioButtonSkeleton`
- [x] `TabsSkeleton`
- [x] `TagSkeleton`

 ... but I didn't find any undocumented or missing props in those. (Unless the purpose is to add `className` props to each?)

Only `RadioButtonSkeleton` had a prop, `id`, but in that case the prop was unnecessary because it was assigned to `label` element that was untied to any `input`. (Which I propose removing)

In the process of checking these components, I took the opportunity to convert them from classes to ~functional components~ function declarations & follow patterns used in other skeleton components. This conversion may also help with auditing these components in the future.

Please let me know if you have questions or concerns about this -- thank you!

#### Changelog

**Changed**

- convert `BreadcrumbSkeleton` to functional component
- convert `FileuploaderSkeleton` to functional component
- convert `ProgressIndicatorSkeleton` to functional component
- convert `RadioButtonSkeleton` to functional component
- convert `TabsSkeleton` to functional component
- convert `TagSkeleton` to functional component

**Removed**

- removed `id` prop from `RadioButtonSkeleton` & updated the `label` to a `span` instead

2019-10-29 23:07 UTC, joshblack requested changes
One super tiny style nit, I think we're going to go with function declarations as our way to define components just based off of React using them in their examples. Would it make sense to update the components in this PR to that syntax?

2019-10-29 23:07 UTC, joshblack commented on packages/react/src/components/Breadcrumb/Breadcrumb.Skeleton.js
> +  const item = (
Since this is static content, should we move it outside of the function block scope? Trying to think through when it might be best to versus not 🤔

2019-10-29 23:07 UTC, joshblack commented on packages/react/src/components/ProgressIndicator/ProgressIndicator.Skeleton.js
> +  const currentSvg = (
Same question as above for static stuff

2019-10-30 13:33 UTC, emyarod approved these changes
looks good to me pending refactor to function declarations

2019-10-30 13:33 UTC, emyarod commented on packages/react/src/components/Tabs/Tabs.Skeleton.js
> -          </li>
not sure why this was here initially but replacing it with `tab` looks fine to me

2019-10-30 14:56 UTC, aagonzales approved these changes
Seems good to me

2019-10-30 15:10 UTC, jendowns commented
Thanks @joshblack & @emyarod! I just converted these components to function declarations and moved all static content outside the function scope.

2019-10-30 15:21 UTC, abbeyhrt approved these changes
Looks good to me! Thanks! @jendowns

2019-10-30 18:28 UTC, joshblack approved these changes

2019-10-30 22:29 UTC, asudoh approved these changes
LGTM 👍 - Thanks @jendowns!

2019-10-30 22:42 UTC, merged