fix(copy-button): fix type of feedback text
carbon-design-system/carbon pull request #4677
Opened 2019-11-14 08:58 UTC by asudoh

Fixes #4606.

#### Changelog

**Changed**

- Choice of type token for feedback text.

#### Testing / Reviewing

Testing should make sure copy button and code snippet is not broken.

2019-11-14 14:32 UTC, emyarod reviewed
copy button and inline code snippet look correct, but single line and multiline code snippet feedback text still appear to be using a different type token

![image](https://user-images.githubusercontent.com/8265238/68865811-0c1a7b80-06b9-11ea-9371-c31fca26a781.png)

![image](https://user-images.githubusercontent.com/8265238/68865837-16d51080-06b9-11ea-9d47-da9e51d9bc70.png)

2019-11-14 15:40 UTC, abbeyhrt commented
I'm seeing the same thing as @emyarod

2019-11-14 19:27 UTC, laurenmrice requested changes
Vanilla and React:

-The `code snippet single line` and the `copy button` should 4px between the border of the hover and the tip of the fin of the tooltip. Right now its too close. 
![Screen Shot 2019-11-14 at 1 22 25 PM](https://user-images.githubusercontent.com/43969356/68889409-7b589580-06e2-11ea-88f2-75c2e0e26486.png)

-Seeing the same thing as andrew and abbey about the type

2019-11-15 15:12 UTC, joshblack approved these changes

2019-11-15 15:12 UTC, joshblack reviewed
Seems great with feedback from above 😄

2019-11-18 17:07 UTC, joshblack requested changes
Any chance we could avoid the magic numbers or document them? Seems like we're setting up the placement to be very precise with the decimal pixels

2019-11-18 17:07 UTC, joshblack commented on packages/components/src/components/code-snippet/_code-snippet.scss
> +    top: rem(50.8px);
Where is this number coming from?

2019-11-18 17:07 UTC, joshblack commented on packages/components/src/components/code-snippet/_code-snippet.scss
> +    top: rem(42.8px);
Where is this number coming from?

2019-11-19 08:06 UTC, asudoh commented
Fixed the tooltip offset, and added the comment how the right offset is generated. Made a change to force serif font as our type token of choice doesn't dictate the font face and code snippet UI has monospace font.

2019-11-19 14:45 UTC, emyarod reviewed
the magic numbers in code snippet should be resolved by pending work for #4605 right?

on a side note the copy button tooltip positioning should be resolved in #4715

2019-11-19 14:45 UTC, emyarod commented on packages/components/src/components/code-snippet/_code-snippet.scss
> +    &:before {
should we use the CSS3 selector with double colon instead?

```suggestion
    &::before {
```

2019-11-19 17:50 UTC, laurenmrice approved these changes
placement of tooltip and the type looks good to me 👍

2019-11-19 22:10 UTC, joshblack approved these changes

2019-11-19 22:55 UTC, merged