fix(project): bundler not consistently creating directories in windows
carbon-design-system/carbon pull request #4797
Opened 2019-11-28 14:12 UTC by sichangi

Closes #2434 

Initially the javascript bundler only created ``es`` directories, this fix supports a more dynamic approach by passing a ``-g formart=<cjs, es or umd>`` flag to the bundler

#### Changelog

**New**

- global flag passed t the javascript bundler ``-g formart=<cjs, es or umd>`` to support dynamic folder creation

**Changed**

- optional flag to specify the javascript bundlers output
- updated build commands in the ``@carbon/type``, ``@carbon/color``, ``@carbon/icon-helper`` & ``@carbon/layout`` packages

**Removed**

- nothing

#### Testing / Reviewing

The build command in the ``@carbon/type``, ``@carbon/color``, ``@carbon/icon-helper`` & ``@carbon/layout`` packages produces the expected ``lib`` directory after compilation.

2019-11-28 14:16 UTC, sichangi commented
A point to note, This is just the first of many fixes to get the project fully functional on windows, I landed  into more unrelated issues just after fixing this one

2019-12-02 16:31 UTC, joshblack requested changes
Hey there! 👋 Thanks so much for taking the time to take this on 🙏 

One thing I noticed when testing the changes is that this removes the generation of ESM and UMD when `format=cjs` is passed in. Would be great if we kept the existing functionality with outputting the various formats while supporting the windows use case 👍

2019-12-02 18:09 UTC, sichangi commented
Hey @joshblack,
I've removed the format option with the understanding that the bundler should generate all three formats as expected.

2019-12-03 10:02 UTC, asudoh commented
Hi @sichangi thank you for your contribution! Though I'm not much familiar with the codebase, one thing I'm wondering is if you can separate Windows support with different bundle type support. Is it something you can do...? Don't hesitate to speak up if it doesn't make sense, wanted to know the reason behind it if it's the case. Thanks!

2019-12-03 10:16 UTC, sichangi commented
Hey @asudoh, 
If am getting you right, I should split the contribution for windows support & multiple bundle types support?

2019-12-03 10:24 UTC, asudoh commented
@sichangi Exactly - Thank you very much for double-checking this!

2019-12-03 10:29 UTC, sichangi commented
No problem @asudoh 👍,
Yeah, I think that's a better approach,
I guess I'll create a new issue & PR for windows support.

2019-12-03 10:32 UTC, emyarod reviewed
when comparing with my [interim work from several months ago](https://github.com/carbon-design-system/carbon/compare/master...emyarod:2434-carbon-bundler-not-properly-creating-directories-on-windows), it looks like so far we have a bit of overlap although we took different approaches

but if I'm not mistaken this PR doesn't address the full extent of the issue so we may need to remove the `Closes #2434` keyword. it looks like the build step will still exit with an error code and log errors when building several packages

can you clarify the scope of the current PR?

2019-12-03 10:45 UTC, sichangi commented
Hey @emyarod,
So in this PR, I specifically went after the javascript bundler not generating expected output directories, i.e [es, lib & umd], although there happen to be more issues, epecially related to path resolution on windows in other packages like the icon-build-helpers that I intended on addressing in another PR, and as agreed upon with @asudoh

2019-12-03 19:50 UTC, sichangi commented
I think I'll close this and rework my approach to the 2 PR's

2019-12-03 19:50 UTC, closed without merging