fix(styles): update placeholder colors
carbon-design-system/carbon pull request #4799
Opened 2019-11-29 03:37 UTC by asudoh

This change updates placeholder color from `$text-03` to `$text-05` to meet the color contrast requirement.

This change also replaces manual usage of colors in style rules with the Sass mixin for placeholder `@include placeholder-colors`.

Fixes #4231.

#### Changelog

**Changed**

- Placeholder colors, to `$text-05`.
- Manual color usage in style rules for placeholders, to use `@include placeholder-colors`.

#### Testing / Reviewing

Testing should make sure the following components are not broken:

* Combo box
* Date picker
* Filterable multi select
* Search
* Text input
* Text area

2019-12-02 16:21 UTC, joshblack approved these changes

2019-12-02 18:26 UTC, abbeyhrt commented
@aagonzales Hey! We talked about doing this here https://github.com/carbon-design-system/carbon/pull/4281#issuecomment-540174852 and you said it might be better to just change the value of $text-03 to the value of $text-05, would we still want to do that or is it too late?

2019-12-02 19:26 UTC, aagonzales commented
I don't have a quick answer for you. I kind of forget the thread of this decision. I want to look at all this again and make sure we're updating the token correctly. I'm need to focus on finishing up my pattern work right now and don't want to get distracted so I can take a look at this later this week maybe.

2019-12-03 17:00 UTC, abbeyhrt approved these changes
This looks good to me!

2019-12-03 17:16 UTC, abbeyhrt commented
Hey @asudoh! Looking into it, I think this will also fix #4254!

2019-12-04 09:43 UTC, emyarod approved these changes
looks good to me, pending visual review

2019-12-04 20:18 UTC, jeanservaas reviewed
Talked to @aagonzales  about this and there's some confusion; need to re-review this after patterns push.

2019-12-17 16:55 UTC, aagonzales reviewed
I have confirmed with Bo Campbell, if the "placeholder" text is actually displaying the format of the input or a prompt then it needs to pass color contrast. If however it is non-informational text (ie an example) then it can remain the low contrast placeholder color `text-03`

Ok so that are 3 possibilities:
- `text-01`: option text, 4.5:1 contrast
   - selects
   - drop-downs
- `text-03`: placeholder low contrast, non-informational text
   - text input
   - text area
- `text-05`: format text or prompt, 4.5:1 contrast
   - date picker
   - time picker
   - search

![image](https://user-images.githubusercontent.com/11670886/71016720-2e8a2500-20bb-11ea-8ab8-8624d5318541.png)

Side note: we should actually probably figure out how to display the format in date and time picker to be present outside of the field.

2019-12-17 17:15 UTC, aagonzales requested changes

2019-12-17 17:15 UTC, aagonzales commented on packages/components/src/globals/scss/_helper-mixins.scss
> +  color: $text-05;
This should stay `text-03` as it is the official "placeholder" text token.

2019-12-17 17:15 UTC, aagonzales commented on packages/components/src/components/search/_search.scss
> +      @include placeholder-colors;
Search should be using `text-05` since placeholder text is being changed back to `text-03`

2019-12-17 17:15 UTC, aagonzales commented on packages/components/src/components/combo-box/_combo-box.scss
> +      @include placeholder-colors;
should be `text-05`

2019-12-18 08:29 UTC, asudoh commented
Thanks for the updated spec @aagonzales - Updated.

2019-12-18 15:42 UTC, aagonzales approved these changes
👍

2019-12-19 00:44 UTC, merged