feat(ui-shell): switch header nav role for side nav
carbon-design-system/carbon pull request #4834
Opened 2019-12-09 08:08 UTC by asudoh

This change allows users of `<HeaderMenu>` and `<HeaderMenuItem>` to specify their ARIA roles so the a11y structure won't be broken when they are put in side nav for narrow screen.

#### Changelog

**New**

- `linkRole` prop to `<HeaderMenu>` and `<HeaderMenuItem>`, that allows to specify their ARIA roles of the `<a>` in them.

#### Testing / Reviewing

Testing should make sure `<HeaderMenu>` and `<HeaderMenuItem>` are not broken.

2019-12-09 18:07 UTC, joshblack requested changes
What issue is this corresponding to btw? If I remember correctly, we ended up just removing the menu pattern so should we only remove `role="menuitem"` and leave it at that? In particular, `role="menuitem"` doesn't work as intended since we removed the parent `role="menu"` (or was that in another component? 🤔)

2019-12-10 08:02 UTC, asudoh commented
Removing `role="menuitem"` sounds good to me, updated.

2019-12-10 16:39 UTC, joshblack approved these changes

2019-12-10 16:41 UTC, joshblack commented
Seems great 🎉 just need to have merge commit be something like:

```git
fix(ui-shell): remove role="menuitem" from header links
```

2019-12-13 18:00 UTC, abbeyhrt commented
@asudoh will this address the "An element with WAI-ARIA role must be contained within a valid element" violation in #3576 as well?

2019-12-13 18:22 UTC, abbeyhrt commented
![Screen Shot 2019-12-13 at 12 22 06 PM](https://user-images.githubusercontent.com/17281178/70822465-38eaad00-1da3-11ea-8a1e-52d2f5366172.png)
Not sure what's happening but something is going on with the Links now

2019-12-13 19:23 UTC, joshblack commented
Ah good catch @abbeyhrt 🤦‍♂️ forgot that the UI Shell selectors are tied to the ARIA role for `menuitem`

2020-01-13 20:07 UTC, abbeyhrt commented
Hey @asudoh! Any progress on this?

2020-01-14 07:28 UTC, asudoh commented
My apologies @abbeyhrt, this completely slipped my mind. Fixed.

> @asudoh will this address the "An element with WAI-ARIA role must be contained within a valid element" violation in #3576 as well?

Not an intent, but seems that you are right.

2020-01-14 15:57 UTC, emyarod approved these changes
looks good to me, just removing redundant sass prefix

2020-01-14 15:57 UTC, emyarod commented on packages/components/src/components/ui-shell/_side-nav.scss
> +    & a.#{$prefix}--header__menu-item {
```suggestion
    a.#{$prefix}--header__menu-item {
```

2020-01-14 15:57 UTC, emyarod commented on packages/components/src/components/ui-shell/_side-nav.scss
> +    & a.#{$prefix}--header__menu-item:hover {
```suggestion
    a.#{$prefix}--header__menu-item:hover {
```

2020-01-14 18:08 UTC, abbeyhrt commented
@asudoh this looks great! Just one thing I noticed, I'm not sure if this is just because of changes to the story but the `Link 4` sub menu won't open for me in the Header Base w/ Navigation story

2020-01-15 04:57 UTC, asudoh commented
Great catch @abbeyhrt, my apologies for leaving another issue. Fixed.

2020-01-15 17:33 UTC, abbeyhrt approved these changes
Looks great! 🎉

2020-01-15 19:52 UTC, merged