fix(Dropdown): rely on list-box height closes #4916
carbon-design-system/carbon pull request #4917
Opened 2019-12-18 21:44 UTC by vpicone

2019-12-18 22:02 UTC, dakahn approved these changes

2019-12-18 22:04 UTC, alisonjoseph requested changes
Dropdown appear broken in vanilla

2019-12-18 22:56 UTC, vpicone commented
@alisonjoseph vanilla is actively making our code worse, someone put it out of its misery.

2019-12-18 23:08 UTC, asudoh reviewed
Thank you for jumping in @vpicone - ~~Vanilla dropdown doesn't have `.bx--list-box`, which will be more solid distinction than detecting ARIA role (given vanilla dropdown may add ARIA role in future).~~

UPDATE: I see what the problem is all about - Selector specify problem. I think the best fix is changing the selector of height rulesets to e.g.: `.bx--list-box.bx--list-box--xl`

2019-12-18 23:13 UTC, vpicone commented on packages/components/src/components/dropdown/_dropdown.scss
>    .#{$prefix}--dropdown--xl {
@asudoh can you explain what these were added for?

2019-12-18 23:17 UTC, vpicone commented
@asudoh The problem, as you mentioned, is the lack of list-box styles in Vanilla. My first solution was to remove the height from Dropdown (because it's defined by list-box), however this means Vanilla has no height and breaks. 

More specificity is not the correct way about this. That makes it even more difficult for someone to theme/style this component.

2019-12-18 23:22 UTC, asudoh commented
I still think the problem is selector specificity, because if you take a look at the Styles tab in Chrome DevTools, we see `.bx--dropdown` (the class for regular list box) overrides the height even though `.bx--list-box-xl` sets the height for the specific size variant, which tells the definition order of `.bx--dropdown` and `.bx--list-box-xl` is in play.

Vanilla dropdown not having `.bx--list-box` came from a historical reason, which is, the divergence of the markup between vanilla and React.

2019-12-18 23:29 UTC, vpicone commented
@asudoh the instructions you gave are the same ones I gave in the issue I opened. The overall issue here is the dropdown styles are competing with the listbox styles. 

The _best_ solution is to remove the height from Dropdown (my first solution). This doesn't work because Vanilla can't use listbox height. So that gives us these options:

Now we have to decide: do we make the styles for _all listbox components_ more specific to override the dropdown components height? (your proposal). OR do we provide a height when one isn't provided by list-box _without_ creating more specificity (my current solution).

If we use your solution, someone styling our component would need to use two classes just to match the specificity you're proposing. In addition that impacts Multiselect, Combobox AND Dropdown.

2019-12-18 23:47 UTC, asudoh commented
I see specificity race is _not_ about dropdown vs. list box. It's rather about [default height of the list box](https://github.com/carbon-design-system/carbon/blob/v10.7.0/packages/components/src/components/list-box/_list-box.scss#L75) vs. specific size variant of list box, and making sure the size variant works regardless of ruleset definition order. BTW `:not(.bx--list-box)` adds specificity to regular version of dropdown for vanilla.

2019-12-18 23:48 UTC, vpicone commented
@asudoh correct, it adds specificity to a single framework for a single component.

Your solution add's specificity for all list box components in all frameworks.

2019-12-18 23:50 UTC, asudoh commented
The important thing is about "regular version". If we add specificity to the regular version, specificity of specific variants will be affected.

2019-12-18 23:52 UTC, vpicone commented
@asudoh those variants would be written only for vanilla? It seems that's what you were attempting to do with the `bx--dropdown-xl` stuff. We definitely don't want to write variants for a single framework...

2019-12-18 23:55 UTC, asudoh commented
No, those variant are both for vanilla/React.

2019-12-18 23:57 UTC, vpicone commented
@asudoh you didn't use those classes in your PR.

2019-12-19 00:08 UTC, asudoh commented
The problem is that a change to selector order (among components) seems to have happened after the dropdown size variant change is checked in, and thus I didn't notice (potential at then) selector order/specificity problem when I implemented it.

2019-12-19 00:09 UTC, vpicone commented
@asudoh this problem existed in the preview for your PR.

2019-12-19 00:10 UTC, asudoh commented
Sounds strange, sorry then. Probably the bug was introduced to when I coped with review comments.

2019-12-19 03:41 UTC, alisonjoseph commented
> UPDATE: I now see the issue with Netlify preview was likely to have been caused by rebasing. 

Agree, this must be what happened, I can't imagine everyone would have approved the PR, design included otherwise.

2019-12-19 04:21 UTC, vpicone commented
@alisonjoseph the only thing that was broken was dropdown xl. dropdown sm and the other listbox components were fine. I can definitely see how it was overlooked.

Regardless of how it was caused, it was broken after that PR and is broken now, this is the best way of fixing it.

2019-12-19 22:19 UTC, asudoh commented
I suggest making size variants work regardless of selector definition order, instead of patching to `.bx--dropdown` selector.

2019-12-19 22:20 UTC, vpicone commented
@asudoh my solution eliminates the order by deleting the height off of the drop down. It only supply’s the height when it’s not defined by the list box class.

2019-12-19 22:24 UTC, asudoh commented
The problem with `.bx--dropdown:not(.bx--list-box)` kind of selector is that it increases the specificity of regular dropdown.

2019-12-19 22:26 UTC, vpicone commented
@asudoh your solution increases the specificity of not just drop down but all listbox components. This rule only applies to drop downs which are not list boxes (vanilla)

2019-12-19 22:36 UTC, asudoh commented
> @asudoh your solution increases the specificity of not just drop down but all listbox components. 3 components on all frameworks.

The increased specificity is how the selectors should have been defined, to make sure we override the default height if it's defined (or application defines the default height).

2019-12-19 22:46 UTC, vpicone commented
@asudoh I disagree. We don’t define the height for the other list box component. Increasing their specificity needlessly would be a bad decision.

2019-12-19 22:48 UTC, vpicone commented
Important disagreement in what you just said: we should _never_ implement a feature by trying to overcome specificity. That results in fragile, difficult to theme styles.

2019-12-19 22:51 UTC, asudoh commented
CSS specificity is used to ensure the more specific the selector is, the more the associated CSS rules are prioritized. Therefore, exact use case for size variants.

2019-12-19 23:00 UTC, vpicone commented
Alright @asudoh , I look forward to your fix! We’re waiting on the large drop down for the website.

2019-12-19 23:00 UTC, closed without merging