fix(tag): added short tag
carbon-design-system/carbon pull request #4953
Opened 2020-01-06 15:28 UTC by alembe

Added a prop for a short tag

2020-01-06 17:23 UTC, abbeyhrt commented
Hi @alembe thank you for taking the time to contribute!  Based on our [versioning guide](https://github.com/carbon-design-system/carbon/blob/master/docs/guides/versioning.md#a-new-prop-is-added-to-a-component), we would consider this change a feature and not a fix, would you mind changing the PR title to `feat(tag): added short tag`? Thank you! 🙏

2020-01-06 17:29 UTC, abbeyhrt commented
@alembe Noticed that the close button outsizes the short Tag on hover, could you address that if you get the chance? 
![Screen Shot 2020-01-06 at 11 25 50 AM](https://user-images.githubusercontent.com/17281178/71835579-86db9380-3077-11ea-8af7-85ffe5edb9fb.png)

2020-01-06 18:29 UTC, alembe commented
@abbeyhrt Fixed the height of the tag on hover, let me know if you need anything else from me!

2020-01-06 18:32 UTC, alembe commented
@abbeyhrt I fixed the height of the svg on hover, let me know if there's anything else you want me to do!

2020-01-06 19:18 UTC, aagonzales reviewed
Looking good, just the hover of the close should be a circle. It's a little oval-y right now. It should also be inset a little so the circle size should be 14x14px.
![image](https://user-images.githubusercontent.com/11670886/71841957-3b7cb180-3086-11ea-99ec-919aac1bca2a.png)

2020-01-06 20:56 UTC, alembe commented
@aagonzales I fixed the circle but 14x14 looks a little small with the x in the middle
<img width="273" alt="Screen Shot 2020-01-06 at 2 54 54 PM" src="https://user-images.githubusercontent.com/25492106/71848264-a59c5300-3094-11ea-98cc-82de72cfb874.png">

2020-01-06 20:56 UTC, dakahn approved these changes
once design signs off we're good! 👍

2020-01-06 21:28 UTC, asudoh reviewed
Thank you for your contribution @alembe!

2020-01-06 21:28 UTC, asudoh commented on packages/react/src/components/Tag/Tag.js
> +  short: PropTypes.bool,
Wondering if we can make `size: PropTypes.oneOf(['regular', 'short'])`. We used to have `small: PropTypes.bool` in `<Button>` but we had to deprecate that prop due to additional size coming up: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js#L131-L144

2020-01-06 21:53 UTC, aagonzales commented
Can you make the x larger but keep the circle that smaller size?

2020-01-07 15:15 UTC, alembe commented
@aagonzales It doesn't look like it because the x is apart of the circle svg

2020-01-07 15:54 UTC, aagonzales commented
Ok then let's make the circle 18x18 and sit flush to the edge of the tag

Image demonstrating only positioning. 
![image](https://user-images.githubusercontent.com/11670886/71908463-ac2dd780-3133-11ea-9341-50b72b301d56.png)

2020-01-07 16:09 UTC, alembe commented
@aagonzales The filter tag doesn't have that at the end of the tag, there's still space at the end. Do you want that change to filter tag as well?
<img width="314" alt="Screen Shot 2020-01-07 at 10 08 58 AM" src="https://user-images.githubusercontent.com/25492106/71909524-d4b6d100-3135-11ea-9cae-d83b1f3576ee.png">

2020-01-07 16:11 UTC, aagonzales commented
@alembe Yes, it would be great to make it look exactly like the filter tag but the only way to do that is make it smaller correct and then we run into the problem of the small x.

2020-01-07 16:13 UTC, aagonzales commented
Oh wait you mean change the filter tag to be flush, no we do not want to change that. That's the ideal design.

2020-01-07 16:14 UTC, alembe commented
@aagonzales I found the removing the padding around the svg, the x looks more normal
<img width="323" alt="Screen Shot 2020-01-07 at 10 13 48 AM" src="https://user-images.githubusercontent.com/25492106/71909855-70e0d800-3136-11ea-80f7-e5db13dc3221.png">

2020-01-07 16:24 UTC, aagonzales commented
Ok sorry this should have all been spec'ed in the original issue but wasn't. 
The circle should be 16x16 which will give it a 1px inset which will make it look like the filterable icon. The focus border should only be 1px.
![image](https://user-images.githubusercontent.com/11670886/71910494-9fab7e00-3137-11ea-8308-b86caa196a8a.png)

2020-01-07 17:15 UTC, alembe commented
@abbeyhrt The 16x16 circle still doesn't have space but a 14x14 does it 
<img width="454" alt="Screen Shot 2020-01-07 at 11 15 03 AM" src="https://user-images.githubusercontent.com/25492106/71914309-f9637680-313e-11ea-9cb4-9aecb6db68e8.png">
vs 
<img width="394" alt="Screen Shot 2020-01-07 at 11 13 33 AM" src="https://user-images.githubusercontent.com/25492106/71914316-fd8f9400-313e-11ea-80bd-e4bbe9419a08.png">

2020-01-07 17:17 UTC, aagonzales commented
Oh must be something about how the circle is drawn in sketch vs code. Yeah that looks almost correct but it needs to move right 1px so its equal all the way around.

2020-01-07 17:46 UTC, alembe commented
@aagonzales I think this is good to go, let me know if you have any more additions!

2020-01-07 19:35 UTC, aagonzales commented
@alembe The react deploy preview failed so I can review it.

2020-01-08 16:40 UTC, abbeyhrt approved these changes
Looks great! Thank you @alembe!

2020-01-08 23:38 UTC, asudoh commented
@alembe A reminder on my review comment: https://github.com/carbon-design-system/carbon/pull/4953/files#r363491401

Please don't hesitate to bring up if you have any questions. Thanks!

2020-01-10 18:04 UTC, joshblack commented
@aagonzales do we need to worry about touch target size with this?

2020-01-10 18:09 UTC, aagonzales commented
Its most like in a data table which will already have touch target problems. In fact our normal tags probably have touch target issues.

2020-01-10 18:17 UTC, joshblack commented
Is there anything we can do to remedy it? I would be worried if we added this and then had to backtrack because of the route we'd have to go down to solve the touch target problem. Unless  addressing the issue isn't that big of a deal? Just curious

2020-01-10 18:30 UTC, aagonzales commented
We can set an invisible it target of 44px then just leave it up to design team to make sure nothing else in the that target area. It will already be a problem with table rows though which are 32px.

2020-01-10 20:00 UTC, joshblack commented
@aagonzales is there a specific article/resource you're thinking of for the invisible target size? If I understand correctly, we can implement something like that with padding but it would impact the overall layout as a result. If the layout doesn't grow, then we would have overlapping targets in the data table use-case.

2020-01-13 16:45 UTC, aagonzales commented
Hmm no I was hoping you'd have suggestions. The acceptable touch target is 44px which if we had to make the actual tag that size it would defeat the purpose of this issue.

2020-01-13 22:58 UTC, asudoh reviewed
@alembe Feel free to let us know if you no longer have time to make this update. Thanks!

2020-01-13 22:58 UTC, asudoh commented on packages/react/src/components/Tag/Tag.js
> +    [`${prefix}--tag--short`]: short,
```suggestion
    [`${prefix}--tag--short`]: size === 'short',
```

2020-01-13 22:58 UTC, asudoh commented on packages/react/src/components/Tag/Tag.js
> +  short,
```suggestion
  size,
```

2020-01-13 22:58 UTC, asudoh commented on packages/react/src/components/Tag/Tag.js
> +  short: PropTypes.bool,
```suggestion
  size: PropTypes.oneOf(['regular', 'short']),
```

2020-01-14 16:05 UTC, emyarod reviewed
is the short size available for filter tags only or should there also be an example of non-filter short tags in the storybook?

2020-01-14 16:05 UTC, emyarod commented on packages/react/src/components/Tag/Tag-story.js
> +      <Tag className="some-class" {...props.filter()} filter short>
going off of @asudoh's suggested changes in `Tag.js`

```suggestion
      <Tag className="some-class" {...props.filter()} filter size="short">
```

2020-01-14 16:05 UTC, emyarod commented on packages/components/src/components/tag/_tag.scss
> +    padding-right: 0.0625rem;
should we use Carbon spacing tokens for this value?

2020-01-28 22:40 UTC, asudoh commented
@alembe Are you still pursuing for completing this PR? Thanks!

2020-02-12 16:56 UTC, vsnichols commented
@emyarod we need the short size for both filterable and non-filterable tags

2020-02-12 17:01 UTC, vsnichols commented
@joshblack The short tag is needed for the short data table use case (32px rows). As @aagonzales  noted, the table in general has a 32px target, not 44px. We would have to decide to stop supporting a condensed view to address this, and we know users want the option for a condensed view.

Gmails "compact" view for example looks like it is also about 32px if not denser. 

As long as we are providing users with the option to set table density, which we will be doing with the new data table component settings menu, this should not be an issue.

2020-02-12 17:02 UTC, joshblack commented
@vsnichols makes sense! Thanks.

2020-02-12 17:15 UTC, aagonzales commented
The react preview deploys are failing and I don't have a local build set up so @laurenmrice can you take a look at this in your local build and approve if it looks good. (sorry for passing the buck)

2020-02-12 17:17 UTC, aagonzales commented
@emyarod were all you concerns fixed?

2020-02-12 17:59 UTC, laurenmrice requested changes
@alembe The tag height looks like its currently set at 16px, it should be 18px. This may resolve some of the hover issues

2020-02-13 02:53 UTC, asudoh commented on packages/react/src/components/Tag/Tag.js
> +  short: PropTypes.oneOf(['regular', 'short']),
```suggestion
  size: PropTypes.oneOf(['regular', 'short']),
```

2020-02-13 17:30 UTC, vsnichols commented
@alembe I think the last change that needs to be made is to make sure the short tag is 18px high (looks like it is 16px currently). Then hopefully we should be good to go...

2020-02-14 14:31 UTC, laurenmrice requested changes
Tag height looks good 👍🏻

The hover circle and focus are nudged too far to the right. The hover circle should be 16px x 16px with a 1px padding between the hover and the tag background.

Spec:
![Artboard](https://user-images.githubusercontent.com/43969356/74539747-910d6f00-4f0c-11ea-8ff5-2dacff23873a.png)

2020-02-17 23:44 UTC, joshblack commented
Hi @alembe! 👋 Let us know if you're still interested in pursuing this!

2020-02-20 18:17 UTC, vsnichols commented
@joshblack we definitely are - @alembe sorry there is one more requested change - see above ^

2020-03-04 21:44 UTC, joshblack commented
Hi there! 👋 We're going through older PRs and closing ones that have gone stale. Let me know if you still want to work on this and we'd be happy to re-open!

2020-03-04 21:44 UTC, closed without merging