fix(text-input): rename sizing props
carbon-design-system/carbon pull request #5167
Opened 2020-01-23 23:57 UTC by tw15egan

Matches Text Input `size` prop naming to Dropdown `size` prop naming

<img width="350" alt="Screen Shot 2020-01-23 at 3 55 01 PM" src="https://user-images.githubusercontent.com/11928039/73034149-021fa200-3df9-11ea-86fc-2f203dd6d104.png">

#### Changelog

**Changed**

- changes prop `small` to `sm `
- changes prop `large` to `xl`

#### Testing / Reviewing

Change knob for size and ensure text input changes to correct size

2020-01-23 23:57 UTC, asudoh approved these changes
LGTM 👍 - Thanks @tw15egan!

2020-01-24 02:44 UTC, vpicone requested changes
LGTM, just this one tweak. Thanks for hopping on this!

2020-01-24 02:44 UTC, vpicone commented on packages/react/src/components/TextInput/TextInput.js
>    size: PropTypes.string,
```suggestion
  size: PropTypes.oneOf(['sm', 'xl']),
```

2020-01-24 02:46 UTC, vpicone commented
It's wild to me that dropdown/listbox goes sm, default, xl

But definitely think it's better to be consistent for future fixes or updates.

2020-01-24 03:17 UTC, tw15egan commented
@vpicone Makes sense, updated and should be good to go

2020-01-24 03:20 UTC, vpicone approved these changes

2020-01-24 03:41 UTC, merged