Also add ref to non-sortable branch
carbon-design-system/carbon pull request #5204
Opened 2020-01-29 10:17 UTC by gmoehler

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2020-01-29 12:07 UTC, asudoh approved these changes
LGTM 👍 - Thanks @gmoehler!

2020-01-29 12:08 UTC, asudoh commented
BTW could you fix the code format? Thanks!

2020-01-29 15:59 UTC, joshblack requested changes

2020-01-29 15:59 UTC, joshblack commented on packages/react/src/components/DataTable/TableHeader.js
> +      <th {...rest} className={headerClassName} scope={scope} colSpan={colSpan}> ref={ref}
```suggestion
      <th {...rest} className={headerClassName} scope={scope} colSpan={colSpan} ref={ref}>
```

2020-01-30 09:58 UTC, gmoehler commented
@asudoh The react deployment probably needs a re-start

2020-01-30 15:47 UTC, joshblack approved these changes

2020-01-30 17:13 UTC, tw15egan approved these changes

2020-01-30 21:14 UTC, merged