fix(button): add aria label to non `button` element buttons
carbon-design-system/carbon pull request #5522
Opened 2020-03-04 00:43 UTC by dakahn

Closes #5521 

Implicit labeling (having wrapped text in the sub-tree acting as the label) only works for native `button` elements. For instances 

#### Changelog

**New**

- added an `aria-label: children` to the `anchorProps` object

#### Testing / Reviewing

Since button is a widely used generic component I could totally be missing something/some use case. Otherwise just open up Chrome and run DAP with the latest ruleset and you should see zero errors reported 🏄

2020-03-04 09:22 UTC, asudoh commented
A question; What happens if the button has non-text content?

2020-03-04 16:26 UTC, dakahn commented
@asudoh Well, if there was no label whatsoever DAP would throw and error for an anchor tag not having an associated label. Is that a use case we support? 

![2020-03-04 10_25_52-Storybook](https://user-images.githubusercontent.com/40970507/75900469-91f63a00-5e02-11ea-844f-7beab81d9bec.png)

2020-03-04 16:53 UTC, abbeyhrt approved these changes
Looks good to me! Separately, I see that DAP is saying that `p` and `a` are form control elements, are they really? Or am I misunderstanding and it's just picking up the `role='button'`?

2020-03-04 17:20 UTC, dakahn commented
@abbeyhrt right yeah! They become form control elements the moment we designate them `role="button"`

2020-03-04 19:34 UTC, joshblack commented
Wow, definitely an awkward violation lol. Would you want to add a quick test to check for this too with any links to refer to why we need to do this?

2020-03-04 21:21 UTC, dakahn commented
@joshblack added test! Though you'll notice we we had two nested divs inside our test button that I removed -- they didn't seem to be directly related to any of the tests I saw in that unit, but there might be something I'm missing.

2020-03-04 21:37 UTC, joshblack requested changes

2020-03-04 21:37 UTC, joshblack commented on packages/react/src/components/Button/Button-test.js
> +      expect(wrapper.props()['aria-label']).toEqual('Child');
```suggestion
      expect(wrapper.prop('aria-label').toEqual('Child');
```

2020-03-04 21:59 UTC, asudoh commented
@dakahn You could detect if `children` is a string. If it's the case you can still propagate it to `aria-label`. Otherwise we can let application to populate `aria-label`.

2020-03-04 22:06 UTC, joshblack commented
That's a great point ☝️, `children` is of type `PropTypes.node` so may not contain text. Would we instead need a prop type warning such that `aria-label` is required if `href` is supplied?

2020-03-04 22:49 UTC, dakahn commented
Hey @joshblack brought up a good point that it probably makes more sense to simply remove `role="button"` for any anchors or whatever else. 👍

2020-03-05 16:09 UTC, abbeyhrt commented
@dakahn I'm not really sure how the non-button elements styled to look like buttons are used but is it a problem that they're no longer announced as buttons?

2020-03-05 19:03 UTC, tw15egan commented
@abbeyhrt my understanding is they are used when you are navigating to different parts of an app, so I think it would make more sense that they were _not_ announced as buttons. I believe they are just styled like them since a lone link doesn't seem to have the same affordance/CTA as a button.

2020-03-05 19:09 UTC, abbeyhrt commented
@tw15egan Ah gotcha, makes sense! Thanks for explaining!

2020-03-05 19:09 UTC, tw15egan approved these changes
Makes sense to me, DAP errors have been eliminated ☠️ 

 👍 ✅

2020-03-05 20:08 UTC, joshblack approved these changes

2020-03-05 22:11 UTC, asudoh approved these changes
LGTM 👍 - Thanks @dakahn!

2020-03-06 00:08 UTC, merged