fix(sketch): add undefined exception handler in icon generate script
carbon-design-system/carbon pull request #5583
Opened 2020-03-10 15:14 UTC by emyarod

Closes #5582

This PR avoid pushing `undefined` as a Layer object to Sketch in the icon page generation script and adds an npm script for viewing the development log

#### Changelog

**New**

- `log` npm script for viewing the development log

**Changed**

- `undefined` exception handler in icons/generate script

#### Testing / Reviewing

1. modify `carbon/packages/sketch/src/commands/icons/shared.js` to only deal with a subset of icons (either modify the `start` and `end` variables to be a subset of the full icons list or directly change the slice size in `symbolsToSync`)
2. `yarn build`
3. sync and generate the icons in Sketch

2020-03-10 15:41 UTC, joshblack requested changes

2020-03-10 15:41 UTC, joshblack commented on packages/sketch/src/commands/icons/generate.js
> +          const instance = symbol?.createNewInstance();
Oh wild, I think we might want to fail if the symbol doesn't exist. Maybe something like:

```js
if (!symbol) {
  throw new Error(`Unable to find symbol for icon ${icon}`);
}
```

2020-03-11 18:27 UTC, joshblack approved these changes

2020-03-11 22:49 UTC, asudoh approved these changes
LGTM 👍 - Thanks @emyarod!

2020-03-19 16:31 UTC, merged