Update icons.yml
carbon-design-system/carbon pull request #5646
Opened 2020-03-17 19:11 UTC by pbenson322

Corrected titles for UI Icon Library noted in InVision (comments 1-124) with the exception of comment #112 Logo Google and comment #120 Logo StumbleUpon, which I can't find in the above coding. Also, awaiting an answer from Conrad Ennis on IoT connect (comment #98) and Edt (comment #102). While looking for content to update, I found other friendly names that needed correction, which aren't part of the UI Icon Library. They are as follows: Logo Instagram, Logo OpenShift®, Logo VMware, Logo Yelp, QR code, VMDK disk, WiFi, WiFi off, Covariate, Hashtag, Script, DNA, Erase 3D, MPEG, MPG2, DOC and PPT.

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2020-03-17 19:13 UTC, joshblack approved these changes

2020-03-17 20:49 UTC, abbeyhrt approved these changes

2020-03-17 20:58 UTC, joshblack requested changes

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-17 20:58 UTC, joshblack commented on packages/icons/icons.yml
> +    - 16
```suggestion
```

2020-03-18 14:35 UTC, connor-leech approved these changes

2020-03-18 14:46 UTC, joshblack approved these changes

2020-03-19 13:37 UTC, emyarod approved these changes
name changes look good to me

2020-03-19 14:56 UTC, merged