feat(sketch): add support for generating icon ranges
carbon-design-system/carbon pull request #5711
Opened 2020-03-25 23:40 UTC by joshblack

Closes #5694
Closes #5695
Closes https://github.com/carbon-design-system/carbon-design-kit/issues/260

Addresses deprecation bit of: #4357 (we no longer generate deprecated icons)

This patch adds support for rendering both `[32, 24]` and `[20, 16]` sets of icons, alongside addressing previous rendering bugs by adding an extension to `icon-build-helpers` that embeds the source of each asset into metadata. As a result, we now use the source of the icon to render the symbol in Sketch.

#### Changelog

**New**

- `icon-build-helpers`
  - New `assets` extension exposed to library consumers to embed source and path information for the assets of an icon
- `sketch`
  - Add two new commands for rendering `[32, 24]` and `[20, 16]` icon sets

**Changed**

- `icon-build-helpers`
  - Update arguments of `build` to take in `input` and `output` paths to specify a custom input/output directory
- `sketch`
  - Generate local metadata in the `generated` folder with extensions for `pictograms` and `icons`
  - Use this metadata instead of `build-info.json` in our sync commands for icon symbols
  - Use the asset source for icon symbols instead of the optimized source from SVGO
- `icons`
  - Fix SVG assets that had extra paths that were causing incorrect rendering behavior when we merge paths

**Removed**

- `sketch`
  - Removed existing icon symbol sync command

2020-03-25 23:40 UTC, joshblack commented
@abbeyhrt @dakahn let me know if you want to go over this!

2020-03-25 23:50 UTC, joshblack commented
FYI @vpicone this is that assets extension work I was talking about. Nothing is changing for `metadata.json` from `@carbon/icons` though 👍 

The big thing most likely will be mirroring the rendering bugs when copying over into Sketch. Most likely we'll go back to optimizing the SVG assets now that we no longer use them in Sketch which might impact the library download capabilities.

2020-03-26 00:02 UTC, joshblack commented on packages/sketch/src/commands/icons/sync.js
> +export async function syncSmallIcons() {
```suggestion
export function syncSmallIcons() {
```

2020-03-26 00:02 UTC, joshblack commented on packages/sketch/src/commands/icons/sync.js
> +export async function syncLargeIcons() {
```suggestion
export function syncLargeIcons() {
```

2020-03-26 02:44 UTC, vpicone commented
@joshblack nice, yeah thankfully the changes to the svgo config fixed our illustrator issues. If someone wants to use one of the SVG icons in sketch, then using the sketch addon would be the preferred workflow compares to downloading from the website anyhow.

2020-03-26 15:44 UTC, emyarod reviewed
should we ignore deprecated icons when we generate the icon page? currently the error for missing symbol is being thrown

2020-03-26 15:48 UTC, joshblack commented
@emyarod ah yeah, definitely lol

2020-03-26 18:26 UTC, laurenmrice requested changes
- We don't need a transparent-rectangle or rectangle background on each icon artboard. The size of artboard the symbol sits on will make this container.
<img width="586" alt="Screen Shot 2020-03-26 at 12 46 27 PM" src="https://user-images.githubusercontent.com/43969356/77682640-45b39b00-6f65-11ea-89e2-b57a89111324.png">

-------------------------------------------------------------------------------------------------

- The `undo` and `redo` icons are rendering in a skewed way.
<img width="307" alt="Screen Shot 2020-03-26 at 12 50 10 PM" src="https://user-images.githubusercontent.com/43969356/77682754-6ed42b80-6f65-11ea-8f73-510035f8672e.png">
<img width="324" alt="Screen Shot 2020-03-26 at 1 02 25 PM" src="https://user-images.githubusercontent.com/43969356/77682764-7267b280-6f65-11ea-9806-8bdbd9e8b649.png">

2020-03-26 18:37 UTC, joshblack commented
@laurenmrice the only reason the rectangles show up is because they're in the original SVG assets 👍 can definitely remove them though.

Good catch on the arrows, let me figure out what's going on!

2020-03-26 18:57 UTC, laurenmrice commented
let me know once you have another build. Could you also send me the 16,20px file so I can make sure they are consistent with the 24,32

2020-03-27 19:25 UTC, joshblack commented
@emyarod @laurenmrice updated!

2020-03-27 19:55 UTC, abbeyhrt approved these changes

2020-03-27 20:32 UTC, dakahn approved these changes
Cool work 🏄

2020-03-30 19:46 UTC, joshblack commented
@laurenmrice confirmed that there were some issues still but that the issues are with the underlying SVG assets (not having transparent rectangle) so will move forward with addressing those in a separate issue!

2020-03-30 19:58 UTC, laurenmrice approved these changes

2020-03-30 20:08 UTC, merged