feat(button): add in tertiary button for use with danger primary
carbon-design-system/carbon pull request #573
Opened 2018-02-14 20:43 UTC by tw15egan

## Adds Tertiary Button

### Added
- Tertiary Button

![screen shot 2018-02-14 at 2 41 55 pm](https://user-images.githubusercontent.com/11928039/36227027-5844eb1e-1195-11e8-90b6-d1ffcba9660d.png)

![screen shot 2018-02-14 at 2 41 51 pm](https://user-images.githubusercontent.com/11928039/36227038-6069aafa-1195-11e8-872f-def61ead9531.png)

This button should **only** be used with a primary Danger button

2018-02-15 05:05 UTC, asudoh approved these changes
LGTM once the design review passes 👍 - Thanks @tw15egan!

2018-02-16 16:59 UTC, marijohannessen requested changes
The code looks good, however, it seems like it's not passing accessibility with a color contrast ratio of 2.67. Can one of our designers take a look? @carbon-design-system/design

2018-02-16 17:04 UTC, bsonefeld commented
We can merge this in for the interim, but keep in mind the colors for `ui-05` and the red support color are changing to meet the new WCAG guidelines. 

Respective issues for each can be found here: 

* [ui-05 new color](https://github.ibm.com/Bluemix/carbon-issues/issues/542)
* [danger button new color](https://github.ibm.com/Bluemix/carbon-issues/issues/546)

CC: @tay-aitken

2018-02-16 17:05 UTC, tay-aitken commented
We are updating the colors for this right now. The update should be coming next sprint (or later this sprint). The new color change will take care of this accessibility issue.

2018-02-16 17:39 UTC, marijohannessen approved these changes

2018-02-16 17:39 UTC, merged