feat(list-box): allow multiselect, combobox to open to top
carbon-design-system/carbon pull request #5735
Opened 2020-03-27 19:25 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/5588
Refs https://github.com/carbon-design-system/carbon/issues/5318

Adds back in the "open up" functionality to `ListBox` elements, namely `Dropdown`, `ComboBox`, and `MultiSelect`

#### Changelog

**New**

- New `direction` prop, accepts either `top` or `bottom`. Defaults to `bottom`.
- New `direction` knob in associated stories
- New styles in `_list-box.scss` to change the menu position 

#### Testing / Reviewing

Check out `Dropdown`, `ComboBox`, and `MultiSelect`. Try changing the direction, and then ensure that each component opens the correct way. Try with different field sizes as well.

2020-03-27 20:12 UTC, abbeyhrt commented
@tw15egan would this close #4686 as well?

2020-03-27 20:16 UTC, abbeyhrt commented
The knob for changing the direction for Dropdown wasn't working for me but Combobox and Multiselect seemed great 👍

2020-03-27 20:22 UTC, laurenmrice requested changes
-As Abbey said, dropdown isnt working yet.
-Not sure if this a big deal, but when `top` is selected the drawer is out of view and is hard to see depending on what field height is selected. Could we move the dropdown down a bit?
<img width="440" alt="Screen Shot 2020-03-27 at 3 15 13 PM" src="https://user-images.githubusercontent.com/43969356/77797223-b5e21f80-703e-11ea-874b-58a1b74226c0.png">

-Combobox and Multiselect chevrons don't adapt to the center with the xlarge and small height changes. (in safari only)
<img width="359" alt="Screen Shot 2020-03-27 at 3 19 21 PM" src="https://user-images.githubusercontent.com/43969356/77797104-859a8100-703e-11ea-86a5-b0b44d0949db.png">
<img width="350" alt="Screen Shot 2020-03-27 at 3 19 44 PM" src="https://user-images.githubusercontent.com/43969356/77797124-89c69e80-703e-11ea-82e1-36b569ddb0af.png">

2020-03-27 20:27 UTC, abbeyhrt commented on packages/react/src/components/Dropdown/Dropdown.js
> +        [`${prefix}--dropdown--up`]: direction === 'top',
```suggestion
        [`${prefix}--list-box--up`]: direction === 'top'
```
I think this might be why Dropdown isn't working?

2020-03-31 16:57 UTC, tw15egan commented
@laurenmrice changes have been made 👍 

We don't have any component-specific overrides in place in the storybook (to center the component), but since the website demo is centered on the page it should be fine when viewing the direction `top`  version

2020-03-31 19:13 UTC, laurenmrice approved these changes
thanks tj! looks good 🙌🏻

2020-04-02 22:33 UTC, asudoh approved these changes
🎉 - Thanks @tw15egan!

2020-04-07 16:08 UTC, aledavila approved these changes
lgtm

2020-04-07 16:48 UTC, merged