fix(inline-notification): fix inline-notification styles on mobile
carbon-design-system/carbon pull request #5763
Opened 2020-03-31 19:50 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/5730

Fixes mobile related issues with `inline-notification`. CTA on `inline-notification` now wraps on mobile and is placed under the subtitle text. On larger screens, it will appear adjacent to the notification text. 

#### Changelog

**New**

- Subtitle text can now be changed via a knob on the storybook
- Mobile styles that are reset to their previous values once they reach the first breakpoint (`md`)

#### Testing / Reviewing

Ensure that inline notification looks correct at all sizes in all browsers.

2020-04-01 15:11 UTC, aledavila approved these changes
lgtm. Checked on all browsers on both views. including on my iphone 👍

2020-04-01 18:30 UTC, aagonzales commented
I'm waiting for the preview links to come back. I can't preview it locally.

2020-04-02 14:40 UTC, joshblack requested changes
Weird, seems like something is going on in IE11 with the Action and Close buttons 🤔 

![image](https://user-images.githubusercontent.com/3901764/78262250-ea822b00-74c5-11ea-8505-4aa2b1f8a32c.png)

2020-04-02 18:11 UTC, tw15egan commented
@joshblack fixed 👍

2020-04-02 18:12 UTC, joshblack approved these changes

2020-04-02 22:50 UTC, aagonzales reviewed
If its easy can we kill the extra 8px of padding-top here when it move under?

![image](https://user-images.githubusercontent.com/11670886/78307009-71f18d80-750a-11ea-9a45-21fbc949ea6b.png)

2020-04-03 18:15 UTC, tw15egan commented
@aagonzales fixed 👍

2020-04-03 18:41 UTC, aagonzales approved these changes
Looks good!

2020-04-03 18:41 UTC, merged