fix(tooltip): change aria-describedby a11y
carbon-design-system/carbon pull request #5957
Opened 2020-04-28 16:21 UTC by FrivalszkyP

I tested the `Tooltip` element with VoiceOver on MacOS and couldn't get it to announce the contents of the tooltip upon focusing on the triggering button element. 

#### Changelog

**Changed**

- I moved the `tooltipId` to the element that has the `role="dialog"` attribute. That seems to fix the issue with VoiceOver

#### Testing / Reviewing

Open the Storybook and fire up VoiceIver to test it.

Important information: I tested the `Tooltip` component with NVDA on Windows and couldn't get it to work either way. I think there are further, more deep-rooted A11Y issues with `Tooltip` but PR #5489 seems to address those.

2020-04-28 19:33 UTC, tw15egan approved these changes
Confirmed VoiceOver is now working as expected ✅ 👍

2020-04-29 02:11 UTC, dakahn requested changes
I'm still seeing this issue in Safari, and Firefox latest. It does appear to solve the problem on Chrome though. Was this fix Chrome specific?

2020-04-29 02:16 UTC, dakahn commented
Cross checking results with [this work-in-progress WAI-Aria example](https://cdpn.io/Moiety/debug/LaPvWy). The interaction differs, but the tooltip text is readable on button focus and if the user moves reading cursor into the dialog.

2020-04-29 08:49 UTC, FrivalszkyP commented
@dakahn you are very right, it seems like it's still not working in Safari. Based on this, the issue is more deeply rooted than I initially thought. For example, the tooltip popup should be reachable by the reading cursor, but right now it closes immediately if I try to move the cursor.

I'm looking into finding a fix but I fear that whatever I do, it'll just introduce conflicts for the eventual merging of #5489. So I think we should close this PR and look for a more all-encompassing solution. I'm keeping an eye on #5489 and see if I can contribute to that discussion instead of doing anything parallel to that.

2020-05-01 15:23 UTC, aledavila commented
Thanks yes we realized tooltip is quite a big issue for us. Keep an eye out. Will close for now.

2020-05-01 15:23 UTC, closed without merging