fix(pagination): conform next/prev button to ghost, icon size to 16
carbon-design-system/carbon pull request #6058
Opened 2020-05-11 18:24 UTC by tay1orjones

Closes #6057 

Refactor pagination to use ghost button w/ size 16 icons for next/prev

#### Changelog

**Changed**

- pagination component to use ghost button
- updated styling

#### Testing / Reviewing

I'd definitely appreciate a review of the styling, particularly the focus styling. There's some specificity issues with the default ghost button styles I had to work around. I think overall it's valid, but it feels like the situation with the borders could be streamlined?

2020-05-12 00:06 UTC, joshblack commented
Definitely would be interested to see what the correct spec is here, it seems like from the image  on the style tab the icons should be 20/20: https://www.carbondesignsystem.com/components/pagination/style but will wait for @jeanservaas to confirm 👀

2020-05-12 00:06 UTC, joshblack reviewed
Left a couple above 👀

2020-05-12 03:06 UTC, tay1orjones commented
No sweat if this PR ends up in the trash. Was an anomaly I noticed as I reviewed the size of icons in the table toolbar (16). Feels like this should be consistent, but as you point out the spec says 20.

2020-05-12 12:16 UTC, jeanservaas commented
@tay1orjones @joshblack 

Can somebody please post a screen grab here of the status quo with the bug and the desired state? 

In general, I'm not seeing them in the issues or the PRs and this makes things very difficult for visual designers to review.

2020-05-12 12:24 UTC, asudoh commented
@tay1orjones Seems that you expect no visual change with your change, is it correct? Otherwise, could you please list what visual change you meant to make? Thanks!

2020-05-12 19:33 UTC, tay1orjones commented
@jeanservaas Yep, sorry for the lack of clarity. The size of the caret icon in the next/prev buttons is decreased to 16 to fall in line with styling of ghost icon-only buttons.

Current:
![image](https://user-images.githubusercontent.com/3360588/81737102-31682680-945d-11ea-8a74-73470fb9930b.png)

Proposed in this PR:
![image](https://user-images.githubusercontent.com/3360588/81737233-670d0f80-945d-11ea-912d-a0264e13531a.png)

2020-05-12 22:14 UTC, jeanservaas approved these changes
OK! Thanks @tay1orjones for the quick turnaround on those grabs, you are a champ!!!... sorry... that was grumpy pre-coffee me this morning. 

I think I know what happened here @joshblack 

Chris Connors modified the carrot when Tyler was working on the new tree component. Mike asked him to make the asset larger on the canvas. As a result, they now look massive at 20px. And this is an awesome catch and update. Boom!

2020-05-12 23:15 UTC, joshblack requested changes
Couple of style-nits 👀

2020-05-12 23:15 UTC, joshblack commented on packages/react/src/components/Pagination/Pagination.js
> +            kind={'ghost'}
```suggestion
            kind="ghost"
```

2020-05-12 23:15 UTC, joshblack commented on packages/react/src/components/Pagination/Pagination.js
> +            tooltipAlignment={'center'}
```suggestion
            tooltipAlignment="center"
```

2020-05-12 23:15 UTC, joshblack commented on packages/react/src/components/Pagination/Pagination.js
> +            tooltipPosition={'top'}
```suggestion
            tooltipPosition="top"
```

2020-05-12 23:15 UTC, joshblack commented on packages/react/src/components/Pagination/Pagination.js
> +            kind={'ghost'}
```suggestion
            kind="ghost"
```

2020-05-12 23:15 UTC, joshblack commented on packages/react/src/components/Pagination/Pagination.js
> +            tooltipAlignment={'end'}
```suggestion
            tooltipAlignment="end"
```

2020-05-12 23:15 UTC, joshblack commented on packages/react/src/components/Pagination/Pagination.js
> +            tooltipPosition={'top'}
```suggestion
            tooltipPosition="top"
```

2020-05-14 00:03 UTC, dakahn approved these changes
Seems cool to me as soon as Josh's changes are sorted 👍

2020-05-19 23:20 UTC, joshblack approved these changes
Seems great! Just have a couple test failures that need to be cleaned up, I think 👀

2020-05-29 21:47 UTC, tay1orjones commented
Sorry for the delay here - tests should be passing now 👍

2020-06-02 19:39 UTC, tw15egan commented
@tay1orjones Thanks for updating those tests!

2020-06-02 20:12 UTC, merged