Focus states: Card, Breadcrumb, Checkbox
carbon-design-system/carbon pull request #61
Opened 2017-05-02 19:33 UTC by marijohannessen

## Overview

Focus states for Card, Breadcrumb, Checkbox

Closes https://github.ibm.com/Bluemix/design-system-website/issues/1052
Closes https://github.ibm.com/Bluemix/design-system-website/issues/1051
Closes https://github.ibm.com/Bluemix/design-system-website/issues/1050

2017-05-03 14:45 UTC, hellobrian commented
Unrelated to this PR but I'm noticing that the tab order defaults to tabbing through all cards and overflow-menu icons, THEN a user can tab through overflow-menu list items. 
Would be good to know if there's a way to allow people to opt into navigating an overflow-menu list without tabbing through a bunch of other cards. 

![image](https://cloud.githubusercontent.com/assets/4185382/25666156/47dfe0ea-2fe5-11e7-9904-b5ad005e2755.png)

2017-05-03 14:50 UTC, hellobrian commented
You need to test these focus states in high-contrast mode on Firefox:

By default, here's how breadcrumb and checkbox components look:

Breadcrumb: 

- All breadcrumb links appear with underline whether they're in focus or not

![image](https://cloud.githubusercontent.com/assets/4185382/25666254/98c31180-2fe5-11e7-9753-6a6d970d61ae.png)

Checkbox:

The focus state works but checkmark SVG fails to show up since it's using `fill="white"`.
Unfortunately, this is something I didn't check before when making checkbox way back when.

![image](https://cloud.githubusercontent.com/assets/4185382/25666306/d10f01f2-2fe5-11e7-913b-d3c3476aa94c.png)

2017-05-16 16:31 UTC, marijohannessen commented
@hellobrian Just pushed up some changes. I added some CSS specific for Firefox only so the breadcrumbs now have the underline only on focus, and the checkmark is visible in high contrast mode. 

I'm a bit confused about your last comment about what the checkbox focus state should look like - is it not showing up with the same style as the toggle focus state for you?

2017-05-16 16:36 UTC, marijohannessen commented
I also created an issue about the tab order for the cards: https://github.ibm.com/Bluemix/carbon-issues/issues/133

2017-05-19 14:57 UTC, hellobrian commented on src/components/breadcrumb/breadcrumb.html
> +    <a href="#" class="bx--link" tabindex="0">Breadcrumb 1</a>
Did you try this without `tabindex="0"`? Usually for links, you don't need to add this since it should be tabbable by default.

2017-05-19 14:58 UTC, hellobrian commented on src/components/checkbox/_checkbox.scss
> +        stroke: $brand-01;
wonderful!

2017-05-19 14:59 UTC, hellobrian commented
> I'm a bit confused about your last comment about what the checkbox focus state should look like - is it not showing up with the same style as the toggle focus state for you?

When I reviewed the checkbox work last week, it wasn't using the correct focus state but I see it now. It must've been something weird with how I checked out your branch. 

After addressing comments, 👍 ✅ ❗️

2017-05-22 16:23 UTC, marijohannessen commented on src/components/breadcrumb/breadcrumb.html
> +    <a href="#" class="bx--link" tabindex="0">Breadcrumb 1</a>
You are correct! Removing it.

2017-05-24 16:51 UTC, chrisdhanaraj reviewed
Just a generic statement to document some of these browser hacks we're doing for future us - good to go otherwise.

2017-05-24 16:51 UTC, chrisdhanaraj commented on src/components/breadcrumb/_breadcrumb.scss
> +    @-moz-document url-prefix() {
Could you drop a comment in to describe what this does?

2017-05-26 14:38 UTC, hellobrian requested changes
👍 ✅ ❗️ approved after addressing @chrisdhanaraj's comments

2017-05-26 15:18 UTC, marijohannessen commented on src/components/breadcrumb/_breadcrumb.scss
> +    @-moz-document url-prefix() {
yup!

2017-05-26 15:43 UTC, hellobrian approved these changes
👍 ✅

2017-05-26 15:44 UTC, merged