fix(Notification): update warning and info icons
carbon-design-system/carbon pull request #6103
Opened 2020-05-18 16:16 UTC by emyarod

Closes #6101

This PR updates the notification components with new information and warning icons from #6046

#### Testing / Reviewing

Confirm the icons for information and warning notifications are correct

2020-05-18 17:26 UTC, joshblack approved these changes

2020-05-18 23:19 UTC, dakahn approved these changes

2020-05-19 14:28 UTC, aagonzales requested changes
Ok so what we actually want to do here is make it possible for the original icons or these new icons to be used in the notification. Both icons are correct and teams can pick if they want the more distinct ones or not. The outer shape is the third indicator plus notifications are always accompanied with text so accessibility was already met. However, products can decided to introduce the outer shape differentiator if they want but its not required.

2020-05-20 17:47 UTC, aagonzales approved these changes
Perfect!

2020-05-26 16:01 UTC, merged