fix(accordion): prevent setting title by default
carbon-design-system/carbon pull request #6236
Opened 2020-06-09 21:50 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/6235

We were setting the `title` attribute on `AccordionItem` headings by default, and taking the value from the `title` prop. The `title` prop has a type of `node`. which rendered incorrectly. Secondly, the `AccordionItem` heading wraps, so a `title` is unnecessary. 

Also of note, we should rename this prop to something besides `title` in `v11`, as this can be confused with the actual HTML title property. 

#### Changelog

**Removed**

- removed `title` attribute being auto-populated from the heading text
- no longer used `iconDescription` 

#### Testing / Reviewing

Verify `AccordionItem` renders correctly

2020-06-09 23:05 UTC, dakahn approved these changes

2020-06-10 16:01 UTC, joshblack requested changes

2020-06-10 16:01 UTC, joshblack commented on packages/react/src/components/Accordion/AccordionItem.js
> -  iconDescription,
Should we keep it here so that it doesn't accidentally get added to wherever `...rest` is applied? 👀

2020-06-10 16:01 UTC, joshblack commented on packages/react/src/components/Accordion/AccordionItem.js
> -        title={title || iconDescription}
Where is `title` being set instead? Or is it just no longer available for this component?

2020-06-10 16:08 UTC, tw15egan commented on packages/react/src/components/Accordion/AccordionItem.js
> -        title={title || iconDescription}
the HTML attribute `title` isn't being set anymore (since the title wraps anyways), but `title` in this component refers to the text that shows up on the accordion item header. It's rendered [here](https://github.com/carbon-design-system/carbon/pull/6236/files#diff-9994d046a59710de8aa5c73ee2b8ff72R83)

Flagged this as a prop that should be renamed for V11.

2020-06-16 20:00 UTC, joshblack approved these changes

2020-06-17 13:58 UTC, merged