fix(pagination): alternate pagination scroll fix
carbon-design-system/carbon pull request #6247
Opened 2020-06-10 18:00 UTC by tw15egan

Refs https://github.com/carbon-design-system/carbon/pull/6246

This is an alternate solution to #6246 that uses an extra container wrapper to scroll the Pagination component

#### Changelog

**New**

- `bx--pagination--scroll-wrapper` wraps the left and right pagination wrappers. The parent is set to `overflow: hidden` and this container is set to `overflow-x: auto`

**Changed**

- Moved some styes from `bx--pagination` to `bx--pagination--scroll-wrapper`

#### Testing / Reviewing

Ensure no scrollbars are present on Windows 10, or MacOS with scroll bar visibility set to 'Always' in System --> General.

Ensure Pagination can still scroll on mobile viewport

I recommend hiding whitespace changes, which makes this change seem larger than it is:
<img width="529" alt="Screen Shot 2020-06-10 at 2 01 14 PM" src="https://user-images.githubusercontent.com/11928039/84302162-c10afe80-ab09-11ea-823e-e2dcf833b2dd.png">

2020-06-10 19:07 UTC, joshblack commented
![demo](https://user-images.githubusercontent.com/3901764/84308224-bcebda80-ab23-11ea-89ee-39ea80348d63.gif)


Hmm I can't seem to scroll at all in this area, but the region itself is scrollable 🤔

2020-06-10 19:42 UTC, tw15egan commented
@joshblack hmm, I didn't notice that as I'm using the trackpad. How is a horizontal scroll normally handled with the scroll wheel? Do you need to hold down shift or something while using the scroll wheel? Or is it always scrolled by grabbing the scrollbar?  

I'm guessing the same issue exists with Tabs then. Focus seems to scroll both components, as well as clicking in and using arrow keys. 

Mobile users, the main target of these fixes, won't be affected by this, but want to make sure it doesn't break things for mouse users (more than the component breaking completely like the scroll was added to fix)

2020-06-10 20:53 UTC, joshblack commented
> How is a horizontal scroll normally handled with the scroll wheel?

I think you're right, holding shift can do it along with dragging the scroll bar. I had no idea you could use shift though 😮

2020-06-11 15:48 UTC, joshblack approved these changes

2020-06-11 17:22 UTC, aagonzales approved these changes
Looks good!

2020-06-11 17:46 UTC, dakahn requested changes
Hiding the scrollbar violates [WCAG Success Criteria 1.4.11](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) which states that active user interface components must have a minimum contrast requirement of 3:1. Worth noting here is that 1.4.11 has a special exemption for users choosing to hide it themselves like say at the OS or browser level.

We also, as noted by @snidersd :pray:, are in violation of [WCAG Success Criteria 1.4.10](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) which requires user interface components and text to reflow when zoomed to 400% (at 1240px). This is relevant to this PR at a higher level, but I'll make a separate issue and link here later so we can figure out how to move forward.

2020-06-11 19:14 UTC, tw15egan commented
@joshblack I'm going to close this due to the a11y concerns, so it looks like for now the best course of action is to revert the scrolling functionality. I can take a look at trying to refactor the preexisting component and see if there is another workaround to better handle mobile pagination.

2020-06-11 19:14 UTC, closed without merging