docs(data-table): batch actions - update documentation
carbon-design-system/carbon pull request #6363
Opened 2020-06-29 23:20 UTC by andreancardona

Closes #5569 

Updated data table - batch actions documentation. 

#### Changelog

**New**

- Added `TableToolbarSearch` as a child of `TableToolbarContent` in the batch actions documentation.

**Changed**

- Updated documentation change should be seen here: [DataTable - Batch Actions](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/README.md#batch-actions)

#### Testing / Reviewing

- [ ] Please make sure `TableToolbarSearch` is now listed in the [DataTable - Batch Actions](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/README.md#batch-actions)

2020-06-30 19:41 UTC, joshblack requested changes
Looking good! Should we also update the code example to reflect this?

![image](https://user-images.githubusercontent.com/3901764/86169673-9b0cc480-badf-11ea-90f4-0cbf56e36ec4.png)

Seems like we might also need to update this so `TableToolbarSearch` in `TableToolbarContent` 👀 Let me know if I'm missing something!

2020-06-30 21:19 UTC, andreancardona commented
> Looking good! Should we also update the code example to reflect this?
> 
> ![image](https://user-images.githubusercontent.com/3901764/86169673-9b0cc480-badf-11ea-90f4-0cbf56e36ec4.png)
> 
> Seems like we might also need to update this so `TableToolbarSearch` in `TableToolbarContent` 👀 Let me know if I'm missing something!

ahh yes of course, I updated the example in filtering as well, lmk now it looks now!

2020-07-01 16:15 UTC, joshblack approved these changes

2020-07-02 18:10 UTC, tw15egan commented on packages/colors/scss/colors.scss
> -// Code generated by @carbon/colors. DO NOT EDIT.
Were these meant to be removed in this PR? 🤔

2020-07-02 18:26 UTC, tw15egan approved these changes
Looks great! 💪 👍 ✅

2020-07-06 05:00 UTC, merged