feat(CodeSnippet): allow copy button to be optional
carbon-design-system/carbon pull request #6505
Opened 2020-07-20 22:57 UTC by emyarod

Closes #6499

This PR allows the copy button to be optionally hidden from single and multiline code snippet. For inline code snippets, a span will be rendered instead of a button

#### Testing / Reviewing

Confirm the code snippet variants without copy buttons appear correct

2020-07-21 14:34 UTC, laurenmrice requested changes
Functionality of showing and hiding the copy is working 👍🏻

When we hide the copy button for single and multi-line code snippets the padding on the left should change to allow more text to fill the empty space.

Spec:
![Artboard](https://user-images.githubusercontent.com/43969356/88068031-46d08f80-cb35-11ea-8c7f-245e6cfa81be.png)

2020-07-21 20:36 UTC, laurenmrice requested changes
Inline code snippet
-The inline code snippet increases in height when the no copy button prop is turned on.

Single line code snippet 
-The overflow text is getting a hard cutoff instead of having the gradient when you horizontal scroll.

2020-07-21 21:06 UTC, emyarod commented
the inline code snippet height change should be resolved now

the gradient does not appear in Netlify because of CSS custom properties (related https://github.com/carbon-design-system/carbon/issues/4426) and this is not a regression in this PR. but I have implemented a workaround at the component level (#6410 for example) and I can resolve this issue for gradients in the other affected components in a separate PR

2020-07-21 21:40 UTC, laurenmrice approved these changes
looks great! thank you 🙌🏻

2020-07-22 19:29 UTC, dakahn approved these changes

2020-07-22 19:44 UTC, tw15egan approved these changes
LGTM 👍 ✅

2020-07-27 22:56 UTC, tw15egan commented
@emyarod it looks like a `border: none` was removed. Was that intentional? Don't see anything referring to the border so just wanted to make sure before I approve the visual diff

2020-07-27 23:07 UTC, emyarod commented
cc @laurenmrice to double check the code snippet borders (single and multiline since it looks like they are the only variants that import border styles and then override them)

2020-07-28 15:37 UTC, laurenmrice requested changes
Actually yeah, now there is a border showing up on the `single line` code snippet. it needs to be removed.
<img width="850" alt="Screen Shot 2020-07-28 at 10 34 02 AM" src="https://user-images.githubusercontent.com/43969356/88687712-36cd2880-d0be-11ea-84a4-fe8415364687.png">

2020-07-28 15:41 UTC, emyarod commented
does it also not belong on the multiline snippet? if so we can change the default mixin styles since they're currently being overridden in both variants

2020-07-28 15:42 UTC, laurenmrice commented
It doesn't need to be used for anything of the code snippet types. @emyarod

2020-07-28 16:32 UTC, laurenmrice approved these changes
looks good! thank you 👍🏻

2020-07-28 16:33 UTC, merged