fix: update left and right gutter class names to start and end
carbon-design-system/carbon pull request #6523
Opened 2020-07-22 18:56 UTC by alisonjoseph

Closes #6510

Updates left/right grid class names to start and end

#### Changelog

**New**

- start / end classnames for grid gutter and hang

#### Testing / Reviewing

Ensure nothing is broken. 

Confirm this is the correct way to comment that the left/right should be deprecated??

2020-07-22 19:21 UTC, tw15egan approved these changes
LGTM 👍 ✅

2020-07-22 20:28 UTC, tw15egan commented
@alisonjoseph seems like it's pulling in the `narrow` code from the other PR?

2020-07-22 22:16 UTC, alisonjoseph commented
Oops, I think I fixed it. 🤞

2020-07-23 14:05 UTC, joshblack requested changes

2020-07-23 14:05 UTC, joshblack commented on packages/grid/scss/_mixins.scss
> +/// Add `no-gutter` and `no-gutter--{start,end}` classes to the output CSS. These
I think we'll need to keep the previous classes as well otherwise it'll be a breaking change, maybe with a note to remove in v11?

2020-07-23 14:05 UTC, joshblack commented on packages/grid/scss/_mixins.scss
> +/// Add `hang--start` and `hang--end` classes for a given gutter. These classes are
Same note for this, I think

2020-07-23 15:31 UTC, joshblack approved these changes
Ignore me! Just was a comment change

2020-07-23 18:02 UTC, merged