fix(overflow-menu): check if function exists before calling
carbon-design-system/carbon pull request #6707
Opened 2020-08-21 16:58 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/6705

Check if `target.matches` exists before invoking it

#### Changelog

**Changed**

- Check if `target.matches` exists before invoking it

#### Testing / Reviewing

Using Firefox, open OverflowMenu, and open the menu. Then click anywhere outside the browser, return to the browser, and click anywhere inside to close the menu. There should not be an error.

2020-08-21 17:03 UTC, dabrad26 commented
I see similar target.matches in 
- pagination-nav
- init-component-by-search
- init-component-by-event
- init-component-by-launcher
- ui-shell/product-switcher
- dropdown
- data-table

Maybe should have this check for all the cases.  IDK what init-component is for, but I assume the others are similar to what overflow was doing.

2020-08-21 17:05 UTC, dabrad26 requested changes
IDK of a reason matches would be set to anything but function. But normally for libraries I go for overly cautious :/

2020-08-21 17:05 UTC, dabrad26 commented on packages/react/src/components/OverflowMenu/OverflowMenu.js
> +          if (target.matches) {
```suggestion
          if (typeof target.matches === 'function') {
```

Which is donehttps://github.com/carbon-design-system/carbon/blob/7a95a7d46c2a36c19fffafcbf1153c7ba19f7f7f/packages/components/src/globals/js/misc/event-matches.js#L19 (function type check).

2020-08-21 17:10 UTC, dabrad26 approved these changes

2020-08-21 17:10 UTC, tw15egan commented
I agree, made it match `function` specifically. Not seeing any issues with those other components, I think the main reason this one was throwing was due to the positioning logic of the `FloatingMenu`. 

Thanks again for catching that and taking a look 👍

2020-08-21 17:13 UTC, dabrad26 commented
Thanks! I am a bit concerned with an event getting triggered in Firefox and then bubbling it in on viewport focus (with no target); that def seems like wrong behavior.  

I hope its a bug in Firefox and they fix it.  But if not I fear it could show as more issue later for other events that rely on target (even if not error can cause the expected behaviors to get impacted).  

One concern I saw was it seemed when clicking in Firefox dev tools around the events backed up and would then hit the app over and over once viewport got focus (causing freezing).  Seems very odd...  Will keep an eye on Firefox's bug reports and open if I don't see others talking about it.

2020-08-21 20:08 UTC, dakahn approved these changes

2020-08-24 15:39 UTC, andreancardona approved these changes

2020-08-24 15:40 UTC, merged