fix(a11y): fixing MultiSelect no focus indicator
carbon-design-system/carbon pull request #6925
Opened 2020-09-28 17:34 UTC by rjhenriquez

Closes #6855

Fixing MultiSelect - accessibility issue - no focus indicator visible on clear button

#### Changelog

**Changed**

MultiSelect component

#### Testing / Reviewing

- Go to http://localhost:9000/?path=/story/multiselect--default
- Select a few elements
- Focus on the button to "Clear Selection" by keyboard, it should show an outline

2020-09-28 17:35 UTC, joshblack approved these changes

2020-09-28 17:36 UTC, joshblack reviewed
Actually, taking a look at the history for `_tag.scss` will this create a regression of: https://github.com/carbon-design-system/carbon/pull/4792 potentially?

2020-09-28 22:23 UTC, tw15egan commented
@joshblack it seems like that regression already exists. Perhaps we need to add a `pointer-events: none` to the disabled tag?

![Sep-28-2020 15-22-13](https://user-images.githubusercontent.com/11928039/94492174-856e7000-019e-11eb-8e9b-37ad3462cdee.gif)

2020-09-30 17:42 UTC, aledavila approved these changes

2020-09-30 17:44 UTC, aledavila requested changes
Ah now I see it. @rjhenriquez did you want to look at the possible fix TJ suggested ?

2020-10-01 15:44 UTC, rjhenriquez commented
@aledavila @tw15egan `pointer-events: none;` added

2020-10-01 16:22 UTC, tw15egan commented
I'm not seeing the disabled focus anymore, but it seems like the rest of the changes are gone now? Not able to tab to the clear icon

2020-10-21 17:53 UTC, joshblack commented
bump @rjhenriquez when you get a sec to respond to above 👀

2020-10-28 18:34 UTC, tw15egan commented
Just a few small issues I'm still seeing:

- [ ] Filter tag no longer receives `not-allowed` cursor styles when disabled




- [ ] Multiselect badge does not receive any disabled styles when the multiselect is disabled (existing bug, can be tackled in a separate PR)
<img width="393" alt="Screen Shot 2020-10-28 at 11 28 27 AM" src="https://user-images.githubusercontent.com/11928039/97480778-1f961500-1911-11eb-9af5-f8bdca8f37d7.png">

- [ ] Multiselect badge loses focus styles when hovered over 

![multiselect](https://user-images.githubusercontent.com/11928039/97480745-16a54380-1911-11eb-8755-1074ff624ef1.gif)

2020-10-28 19:23 UTC, rjhenriquez commented
@tw15egan 

- Sadly, `pointer-events: none` will override `cursor: not-allowed`, making the cursor default to the normal one. Do we create another issue to handle the onClick behavior in the React code ?

- > Multiselect badge does not receive any disabled styles when the multiselect is disabled
I think it's now fixed

- > Multiselect badge loses focus styles when hovered over
The `.bx--tag--filter:hover` has no outline on hover, so I added a hover inside the focus state.. weird but it works.

2020-10-28 20:53 UTC, tw15egan commented on packages/components/src/components/list-box/_list-box.scss
> +    @include tag-theme($disabled-02, $disabled-01);
Seems like `tag-theme` is not imported in `_list-box.scss` and is causing some build errors. 

We'll need to add a `@import '../tag/mixins';` to the top of `_list-box.scss`

2020-10-28 20:56 UTC, tw15egan commented
@rjhenriquez just two small issues, but the rest looks great! 

Let's remove the `pointer-events: none` and I'll create a separate issue to investigate what's going on with the click action. I think having the disabled cursor is more important since the `onClick` is just an action created by our story and the `onClose` is not firing

2020-10-29 15:37 UTC, aledavila approved these changes

2020-10-29 15:38 UTC, emyarod approved these changes
thanks for the updates @tw15egan, looks good to me

2020-10-29 16:43 UTC, merged