fix(date-picker): updated styles based on new flatpickr version
carbon-design-system/carbon pull request #705
Opened 2018-04-17 17:07 UTC by marijohannessen

## Overview

Flatpickr added some new containers in its latest update, so had to add some additional styling to fix some rendering bugs.

While working on this, I noticed that I couldn't get the calendar to show up in the range calendar, I wonder if it has to do with the update that @asudoh did in https://github.com/carbon-design-system/carbon-components/pull/676. @asudoh , do you know what might be causing this?

### Changed

`_date-picker.scss`

## Testing / Reviewing

Make sure the date picker calendar renders as expected.

2018-04-17 17:23 UTC, tw15egan requested changes
Single date picker looks great, but also unable to see range calendar

2018-04-18 02:04 UTC, asudoh commented
Thanks @marijohannessen for making the fix! One note here is that `4.x` version of Flatpickr does not allow us to do workarounds wrt ranges - We may want to stick to `2.x` for vanilla because of that, if we can do the style fix there to cope with both Flatpickr versions.

2018-04-18 03:24 UTC, asudoh commented
Refs: https://github.com/carbon-design-system/carbon-components-react/issues/802

2018-04-18 14:39 UTC, marijohannessen commented
Ahh I see! I changed it back to version 2, but kept the style changes so it can be fixed in the React version.

2018-04-18 14:52 UTC, alisonjoseph approved these changes
LGTM 👍

2018-04-18 14:59 UTC, joshblack approved these changes
Works great! 🙌 Only issue I came across was with range on IE11, but that might be unrelated to the style updates here.

2018-04-18 20:20 UTC, asudoh reviewed
Thanks @marijohannessen for finishing up the fix! Just one comment.

2018-04-18 20:20 UTC, asudoh commented on src/components/date-picker/_date-picker.scss
> +    width: rem(285px) !important;
Any way to make the selector here [more specific](https://www.w3.org/wiki/CSS/Training/Priority_level_of_selector) than presumably the one in Flatpicker that conflicts here, so that our one wins without `!important`?

2018-04-25 15:21 UTC, marijohannessen commented on src/components/date-picker/_date-picker.scss
> +    width: rem(285px) !important;
I don't think so, unfortunately, as the width is being set using inline styles in the newest version of Flatpickr 😞

2018-04-25 15:32 UTC, tw15egan approved these changes

2018-04-25 15:32 UTC, merged