feat: adds option for ordered list native decimal style
carbon-design-system/carbon pull request #7063
Opened 2020-10-16 21:46 UTC by jnm2377

Closes #7027 

This new style is meant to be optional for users that want native decimal styles and not a custom counter for ordered lists. I realize, this means the style won't be left-aligned like the custom counter, hence it being optional. The reason this is important for the Gatsby Theme is because we use the `start` attribute for ordered lists to be able to temporarily end and continue lists as needed. However, this attribute doesn't work with the `counter()` because it needs native decimal styles. Right now we are overriding the list styles, but still have some existing issues with it due to the custom counter (see issue).

#### Changelog

- adds ` .#{$prefix}--list--ordered_native` className for decimal styles which won't use any of the pseudo element styles
- adds example in vanilla dev environment and react storybook under "native styles", with additional list items so reviews can see how the alignment changes in double digit numbers

Wasn't sure if the className or prop name would be intuitive enough, but I'm open for feedback! 🙂 🙂

2020-10-19 23:14 UTC, dakahn approved these changes

2020-10-19 23:16 UTC, dakahn commented
ah missed the busted test! @jnm2377

2020-10-20 15:59 UTC, aagonzales commented
It looks fine in storybook but is there a way for me to see that its working correctly in the gatsby theme?

2020-10-20 16:14 UTC, jnm2377 commented
@aagonzales the only real way to test it out on the gatsby theme is by manipulating styles in the dom rn, otherwise you'll only see it when we update the carbon dependencies.

2020-10-20 17:44 UTC, aagonzales approved these changes
Ok blindly approving then!

2020-10-21 01:11 UTC, jnm2377 commented on packages/components/tests/styles-test.js
> +  jest.setTimeout(40000);
for reviewers: tests were failing bc it said it was timing out, so I updated it to have more time

2020-10-21 19:16 UTC, joshblack requested changes

2020-10-21 19:16 UTC, joshblack commented on packages/components/src/components/list/_list.scss
> +  .#{$prefix}--list--ordered_native {
```suggestion
  .#{$prefix}--list--ordered--native {
```

To follow our BEM convention, would it make sense to do `list--ordered--native`?

2020-10-23 15:14 UTC, joshblack approved these changes

2020-10-23 15:32 UTC, merged