chore: avoid circular dependencies in DataTable and FileUploader
carbon-design-system/carbon pull request #7066
Opened 2020-10-17 01:59 UTC by dbrugger

Closes 
```
carbon-components-react: (!) Circular dependencies
carbon-components-react: src/components/DataTable/state/sorting.js -> src/components/DataTable/tools/sorting.js -> src/components/DataTable/state/sorting.js
carbon-components-react: src/components/FileUploader/index.js -> src/components/FileUploader/FileUploaderItem.js -> src/components/FileUploader/index.js
```
#### Changelog

**Changed**

- DataTable: split commonly needed sortStates into separate sortStates.js
- FileUploader: import Filename directly instead of from index

#### Testing / Reviewing

- verify `yarn build` contains no more warning

2020-10-21 19:10 UTC, joshblack requested changes
Thanks so much for doing this! Just left a couple of notes for the copyright banner, we have an automated fix for this with the right dates so might help to keep it consistent 👀

2020-10-21 19:10 UTC, joshblack commented on packages/react/src/components/DataTable/state/sortStates.js
> + * Copyright IBM Corp. 2020
```suggestion
 * Copyright IBM Corp. 2016, 2018
```

2020-10-21 19:10 UTC, joshblack commented on packages/react/src/components/DataTable/state/sorting.js
> + * Copyright IBM Corp. 2016, 2020
```suggestion
 * Copyright IBM Corp. 2016, 2018
```

2020-10-21 19:10 UTC, joshblack commented on packages/react/src/components/DataTable/tools/sorting.js
> + * Copyright IBM Corp. 2016, 2020
```suggestion
 * Copyright IBM Corp. 2016, 2018
```

2020-10-21 19:10 UTC, joshblack commented on packages/react/src/components/FileUploader/FileUploaderItem.js
> + * Copyright IBM Corp. 2016, 2020
```suggestion
 * Copyright IBM Corp. 2016, 2018
```

2020-10-21 19:14 UTC, joshblack commented
bump @dakahn when you have a sec today

2020-10-21 19:37 UTC, dbrugger commented
yeah sure thing @joshblack - requested changes made

2020-10-22 23:29 UTC, dakahn approved these changes

2020-10-28 15:57 UTC, joshblack approved these changes

2020-10-28 16:16 UTC, merged