feat(OverflowMenu): add size variants
carbon-design-system/carbon pull request #7116
Opened 2020-10-22 16:56 UTC by emyarod

Closes #7101

This PR updates the default overflow menu trigger button size to 40px by 40px and adds `sm` and `xl` size variants

#### Changelog

**New**

- `sm` and `xl` size variants

**Changed**

- update default trigger button size according to spec

**Removed**

- {{removed thing}}

#### Testing / Reviewing

Confirm that the current and new overflow menu variants appear visually correct

2020-10-22 19:11 UTC, laurenmrice requested changes
**48px size:**
There is a little notch/line on the right hand side between the square and the open menu . It should be a seamless connection between the square and the menu.
<img width="229" alt="Screen Shot 2020-10-22 at 3 03 08 PM" src="https://user-images.githubusercontent.com/43969356/96918545-76669f00-1478-11eb-97ec-5d8a2b9aa81a.png">

--------------------------------------------------------------------------------------------

**32px size:**
There is block of color between the square and the menu when open that shouldn't be there.
<img width="228" alt="Screen Shot 2020-10-22 at 3 04 44 PM" src="https://user-images.githubusercontent.com/43969356/96918644-9ac27b80-1478-11eb-9af4-8b4eb13cf941.png">

2020-10-22 23:56 UTC, dakahn approved these changes
Great work! Love the chonky xl size 😆

2020-10-23 13:42 UTC, laurenmrice approved these changes
Looks great! thank you 🎉

2020-10-26 20:01 UTC, joshblack approved these changes

2020-10-26 21:11 UTC, merged