fix(accordion): increases active class selector specificity
carbon-design-system/carbon pull request #7329
Opened 2020-11-20 19:01 UTC by jpbyrne

Closes #7328 

Vanilla Carbon Accordions are not functional when placed inside of another Accordion. Nested Accordions do not expand and collapse.

#### Changelog

**Changed**

- Vanilla Accordions can now placed in one another.

#### Testing / Reviewing

Confirm that when an Accordion appears inside another Accordion, both Accordion buttons toggle independently.

2020-12-10 15:04 UTC, tw15egan approved these changes

2020-12-10 21:59 UTC, aledavila requested changes
Waiting on design to review as this issue was changed to a proposal that has not been reviewed yet.

2020-12-11 21:10 UTC, aagonzales commented
We are advising against putting accordions inside of accordions. For nesting content we recommend a using a tree view or figuring out a better ux solutions where only one level of nesting content occurs. 

In the example shown in the issue the first image looks like dropdowns inside of an accordion, not nested accordions. People have mentioned wanting a large page section type of accordion that could include more bits of ui. I think that would be fine but I think that is a new variant to the standard accordion. This as is accordion is meant for one level of content and be exclusive to content like what you see here on the [cloud docs](https://cloud.ibm.com/docs?tab=faqs) page. 
![image](https://user-images.githubusercontent.com/11670886/101954743-3ee7b980-3bc2-11eb-865a-0d8a7c969434.png)

And the second doesn't have real content so its hard to evaluate but I would say that the second layer of collapsed content was unnecessary. Why can't that content just be shown open already? Or why aren't those nested bits in two separated top level buckets. 

For the moment, I don't think we should allow nesting accordions in this basic accordion from the system level. Your team is welcomed to do it on your end if you see that its best but I still have some ux concerns about promoting it as an acceptable system pattern.

2020-12-15 19:13 UTC, aledavila commented
Going to close this as this isn’t a pattern we want in our core components. Thank you

2020-12-15 19:13 UTC, closed without merging