feat(CodeSnippet): support disabled single and multiline snippets
carbon-design-system/carbon pull request #7478
Opened 2020-12-17 17:16 UTC by emyarod

Closes #7455

This PR adds support for disabled single and multiline code snippets

#### Changelog

**New**

- `disabled` prop for single and multiline code snippets

#### Testing / Reviewing

Confirm that the component does not respond and appears correct when disabled

2020-12-17 18:25 UTC, laurenmrice requested changes
The only bug I see is that the single line code snippet gets a focus when disabled. It should not get focus.
<img width="819" alt="Screen Shot 2020-12-17 at 12 23 29 PM" src="https://user-images.githubusercontent.com/43969356/102527609-f5381c80-4062-11eb-9c98-bf617523f0a9.png">

2020-12-17 19:43 UTC, laurenmrice approved these changes
Looks good to me ! 👍🏻

2021-01-13 20:45 UTC, joshblack approved these changes

2021-01-15 23:19 UTC, andreancardona approved these changes
@emyarod looks good 🌞

2021-01-19 18:21 UTC, merged