feat(truncation): add truncation classes
carbon-design-system/carbon pull request #757
Opened 2018-05-09 18:34 UTC by tw15egan

## Adds in Truncation Classes

**Frontline truncation:** `.bx--front-line`
**Endline truncation:** `.bx--end-line`

The user will need to add `title` to populate the tooltip when the truncated text is hovered over. The user will also need to configure the `width` of the container (or the text element itself) to calculate _when_ truncation will start.

**Example Usage:**
```html
<div class="container">
  <span title="123456789" class="bx--front-line">123456789</span>
</div>
```

```css
.container { 
  width: 65px; 
}
```

```css
.bx--front-line {
  width: 100%;
  display: inline-block;
  direction: rtl;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}
```

**Result:**
![screen shot 2018-05-09 at 1 22 51 pm](https://media.github.ibm.com/user/1679/files/1c695894-538c-11e8-8cd2-bb0b1cac151b)

**Midline truncation:** Will create an example since this will require javascript.

### Added
- `_helper-classes.scss` file under `globals/scss`
- `@import 'helper-classes'` in `_layout.scss`
- `.bx--front-line` and `.bx--end-line` classes

## Testing / Reviewing
Can use the example above to test out both classes

2018-05-09 18:35 UTC, tw15egan commented
Currently, this is creating a new file `_helper-classes.scss` and is being imported in to `_layout.scss`. Wondering what @carbon-design-system/ui thinks of this structure, as it seems like we will have more helper classes being added in the near future.

2018-05-09 19:57 UTC, marijohannessen commented
It's not immediately clear to me that the classes `bx--front-line` and `bx--end-line` are related to truncation, could we maybe do something like `bx--truncation-front-line` or is that too long?

2018-05-09 21:32 UTC, tw15egan commented
@marijohannessen I agree, the discoverability isn't great. Open to suggestions

2018-05-10 18:36 UTC, joshblack commented
I'm down for some variation of `.bx--truncate--front` or `.bx--truncate--end`, or if we need to organize around additional utility classes maybe some pattern like:

```
.bx--[type]-[behavior]--[variant]
```

Some ideas:

```
.bx--text-trunc--front
.bx--text-truncation--front
.bx--text-truncate--front
...
```

2018-05-10 20:20 UTC, tw15egan commented
👍 I like that, went with `.bx--text-truncate--front` and `.bx--text-truncate--end`

2018-05-10 20:24 UTC, joshblack requested changes

2018-05-10 20:24 UTC, joshblack commented on src/globals/scss/_helper-classes.scss
> +.bx--text-truncate--end {
Should we use `.#{$prefix}` here instead of `bx`?

2018-05-10 20:33 UTC, tw15egan commented on src/globals/scss/_helper-classes.scss
> +.bx--text-truncate--end {
Yes, we should. Updating

2018-05-10 20:48 UTC, joshblack approved these changes

2018-05-10 21:18 UTC, alisonjoseph approved these changes
LGTM! 👍

2018-05-11 14:56 UTC, merged