refactor(global-scss-vars): update scss config vars
carbon-design-system/carbon pull request #76
Opened 2017-05-16 20:33 UTC by hellobrian

## Overview

resubmission of #72

2017-05-16 20:36 UTC, hellobrian commented on src/globals/scss/_css--body.scss
> +  body {
Settings `$css--body: true` will output these `body` styles to CSS. 
This is the default.

2017-05-16 20:38 UTC, hellobrian commented on src/globals/scss/_css--helpers.scss
> +  .bx--body {
`.bx--body` class gets applied when `$css--helpers: true`, which is the same styles as `body` from `_css--body.scss`

2017-05-16 20:39 UTC, hellobrian commented on src/globals/scss/styles.scss
> +$css--typography: true !default;
`$css--typography: true` will output CSS from `_css--typography.scss` and this is default.

2017-05-17 18:31 UTC, tw15egan requested changes
👍 ✅ ❗️

2017-05-17 18:31 UTC, tw15egan commented on src/globals/scss/_css--typography.scss
> +@import 'reset';
I think this should be `css--reset`

2017-05-17 18:31 UTC, tw15egan commented on src/globals/scss/_css--helpers.scss
> +@import 'reset';
I think this should be `css--reset`

2017-05-17 18:31 UTC, tw15egan commented on src/globals/scss/_css--body.scss
> +@import 'reset';
I think this should be `css--reset`

2017-05-19 15:24 UTC, hellobrian commented on src/globals/scss/_css--typography.scss
> +@import 'reset';
blargh! sorry, thanks for pointing this out haha

2017-05-31 19:06 UTC, hellobrian commented on src/components/accordion/_accordion.scss
> +    width: 1.25rem;
Change: `padding` was affecting size of accordion arrow icons making them appear smaller than normal.

2017-05-31 19:08 UTC, hellobrian commented on src/components/card/_card.scss
> +    line-height: 1.2;
Change: new styles here fix unwanted scrollbar from appearing

![image](https://cloud.githubusercontent.com/assets/4185382/26649154/8e03f9ae-460a-11e7-88fb-1f0d22355557.png)

☝️ with unwanted scrollbar

2017-05-31 19:10 UTC, hellobrian commented on src/components/file-uploader/_file-uploader.scss
> +    height: 1.875rem;
Change: styles added here fix unwanted scrollbar and prevents it from appearing

2017-05-31 19:11 UTC, hellobrian commented on src/components/notification/_inline-notification.scss
> +    justify-content: space-between;
Change: fixes missing space between inline-notification text and close button.

![image](https://cloud.githubusercontent.com/assets/4185382/26649256/f3b1a08a-460a-11e7-9b16-faa1522b2c5a.png)

☝️  missing space

2017-05-31 19:12 UTC, hellobrian commented on src/components/progress-indicator/_progress-indicator.scss
> +    right: 100%;
Change: fixes gap between line and indicators.

2017-05-31 19:16 UTC, hellobrian commented on src/components/search/_search.scss
> +    vertical-align: middle;
Need to add more styles

```css

    position: relative;
    top: -2px;
```

2017-05-31 19:16 UTC, hellobrian commented on src/components/toolbar/_toolbar.scss
> +      @include focus-outline;
Change: fixes missing focus outline on toolbar search button

2017-05-31 19:17 UTC, hellobrian commented on src/components/tooltip/_tooltip.scss
> +    @include helvetica;
Change: adds Helvetica font-family to tooltip triggers

2017-05-31 19:28 UTC, hellobrian commented on src/components/search/_search.scss
> +    vertical-align: middle;
Change: centers icon in buttons

2017-06-06 15:35 UTC, tw15egan approved these changes

2017-06-08 19:57 UTC, hellobrian commented
@chrisdhanaraj Went through the components one more time and made sure all components that need `_css--typography.scss` are now importing it.

2017-06-09 18:35 UTC, hellobrian commented
@chrisdhanaraj says: 👍 ✅

2017-06-09 18:35 UTC, chrisdhanaraj commented
👍 ✅

2017-06-09 18:36 UTC, merged