fix(button): remove danger ghost icon only button svg margin
carbon-design-system/carbon pull request #7618
Opened 2021-01-21 17:35 UTC by emyarod

Closes #7534

This PR fixes support for danger ghost icon only buttons (related #5610)

#### Changelog

**New**

- Storybook knob updates for new button kind values
- 
**Changed**

- Adjust danger ghost icon only button svg margins

#### Testing / Reviewing

Confirm the new button kinds are viewable in storybook and the danger ghost icon only button appears correct

2021-01-21 19:51 UTC, joshblack approved these changes

2021-01-21 22:45 UTC, tw15egan commented
Not introduced in this PR, but I noticed the Danger variant with icons are rendering wrong

<img width="455" alt="Screen Shot 2021-01-21 at 2 44 57 PM" src="https://user-images.githubusercontent.com/11928039/105421628-405fc500-5bf7-11eb-8fd5-8d1e8fe8ea0b.png">
<img width="488" alt="Screen Shot 2021-01-21 at 2 44 44 PM" src="https://user-images.githubusercontent.com/11928039/105421631-40f85b80-5bf7-11eb-8213-24d217ad58c7.png">

2021-01-22 18:12 UTC, emyarod commented
since the issue is already existing in the current library version I opened a separate issue and PR to resolve it #7631 #7632

2021-01-22 18:52 UTC, andreancardona approved these changes

2021-01-25 19:29 UTC, laurenmrice requested changes
When the danger tertiary button is disabled it is receiving the primary button disabled state. It needs to look like this:
![Artboard](https://user-images.githubusercontent.com/43969356/105755668-3dbfe100-5f11-11eb-95b3-6f597fea039b.png)

2021-01-26 20:18 UTC, laurenmrice approved these changes
Looks good to me! 🙌🏻

2021-01-26 21:25 UTC, merged