7512 short tag
carbon-design-system/carbon pull request #7619
Opened 2021-01-21 19:35 UTC by emyarod

Closes #7512

related #4953

This PR implements support for short Tag and Filter Tag sizes

#### Changelog

**New**

- `size` support for short tags

#### Testing / Reviewing

Confirm the short tag, short filter tag, and short skeleton tags appear correct

2021-01-21 19:50 UTC, joshblack approved these changes

2021-01-21 21:36 UTC, tw15egan commented
Should we reduce the size of the icon in the custom icon variant when the size is small as well?

2021-01-22 17:47 UTC, laurenmrice requested changes
- The text in the filterable tag is getting cut off at the bottom for both sizes.
<img width="165" alt="Screen Shot 2021-01-22 at 11 42 38 AM" src="https://user-images.githubusercontent.com/43969356/105525921-562cc300-5ca7-11eb-8496-52b14126f55a.png">

- Can we name the 18px tag `small` instead of short?
- I don't think we need to change the size of the custom icon when using the small tag. 16px is our smallest icon size and it is also going to be the size of the close icon for the filterable tag still.

2021-01-25 16:51 UTC, laurenmrice approved these changes
Thanks for adding this in! 🙌🏻

2021-01-25 22:09 UTC, tw15egan approved these changes

2021-01-25 22:10 UTC, tw15egan requested changes

2021-01-25 22:10 UTC, tw15egan commented on packages/react/src/components/Tag/Tag.Skeleton.js
> +  size: PropTypes.oneOf(['short']),
I think this needs to be `sm`

2021-01-26 21:48 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-01-26 22:11 UTC, merged