chore: update addon to match current release
carbon-design-system/carbon pull request #7694
Opened 2021-01-29 10:16 UTC by lee-chase

Relates to  #7048 

Update to match the current release published from ibm-cloud-cognitive

@andreancardona publish will fail without bumping the version beyond the current 0.3.0 release.

carbon-bot is already an owner so I believe publishing from Carbon should work.

#### Changelog

M       packages/storybook-addon-carbon-theme/README.md
M       packages/storybook-addon-carbon-theme/package.json

2021-02-01 16:39 UTC, joshblack commented
@lee-chase I think this PR may be related to the confusion from the PR being merged and revert in https://github.com/carbon-design-system/carbon/pull/7700 right?

2021-02-01 16:53 UTC, lee-chase commented
> @lee-chase I think this PR may be related to the confusion from the PR being merged and revert in https://github.com/carbon-design-system/carbon/pull/7700 right?

Yes. Didn't want to prevent a publish.

2021-02-01 21:04 UTC, joshblack approved these changes

2021-02-01 21:04 UTC, joshblack reviewed
Ah sorry, hit the wrong button above 🤦‍♂️

2021-02-02 04:13 UTC, dakahn approved these changes

2021-02-02 16:35 UTC, joshblack commented
@lee-chase since we reverted the change that added the package, is this PR still relevant?

I think Andrea shared this in the PR itself, but I think our hope will be to use the storybook preset package and included in that should be an add-on that folks can use.

2021-02-02 16:35 UTC, joshblack requested changes
Leaving a comment year since I made the review mistake earlier 🤦‍♂️

2021-02-03 17:27 UTC, andreancardona commented
@lee-chase Hi Lee! Sorry for all the confusion. I made a comment here: https://github.com/carbon-design-system/carbon/pull/7700

@aledavila and I have been working on a storybook preset that can be seen here: https://github.com/carbon-design-system/carbon/pull/7569

In which case it made sense to revert #7048. Please let me know if you have any questions or concerns!

2021-02-08 18:33 UTC, joshblack commented
Going to go ahead and close this PR out, let me know if you have any questions @lee-chase after @andreancardona 's clarification above 👀

2021-02-08 18:33 UTC, closed without merging