fix(multi-select): remove right margin on filterable tag
carbon-design-system/carbon pull request #7740
Opened 2021-02-04 17:05 UTC by emyarod

Closes #7735

Related #7722

This PR removes the right margin on the filterable multiselect selection tag, resolving an existing issue with filterable multiselect spacing

#### Testing / Reviewing

Confirm the filterable multiselect input has the correct spacing from the tag

2021-02-04 17:20 UTC, tay1orjones approved these changes

2021-02-04 17:40 UTC, tw15egan approved these changes

2021-02-04 17:43 UTC, laurenmrice requested changes
After the tag appears in the input after selecting an option, the text in the input is still too far away from the tag. It needs to be 8px/1rem.
![Artboard](https://user-images.githubusercontent.com/43969356/106806197-414c1a00-662d-11eb-932f-575d946aaa4d.png)

2021-02-05 15:10 UTC, laurenmrice approved these changes
LGTM! 👍🏻

2021-02-05 18:08 UTC, merged