fix(list-box): update hover active item background color
carbon-design-system/carbon pull request #7832
Opened 2021-02-17 21:37 UTC by emyarod

Closes #7490

This PR updates the hover state background color for active/selected items in list boxes per new spec guidelines

#### Testing / Reviewing

Select and hover over a multiselect item in the storybook and confirm the correct color tokens are used

2021-02-17 22:21 UTC, aagonzales requested changes
The selected+hover looks correct now but the original problem in the issue is still there. When using the keyboard and arrowing through the selected options there is no visual indicator. It should look the same keyboard arrowing through the items as it does when you hover over them.

2021-02-18 18:27 UTC, aagonzales approved these changes

2021-02-19 18:17 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-02-23 20:06 UTC, tay1orjones approved these changes

2021-02-23 20:34 UTC, merged