6306 radio tile outline bug
carbon-design-system/carbon pull request #8258
Opened 2021-03-31 20:47 UTC by andreancardona

Closes #6306

- fixes RadioTile outline bug that can be seen [here](https://github.com/carbon-design-system/carbon/issues/6306) &  below:
<img width="894" alt="Screen Shot 2021-03-31 at 2 44 40 PM" src="https://user-images.githubusercontent.com/32720851/113209170-eea76c80-922f-11eb-809a-31a9819d929a.png">

#### Testing / Reviewing

- [ ] Checkout: 

- [ ] Zoom view to less than 100% - ex: 90%, 80%, etc.
- [ ] Make sure Tile --> Radio & MultiSelect outlines can be seen
  - Select a tile 
  - Then click out of the container to confirm bug is fixed

2021-03-31 21:14 UTC, tw15egan commented
The radio looks great!

Still seeing some cutoff on the multi select variant
<img width="989" alt="Screen Shot 2021-03-31 at 5 13 34 PM" src="https://user-images.githubusercontent.com/11928039/113212189-6f706380-9244-11eb-9766-eb7842408619.png">

2021-03-31 22:05 UTC, andreancardona commented
> The radio looks great!
> 
> Still seeing some cutoff on the multi select variant
> <img alt="Screen Shot 2021-03-31 at 5 13 34 PM" width="989" src="https://user-images.githubusercontent.com/11928039/113212189-6f706380-9244-11eb-9766-eb7842408619.png">

Ooo I see! Going to confirm a visual change. Converting this to a draft in the mean time

2021-03-31 22:21 UTC, andreancardona commented
@laurenmrice would like your opinion on the visual change to the border to 2px for the following reasons:

- It matches the focus state 2px outline
- and fixes all the bugs/issues

Thank you!

2021-04-01 14:16 UTC, laurenmrice commented
@andreancardona The border for the selected state needs to still be 1px. We use 1px for borders like this across our system unless it is a focus state.

2021-04-02 16:20 UTC, andreancardona commented
@tw15egan should be ready for review!

2021-04-02 20:49 UTC, jnm2377 approved these changes
LGTM! :)

2021-04-02 21:04 UTC, laurenmrice requested changes
- When there are two selected tiles next to eachother, there should not be an overlap of the tile borders. It should still look like 1px border between the tiles. 
![Artboard](https://user-images.githubusercontent.com/43969356/113454097-0e27cc00-93cd-11eb-9024-ec45f489c6b8.png)


- When you select a tile, there is a slight jump of the tile text moving out of place. The text should always remain in the same place not matter what state.
![Apr-02-2021 16-00-08](https://user-images.githubusercontent.com/43969356/113454074-fea88300-93cc-11eb-874c-b0d865cac721.gif)

2021-04-02 23:55 UTC, andreancardona commented
@laurenmrice I'll make sure to look into the jumping text (I think it's an outline v border issue)

But when there are 2 selected tiles - that is the current styling- is that something we still want to update?
![Uploading Screen Shot 2021-04-02 at 5.40.59 PM.png…]()

2021-04-04 17:40 UTC, laurenmrice commented
@andreancardona Yes, we want to fix that, that is a bug.

2021-04-05 21:01 UTC, tw15egan commented on packages/components/src/components/tile/_tile.scss
> +  // .#{$prefix}--tile--selectable {
Just need to remove this comment and we should be good to go 👍🏻

2021-04-05 21:34 UTC, tw15egan approved these changes
LGTM 👍 ✅ 🎉

2021-04-06 14:02 UTC, laurenmrice approved these changes
Looks good ! 🙌

2021-04-06 14:33 UTC, merged