feat(PasswordInput): support `warn` and `inline` props
carbon-design-system/carbon pull request #8366
Opened 2021-04-12 17:04 UTC by emyarod

Closes #8365

This PR adds support for the `warn` and `inline` props in the PasswordInput component to match TextInput

#### Changelog

**New**

- `warn` and `warnText` props to enable warning state
- `inline` prop to support inline password input variant

**Changed**

- password input markup more closely matches text input now
- vertical alignment of inline text input elements

#### Testing / Reviewing

Ensure the newly supported props work properly in the PasswordInput component

2021-04-12 17:52 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-04-17 16:51 UTC, laurenmrice requested changes
- The `Label` needs to bottom align with the text in the input. Right now its a little higher.
![Artboard](https://user-images.githubusercontent.com/43969356/115120292-6684cf00-9f72-11eb-995a-ea71a0ecc1ac.png)

- When the inline knob is selected and then selecting the warning state knob, the label and helper text shift down. They should remain in the same place. This also seems to happen for the invalid state.
![warning](https://user-images.githubusercontent.com/43969356/115120425-0e9a9800-9f73-11eb-998c-2af108c5b6de.gif)


- *Note - Eventually I think design needs to redesign the inline variant for form components across the board. I have realized it might make more sense to keep the helper text under the input, since it now gets replaced by the invalid and warning text that appears for these states. But this will be a design spec we can provide for a later PR. 👍

2021-04-19 18:47 UTC, laurenmrice approved these changes
Looks good! Thanks 🙌

2021-04-23 11:59 UTC, jnm2377 approved these changes

2021-04-23 12:30 UTC, merged