fix(modal): set pagination background color within modals
carbon-design-system/carbon pull request #8434
Opened 2021-04-16 15:48 UTC by emyarod

Closes #8433

This PR sets the correct pagination background color when used within modals

#### Testing / Reviewing

Confirm that full size pagination components nested within modals receive the correct background colors

2021-04-16 17:54 UTC, tw15egan approved these changes
LGTM, thanks for adding in the demo story!

2021-04-17 16:14 UTC, laurenmrice requested changes
- The form components are not being displayed correctly in the modal unless you turn on the `Modal contains a form` knob. But when this knob turns on, the `p` text should not be lengthening, it should wrap at 20% of the modal.

![Artboard](https://user-images.githubusercontent.com/43969356/115119552-8d410680-9f6e-11eb-829a-c220b23dbf1d.png)

- The pagination component example is visually broken if the form knob isn’t turned on. When the form knob is turned on, playing with the pagination makes it break.
<img width="827" alt="Screen Shot 2021-04-17 at 10 50 05 AM" src="https://user-images.githubusercontent.com/43969356/115119449-01c77580-9f6e-11eb-9922-a89e3e6facb6.png">

![Apr-16-2021 13-54-39](https://user-images.githubusercontent.com/43969356/115119477-23286180-9f6e-11eb-82b0-70f51fc62095.gif)

- Can we take the specific example of pagination out before being merging (similarly like we did with data table inline inputs?)

2021-04-19 15:18 UTC, emyarod commented
I'm unable to replicate the issue with the broken pagination when the form knob is off

![image](https://user-images.githubusercontent.com/8265238/115260467-644c7d00-a0f8-11eb-8adb-52aa99a206e3.png)

for the `p` text lengthening when the form knob is on, that appears to be separate from this change and an existing problem so I can address it in another ticket

2021-04-19 18:59 UTC, laurenmrice commented
@emyarod It is happening in Firefox (88.0). I am up to date. I also had another person test this and they it is broken for them as well.

- The pagination also seems to have a visual issue with the top rule not extending all the way to the end of the component. This is happening in Firefox/Chrome/Safari.
<img width="678" alt="Screen Shot 2021-04-19 at 1 57 15 PM" src="https://user-images.githubusercontent.com/43969356/115288693-5e19c900-a117-11eb-8d26-7a5351630829.png">

2021-04-19 19:05 UTC, emyarod commented
I was testing in Firefox as well and I saw the top rule issue but haven't seen the spacing issue from earlier

2021-04-19 23:04 UTC, dakahn approved these changes

2021-04-20 14:25 UTC, tay1orjones reviewed
@emyarod I was able to reproduce the issue. FF v86 and then I updated to v88 and it still happened.

![modal sizing](https://user-images.githubusercontent.com/3360588/115412878-5d863e80-a1ba-11eb-860a-69dc5f525f30.gif)

2021-04-20 15:43 UTC, emyarod commented
my earlier screenshots were from FF 89/90 so I will have to look into this further. I don't believe these would be caused by the color token changes in this PR so it's likely an existing issue with trying to use pagination components within modals

2021-04-20 16:03 UTC, emyarod commented
my guess is this would be related to the forced 20% right padding on the non-form modal content since the pagination component isn't responsive within modals. how should the pagination component appear in these scenario?

2021-04-20 17:45 UTC, tw15egan commented
We can track the Modal padding issue here https://github.com/carbon-design-system/carbon/issues/8373

I think this PR is good just focusing on the color updates.

2021-04-20 20:00 UTC, laurenmrice approved these changes
Approving since color looks good and we can track spacing issues separately. 👍

2021-04-20 21:56 UTC, tw15egan commented
@emyarod good to go once stories are reverted 👍🏻

2021-04-22 16:31 UTC, merged