fix: update chevron animations
carbon-design-system/carbon pull request #8437
Opened 2021-04-16 16:06 UTC by emyarod

Closes #8360

This PR updates accordion and expandable tile chevron expand/collapse animations to be consistent with the rest of the system

2021-04-16 17:20 UTC, tw15egan requested changes

2021-04-16 17:20 UTC, tw15egan commented on packages/components/src/components/accordion/_accordion.scss
> +    transform: rotate(-270) #{'/*rtl:ignore*/'};
```suggestion
    transform: rotate(-270deg) #{'/*rtl:ignore*/'};
```

![2021-04-16 10 15 03](https://user-images.githubusercontent.com/11928039/115060916-49ca9780-9e9d-11eb-8481-71ef47c4a5dd.gif)

2021-04-16 18:52 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-04-16 19:02 UTC, johnbister approved these changes
Looks great!

2021-04-23 12:16 UTC, jnm2377 approved these changes

2021-04-23 13:41 UTC, merged