fix(tooltip): tooltip margin bug
carbon-design-system/carbon pull request #8461
Opened 2021-04-20 21:22 UTC by andreancardona

Closes #8275 

Adds small 8px margin to tooltip to match current design in Sketch kit

2021-04-20 21:58 UTC, laurenmrice requested changes
The alignments are off when you change the `direction` prop to `left` , `right` and `top`. After fixing those I would also check them against the `alignment` prop options as well.

Everything else looks good though!

![tooltip](https://user-images.githubusercontent.com/43969356/115468953-7104ca00-a1f9-11eb-85d9-2132513a7052.gif)

2021-04-20 22:03 UTC, tw15egan commented on packages/components/src/components/tooltip/_tooltip.scss
> +    margin-top: $spacing-03;
I think we'll need to add these changes to `src/globals/scss/_tooltip.scss` to account for all the alignment variants

2021-04-27 16:27 UTC, tw15egan commented on packages/react/src/internal/FloatingMenu.js
> +        // margin-bottom: 0,
Can we remove this comment?

2021-04-28 14:08 UTC, laurenmrice requested changes
- The left and top directions with start, center and end alignments still need `8px (spacing-03)` between the icon and the caret tip. The others look good !

2021-04-28 15:29 UTC, tw15egan commented on packages/components/src/components/tooltip/_tooltip.scss
> +      margin-left: -$spacing-03;
Looks like this is an issue with negative numbers and css custom properties. We can do either:

`margin-left: calc(#{$spacing-03} * -1)`

or

`margin-left: rem(-8px)`

2021-04-28 15:35 UTC, tw15egan commented on packages/components/src/components/tooltip/_tooltip.scss
> +      margin-top: -$spacing-03;
Same as above

2021-04-29 04:09 UTC, andreancardona commented
@tw15egan @laurenmrice updated :)

2021-04-29 13:20 UTC, laurenmrice requested changes
- The top direction for start,center and end alignment needs to fixed still. The rest of the directions and alignments look great!

2021-04-29 17:27 UTC, tw15egan commented on packages/components/src/components/tooltip/_tooltip.scss
> +      margin-left: calc(#{$spacing-03} * -1);
```suggestion
      margin-top: calc(#{$spacing-03} * -1);
```

2021-05-03 18:53 UTC, laurenmrice approved these changes
Looks good to me! 🎉

2021-05-03 18:58 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-05-03 18:58 UTC, tay1orjones approved these changes

2021-05-03 19:39 UTC, merged