fix(css-grid): various bugfixes, first docs pass
carbon-design-system/carbon pull request #8797
Opened 2021-05-28 16:52 UTC by tay1orjones

Part of #8556

A few bugfixes to the css grid implementation - mixed mode gutters, add aspect ratio

#### Changelog

**New**

- New stories covering various parts of CSS Grid
- CSS Grid mdx storybook docs
- Configured storybook breakpoint switcher to use CDS defined breakpoints

**Changed**

- CSS Grid styling for mixed mode gutters, max width, among other small fixes

#### Testing / Reviewing

Spin up the new storybook and check it out

https://user-images.githubusercontent.com/3360588/120017114-16564f00-bfab-11eb-8fe6-d7f70557ad2b.mov

2021-05-28 17:57 UTC, joshblack requested changes
Looking great! Left a couple of QOL fixes/updates

One note for the span classes, feel free to update to have the behavior match CSS Grid instead of our old behavior if it makes sense. I think aligning with CSS Grid terminology instead of having our implementation try and map back to our v10 work makes a ton of sense 👍

2021-05-28 17:57 UTC, joshblack commented on packages/carbon-react/.storybook/main.js
> +                // require('rtlcss')(),
```suggestion
```

2021-05-28 17:57 UTC, joshblack commented on packages/grid/examples/css-grid/src/pages/layouts.js
> +// import { Tile, Button, UnorderedList, ListItem } from 'carbon-components-react';
```suggestion
```

Might help for this diff to just remove any commented out code so we have a minimal working example without needing to come back and clean anything up in the future 👍

2021-05-28 17:57 UTC, joshblack commented on packages/grid/scss/modules/_css-grid.scss
> +  --cds-grid-gutter-wide: 2rem; /* used to configure appropriate margins for condensed subgrids inside wide grids */
Style nit

```suggestion
  // Used to configure appropriate margins for condensed subgrids inside wide grids
  --cds-grid-gutter-wide: 2rem; 
```

2021-06-03 01:42 UTC, tay1orjones commented
@joshblack thanks! I revised the span/offset classes to match CSS Grid more appropriately, improved the offset story, and addressed the other feedback items 👍

2021-06-03 14:40 UTC, joshblack approved these changes

2021-06-08 01:00 UTC, dakahn approved these changes

2021-06-08 17:06 UTC, merged