feat(Definition Tooltip): add definition tooltip
carbon-design-system/carbon pull request #8871
Opened 2021-06-09 20:05 UTC by dakahn

Closes #8814 

Implements v11 /next/TooltipDefinition

#### Testing / Reviewing

In the Storybook make sure that the unstable_Tooltip / Definition story works and appears as intended.

2021-06-09 21:15 UTC, jnm2377 approved these changes

2021-06-09 21:16 UTC, dakahn commented
@joshblack throwing you on this for a PR review -- just wanna make sure I hit what I needed to hit API wise

2021-06-18 15:05 UTC, joshblack requested changes

2021-06-18 15:05 UTC, joshblack commented on packages/react/src/components/Tooltip/next/TooltipDefinition.js
> +      <div
We should make sure this component uses `Popover` directly, it should mean that we won't need the debounce or mouseover/mouseout handlers 👍

2021-10-25 19:07 UTC, closed without merging