fix(DatePicker): avoid aggressive range input clearing
carbon-design-system/carbon pull request #8893
Opened 2021-06-11 18:22 UTC by emyarod

Closes #8892

This PR updates the DatePicker so that clearing part of a range DatePicker will not clear all input fields and reset the component

#### Testing / Reviewing

Populate the inputs in a range date picker and then clear one. After moving focus, the other input should remain unmodified

2021-06-14 14:43 UTC, sstrubberg requested changes
Still getting some weird interactions with datepicker. Also, I noticed that the calendar pops up if you click anywhere in the label.

![Jun-14-2021 09-40-14](https://user-images.githubusercontent.com/15822070/121910817-cab6db80-ccf4-11eb-9237-39cef72c69b1.gif)

2021-06-14 15:03 UTC, emyarod commented
@sstrubberg can you elaborate on what weird interactions are occurring? updated the description to specify clearing the end date

for clicking on labels to activate inputs, that is the default behavior of form controls

2021-06-15 17:19 UTC, sstrubberg approved these changes
I think I wasn't understanding the original intent when I first reviewed. Getting it now :)

2021-06-15 19:33 UTC, andreancardona approved these changes

2021-06-16 16:09 UTC, merged