feat(date-picker): move styles to sass modules
carbon-design-system/carbon pull request #8895
Opened 2021-06-11 22:05 UTC by tay1orjones

Refs #8555 

Begins work on bringing `DatePicker` to the `@carbon/styles` package

#### Changelog

**New**

- Styles added for `DatePicker`
- Stories added for `DatePicker`

#### Testing / Reviewing

Pull down the PR locally, go to `carbon-react` folder and run `yarn storybook`. Ensure `DatePicker` renders properly.

2021-06-15 20:07 UTC, tay1orjones commented on packages/styles/scss/components/date-picker/_date-picker.scss
> +// @use '../form/form';
Another set of eyes on this would be appreciated! 👀  Will remove it if we can't find out why it was there in the first place.

2021-06-18 00:42 UTC, tay1orjones commented on packages/styles/scss/components/date-picker/_date-picker.scss
> +// @use '../form/form';
Sounds like the answer to this is yes, we want to continuing including these. I've pushed a fix to update.

2021-06-18 15:11 UTC, joshblack requested changes

2021-06-18 15:11 UTC, joshblack commented on packages/styles/scss/components/date-picker/_date-picker.scss
> +@use '../form/form';
Quick style nit: order of imports should be:

- top-level (colors, config, etc)
- component imports (form, others used)
- utilities
- local

2021-06-18 15:11 UTC, joshblack commented on packages/styles/scss/components/date-picker/_date-picker.scss
> +@use 'flatpickr.scss' as *;
```suggestion
@use 'flatpickr' as *;
```

2021-06-18 15:11 UTC, joshblack commented on packages/styles/scss/components/date-picker/_date-picker.scss
> +@include flatpickr;
Would we want this brought in as part of the date-picker mixin?

2021-06-21 17:36 UTC, andreancardona approved these changes
looks good to me!

2021-06-21 20:14 UTC, joshblack approved these changes

2021-06-21 23:19 UTC, merged