feat(file-uploader): add FileUploader to @carbon/styles
carbon-design-system/carbon pull request #8920
Opened 2021-06-15 20:37 UTC by tay1orjones

Refs #8555

Brings `FileUploader` to the `@carbon/styles` package

#### Changelog

**New**

- include refactored file added to `/styles`, including a test

2021-06-15 20:37 UTC, tay1orjones commented on packages/styles/scss/components/file-uploader/_file-uploader.scss
> +// @use '../../globals/scss/vendor/@carbon/elements/scss/type/styles';
Is the `@use '../../type' as *;` above enough to remove this?

2021-06-18 00:44 UTC, tay1orjones commented on packages/styles/scss/components/file-uploader/_file-uploader.scss
> +// @use '../../globals/scss/vendor/@carbon/elements/scss/type/styles';
Sounds like the answer to this is yes, the vendor stuff can be removed.

2021-06-21 17:09 UTC, joshblack requested changes
Could you include the story files too @tay1orjones? Just to double-check that the styles work 👀  (sorry we forgot to include this in the template 🤦 )

2021-06-22 16:56 UTC, tay1orjones commented
@joshblack Yes! Thank you for the reminder. I took a stab at not only bringing them over but refactoring them to use the new storybook 6 args, argTypes, and controls.

2021-06-22 21:50 UTC, joshblack commented
@tay1orjones seems like a weird storybook issue coming up 🤔

2021-06-23 15:22 UTC, tw15egan approved these changes
The controls look ✨ wonderful ✨  💯

2021-06-23 15:26 UTC, tay1orjones commented
@joshblack I'm not sure what happened, but it's up and working now since I updated with latest from `main`.

2021-06-23 15:32 UTC, joshblack approved these changes

2021-06-23 16:41 UTC, merged