feat(colors): add hover colors to `@carbon/colors`
carbon-design-system/carbon pull request #8942
Opened 2021-06-17 20:32 UTC by joshblack

Closes #8822

This PR updates our `@carbon/colors` package to include the hover palette from the IDL. It also updates our build task to export hover variables in Sass.

#### Changelog

**New**

- Hover colors from the IDL

**Changed**

- Update build taskt to emit hover colors

**Removed**

#### Testing / Reviewing

- Pull down the PR locally
- Make sure to run `yarn build` in `@carbon/colors`
- Verify that the `scss/mixins.scss` file includes the hover colors from the IDL
- Verify that the `index.scss` file includes the hover colors from the IDL

2021-06-17 20:32 UTC, joshblack commented
FYI @sstrubberg here's that draft PR!

2021-06-21 19:28 UTC, sstrubberg commented
> FYI @sstrubberg here's that draft PR!

Thx! I got all the colors in. Still getting some build errors though and i'm not confident about the tests either.

2021-06-23 18:00 UTC, joshblack commented
cc @aagonzales here are the hover colors added to our colors package from the IDL. We used the values from the file and converted them to HEX

2021-06-24 14:15 UTC, sstrubberg approved these changes
so many colors!

2021-06-24 14:35 UTC, emyarod approved these changes
looks good to me

2021-06-24 15:26 UTC, joshblack commented
Also just a heads up @aagonzales I updated the colors preview so the table should include the color hovers in there with the hex value 👍

2021-06-24 19:42 UTC, aagonzales requested changes
Values that need to be updated: 
Purple-10-hover: `#ede5ff`
Cyan-100-hover: `#0b2947`
Blue-30-hover: `#8ab6ff`

2021-06-24 19:42 UTC, aagonzales commented on packages/colors/__tests__/__snapshots__/colors-test.js.snap
> +    "30": "#b8d3ff",
```suggestion
    "30": "#8ab6ff",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/colors/__tests__/__snapshots__/colors-test.js.snap
> +    "100": "#cceeff",
```suggestion
    "100": "#0b2947",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/colors/__tests__/__snapshots__/colors-test.js.snap
> +    "10": "#eee6ff",
```suggestion
    "10": "#ede5ff",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/colors/__tests__/__snapshots__/modules-test.js.snap
> +  "purple-10-hover": "#eee6ff",
```suggestion
  "purple-10-hover": "#ede5ff",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/colors/__tests__/__snapshots__/modules-test.js.snap
> +  "cyan-100-hover": "#cceeff",
```suggestion
  "cyan-100-hover": "#0b2947",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/colors/__tests__/__snapshots__/modules-test.js.snap
> +  "blue-30-hover": "#b8d3ff",
```suggestion
  "blue-30-hover": "#8ab6ff",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/styles/scss/__tests__/__snapshots__/colors-test.js.snap
> +  "purple-10-hover": "#eee6ff",
```suggestion
  "purple-10-hover": "#ede5ff",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/styles/scss/__tests__/__snapshots__/colors-test.js.snap
> +  "blue-30-hover": "#b8d3ff",
```suggestion
  "blue-30-hover": "#8ab6ff",
```

2021-06-24 19:42 UTC, aagonzales commented on packages/styles/scss/__tests__/__snapshots__/colors-test.js.snap
> +  "cyan-100-hover": "#cceeff",
```suggestion
  "cyan-100-hover": "#0b2947",
```

2021-06-24 19:58 UTC, joshblack commented
Thanks Anna! Just updated. Just a quick heads up, all the `*.snap` files are generated so feel free to look at the `colors.js` file here: https://github.com/carbon-design-system/carbon/pull/8942/files#diff-e2ecd2a0df3376b7c433e2fdc41d587c14a3b56ce0b6bfa65bb6385246fe69e7 and disregard the rest (should save some time, I hope 🤞 )

2021-06-24 21:05 UTC, aagonzales approved these changes
lol i was dumb and didn't even think to look at the elements preview smh

2021-06-24 21:07 UTC, joshblack commented
😂

2021-06-24 23:19 UTC, merged