8940 search sass module refactor
carbon-design-system/carbon pull request #8967
Opened 2021-06-21 16:02 UTC by dakahn

Closes #8940 

Sass module refactor for Search component

## Testing

Component should behave and appear the same 👍🏽

2021-06-22 23:45 UTC, dakahn commented
Seems like the styles are broken in the Story -- :| ON IT

2021-06-23 19:56 UTC, tay1orjones requested changes
Just a couple super minor things

2021-06-23 19:56 UTC, tay1orjones commented on packages/styles/scss/components/search/_search.scss
> +@use '../../type';
If there's no mixin name conflicts you can use the `as *`

```suggestion
@use '../../type' as *;
```

which then simplifies the usages:

```diff
-@include type.type-style('body-short-01');
+@include type-style('body-short-01');
```

Also a small style nit I got from Josh: order of imports should be:

* top-level (colors, config, etc)
* component imports (form, others used)
* utilities
* local

2021-06-23 19:56 UTC, tay1orjones commented on packages/styles/scss/components/search/_search.scss
> +/// @access private
```suggestion
/// @access public
```

2021-06-23 22:09 UTC, dakahn commented on packages/styles/scss/components/search/_search.scss
> +@use '../../type';
Ah, yeah I was getting more specific with type because both /type and /component-reset forwarded `@include reset` which was throwing an error

2021-06-24 14:29 UTC, sstrubberg approved these changes

2021-06-24 15:22 UTC, dakahn commented on packages/styles/scss/components/search/_search.scss
> +@use '../../type';
If there's a better way to take care of those overlapping imports like that let me know tho

2021-06-24 19:30 UTC, tay1orjones commented on packages/styles/scss/components/search/_search.scss
> +@use '../../type';
No that's totally cool, I ran into the same thing!

2021-06-24 19:31 UTC, tay1orjones approved these changes

2021-06-25 14:54 UTC, tw15egan approved these changes

2021-06-25 16:39 UTC, merged