feat(Radiobutton):
carbon-design-system/carbon pull request #8980
Opened 2021-06-21 21:18 UTC by dakahn

Closes #8975 

Sass module refactor for Radio-button

#### Testing / Reviewing

Functionality and styling should be identical

#### Notes

I brought in the `radio-button-border` token from ../globals as per a slack discussion, but not sure how _exactly_ we want to handle that

2021-06-22 21:47 UTC, joshblack requested changes
Forgot to add this to the checklist but could you add in the storybook stories for this component? 👀

2021-06-22 23:52 UTC, dakahn commented
Storybook stories are mega busted -- ON IT! @joshblack

2021-06-23 15:30 UTC, tw15egan requested changes
Just a few changes needed but then looks like it's good to go

2021-06-23 15:30 UTC, tw15egan commented on packages/styles/scss/components/radio-button/_radio-button.scss
> +@use '../../utilities/skeleton' as *;
```suggestion
@use '../../utilities/skeleton' as *;
@use '../../utilities/convert' as *;
```

For some reason, functions don't throw errors if they aren't found, so the `rem` function silently fails. This should fix most of the styling issues I'm seeing

2021-06-23 15:30 UTC, tw15egan commented on packages/styles/scss/components/radio-button/_radio-button.scss
> +
```suggestion
@use '../form';
```

We'll need to pull in the label styles from `Form`

2021-06-23 15:30 UTC, tw15egan commented on packages/carbon-react/src/components/Radio-button/Radio-button.stories.js
> +export default { title: 'Components/Radio-button' };
```suggestion
export default { title: 'Components/RadioButton' };
```

2021-06-23 16:06 UTC, dakahn commented on packages/styles/scss/components/radio-button/_radio-button.scss
> +@use '../../utilities/skeleton' as *;
Dude this is huge! Thanks for the heads up

2021-06-24 13:51 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-06-24 18:49 UTC, joshblack approved these changes

2021-06-24 22:41 UTC, merged