8905 notification refactor inline toast
carbon-design-system/carbon pull request #9004
Opened 2021-06-23 16:19 UTC by andreancardona

Closes #8905 

- Refactors `Notification: inline-notification & toast-notification` to SASS modules 

### Testing: 

- [ ] run `yarn test --watch packages/styles/scss/components/__tests__/inline-notification-test.js`
- [ ] run `yarn test --watch packages/styles/scss/components/__tests__/toast-notification-test.js`
- [ ] Make sure tests pass
- [ ] cd `packages/carbon-react` run `yarn storybook` to make sure none of the styles are broken for `notification`

2021-06-23 16:21 UTC, andreancardona commented
@joshblack 

was talking to @tw15egan and it seems some of the styles within the `feature flag` are broken - should we leave that as is for now since that won't be an issue for the v11 release?

2021-06-24 17:41 UTC, tw15egan requested changes
Few small tweaks but otherwise looking good

2021-06-24 17:41 UTC, tw15egan commented on packages/carbon-react/src/components/Notification/Notification.stories.js
> +});
Can we hardcode these as props since the knobs don't work?

2021-06-24 17:41 UTC, tw15egan commented on packages/carbon-react/src/components/Notification/Notification.stories.js
> +import { boolean, number, select, text } from '@storybook/addon-knobs';
We can get rid of these since we aren't using knobs

2021-06-24 17:41 UTC, tw15egan commented on packages/styles/scss/components/notification/_inline-notification.scss
> +  @if feature-flag-enabled('enable-v11-release') {
```suggestion
  @if enabled('enable-v11-release') {
```

2021-06-24 17:41 UTC, tw15egan commented on packages/styles/scss/components/notification/_toast-notification.scss
> +  @if feature-flag-enabled('enable-v11-release') {
```suggestion
  @if enabled('enable-v11-release') {
```

2021-06-24 17:41 UTC, tw15egan commented on packages/styles/scss/components/notification/_toast-notification.scss
> +  @if not feature-flag-enabled('enable-v11-release') {
```suggestion
  @if not enabled('enable-v11-release') {
```

2021-06-24 18:21 UTC, andreancardona commented
> Few small tweaks but otherwise looking good

Ready for your review again - removed knobs and stripped out a lot of the unneeded props. :)

2021-06-24 18:26 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-06-30 14:12 UTC, joshblack approved these changes

2021-06-30 16:30 UTC, merged