fix(tile): add link color contrast
carbon-design-system/carbon pull request #9025
Opened 2021-06-24 16:51 UTC by andreancardona

Closes #8701 

## Testing:

- [ ] Checkout `Tile --> Expandable` and it should be seen as below with `color: $link-secondary`

https://user-images.githubusercontent.com/32720851/123302547-cfe10b00-d4ea-11eb-9fa6-4da1d6f2a7cf.mov

2021-06-24 17:06 UTC, tw15egan requested changes

2021-06-24 17:06 UTC, tw15egan commented on packages/components/src/components/tile/_tile.scss
> +  .#{$prefix}--tile-clickable tbody tr:hover th .#{$prefix}--link {
I think we just need something like

```suggestion
  .#{$prefix}--tile--expandable .#{$prefix}--link {
```

2021-06-24 17:14 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-06-28 18:56 UTC, jnm2377 approved these changes

2021-06-28 19:30 UTC, merged