feat(Tag): add Tag to @carbon/styles
carbon-design-system/carbon pull request #9131
Opened 2021-07-07 02:07 UTC by dakahn

Adds Tag to @carbon/styles

2021-07-08 15:07 UTC, joshblack approved these changes

2021-07-08 17:29 UTC, tw15egan commented
The styles don't seem to be rendering correctly 🤔 

![Screen Shot 2021-07-08 at 1 29 14 PM](https://user-images.githubusercontent.com/11928039/124965771-7ef40b00-dff0-11eb-85ca-b90291cf1f23.png)

2021-07-12 15:36 UTC, andreancardona requested changes, later dismissed
also not seeing updated styles :(

2021-07-22 00:37 UTC, dakahn commented
Sorry this was in limbo so long team -- this one was a real doozy

2021-07-22 14:13 UTC, tw15egan commented on packages/carbon-react/.storybook/styles.scss
> +@debug meta.module-variables('tag');
```suggestion
```

2021-07-22 14:15 UTC, tw15egan commented on packages/carbon-react/.storybook/styles.scss
> +@use 'sass:meta';
```suggestion
```

2021-07-22 15:24 UTC, tw15egan commented on packages/styles/scss/components/tag/_tag.scss
> +@use 'sass:meta';
Is this needed?

2021-07-22 15:25 UTC, tw15egan commented
@dakahn just a few comments, but it looks great! 🎉 🎸

2021-07-22 19:06 UTC, andreancardona reviewed
approved - pending TJ's comments 🌮

2021-07-23 14:29 UTC, joshblack requested changes

2021-07-23 14:29 UTC, joshblack commented on packages/carbon-react/.storybook/styles.scss
> +  @include styles.theme(styles.$white, tag.$white);
```suggestion
  @include styles.theme(styles.$white, button.$white, tag.$white);
```

2021-07-23 14:29 UTC, joshblack commented on packages/carbon-react/src/components/Tag/Tag.stories.js
> +export default { title: 'Components/Tag' };
I think we can add in a `component: Tag` field to this for the prop table to work

2021-07-23 15:12 UTC, joshblack approved these changes

2021-07-23 15:16 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-07-23 15:29 UTC, merged