docs(tokens): add token documentation
carbon-design-system/carbon pull request #9232
Opened 2021-07-20 19:39 UTC by andreancardona

Closes #9177

- adds a couple more pieces of information for the following packages: 

- [ ] type tokens

- [ ] migration tokens

- [ ] color tokens

2021-07-21 16:26 UTC, joshblack commented on packages/styles/docs/sass.md
> +  transition: transform $duration-fast-02 motion(standard, productive);
I think the snippet will need to be updated to:

```scss
@use '@carbon/styles/scss/motion' as *;
```

For those variables to be defined.

2021-07-21 16:33 UTC, joshblack requested changes

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> +The colors package will give you access to every color token within the IBM Design Language.
```suggestion
The colors package will give you access to each swatch from the IBM Design Language. You can refer to a color by its swatch and grade.
```

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> + @use '@carbon/styles/scss/colors';
```suggestion
 @use '@carbon/styles/scss/colors';
 
 .selector {
   background-color: colors.$blue-50;
 }
```

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
>  | Import                               | Filepath            |
Make sure this is before all the content above

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> +For more information checkout our [Files](#files) docs.
To see all the colors available to be imported, checkout our [colors](#todo) docs.

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> +
I think we can drop these kinds of snippets and just reference the snippet directly 👀 

```suggestion
```

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> +For more information checkout our [Files](#files) docs.
```suggestion
For more information, checkout our [motion](#todo) docs.
```

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> +To bring in the `@carbon/type` package use `@use`. For example:
```suggestion
```

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> + @use '@carbon/styles/scss/type';
```suggestion
 @use '@carbon/styles/scss/type';
 
 .selector {
   @include type.style(type.$productive-heading-01);
 }
```

2021-07-21 16:33 UTC, joshblack commented on packages/styles/docs/sass.md
> +For more information checkout our [Files](#files) docs.
```suggestion
For more information, check out our [type](#todo) docs.
```

2021-07-22 19:20 UTC, joshblack approved these changes

2021-07-22 19:43 UTC, sstrubberg approved these changes

2021-07-22 20:00 UTC, merged