docs: fix irregularities and update language
carbon-design-system/carbon pull request #9349
Opened 2021-07-28 16:29 UTC by adamalston

Closes #9347

Fix irregularities and update language used in many documentation files.

#### Changelog

**New**

- Improved language so that docs can be translated easier by users.

**Changed**

- Fixed irregularities so that code templates were accurate.

**Removed**

- N/A

#### Testing / Reviewing

Check spelling/format of code blocks and comments in the documentation

2021-07-28 16:47 UTC, adamalston commented
I have read the DCO document and I hereby sign the DCO.

2021-07-28 16:47 UTC, adamalston commented
recheck

2021-07-29 19:32 UTC, sstrubberg requested changes
This is incredible. Thank you for finding all these typos. Ready to approve once you get your merge conflict resolved! 🔥 

Re-request a review from me when you're ready so I get notified.

2021-07-29 22:15 UTC, adamalston commented
Yea it's quite a lot. If you noticed in the files changed for this PR, all of them are under `packages/react`. I suspect when I dive into the other packages (in future PRs), there will be even more corrections that need to be made. 

Within my team, I know there is a translation push. Extrapolating a bit, spelling errors make text more difficult to translate so just fixing these inconsistencies in the documentation may give some users a better experience when interacting with the Carbon Design System.

2021-07-29 22:29 UTC, tw15egan approved these changes

2021-07-30 15:26 UTC, sstrubberg requested changes
You might also need to run `yarn lint` to clear up linting errors.

2021-07-30 15:26 UTC, sstrubberg commented on packages/react/src/components/Slider/Slider.js
>        const stepMultiplier =
![image](https://user-images.githubusercontent.com/15822070/127675499-39466387-be67-4dd3-82f4-ead8abb4f4ec.png)

Looks like CircleCI is getting choked up around here.

2021-07-30 16:32 UTC, jnm2377 requested changes

2021-07-30 16:32 UTC, jnm2377 commented on packages/react/src/components/Slider/Slider.js
> +    stepMultiplier: deprecate(
This should not change. Changing the prop name would be breaking, that's why it's been deprecated in favor of a different prop. Please revert these changes.

2021-08-02 16:02 UTC, sstrubberg approved these changes

2021-08-02 21:53 UTC, jnm2377 approved these changes

2021-08-02 22:27 UTC, merged