chore(grid): migrate slash to math.div
carbon-design-system/carbon pull request #9357
Opened 2021-07-28 21:46 UTC by tay1orjones

Refs #8746 

Migrates the CSS Grid off of slash for division. This PR is the output from the codemod:
```
npx sass-migrator division packages/grid/scss/modules/*.scss
```

#### Changelog

**Changed**

- css-grid: migrate off slash for division

#### Testing / Reviewing

Grid stories in the `@carbon/react` storybook should still work and the `css-grid` elements example should too.

2021-07-30 15:18 UTC, sstrubberg requested changes
![image](https://user-images.githubusercontent.com/15822070/127674578-60d6c30d-d280-458b-a488-42d6581faf08.png)

I'm getting errors similar to Github Actions when I run `yarn storybook`.

2021-08-02 15:21 UTC, tay1orjones commented
@sstrubberg sorry about that, forgot to update the sass dependency. Should be fixed 👍

2021-08-03 14:09 UTC, sstrubberg approved these changes

2021-08-03 15:01 UTC, tw15egan approved these changes
LGTM 👍 ✅

2021-08-03 15:40 UTC, merged