feat(Type): add new type tokens
carbon-design-system/carbon pull request #9480
Opened 2021-08-16 11:52 UTC by tw15egan

Closes https://github.com/carbon-design-system/carbon/issues/9377

This PR adds in a few new type tokens, as well as aliasing old type-token names to their new V11 token name. The old values will be removed in V12. 

#### Changelog

**New**

- `legal-01` and `legal-02` added as net new tokens

**Changed**

-Old token names are set as values of token names in blue

 <img width="544" alt="Screen Shot 2021-08-16 at 1 48 11 PM" src="https://user-images.githubusercontent.com/11928039/129558995-67533b37-7a31-441f-a410-918ee58f2aab.png">

**Removed**

- No code should have been removed, and all old tokens should still work

#### Testing / Reviewing

A few notes for design:
- Noticed some value discrepancies between the values in the code, and what is currently in a PR (https://github.com/carbon-design-system/carbon-website/pull/2410). Is there a source-of-truth value table so that I can ensure all token values are correct?
- `heading01` currently exists, but it is mapped to `productiveHeading01`, _not_ `expressiveHeading01`. We can change these mappings, but I wanted to get clarification.
- `heading02` has the same issue as `heading01`. 
- Everything else mapped 1:1

2021-08-23 15:36 UTC, dakahn approved these changes

2021-08-25 15:27 UTC, tay1orjones approved these changes

2021-08-26 16:21 UTC, laurenmrice requested changes
I inspected all of the type tokens and found a couple of discrepancies. They should be changed to the following:

`helper-text-02` should be:
Letter spacing: .16px

For `heading-compact-01` and `heading-compact-02`, the Computed tab was not showing the line height and letter spacing for me, and they looked the same size so just double checking that they should be this:

`heading-compact-01` should be:
Size: 14px / 0.875rem
Line height: 18px / 1.125rem
Letter spacing: .16px

`heading-compact-02` should be:
Size: 16px / 1rem
Line height: 22px / 1.375rem
Letter spacing: 0px

`quotation-01` and `fluid-quotation-01` should be using IBM Plex Serif instead of Sans.
`quotation-02` and `fluid-quotation-02` should be using IBM Plex Serif instead of Sans.

`heading-01` and` expressive-heading-01 `should be:
Line height: 20px / 1.25rem

`heading-02` and `expressive-heading-02` should be:
Line height: 24px / 1.5rem

2021-08-27 14:41 UTC, laurenmrice approved these changes
Double checked again today after changes and it looks good to me! 👍

2021-08-30 15:35 UTC, joshblack approved these changes

2021-08-30 20:26 UTC, merged