5022 remove default placeholder
carbon-design-system/carbon pull request #9510
Opened 2021-08-20 00:20 UTC by dakahn

Closes #5022

### Changes

- Removes default placeholder for Combobox, TextArea, and TextInput
- Also sets the `title` prop to `labelText` in TextArea -- which made sense to me, but can adjust if we need to 👍🏾 

### Notes
Search is not part of this work. @joshblack since that seems like a bigger piece of work (with potentially some design input on label placement and docs) I wasn't sure if we wanted to include that here. It'd be easy enough to just port over label styling from another input and add a `hideLabel` prop so let me know and I can bust that out real quick if you think we should just get it done 🏄🏾

2021-08-20 14:09 UTC, sstrubberg approved these changes
LGTM!

2021-08-24 18:02 UTC, jnm2377 approved these changes

2021-08-31 15:48 UTC, tay1orjones approved these changes

2021-09-08 20:55 UTC, joshblack requested changes
Looking great! I think in this PR we saw: ComboBox, TextArea, and TextInput covered. Was curious if we were also going to cover:

- TimePicker
- ControlledPasswordInput
- PasswordInput
- Search
- FilterableMultiSelect
- DatePickerInput
- TableToolbarSearch

Which I think also have a `placeholder` prop: https://carbon-react-explorer.vercel.app/props/placeholder

I think there are several with `placeholderText` too that I wasn't sure if they applied either but wanted to confirm: https://carbon-react-explorer.vercel.app/props/placeHolderText

2021-09-08 20:55 UTC, joshblack commented on packages/react/src/components/TextInput/TextInput.js
> -    title: placeholder,
I _think_ this is considered a breaking change since existing code is now incorrect so might be worth flagging this

2021-09-09 19:10 UTC, dakahn commented
@joshblack 

It doesn't look like we have helper text functionality for:
- tableToolbarSearch
- search
- datepicker

So without some design we'd probably need to punt removal of placeholder on those components since we don't really have a codified way of showing -- date format in DatePIcker apart from placeholder text for example.

That said it looks like:
- timepicker
- filterableMultiselect
- passwordInput
- controlledPasswordInput
Have placeholder functionality and so i'll circle back through and change these 👍🏾

2022-01-27 16:52 UTC, tay1orjones approved these changes

2022-01-27 17:26 UTC, joshblack approved these changes

2022-01-27 20:01 UTC, aagonzales approved these changes
LGTM!

2022-01-27 20:48 UTC, merged