0903Update icons.yml
carbon-design-system/carbon pull request #9595
Opened 2021-09-03 08:04 UTC by LMapes

0903

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

2021-09-17 19:10 UTC, jnm2377 commented
Looks like some tests are failing for this.

2021-09-17 19:16 UTC, LMapes commented
@jnm2377 I don't know how to fix these errors.

2021-09-17 20:13 UTC, jnm2377 commented
Looks like it's breaking bc of bad indentation. I would double check your formatting to make sure there aren't other bad indentations besides this one. 
<img width="1008" alt="Screen Shot 2021-09-17 at 3 08 15 PM" src="https://user-images.githubusercontent.com/32556167/133847560-de8f0cba-6639-48d2-b4d2-b1c5c675dac9.png">


Also, public tests might need to be updated. I'm not sure. But looking at the PR you linked, it definitely updated test after adding new icon data.
<img width="1323" alt="Screen Shot 2021-09-17 at 3 09 41 PM" src="https://user-images.githubusercontent.com/32556167/133847779-f8e4f873-c3c4-46dd-b42d-83c01eab99c5.png">

2021-09-17 20:19 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Fit-to-height
  aliases:
```

2021-09-17 20:19 UTC, LMapes commented
@joshblack I don't know how to fix indentation. It looked visually okay to me in VS Code.

2021-09-17 20:44 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Inspection
  aliases:
```

2021-09-17 20:45 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Media cast
  aliases:
```

2021-09-17 20:46 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Settings services
  aliases:
```

2021-09-17 20:46 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Settings view
  aliases:
```

2021-09-17 20:47 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Volume block storage
  aliases:
```

2021-09-17 20:49 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Tank
  aliases:
```

2021-09-17 20:49 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
cc: @LMapes these are the indentations that aren't correct

2021-09-17 20:50 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Task approved
  aliases:
```

2021-09-17 20:50 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Task asset-view
  aliases:
```

2021-09-17 20:51 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Task settings
  aliases:
```

2021-09-17 20:51 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Task tools
  aliases:
```

2021-09-17 20:52 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Tool kit
  aliases:
```

2021-09-17 20:52 UTC, jnm2377 commented on packages/icons/icons.yml
> +  aliases:
```suggestion
  friendly_name: Ungroup objects
  aliases:
```

2021-10-04 15:37 UTC, mjabbink commented
@LMapes @jnm2377 Did the naming get resolved on this issue? I’m seeing lots of code names showing up in the library that I think this issue will resolve.

2021-10-04 15:50 UTC, LMapes commented
@mjabbink I added all the metadata content for all the UI icons into the .yml. Why it's not displaying by now is unclear to me.

2021-10-04 16:17 UTC, jnm2377 commented
Hey @LMapes sorry if I didn't make it clear in the past comments. I brought up tests failing a while back, which need to be addressed before this PR can get merged. Typically, contributors are responsible for updating their PRs accordingly when we give feedback or leave reviews. I tried to help out by updating all of the indentation errors your code had, but looks like the snapshots still need to be updated since you've added new metadata.

2021-10-04 17:13 UTC, tay1orjones requested changes

2021-10-04 17:13 UTC, tay1orjones commented on packages/icons/icons.yml
> +  - map
This line is the problem. Running the file through a yaml validator returns the following error:

```
Error : bad indentation of a sequence entry at line 10812, column 3:
      - map
      ^
```

2021-10-04 18:36 UTC, LMapes commented
@mjabbink I don't know how to correct this. Please assign a Carbon dev.

2021-10-04 20:14 UTC, Katie-A-IBM commented
@joshblack @jnm2377 @tay1orjones 
Hi All, Would you be able to set up a call to discuss this issue?
Thanks
cc @LMapes

2021-10-04 21:31 UTC, tay1orjones commented
@LMapes I'm happy to fix it, but don't know what the proper values should be. This is what it is currently:

```yml
- name: map--identify
  - map
    - travel
    - point
    - identify
    - ID
    - center
    - locate
    - location
    - graph
  sizes:
    - 32
```

There's no `friendlyName` or `aliases` entries. They were there previously but were removed as part of this PR. Should it be this instead?
```yaml
- name: map--identify
  friendly_name: map--identify
  aliases:
    - map
    - travel
    - point
    - identify
    - ID
    - center
    - locate
    - location
    - graph
  sizes:
    - 32
```

2021-10-05 00:41 UTC, LMapes commented
@tay1orjones Thanks for clarifying what you need. This should work

- name: map--identify
  friendly_name: Map identify
  aliases:
    - map
    - travel
    - point
    - identify
    - target
    - exact
    - ID
    - center
    - locate
    - location
    - graph
  sizes:
    - 32

2021-10-05 15:53 UTC, tay1orjones approved these changes
I've corrected the `map--identify` metadata as well as another piece of indentation I found. There were also a few entries that had the `.svg` suffix added, which isn't needed and caused the build to fail.

2021-10-05 16:30 UTC, jnm2377 approved these changes

2021-10-05 16:30 UTC, merged