chore: change comment type for stylint-ignore comments
carbon-design-system/carbon pull request #9673
Opened 2021-09-15 18:51 UTC by dcwarwick

Closes #9672

#### Changelog

`packages/type/scss/_styles.scss`
`packages/type/scss/modules/_styles.scss`
In both files, replace a CSS-preserved comment (`/* ... */`) with a non-preserved comment (`// ...`) since the comment is only a linter instruction required at build/lint time and not in the final CSS.

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

Built file `carbon-components/css/carbon-components.css` currently contains 472 copies of the line `/* stylelint-disable number-max-precision */`. After this PR is applied and the files built, it should contain none (and thus be a little over 21KB smaller!).

2021-09-15 22:25 UTC, jnm2377 commented
Looks like some of the snapshots need to be updated.

2021-09-16 14:11 UTC, joshblack approved these changes

2021-09-17 18:55 UTC, sstrubberg approved these changes

2021-09-17 18:56 UTC, sstrubberg requested changes
Just fix up those testing errors and you're good to go :)

2021-09-27 18:47 UTC, joshblack approved these changes

2021-09-28 14:31 UTC, sstrubberg approved these changes

2021-09-28 15:02 UTC, merged

2021-09-28 15:42 UTC, dcwarwick commented
Thanks @jnm2377 -- sorry, I've been away and just catching up with things now I'm back :-) many thanks all.