feat(Carbon-React): add prefix context refactor to class components
carbon-design-system/carbon pull request #9691
Opened 2021-09-17 00:51 UTC by dakahn

ref #9690 

Refactors prefix to use context for class components 🏄🏾 

#### Testing / Reviewing

Test that the components function and have classname prefixes as expected in the corresponding storybooks

2021-09-17 20:38 UTC, jnm2377 commented
I noticed some of the class components that use `PrefixContext` update the classNames to be $`{this.prefix}--` and some don't. Is there a reason?

2021-09-21 16:51 UTC, joshblack requested changes
Submitting a WIP review since I think you figured this out already, will review again once you push up changes 👀

2021-09-21 16:51 UTC, joshblack commented on packages/react/src/components/ComposedModal/ComposedModal.js
> +  prefix = this.context;
```suggestion
```

2021-09-21 16:51 UTC, joshblack commented on packages/react/src/components/ComposedModal/ComposedModal.js
> +        `${this.prefix}--body--with-modal-open`,
```suggestion
        `${this.context}--body--with-modal-open`,
```

2021-09-21 16:51 UTC, joshblack commented on packages/react/src/components/ComposedModal/ComposedModal.js
> +    toggleClass(document.body, `${this.prefix}--body--with-modal-open`, false);
```suggestion
    toggleClass(document.body, `${this.context}--body--with-modal-open`, false);
```

2021-09-21 16:51 UTC, joshblack commented on packages/react/src/components/ComposedModal/ComposedModal.js
> +      `${this.prefix}--body--with-modal-open`,
```suggestion
      `${this.context}--body--with-modal-open`,
```

2021-09-21 16:51 UTC, joshblack commented on packages/react/src/components/DatePicker/DatePicker.js
> +  prefix = this.context;
```suggestion
```

2021-09-21 20:55 UTC, jnm2377 approved these changes
prefix is working for me and everything looks good 🔥

2021-09-21 21:58 UTC, joshblack requested changes

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/DatePicker/DatePicker.js
> +  prefix = this.context;
@dakahn I think this won't work as a class instance property and will need to be changed. If the context value changes, then `this.prefix` would not be updated.

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/FileUploader/FileUploader.js
> +  prefix = this.context;
```suggestion
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/Modal/Modal.js
> +  modalCloseButtonClass = `${this.context}--modal-close`;
I think we'll have to add these to `render()` because `this.context` will not be defined in a `static` class property

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/OverflowMenu/OverflowMenu.js
> +  prefix = this.context;
```suggestion
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/ProgressIndicator/ProgressIndicator.Skeleton.js
> +      {Step()}
```suggestion
      <Step />
      <Step />
      <Step />
      <Step />
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/ProgressIndicator/ProgressIndicator.js
> +    const prefix = this.prefix;
```suggestion
    const prefix = this.context;
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/RadioButton/RadioButton.js
> +  prefix = this.context;
```suggestion
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/RadioButton/RadioButton.js
> +    const prefix = this.prefix;
```suggestion
    const prefix = this.context;
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/Tabs/Tabs.Skeleton.js
> +// );
```suggestion
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/Tabs/Tabs.Skeleton.js
> +        {Tab()}
```suggestion
        <Tab />
        <Tab />
        <Tab />
        <Tab />
        <Tab />
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/Tabs/Tabs.js
> +  prefix = this.context;
```suggestion
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/Tabs/Tabs.js
> +    const prefix = this.prefix;
```suggestion
    const prefix = this.context;
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/TextInput/TextInput.js
> +  }
```suggestion
```

I'd re-write this later on in `classNames()` like:

```jsx
  const customClassName =  className ?? `${prefix}--text__input`;
  const textInputClasses = classNames(
    `${prefix}--text-input`,
    {
      [customClassName]: enabled,
      [`${prefix}--text-input--light`]: light,
      [`${prefix}--text-input--invalid`]: normalizedProps.invalid,
      [`${prefix}--text-input--warning`]: normalizedProps.warn,
      [`${prefix}--text-input--${size}`]: size,
    }
  );
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/Toggle/Toggle.js
> +  prefix = this.context;
```suggestion
```

2021-09-21 21:58 UTC, joshblack commented on packages/react/src/components/Toggle/Toggle.js
> +    const prefix = this.prefix;
```suggestion
    const prefix = this.context;
```

2021-09-22 18:58 UTC, joshblack approved these changes

2021-09-22 19:01 UTC, merged