9733 progress indicator active state
carbon-design-system/carbon pull request #9740
Opened 2021-09-24 17:47 UTC by andreancardona

Closes #9733 

This PR adds the :active state to interactive steps that do not have a tooltip. Checkout original issue for full details. 

- [ ] Make sure interactive step that _does_ not have tooltip has `:active`

2021-09-24 18:25 UTC, aledavila approved these changes

2021-09-27 07:55 UTC, janhassel commented
Testing out the storybook preview this seems to also add the `:active` state on non-interactive steps ("Really long label" in the story) again. Ref #9609

Would `.bx--progress-step-button:not(.bx--progress-step-button--unclickable) .bx--progress-label` be an appropriate selector for this? If `:not()` is discouraged, I think there would need to be a class `.bx--progress-step-button--clickable` to identify interactive steps of any kind.

2021-09-28 15:41 UTC, joshblack approved these changes

2021-09-28 15:41 UTC, joshblack requested changes, later dismissed
Ah, wrong button click 🤦  Quick +1 to Jan's comments above

2021-10-11 15:27 UTC, jnm2377 requested changes

2021-10-11 15:27 UTC, jnm2377 commented on packages/components/src/components/progress-indicator/_progress-indicator.scss
> +    .#{$prefix}--progress-label:active {
looks good, but can you add this fix to the `@carbon/styles` package as well?

2021-10-13 15:10 UTC, theiliad approved these changes

2021-10-13 16:58 UTC, jnm2377 approved these changes

2021-10-13 16:59 UTC, jnm2377 requested changes

2021-10-13 16:59 UTC, jnm2377 commented on packages/styles/scss/components/progress-indicator/_progress-indicator.scss
> +    color: $interactive-01;
it doesn't seem to like this token. Is this a v11 token?

2021-10-13 17:03 UTC, andreancardona commented on packages/styles/scss/components/progress-indicator/_progress-indicator.scss
> +    color: $interactive-01;
@jnm2377 Just saw this also...looking into it now

2021-10-13 17:14 UTC, jnm2377 approved these changes

2021-10-18 00:46 UTC, merged