fix(carbon-react): removes default props for accessible placeholders
carbon-design-system/carbon pull request #9741
Opened 2021-09-24 18:05 UTC by abbeyhrt

Closes #9466
(Once #9731 is merged) 

Removes default props in v11 for accessible placeholder's and ensures that the props are required. 

Also makes `Tab`'s `id` prop required since the component has an accessibilty violation if it's not provided (reference #9666) 

#### Changelog

**Changed**

- iconDescription for `FileUploader` is now required and default is empty
- iconDescription's and invalidText's default prop for `NumberInput` are now empty
- default prop for label is now empty and `label` and `id` are required

#### Testing / Reviewing

Verify that everything works as expected

2021-09-27 15:55 UTC, joshblack requested changes
I think for the default props we'll want the value to be `undefined` versus an empty string.

For dropping isRequired, is it the case that all of these are no longer required? It seemed like we would still want them but want the user to provide them versus the default props being used. Let me know if I'm misunderstanding 👀

2021-09-27 15:55 UTC, joshblack commented on packages/react/src/components/FileUploader/FileUploader.js
> +      ? ''
```suggestion
      ? undefined
```

2021-09-27 15:55 UTC, joshblack commented on packages/react/src/components/NumberInput/NumberInput.js
> +      ? ''
```suggestion
      ? undefined
```

2021-10-04 16:35 UTC, abbeyhrt commented
> For dropping isRequired, is it the case that all of these are no longer required? It seemed like we would still want them but want the user to provide them versus the default props being used. Let me know if I'm misunderstanding 👀

I think you might have it backwards! If v11 is enabled, they are required, if not, they aren't

2021-10-26 13:53 UTC, aledavila approved these changes

2021-10-26 15:26 UTC, joshblack requested changes

2021-10-26 15:26 UTC, joshblack commented on packages/react/src/components/Tab/Tab.js
> +    label: FeatureFlags.enabled('enable-v11-release') ? '' : 'provide a label',
```suggestion
    label: FeatureFlags.enabled('enable-v11-release') ? undefined : 'provide a label',
```

2021-10-26 15:26 UTC, joshblack commented on packages/react/src/components/Tab/Tab.js
> +      : PropTypes.string,
Do we auto-generate the id for the component if it doesn't exist already?

2021-10-26 15:26 UTC, joshblack commented on packages/react/src/components/SelectItemGroup/SelectItemGroup.js
> +  label: FeatureFlags.enabled('enable-v11-release') ? '' : 'Provide label',
```suggestion
  label: FeatureFlags.enabled('enable-v11-release') ? undefined : 'Provide label',
```

2021-10-26 15:26 UTC, joshblack commented on packages/react/src/components/NumberInput/NumberInput.js
> +      : 'choose a number',
Should we just update `iconDescription` to `label` in a general sense for components that require labels?

2021-10-26 15:26 UTC, joshblack commented on packages/react/src/components/NumberInput/NumberInput.js
> +      ? ''
```suggestion
      ? undefined
```

2021-10-26 17:06 UTC, abbeyhrt commented on packages/react/src/components/NumberInput/NumberInput.js
> +      : 'choose a number',
I think a lot of the time, the iconDescription is a distinct thing from the label and depends component to component, so it's something we could talk about but I'm not sure if it should prevent this PR from being merged in

2021-10-26 17:13 UTC, joshblack approved these changes

2021-10-30 00:22 UTC, merged