fix(Modal): fix Formik bug in Modal
carbon-design-system/carbon pull request #9797
Opened 2021-10-04 15:59 UTC by ColbyJohnIBM

Closes #9523 

Breaking the secondary buttons out into their own sub-component [(here)](https://github.com/carbon-design-system/carbon/commit/647ec1e75#diff-22f235c4784785309ea4abec2fa146f38d2be0d56b42466af68a247a0fe898b3R437) created the bug described in the above issue. I understand that this was probably done for readability / maintainability, but it also is causing additional re-renders when used with Formik that are resulting in incorrect behavior.

#### Changelog

**Changed**

- Directly build out the secondary button set rather than using a sub-component

**Removed**

- Remove SecondaryButtonSet sub-component

#### Testing / Reviewing
I tested this by linking my local version of Carbon to my local version of our application, but a more generic way to test would be to run [this CodeSandbox](https://codesandbox.io/s/carbon-react-modal-formik-bug-2bho4) locally, linked to a local version of Carbon on this branch.

2021-10-04 16:01 UTC, ColbyJohnIBM commented
I have read the DCO document and I hereby sign the DCO.

2021-10-04 16:03 UTC, ColbyJohnIBM commented on packages/react/src/components/Modal/Modal.js
> +      >
These changes throughout this file seemed to be added via `husky` during the commit process-- hopefully they fit with this repo's conventions.

2021-10-04 18:38 UTC, aledavila requested changes
Looks like this completely breaks modal as I'm not seeing in the preview at all.

2021-10-05 01:15 UTC, ColbyJohnIBM commented
Interesting, the preview excludes the following components that appear on https://react.carbondesignsystem.com/:
AspectRatio
ComposedModal
CopyButton
DataTable
ErrorBoundary
FormGroup
FormLabel
Grid
Link
Loading
Modal
OrderedList
TooltipDefinition
TooltipIcon
UnorderedList

It also includes a few components that don't exist there:
Layer
Popover
Theme

I'm not sure why this might be...

2021-10-05 04:23 UTC, ColbyJohnIBM commented
Is there a way to get netlify to run again with the latest? Or does it do that automatically?

2021-10-05 15:47 UTC, tay1orjones commented
Sorry for the confusion @ColbyJohnIBM, there are three different deploy previews built for each pull request:

1. `carbon-react-next` 
   - New storybook from a new v11 package `@carbon/react`, `./packages/carbon-react`, currently in beta.
2. `carbon-components-react` 
   - This is the one you'll want to validate against, it's the preview for the existing storybook for 
   `carbon-components-react`, `./packages/react` 
3. `carbon-elements` 
   - Preview specifically for the elements packages; `grid`, `layout`, `colors`, etc.

The Netlify comment body will indicate which link is for which preview.

These deploys will all automatically update/re-deploy to the same URL when new commits are pushed to the pull request.

2021-10-05 20:51 UTC, jnm2377 approved these changes

2021-10-05 22:17 UTC, aledavila approved these changes
works as expected

2021-10-07 14:37 UTC, merged