feat(grid): add offset capability
carbon-design-system/carbon pull request #981
Opened 2018-07-17 15:07 UTC by rodet

## Overview

Resolves #288 
This PR adds an offset capability in the grid - instead of using empty DOM nodes to specify an empty space, developers can now add an offset class to their cells. This makes programming easier, and improves the performance and readability of the markup.

The offset functionality must be used with the grid columns functionality. It works with the same pattern.

*Former usage:*
```
<div class="bx--row">
  <div class="bx--col-xs-2"></div>
  <div class="bx--col-xs-6">Offset content</div>
</div>
```

*New usage:*
```
<div class="bx--row">
  <div class="bx--offset-xs-2 bx--col-xs-6">Offset content</div>
</div>
```

Full HTML with multiple examples: https://github.com/rodet/carbon-offset-demo

![image](https://user-images.githubusercontent.com/343696/42825757-010e3d70-89e3-11e8-9dfc-d0a0e6f8a70b.png)

### Added

Classes `bx--offset-xs-{column}` and `bx--offset-{breakpoint}-{column}` to enable a left margin fitting the grid size.

### Removed

Nothing

### Changed

Commas at the end of the breakpoint definitions (was added by the tooling apparently)

## Testing / Reviewing

Check https://github.com/rodet/carbon-offset-demo

2018-07-17 18:47 UTC, alisonjoseph requested changes
Thanks for adding this! 

Can you add a simple example to the bottom of `grid.hbs` file?
```
<div class="bx--row">
    <div class="bx--offset-xs-6 bx--col-xs-6 green">Offset content</div>
  </div>
```

We also need to update the docs on the website. Is this something you have time to do? Otherwise I can create an issue and add to our backlog. 
_http://www.carbondesignsystem.com/style/grid/code (https://github.com/IBM/design-system-website/blob/master/src/content/style/grid/code.md)_

2018-07-18 08:02 UTC, rodet commented
Hi @alisonjoseph , of course. Find commit 4c90b6b for the `grid.hbs` update, and the website update is on its way as well.

2018-07-18 19:18 UTC, alisonjoseph approved these changes
Thanks for making the updates!

2018-07-18 19:34 UTC, aledavila approved these changes

2018-07-18 19:37 UTC, merged