feat(modal): deprecate iconDescription
carbon-design-system/carbon pull request #9828
Opened 2021-10-08 20:35 UTC by sstrubberg

REF #9624 

Added deprecation warnings for `iconDescription` for v11.

#### Changelog

- Removed iconDescription from Storybook
- `title` and `aria-label` attributes now use the `ariaLabel` prop instead of `iconDescription`.
- The close button now gets an `aria-hidden="true"`
- Removed tests involving `iconDescription`. Added a new test to ensure the `aria-hidden` is applied to the `Close20` icon.

#### Testing / Reviewing

Review Modal in Storybook and ensure tests are firing off correctly.

#### Questions

- Should the `aria-label` be required now? REF [9466](https://github.com/carbon-design-system/carbon/issues/9466) - thx @abbeyhrt

2021-10-14 22:06 UTC, dakahn requested changes

2021-10-14 22:06 UTC, dakahn commented on packages/react/src/components/Modal/Modal-test.js
> +    it('should have aria-hidden on the Icon component', () => {
```suggestion
    it('should not place the svg icon in the accessibility tree', () => {
```

2021-10-14 22:06 UTC, dakahn commented on packages/react/src/components/Modal/Modal-test.js
> +    it('should have aria-hidden on the Icon component', () => {
just rewriting this one a bit to keep it in the perspective of a user using the component. A little background on what I mean by accessibility tree
https://developers.google.com/web/fundamentals/accessibility/semantics-builtin/the-accessibility-tree

2021-10-14 22:06 UTC, dakahn commented on packages/react/src/components/Modal/Modal-test.js
> +      expect(ariaHidden).toEqual('true');
it could also be helpful to test that the SVG is not a tab stop, but we may do this elsewhere

2021-10-20 23:28 UTC, dakahn commented
glorious work 
![image](https://user-images.githubusercontent.com/40970507/138186213-82577806-5437-47ca-8065-6ab834256f81.png)

2021-10-20 23:29 UTC, dakahn approved these changes
looks good to me 🏄🏾

2021-10-21 03:48 UTC, aledavila approved these changes
lgtm just looks like you need to update snapshots

2021-10-21 17:21 UTC, merged