feat(react): upgrade ExpandableTile from class to function
carbon-design-system/carbon pull request #9885
Opened 2021-10-18 15:55 UTC by abbeyhrt

Partially addresses #9712 

Updates ExpandableTile to functional component and updates the tests since they relied on the component being a class. 

#### Changelog

**Changed**

- tests
- ExpandableTile class -> function

#### Testing / Reviewing

Check that ExpandableTile works the same as it currently does

2021-10-18 17:29 UTC, sstrubberg commented on packages/react/src/components/Tile/next/Tile.js
> +  light: PropTypes.bool,
the light prop needs to be deprecated

2021-10-18 17:30 UTC, sstrubberg commented on packages/react/src/components/Tile/next/Tile.js
> +export function TileBelowTheFoldContent({ children }) {
Why rip out the `React.forwardRef()`?

2021-10-18 18:09 UTC, abbeyhrt commented on packages/react/src/components/Tile/next/Tile.js
> +export function TileBelowTheFoldContent({ children }) {
Not intentional! I accidentally was working on a branch without your changes merged in and didn't catch this when I merged in main, good catch! Thanks!

2021-10-25 19:51 UTC, sstrubberg requested changes
Looks great! How did you know to dig up that useIsomorphicEffect hook?!

I think all you need is to replace your function with the `React.fowardRef()`.

2021-10-25 20:40 UTC, tay1orjones approved these changes

2021-11-01 18:55 UTC, sstrubberg approved these changes

2021-11-01 19:47 UTC, merged