fix(button): hcm for ghost icon color contrast
carbon-design-system/carbon pull request #9904
Opened 2021-10-19 21:05 UTC by kinueng

Closes #9903

Add CSS specifically for Windows high contrast mode for the ghost style `<Button>`

#### Changelog

**Changed**

Added CSS specific to the ghost styling for the Button that will apply `fill: white` to the SVG.

#### Testing / Reviewing

# Before fix
![image](https://user-images.githubusercontent.com/31117513/137990839-9051174e-2fff-4f81-8f5b-1b8dacb8ab06.png)
# After fix
![image](https://user-images.githubusercontent.com/31117513/137990898-c1041233-68d1-496b-8c88-28c587c0cb5a.png)

2021-10-19 22:54 UTC, abbeyhrt approved these changes
Looks great to me! Thank you for the contribution! 🎉

2021-10-20 15:26 UTC, tay1orjones requested changes
Thanks for submitting this fix! A couple things in addition to the change requested in this review below:

1. The HCM styles need to be at the very end of the file to ensure they're not overridden
2. This fix needs to be mirrored in ~`packages/carbon-react`~ -- Edit, sorry I meant `packages/styles`

2021-10-20 15:26 UTC, tay1orjones commented on packages/components/src/components/button/_button.scss
> +    }
We can use the `icon-fill` parameter instead to ensure the fill is the same as the ButtonText forced color

https://github.com/carbon-design-system/carbon/blob/3c9fdbcc12116759c47605ad562aa4d3be78b9d5/packages/components/src/globals/scss/_helper-mixins.scss#L256-L258

```suggestion
    @include high-contrast-mode('icon-fill');
```

2021-10-20 15:34 UTC, tay1orjones approved these changes
@kinueng I hope you don't mind - I went ahead and pushed an update to this PR with the suggestions above. Let me know what you think

2021-10-20 16:29 UTC, tay1orjones commented
Fantastic! thanks @kinueng

2021-10-20 17:09 UTC, merged