feat(listbox): support disabled items in combobox, dropdown, filterablemultiselect
carbon-design-system/carbon pull request #9913
Opened 2021-10-20 20:57 UTC by tay1orjones

Closes #6477

Refs #9859, #9610, #7772, #7780

Adds support for disabling individual items inside `ComboBox`, `Dropdown`, and `FilterableMultiSelect`.

#### Changelog

**Changed**

- combobox, dropdown, filterablemultiselect: enable disabled items prop through downshift, update stories/docs/styles

#### Testing / Reviewing

View each of the stories for these components. They have been updated to have a single disabled item for testing purposes.

2021-10-20 21:03 UTC, joshblack requested changes

2021-10-20 21:03 UTC, joshblack commented on packages/react/src/components/Dropdown/Dropdown.js
> +                disabled: item?.disabled,
```suggestion
                disabled: item.disabled,
```

I think `item` should always be defined / an object, or is that not the case?

2021-10-20 21:10 UTC, tay1orjones commented on packages/react/src/components/Dropdown/Dropdown.js
> +                disabled: item?.disabled,
@joshblack `item` is but `disabled` is optional and may not always be available

2021-10-20 21:18 UTC, joshblack commented on packages/react/src/components/Dropdown/Dropdown.js
> +                disabled: item?.disabled,
@tay1orjones nice, if `item` will be always be defined then what is the purpose of using `?.`? I had thought that the intent of optional chaining was that it would short-circuit if the value on the left hand was null-ish. In this case, since `item` is always an object, it seems like it'd be the same as `item.disabled` since they'd both return `undefined`.

2021-10-20 21:44 UTC, tay1orjones commented on packages/react/src/components/Dropdown/Dropdown.js
> +                disabled: item?.disabled,
@joshblack Yeah! Sorry I overlooked this, I could've sworn I ran into a problem where `item` wasn't available. The optional chain fixed it, but I can't figure out how to repro it. Could be from my initial explorations and unrelated to how I ended up implementing this. 

I just pushed up a commit removing them 👍

2021-10-21 17:31 UTC, joshblack approved these changes

2021-10-21 22:24 UTC, dakahn approved these changes

2021-10-22 16:20 UTC, merged