feat(TimePickerSelect): updated props for v11
carbon-design-system/carbon pull request #9914
Opened 2021-10-20 21:31 UTC by sstrubberg

REF #9535 #9624 

Refactoring `TimePickerSelect` with prop changes in preparation for migration to a functional component.

#### Storybook

- Removed `iconDescription` from "Select" in the `TimePicker` story.
- Added an `aria-label` knob to "Select" in the `TimePicker` story.

#### TimePickerSelect

- Added a deprecation warning to `iconDescription`.
- Remove the unused `inline` prop.
- Put the props in alphabetical order.
- Renamed `...other` -> `...rest`
- Added an `ariaLabel` prop.
- Added proper aria attributes to the Chevron.

#### Testing
- Make sure `TimePicker` tests are passing.
- Ensure `TimePicker` does it's thing in Storybook, especially as it pertains to `TimePickerSelect`.

2021-10-25 17:45 UTC, abbeyhrt commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> +     * hideLable has been deprecated in v10 and will be removed in v11.
```suggestion
     * hideLabel has been deprecated in v10 and will be removed in v11.
```

2021-10-25 17:45 UTC, abbeyhrt commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> -    inline: PropTypes.bool,
Should `inline` be deprecated too or is it cool for it to just be removed?

2021-10-25 19:03 UTC, tay1orjones commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> -    inline: PropTypes.bool,
It doesn't look like it was being used, and it had an `// eslint-disable-line` next to it in the props destructuring. Looks like it's been around for a long time and hasn't been used. I think it's safe to delete. I'm curious if this is what you understood as well @sstrubberg?

2021-10-25 19:24 UTC, sstrubberg commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> -    inline: PropTypes.bool,
Took the words right out of my mouth :)

2021-10-25 19:35 UTC, tay1orjones reviewed
Overall looks good!

Do we need to change the `labelClasses` block w/ `visually-hidden` to always be true since the `hideLabel` default has been removed? https://github.com/carbon-design-system/carbon/pull/9914/files#diff-a67cbb553a741d3befb1f3b64288b2c0acf8e9f033976bf1f2bd5a7553138ad8R97-R100

2021-10-25 19:35 UTC, tay1orjones commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> +        'been deprecated. It will be removed in the next major release.'
Should we recommend `ariaLabel` usage in its place?

```suggestion
      'The `iconDescription` prop for `TimePickerSelect` is no longer needed and has ' +
        'been deprecated. It will be removed in the next major release. Use `ariaLabel` instead.'
```

2021-10-25 19:47 UTC, tay1orjones commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> -      hideLabel = true,
@sstrubberg Cool! I think we should leave in this `true` default until then

2021-10-25 20:49 UTC, tay1orjones approved these changes

2021-10-26 15:16 UTC, joshblack requested changes

2021-10-26 15:16 UTC, joshblack commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> +    ariaLabel: PropTypes.string,
Does this need to be `aria-label` according to how it's used in `render`?

```suggestion
   ['aria-label']: PropTypes.string,
```

2021-10-26 15:16 UTC, joshblack commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> +        'been deprecated. It will be removed in the next major release. Use `ariaLabel` instead.'
I think the message would need to be that `iconDescription` has been replaced with `aria-label` and will be removed in the next major release. Use `aria-label` instead.

2021-10-26 15:16 UTC, joshblack commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> +          aria-hidden="true"
```suggestion
```

I think we might want to keep the `aria-hidden` off of the SVG, right? So the label could be read. Let me know if I'm misunderstanding

2021-10-26 18:40 UTC, sstrubberg commented on packages/react/src/components/TimePickerSelect/TimePickerSelect.js
> +          aria-hidden="true"
This came up in a [previous PR](https://github.com/carbon-design-system/carbon/commit/a9c13fffe27b61c5662b785af0010489caa18ae1#diff-22f235c4784785309ea4abec2fa146f38d2be0d56b42466af68a247a0fe898b3) i did for Modal. @dakahn had suggested this for accessibility. Let me know if I misinterpreted that.

2021-10-26 21:21 UTC, abbeyhrt approved these changes
🎉

2021-10-27 21:05 UTC, joshblack approved these changes

2021-10-28 01:23 UTC, merged