feat(TimePicker): class -> functional component
carbon-design-system/carbon pull request #9921
Opened 2021-10-21 20:54 UTC by sstrubberg

REF #9712 

Refactored `TimePicker` into a functional component with RTL tests.

- Removed instances of `evt.persist();` because it is no longer needed as of React 17. However, this causes Storybook to generate console error messages when using Actions, so I removed them.

#### Testing / Reviewing

1. Pull down locally
2. Go to `packages/react`
3. Run `yarn start:v11` to run old storybook with v11 components.
4. Ensure tests for Next versions of `TimePicker` go green.

2021-10-22 19:21 UTC, joshblack requested changes
Looking great! Just left a couple of style nits

2021-10-22 19:21 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +import '@testing-library/jest-dom';
```suggestion
```

This is automatically included in our Jest entrypoint 👍

2021-10-22 19:21 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +    afterEach(cleanup);
```suggestion
```

This is automatically run by RTL so feel free to remove it 👍

2021-10-22 19:21 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" />);
```

If a component has no children we can use `<ComponentName />` as a shorthand

2021-10-22 19:21 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +    afterEach(cleanup);
```suggestion
```

2021-10-25 15:29 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker.js
> +    value,
Random refactoring thought, not sure about the content from the original file but can we just put these on the component below directly? 🤔  The one that is the `<input>`

2021-10-25 15:31 UTC, joshblack requested changes

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +  describe('label', () => {
Style nit for spacing

```suggestion

  describe('label', () => {
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +  describe('events', () => {
```suggestion

  describe('events', () => {
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker" className="🚀"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" className="🚀" />);
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" />);
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker" value="🐶"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" value="🐶" />);
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +        <TimePicker id="time-picker" onClick={onClick} disabled></TimePicker>
```suggestion
        <TimePicker id="time-picker" onClick={onClick} disabled />
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker" placeholder="🧸"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" placeholder="🧸" />);
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" />);
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker" labelText="🐳"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" labelText="🐳" />);
```

2021-10-25 15:31 UTC, joshblack commented on packages/react/src/components/TimePicker/next/TimePicker-test.js
> +      render(<TimePicker id="time-picker"></TimePicker>);
```suggestion
      render(<TimePicker id="time-picker" />);
```

2021-10-26 15:11 UTC, joshblack approved these changes

2021-10-27 01:30 UTC, tay1orjones reviewed
The storybook actions throw this error:

> Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `buttons` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

Will users accessing the `onChange`, `onClick`, and `onBlur` get this same error message  if they're using React v16?

The React  [v17 blog post](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling) has a brief note that `event.persist()` is still available on the React event object, it just doesn't do anything in React v17. 

Should we continue to use `event.persist()` and wait to remove it until (if?) we remove support for React v16?

2021-10-29 16:59 UTC, tay1orjones approved these changes

2021-10-30 01:51 UTC, merged