feat(RadioButton): refactor radio btn and btn group to functional components
carbon-design-system/carbon pull request #9940
Opened 2021-10-25 18:15 UTC by jnm2377

Ref #9712 

#### Changelog

- refactor `RadioButton`
- refactor `RadioButtonGroup`
- adds tests in `/next` folder (these tests were just copied over from v10, nothing changed).

#### Testing / Reviewing

- test radio button story in v11 to make sure everything is working correctly,
- ensure all tests are passing
- Note for reviewers: radio btn group won't have margin between the label and btns. This is a known issue from these changes: https://github.com/carbon-design-system/carbon/pull/9830 and will be addressed here: https://github.com/carbon-design-system/carbon/issues/9947

2021-10-26 17:00 UTC, joshblack requested changes

2021-10-26 17:00 UTC, joshblack commented on packages/react/src/components/RadioButton/next/RadioButton.js
> +  const uniqueId = id || uid;
I think we can use the `useId` hook for this use-case as a refactor opportunity 👀

2021-10-26 17:00 UTC, joshblack commented on packages/react/src/components/RadioButton/next/RadioButton.js
> +  };
Style nit: use function declarations versus arrow functions

```suggestion
  function handleOnChange(event) {
    onChange(value, name, event);
  }
```

2021-10-26 17:00 UTC, joshblack commented on packages/react/src/components/RadioButtonGroup/next/RadioButtonGroup.js
> +  }, [valueSelected]); //eslint-disable-line react-hooks/exhaustive-deps
We can use an `if` here instead of wrapping in an effect 👍 

```suggestion
    if (prevValueSelected !== valueSelected) {
      setSelected(
        valueSelected !== 'undefined' ? valueSelected : defaultSelected
      );
      setPrevValueSelected(valueSelected);
    }
```

2021-10-26 17:00 UTC, joshblack commented on packages/react/src/components/RadioButtonGroup/next/RadioButtonGroup.js
> +  const handleChange = (newSelection, value, evt) => {
Style nit: use function declarations

2021-10-26 19:34 UTC, sstrubberg commented on packages/react/src/components/RadioButton/next/RadioButton.js
> +        {...other}
```suggestion
        {...rest}
```

2021-10-26 19:34 UTC, sstrubberg commented on packages/react/src/components/RadioButton/next/RadioButton.js
> +    ...other
```suggestion
    ...rest
```

2021-10-27 14:07 UTC, sstrubberg approved these changes

2021-10-27 21:06 UTC, joshblack approved these changes

2021-10-27 23:44 UTC, merged