style(DatePicker): updated tokens
carbon-design-system/carbon pull request #9951
Opened 2021-10-26 16:43 UTC by sstrubberg

REF #9888 

Update tokens to v11 based on [the following specs](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/11.x-color.md).

- Replaced compat theme with theme.
- Brought in button tokens.

Updated the following:
- `ui-01` -> `layer-01`
- `text-01` -> `text-primary`
- `hover-ui` -> `background-hover`
- `ui-05` -> `border-inverse`
- `disabled-02` -> `text-disabled`
- `icon-01` -> `icon-primary`
- `interactive-01` -> `button-primary`
- `interactive-04` -> `border-interactive`
- `text-05` -> `text-helper`
- `link-01` -> `link-primary`
- `text-04` -> `text-on-color`
- `ui-02` -> `layer-02`

2021-10-26 17:07 UTC, tay1orjones requested changes
Let me know what you think about these suggestions. I'm not sure when a `brand` token wins out against `button` if the element is effectively a button.

2021-10-26 17:07 UTC, tay1orjones commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +      border-bottom-color: $background-brand;
I think it might make more sense to have these map to the `button-primary` token since these styles appear to be related to the increment up/decrement down buttons

```suggestion
      border-top-color: $button-primary;
      border-bottom-color: $button-primary;
```

2021-10-26 17:07 UTC, tay1orjones commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +      outline-color: $background-brand;
Same thing here since I believe this is a button?

```suggestion
      outline-color: $button-primary;
```

2021-10-26 17:07 UTC, tay1orjones commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +    background-color: $background-brand;
```suggestion
    background-color: $button-primary;
```

2021-10-26 17:07 UTC, tay1orjones commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +    background: $background-brand;
```suggestion
    background: $button-primary;
```

2021-10-26 17:08 UTC, sstrubberg commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +      border-bottom-color: $background-brand;
Good call. It was breaking when i used `$button-primary`. I probably need to find where the import for that comes.

2021-10-27 00:38 UTC, jnm2377 reviewed
I just have some questions around some of the tokens. Maybe we need design review on this for the tokens?

2021-10-27 00:38 UTC, jnm2377 commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +    fill: $border-inverse;
this is an svg, so should it use an icon token? I remember when updating other component tokens, some of the old tokens weren't correct to begin with.

2021-10-27 00:38 UTC, jnm2377 commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +    fill: $border-inverse;
same as above

2021-10-27 00:38 UTC, jnm2377 commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +      border-bottom: rem(4px) solid $icon-primary;
and I think this would need a border token, not icon token

2021-10-27 00:38 UTC, jnm2377 commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +      border-top: rem(4px) solid $icon-primary;
same as above, border token?

2021-10-27 00:50 UTC, tay1orjones commented on packages/styles/scss/components/date-picker/_flatpickr.scss
> +    fill: $border-inverse;
`icon-disabled` or `icon-on-color-disabled ` maybe since this is the disabled state of the next/prev button icon?

2021-10-27 00:52 UTC, tay1orjones approved these changes
Looks good once @jnm2377's feedback above is addressed 👍

2021-10-27 16:02 UTC, jnm2377 approved these changes

2021-10-27 16:29 UTC, merged