style(tree-view): update color tokens
carbon-design-system/carbon pull request #9957
Opened 2021-10-27 11:56 UTC by motou

REF #9888

Update color tokens to v11 based on the following specs: https://github.com/carbon-design-system/carbon/blob/main/docs/migration/11.x-color.md

- Replaced compat theme with theme.
- Updated the following:
  - ui-01 -> layer-01
  - text-02 -> text-secondary
  - disabled-01 -> field-disabled-01
  - disabled-02 -> text-disabled
  - disabled-02 -> field-disabled-02
  - hover-ui -> background-hover
  - text-01 -> text-primary
  - icon-02 -> icon-secondary
  - selected-ui -> layer-selected-01
  - hover-selected-ui -> background-selected-hover
  - icon-01 -> icon-primary
  - interactive-04 -> interactive

2021-10-27 16:02 UTC, sstrubberg requested changes
@motou You rock for helping with these token updates. Thank you for lending a hand. It looks like your tests are failing because it's having a hard time finding `$field-disabled-01`. Let me know if you need any help isolating that :)

![image](https://user-images.githubusercontent.com/15822070/139103211-d4b4a9e6-509c-42a3-b758-c00a0a40fb9b.png)

2021-10-29 01:32 UTC, sstrubberg approved these changes

2021-10-29 16:55 UTC, jnm2377 approved these changes

2021-10-29 17:19 UTC, aagonzales submitted a review, later dismissed

2021-10-29 17:19 UTC, aagonzales commented on packages/styles/scss/components/treeview/_treeview.scss
> +        background-color: $background-hover;
Since the enabled background use `$layer-01` the hover should use `$layer-hover-01`

```suggestion
        background-color: $layer-hover-01;
```

2021-10-29 17:19 UTC, aagonzales commented on packages/styles/scss/components/treeview/_treeview.scss
> +        background-color: $background-selected-hover;
It should continue to use the `layer` tokens instead of the `background` ones.
```suggestion
        background-color: $layer-selected-hover-01;
```

2021-10-29 19:48 UTC, motou commented
@aagonzales thanks for the review! The requested changes are incorporated.

2021-11-01 16:51 UTC, sstrubberg commented
@motou can you update the branch so we can merge?

2021-11-02 14:12 UTC, merged