refactor(popover): update styles and add new story
carbon-design-system/carbon pull request #9965
Opened 2021-10-27 16:19 UTC by joshblack

Reference #9941

#### Changelog

**New**

- Add tests for popover

**Changed**

- Update popover to use new tokens and update styles to use new CSS features now available

**Removed**

#### Testing / Reviewing

- Look at the story in storybook and verify that it works in every direction

2021-10-27 16:32 UTC, abbeyhrt commented on packages/styles/scss/components/popover/_popover.scss
> +  $popover-background-color: custom-property.get-var(
Woah! I've never seen this `get-var`, what does it do? Is it getting that theme layer token and then assigning `popover-backround-color` to it?

2021-10-27 21:01 UTC, joshblack commented on packages/styles/scss/components/popover/_popover.scss
> +  $popover-background-color: custom-property.get-var(
@abbeyhrt good question! Here's a breakdown from the module: https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/utilities/_custom-property.scss#L10-L29

Basically `get-var` gives you back the `var(--cds-token-name)` format of the token.

2021-10-27 21:42 UTC, abbeyhrt approved these changes

2021-10-28 15:15 UTC, laurenmrice requested changes
- The dropshadow should be `0 2px 6px 0 rgba(0, 0, 0, 0.2)`

- When a radio button under the "Caret Position" section is selected, the caret tip is not showing up in the storybook demo on the popover.  Is that related to the changes in this PR?

2021-10-28 23:45 UTC, aledavila approved these changes
lgtm

2021-11-01 16:46 UTC, laurenmrice requested changes
**Storybook demo spec:**
- [x] Instead of using a 48px container and a 32px icon for the trigger, lets use a `32px container` and a `16px icon`.
- [x] When the caret tip is set to true: there should be a `4px space` between the caret and the container bounding box.
![storybook demo spec](https://user-images.githubusercontent.com/43969356/139707693-5aef0cd0-66cb-49a1-8135-48344ff8ee6e.png)


-----

**Direction alignments:**
When the caret tip is set to true, most of the alignments looks good, but some popovers just need a 2px nudge)
- [x] Top-left (move popover 2px to right)
- [x] Top-right (move popover 2px to left)
- [x] Bottom-left (move popover 2px to right)
- [x] Bottom-right  (move popover 2px to left)
- [x] Left-bottom (move popover 2px up)
- [ ] Left-top (move popover 2px down)
- [ ] Right-bottom (move popover 2px up)
- [ ] Right-top (move popover 2px down)

2021-11-02 22:15 UTC, joshblack commented
@laurenmrice should be good to go for a re-review!

2021-11-03 15:40 UTC, dakahn approved these changes
Cool!

2021-11-03 16:35 UTC, laurenmrice requested changes
- Directions look great in Safari/Chrome/Firefox! 🎉

- The only thing we need to adjust now is that the 16px checkbox icon looks like it was enlarged to fill the 16px container around it. The true asset of the 16px icon has some padding around the artwork inside of the 16px container. https://carbon-elements.netlify.app/icons/examples/preview/#Checkbox16

- Example of current code versus design spec:
![Artboard](https://user-images.githubusercontent.com/43969356/140102994-170a248c-7a87-4010-bb13-f3d05066d782.png)

2021-11-03 16:45 UTC, joshblack commented
@laurenmrice updated!

2021-11-03 18:54 UTC, laurenmrice approved these changes
Looks great ! 🎉

2021-11-03 20:12 UTC, merged