style(structured-list): update theme import
carbon-design-system/carbon pull request #9970
Opened 2021-10-27 19:12 UTC by motou

REF #9888

Update color tokens to v11 based on the following specs: https://github.com/carbon-design-system/carbon/blob/main/docs/migration/11.x-color.md

- Replaced compat theme with theme.

2021-10-27 21:09 UTC, joshblack requested changes
It seems like there are some tokens still being used from `compat/theme` potentially like `$hover-row` that need to be replaced 👀

2021-10-29 01:34 UTC, sstrubberg approved these changes

2021-10-29 15:00 UTC, joshblack approved these changes

2021-10-29 19:36 UTC, motou commented
@aagonzales sure, the token doc is updated.

2021-10-29 21:40 UTC, tay1orjones approved these changes

2021-11-01 21:10 UTC, sstrubberg commented
@motou Can you enable this?

![image](https://user-images.githubusercontent.com/15822070/139742566-53d19c16-fb2b-4c55-bf56-f0b8ae5a2d26.png)

2021-11-01 23:55 UTC, merged