style(Search): updated tokens
carbon-design-system/carbon pull request #9993
Opened 2021-10-28 21:40 UTC by sstrubberg

REF #9888

Update color tokens to v11 based on the following specs: https://github.com/carbon-design-system/carbon/blob/main/docs/migration/11.x-color.md

2021-10-28 21:56 UTC, aagonzales approved these changes

2021-10-28 23:47 UTC, aledavila approved these changes

2021-10-29 15:13 UTC, joshblack approved these changes

2021-10-29 19:41 UTC, motou commented on packages/styles/scss/components/search/_search.scss
> +    color: $field;
Looks like the same issue that I discovered here: https://github.com/carbon-design-system/carbon/pull/9971#discussion_r737782924

The color and the background color are the same? ;)

2021-10-29 22:01 UTC, tay1orjones requested changes
Thanks for the catch @motou ! Those shouldn't be the same value.

2021-11-02 16:07 UTC, tay1orjones approved these changes

2021-11-02 16:07 UTC, merged