refactor(react): update Tooltip to latest
carbon-design-system/carbon pull request #9997
Opened 2021-10-29 16:32 UTC by joshblack

This PR cleans up our work for Tooltip next, adds tests, and updates stories. The key integration is combining tooltip with the style from popovers 🎉 

#### Changelog

**New**

- Add `Tooltip` based on popover styles with new API

**Changed**

- Add ref support to `Popover`
- Update playground stories with a tooltip/popover trigger to use `theme.$background-inverse` for dark themes

**Removed**

- Removed v11 for tooltip from `carbon-components`

#### Testing / Reviewing

- View `unstable_Tooltip` stories in the `carbon-react-next` storybook
- Verify styles work across themes and browsers
- Make sure Tooltip component has test coverage
- Make sure changes to Popover component has test coverage

2021-11-04 14:59 UTC, joshblack commented
FYI @laurenmrice @kingtraceyj  this is the PR that is updating Tooltip (interactive specifically) to use the new popover styles. There will be a couple of follow-up PRs for:

- Icon tooltip -> Icon button
- Definition tooltip

As well!

2021-11-04 17:33 UTC, abbeyhrt commented
I'm still seeing the line of doom, at least in firefox
![Screen Shot 2021-11-04 at 12 32 35 PM](https://user-images.githubusercontent.com/17281178/140390029-033eec88-7cf2-41c8-b1d2-a3c88c2ab711.png)

2021-11-08 15:54 UTC, joshblack commented
@abbeyhrt could you share steps to reproduce? This is what I see right now on FF 

![Screen Shot 2021-11-08 at 09 53 53](https://user-images.githubusercontent.com/3901764/140774326-e45e0a47-3774-49fb-bdad-a5d949c27170.png)


![Screen Shot 2021-11-08 at 09 53 58](https://user-images.githubusercontent.com/3901764/140774335-fae862c7-ac89-46bb-97da-9b324ca3b0fd.png)

2021-11-08 19:08 UTC, joshblack commented
cc @abbeyhrt @tay1orjones @kingtraceyj let me know if you have any questions!

2021-11-08 19:58 UTC, tay1orjones requested changes
Couple small bits, but otherwise looks good

2021-11-08 19:58 UTC, tay1orjones commented on packages/react/src/components/Tooltip/next/Tooltip.stories.js
> +      <Tooltip label="Label two" enterDelayMs={500} leaveDelayMs={500}>
```suggestion
      <Tooltip label="Label three" enterDelayMs={500} leaveDelayMs={500}>
```

2021-11-08 19:58 UTC, tay1orjones commented on packages/react/src/components/Tooltip/next/Tooltip.stories.js
> +  const { align, defaultOpen, description, label } = props;
I think this needs a `...rest` to then be applied to the Tooltip below. The `enterDelayMs` and `leaveDelayMs` controls aren't working for me.

https://user-images.githubusercontent.com/3360588/140809133-66c35575-1bb5-49bf-bdaa-9e9f6d5706b8.mov

2021-11-08 22:59 UTC, tay1orjones approved these changes

2021-11-09 21:11 UTC, joshblack commented
cc @laurenmrice let me know if you have any questions!

2021-11-09 22:03 UTC, abbeyhrt approved these changes
Looks good to me!

2021-11-10 17:24 UTC, laurenmrice requested changes
The tooltip does not need to have a dropshadow because it is high contrast. Everything else looks great!

2021-11-10 18:37 UTC, laurenmrice approved these changes
lgtm!

2021-11-10 19:10 UTC, merged